/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeGroup.Invariants.IsSU2BiFundamental
/-!
# Gauge tensors carrying four `su(2)` fundamental indices

`IsSU2QuadFundamental B repGauge T` says that a family `T`, indexed by four `su(2)`
fundamental indices and valued in a module `B` carrying a representation of the gauge
group `GaugeGroupI`, transforms as a tensor `T^{a₁ a₂ a₃ a₄}` in the `su(2)` factor of the
fundamental representation.

This is the four-index analogue of `IsSU2BiFundamental`, whose antisymmetric symbol and
proof of its invariance are used here rather than repeated. A conjugate Higgs symbol
carries one `su(2)` fundamental index, so a product of four of them is such a family, and
the quartic sector of `IsHiggsSector` runs the argument below in that special case. Nothing
here mentions the Higgs: every statement is about an arbitrary family with four fundamental
indices.

Two indices admit one contraction; four admit three, one for each way of pairing the
indices off. They do not span a three-dimensional space of contractions. The Schouten
identity, which says that antisymmetrizing three indices of a two-dimensional space
vanishes, gives one linear relation between the three, so exactly two of them are
independent, and the third is the difference of the other two.

Section A gives the proposition, the span of its components, and the way a linear
combination of the components transforms. Section B builds the three double epsilon
contractions, proves each gauge invariant, and proves the Schouten relation between them.
Section C is the gauge weight decomposition of the span, whose zero-weight piece is the
join of the six lines through the components with two indices of each value. Section D
grades that piece by the Weyl element of the `SU(2)` factor, leaving a grade zero spanned
by three symmetric combinations.
Section E removes the one direction that survives both gradings, the neutral state of the
isospin-two multiplet, by averaging over the cyclic group generated by a third of a turn
about the diagonal isospin axis, and so cuts the invariants down to the plane spanned by
two of the epsilon contractions.
-/

@[expose] public section

namespace StandardModel

open Matrix
open IsSU2BiFundamental (epsilon sum_epsilon_mul fundWeight)
open IsSU2BiFundamental (toSU2_gaugeTorusGen_apply toSU2_gaugeSU2Perm_apply)
open IsSU2BiFundamental (sup_span_sub_add)

/-!

## A. Quad-fundamental `su(2)` families and the span of their components

The transformation law carries one factor of the fundamental matrix `GaugeGroupI.toSU2 g`
per index, with the summed index in the row slot, exactly as in `IsSU2BiFundamental`. Since
`toSU2` is a monoid homomorphism this is an action, and it is the `SU(2)` factor alone.

The element `g` still ranges over the whole of `GaugeGroupI`, and that asymmetry is what
makes the proposition say more than a statement about `SU(2)` would. The right-hand side
sees only `GaugeGroupI.toSU2 g`, so taking `g` in the colour or hypercharge factor forces
that factor to fix every component; section C reads that off as the vanishing of the colour
and hypercharge coordinates of every weight. `GaugeWeightDecomposition` is in any case
stated for representations of `GaugeGroupI`, which a bare `SU(2)` representation cannot
supply.

Everything after section A is phrased through `repGauge_sum`, which says how a linear
combination of the components transforms: the coefficients move by the fourfold tensor
power of the fundamental matrix, and the components stay where they are. Each later
statement is then a statement about coefficient families, which are functions to `ℂ` and so
can be computed with.

-/

/-- A family `T` of elements of `B`, indexed by four `su(2)` fundamental indices,
  transforms as a tensor `T^{a₁ a₂ a₃ a₄}` under the representation `repGauge` of the gauge
  group. -/
structure IsSU2QuadFundamental (B : Type*) [AddCommMonoid B] [Module ℂ B]
    (repGauge : Representation ℂ GaugeGroupI B)
    (T : (Fin 4 → Fin 2) → B) : Prop where
  repGauge_T : ∀ (g : GaugeGroupI) (l : Fin 4 → Fin 2),
    repGauge g (T l) = ∑ a : Fin 4 → Fin 2,
      (∏ i : Fin 4, (GaugeGroupI.toSU2 g).1 (a i) (l i)) • T a

TODO (lines := 82-85) "This should just be about the action of
  the SU(2) part, along with the rest of the content of this file."

namespace IsSU2QuadFundamental
set_option linter.unusedVariables false

variable {B : Type*} [AddCommGroup B] [Module ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {T : (Fin 4 → Fin 2) → B}
  (hT : IsSU2QuadFundamental B repGauge T)

/-- The span of all the components. -/
def span (hT : IsSU2QuadFundamental B repGauge T) : Submodule ℂ B := ⨆ d, ℂ ∙ T d

/-- An element of `B` lies in the span of the components of `T` precisely when it is a
  linear combination of them. -/
lemma mem_span_iff (x : B) :
    x ∈ hT.span ↔ ∃ (c : (Fin 4 → Fin 2) → ℂ), x = ∑ d, c d • T d := by
  constructor
  · intro hx
    rw [span] at hx
    refine Submodule.iSup_induction
      (motive := fun y => ∃ c : (Fin 4 → Fin 2) → ℂ, y = ∑ d, c d • T d)
      (fun d => ℂ ∙ T d) hx ?_ ?_ ?_
    · intro d y hy
      obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.1 hy
      refine ⟨fun e => if e = d then a else 0, ?_⟩
      simp only [ite_smul, zero_smul, Finset.sum_ite_eq', Finset.mem_univ, if_true]
    · exact ⟨0, by simp⟩
    · rintro y z ⟨c₁, rfl⟩ ⟨c₂, rfl⟩
      exact ⟨c₁ + c₂, by simp [add_smul, Finset.sum_add_distrib]⟩
  · rintro ⟨c, rfl⟩
    exact sum_mem fun d _ => Submodule.smul_mem _ _
      (Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _))

/-- Every component lies in the span. -/
lemma mem_span (d : Fin 4 → Fin 2) : T d ∈ hT.span :=
  Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _)

/-- A sum over families of four `su(2)` fundamental indices is a fourfold sum. -/
lemma sum_pi_four {M : Type*} [AddCommMonoid M] (F : (Fin 4 → Fin 2) → M) :
    ∑ d : Fin 4 → Fin 2, F d
      = ∑ x : Fin 2, ∑ y : Fin 2, ∑ z : Fin 2, ∑ w : Fin 2, F ![x, y, z, w] := by
  rw [show (∑ d : Fin 4 → Fin 2, F d)
      = ∑ p : Fin 2 × Fin 2 × Fin 2 × Fin 2, F ![p.1, p.2.1, p.2.2.1, p.2.2.2] from
        Fintype.sum_equiv
          { toFun := fun d => (d 0, d 1, d 2, d 3)
            invFun := fun p => ![p.1, p.2.1, p.2.2.1, p.2.2.2]
            left_inv := fun d => by funext i; fin_cases i <;> simp
            right_inv := fun p => by simp } _ _ fun d => by
          congr 1
          funext i
          fin_cases i <;> simp]
  simp only [Fintype.sum_prod_type]

/-- A gauge transformation moves a linear combination of the components to the combination
  whose coefficients have been moved by the fourfold tensor power of the fundamental
  matrix. -/
lemma repGauge_sum (hT : IsSU2QuadFundamental B repGauge T) (g : GaugeGroupI)
    (c : (Fin 4 → Fin 2) → ℂ) :
    repGauge g (∑ l : Fin 4 → Fin 2, c l • T l)
      = ∑ a : Fin 4 → Fin 2,
        (∑ l : Fin 4 → Fin 2, c l * ∏ i, (GaugeGroupI.toSU2 g).1 (a i) (l i)) • T a := by
  rw [map_sum]
  have h1 : ∀ l : Fin 4 → Fin 2, repGauge g (c l • T l)
      = ∑ a : Fin 4 → Fin 2,
        (c l * ∏ i, (GaugeGroupI.toSU2 g).1 (a i) (l i)) • T a := by
    intro l
    rw [map_smul, hT.repGauge_T g l, Finset.smul_sum]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [smul_smul]
  simp only [h1]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [← Finset.sum_smul]

/-- A linear combination of the components whose coefficient family is fixed by every
  `SU(2)` matrix is gauge invariant. -/
lemma repGauge_sum_eq_self (hT : IsSU2QuadFundamental B repGauge T)
    (c : (Fin 4 → Fin 2) → ℂ)
    (hc : ∀ (U : specialUnitaryGroup (Fin 2) ℂ) (a : Fin 4 → Fin 2),
      ∑ l : Fin 4 → Fin 2, c l * ∏ i, U.1 (a i) (l i) = c a)
    (g : GaugeGroupI) :
    repGauge g (∑ l : Fin 4 → Fin 2, c l • T l) = ∑ l : Fin 4 → Fin 2, c l • T l := by
  rw [hT.repGauge_sum g c]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [hc (GaugeGroupI.toSU2 g) a]

/-!

## B. The three epsilon pairings

A doublet index has nowhere to be contracted against another doublet index except through
the antisymmetric symbol, so a contraction of four doublet indices is a choice of a pairing
of the four. There are three such pairings, and hence three double contractions. The symbol
and its invariance are those of `IsSU2BiFundamental`: the invariance is the statement that
the determinant of an `SU(2)` matrix is one, and it needs no mention of the gauge group.

The three contractions are not independent. Antisymmetrizing three indices of a
two-dimensional space gives zero, and writing that out is the Schouten identity, one linear
relation holding pointwise in the four indices. Two of the three pairings are therefore
independent, and the third is the difference of the other two. Section E shows that these
two exhaust the gauge invariants in the span of the components, so the count here is sharp.

-/

/-- The coefficient family of the contraction pairing the first index with the second and
  the third with the fourth. -/
def epsilonPair₁₂ (l : Fin 4 → Fin 2) : ℂ := epsilon (l 0) (l 1) * epsilon (l 2) (l 3)

/-- The coefficient family of the contraction pairing the first index with the third and
  the second with the fourth. -/
def epsilonPair₁₃ (l : Fin 4 → Fin 2) : ℂ := epsilon (l 0) (l 2) * epsilon (l 1) (l 3)

/-- The coefficient family of the contraction pairing the first index with the fourth and
  the second with the third. -/
def epsilonPair₁₄ (l : Fin 4 → Fin 2) : ℂ := epsilon (l 0) (l 3) * epsilon (l 1) (l 2)

/-- The Schouten identity: antisymmetrizing three indices of a two-dimensional space gives
  zero, which written out is a linear relation between the three ways of pairing four
  indices off. -/
lemma epsilon_schouten (a b c d : Fin 2) :
    epsilon a b * epsilon c d - epsilon a c * epsilon b d + epsilon a d * epsilon b c = 0 := by
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;> norm_num

/-- The third pairing is the difference of the other two, pointwise in the four indices. -/
lemma epsilonPair₁₄_eq (l : Fin 4 → Fin 2) :
    epsilonPair₁₄ l = epsilonPair₁₃ l - epsilonPair₁₂ l := by
  have h := epsilon_schouten (l 0) (l 1) (l 2) (l 3)
  rw [epsilonPair₁₄, epsilonPair₁₃, epsilonPair₁₂]
  linear_combination h

/-- The first two pairings are linearly independent as coefficient families, each
  vanishing on a family of indices where the other takes the value one. With the Schouten
  relation this pins the span of the three pairings down to a plane. -/
lemma epsilonPair_linearIndependent :
    LinearIndependent ℂ ![epsilonPair₁₂, epsilonPair₁₃] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  have h1 := congrFun hst ![0, 1, 0, 1]
  have h2 := congrFun hst ![0, 0, 1, 1]
  simp only [Pi.add_apply, Pi.smul_apply, Pi.zero_apply, smul_eq_mul, epsilonPair₁₂,
    epsilonPair₁₃, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.cons_val_three, Matrix.tail_cons,
    IsSU2BiFundamental.epsilon_zero_zero, IsSU2BiFundamental.epsilon_zero_one,
    IsSU2BiFundamental.epsilon_one_one] at h1 h2
  constructor
  · linear_combination h1
  · linear_combination h2

/-- The first pairing is invariant under the fundamental representation of an `SU(2)`
  element: the sum over the four indices factors into the two epsilon contractions, each of
  which is invariant. -/
lemma sum_epsilonPair₁₂_mul (U : specialUnitaryGroup (Fin 2) ℂ) (a : Fin 4 → Fin 2) :
    ∑ l : Fin 4 → Fin 2, epsilonPair₁₂ l * ∏ i, U.1 (a i) (l i) = epsilonPair₁₂ a := by
  have key : ∑ l : Fin 4 → Fin 2, epsilonPair₁₂ l * ∏ i, U.1 (a i) (l i)
      = (∑ x : Fin 2, ∑ y : Fin 2, epsilon x y * (U.1 (a 0) x * U.1 (a 1) y))
        * (∑ z : Fin 2, ∑ w : Fin 2, epsilon z w * (U.1 (a 2) z * U.1 (a 3) w)) := by
    rw [sum_pi_four]
    simp only [epsilonPair₁₂, Fin.prod_univ_four, Fin.sum_univ_two]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
      Matrix.cons_val_two, Matrix.cons_val_three, Matrix.tail_cons]
    ring
  rw [key, sum_epsilon_mul, sum_epsilon_mul, epsilonPair₁₂]

/-- The second pairing is invariant under the fundamental representation of an `SU(2)`
  element, by the same factorization with the indices interleaved. -/
lemma sum_epsilonPair₁₃_mul (U : specialUnitaryGroup (Fin 2) ℂ) (a : Fin 4 → Fin 2) :
    ∑ l : Fin 4 → Fin 2, epsilonPair₁₃ l * ∏ i, U.1 (a i) (l i) = epsilonPair₁₃ a := by
  have key : ∑ l : Fin 4 → Fin 2, epsilonPair₁₃ l * ∏ i, U.1 (a i) (l i)
      = (∑ x : Fin 2, ∑ z : Fin 2, epsilon x z * (U.1 (a 0) x * U.1 (a 2) z))
        * (∑ y : Fin 2, ∑ w : Fin 2, epsilon y w * (U.1 (a 1) y * U.1 (a 3) w)) := by
    rw [sum_pi_four]
    simp only [epsilonPair₁₃, Fin.prod_univ_four, Fin.sum_univ_two]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
      Matrix.cons_val_two, Matrix.cons_val_three, Matrix.tail_cons]
    ring
  rw [key, sum_epsilon_mul, sum_epsilon_mul, epsilonPair₁₃]

/-- The third pairing is invariant under the fundamental representation of an `SU(2)`
  element. -/
lemma sum_epsilonPair₁₄_mul (U : specialUnitaryGroup (Fin 2) ℂ) (a : Fin 4 → Fin 2) :
    ∑ l : Fin 4 → Fin 2, epsilonPair₁₄ l * ∏ i, U.1 (a i) (l i) = epsilonPair₁₄ a := by
  have key : ∑ l : Fin 4 → Fin 2, epsilonPair₁₄ l * ∏ i, U.1 (a i) (l i)
      = (∑ x : Fin 2, ∑ w : Fin 2, epsilon x w * (U.1 (a 0) x * U.1 (a 3) w))
        * (∑ y : Fin 2, ∑ z : Fin 2, epsilon y z * (U.1 (a 1) y * U.1 (a 2) z)) := by
    rw [sum_pi_four]
    simp only [epsilonPair₁₄, Fin.prod_univ_four, Fin.sum_univ_two]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
      Matrix.cons_val_two, Matrix.cons_val_three, Matrix.tail_cons]
    ring
  rw [key, sum_epsilon_mul, sum_epsilon_mul, epsilonPair₁₄]

/-- The contraction pairing the first index with the second and the third with the
  fourth. -/
def epsilonContraction₁₂ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 1, 0, 1] - T ![0, 1, 1, 0] - T ![1, 0, 0, 1] + T ![1, 0, 1, 0]

/-- The contraction pairing the first index with the third and the second with the
  fourth. -/
def epsilonContraction₁₃ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 0, 1, 1] - T ![0, 1, 1, 0] - T ![1, 0, 0, 1] + T ![1, 1, 0, 0]

/-- The contraction pairing the first index with the fourth and the second with the
  third. -/
def epsilonContraction₁₄ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 0, 1, 1] - T ![0, 1, 0, 1] - T ![1, 0, 1, 0] + T ![1, 1, 0, 0]

/-- The first contraction written as a sum over all families of four fundamental indices
  weighted by its pairing. -/
lemma epsilonContraction₁₂_eq_sum (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₂ = ∑ l : Fin 4 → Fin 2, epsilonPair₁₂ l • T l := by
  rw [sum_pi_four]
  simp [epsilonContraction₁₂, epsilonPair₁₂, Fin.sum_univ_two]
  abel

/-- The second contraction written as a sum over all families of four fundamental indices
  weighted by its pairing. -/
lemma epsilonContraction₁₃_eq_sum (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₃ = ∑ l : Fin 4 → Fin 2, epsilonPair₁₃ l • T l := by
  rw [sum_pi_four]
  simp [epsilonContraction₁₃, epsilonPair₁₃, Fin.sum_univ_two]
  abel

/-- The third contraction written as a sum over all families of four fundamental indices
  weighted by its pairing. -/
lemma epsilonContraction₁₄_eq_sum (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₄ = ∑ l : Fin 4 → Fin 2, epsilonPair₁₄ l • T l := by
  rw [sum_pi_four]
  simp [epsilonContraction₁₄, epsilonPair₁₄, Fin.sum_univ_two]
  abel

/-- The first contraction is gauge invariant. -/
lemma repGauge_epsilonContraction₁₂ (hT : IsSU2QuadFundamental B repGauge T)
    (g : GaugeGroupI) :
    repGauge g hT.epsilonContraction₁₂ = hT.epsilonContraction₁₂ := by
  rw [hT.epsilonContraction₁₂_eq_sum]
  exact hT.repGauge_sum_eq_self _ sum_epsilonPair₁₂_mul g

/-- The second contraction is gauge invariant. -/
lemma repGauge_epsilonContraction₁₃ (hT : IsSU2QuadFundamental B repGauge T)
    (g : GaugeGroupI) :
    repGauge g hT.epsilonContraction₁₃ = hT.epsilonContraction₁₃ := by
  rw [hT.epsilonContraction₁₃_eq_sum]
  exact hT.repGauge_sum_eq_self _ sum_epsilonPair₁₃_mul g

/-- The third contraction is gauge invariant. -/
lemma repGauge_epsilonContraction₁₄ (hT : IsSU2QuadFundamental B repGauge T)
    (g : GaugeGroupI) :
    repGauge g hT.epsilonContraction₁₄ = hT.epsilonContraction₁₄ := by
  rw [hT.epsilonContraction₁₄_eq_sum]
  exact hT.repGauge_sum_eq_self _ sum_epsilonPair₁₄_mul g

/-- The Schouten relation between the three contractions: the third is the difference of
  the other two, so the three span a plane and not a three-dimensional space. -/
lemma epsilonContraction₁₄_eq_sub (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₄ = hT.epsilonContraction₁₃ - hT.epsilonContraction₁₂ := by
  rw [epsilonContraction₁₄, epsilonContraction₁₃, epsilonContraction₁₂]
  abel

/-- The first contraction lies in the span of the components. -/
lemma epsilonContraction₁₂_mem_span (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₂ ∈ hT.span := by
  rw [epsilonContraction₁₂]
  exact add_mem (sub_mem (sub_mem (hT.mem_span _) (hT.mem_span _)) (hT.mem_span _))
    (hT.mem_span _)

/-- The second contraction lies in the span of the components. -/
lemma epsilonContraction₁₃_mem_span (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₃ ∈ hT.span := by
  rw [epsilonContraction₁₃]
  exact add_mem (sub_mem (sub_mem (hT.mem_span _) (hT.mem_span _)) (hT.mem_span _))
    (hT.mem_span _)

/-- The third contraction lies in the span of the components. -/
lemma epsilonContraction₁₄_mem_span (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₄ ∈ hT.span := by
  rw [epsilonContraction₁₄]
  exact add_mem (sub_mem (sub_mem (hT.mem_span _) (hT.mem_span _)) (hT.mem_span _))
    (hT.mem_span _)

end IsSU2QuadFundamental

/-!

## C. The gauge weight decomposition of the span

No change of basis is needed. The gauge torus is diagonal in the fundamental representation
of the `SU(2)` factor, so the two basis doublet directions are already weight vectors, with
weights `+1` and `-1` in the isospin normalization `2T₃`. A component `T d` therefore
carries the definite weight `wtWeight d`, the sum of the weights of its four indices, and
the span of the components is already the join of sixteen weight lines.

The weights that occur are those of the fourth tensor power of the `su(2)` fundamental,
`±4`, `±2` and `0` in isospin, with vanishing colour and hypercharge. The zero-weight piece
is spanned by the six components carrying two indices of each value, the multiplicity of
the zero weight in that tensor power.

The stronger typeclass assumptions are forced: `GaugeWeightDecomposition` lives in an
algebra and records multiplicativity of the representation, neither of which
`IsSU2QuadFundamental` needs, so both appear as extra arguments here.

-/

namespace IsSU2QuadFundamental

set_option linter.unusedVariables false

/-!

## C.1. The gauge torus in the fundamental representation

-/

/-- The gauge torus acts on a fundamental index by the character of the weight of that
  index, the off-diagonal entries vanishing. -/
lemma toSU2_gaugeTorusGen_diag (i : Fin 4) (a : Fin 2) :
    (GaugeGroupI.toSU2 (gaugeTorusGen i)).1 a a
      = (expI : ℂ) ^ GaugeWeight.coord (fundWeight a) i := by
  rw [toSU2_gaugeTorusGen_apply, if_pos rfl]

/-- The gauge weight carried by a component of a quad-fundamental family: the sum of the
  weights of its four indices. -/
def wtWeight (l : Fin 4 → Fin 2) : GaugeWeight :=
  fundWeight (l 0) + fundWeight (l 1) + fundWeight (l 2) + fundWeight (l 3)

/-!

## C.2. The components are weight vectors

-/

section Weights

variable {B : Type*} [AddCommGroup B] [Module ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {T : (Fin 4 → Fin 2) → B}

/-- Every component of a quad-fundamental family is a simultaneous eigenvector of the gauge
  torus, at the character of the sum of the weights of its four indices. -/
lemma repGauge_gaugeTorusGen (hT : IsSU2QuadFundamental B repGauge T) (l : Fin 4 → Fin 2)
    (i : Fin 4) :
    repGauge (gaugeTorusGen i) (T l)
      = ((expI : ℂ) ^ GaugeWeight.coord (wtWeight l) i) • T l := by
  rw [hT.repGauge_T (gaugeTorusGen i) l, Finset.sum_eq_single l]
  · congr 1
    simp only [Fin.prod_univ_four, toSU2_gaugeTorusGen_diag, wtWeight,
      GaugeWeight.coord_add]
    rw [zpow_add₀ expI_ne_zero, zpow_add₀ expI_ne_zero, zpow_add₀ expI_ne_zero]
  · intro a _ hal
    obtain ⟨j, hj⟩ := Function.ne_iff.1 hal
    rw [Finset.prod_eq_zero (Finset.mem_univ j)
      (by rw [toSU2_gaugeTorusGen_apply, if_neg hj]), zero_smul]
  · intro hl
    exact absurd (Finset.mem_univ l) hl

end Weights

/-!

## C.3. The decomposition

-/

section Decomposition

variable {B : Type*} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {T : (Fin 4 → Fin 2) → B}

variable (hT : IsSU2QuadFundamental B repGauge T)

/-- The gauge weight decomposition of the span of a quad-fundamental `su(2)` family. The
  span is the join of the lines through the sixteen components, and each of those carries
  the sum of the weights of its four indices. -/
@[implicit_reducible]
noncomputable def gaugeWeightDecomposition (hT : IsSU2QuadFundamental B repGauge T)
    (hmul : IsMulRep repGauge) : GaugeWeightDecomposition repGauge hT.span :=
  GaugeWeightDecomposition.copy
    (GaugeWeightDecomposition.iSup hmul fun d : Fin 4 → Fin 2 =>
      GaugeWeightDecomposition.spanSingleton hmul (T d) (wtWeight d)
        (hT.repGauge_gaugeTorusGen d))
    _ rfl

/-- The pieces of the decomposition: the weight-`w` piece is the join of the lines through
  those components whose weight is `w`. -/
lemma gaugeWeightDecomposition_piece (hmul : IsMulRep repGauge) (w : GaugeWeight) :
    (hT.gaugeWeightDecomposition hmul).piece w
      = ⨆ d : Fin 4 → Fin 2, (if w = wtWeight d then ℂ ∙ T d else ⊥) := rfl

/-- The support of the decomposition, before evaluation. -/
lemma gaugeWeightDecomposition_supp_eq (hmul : IsMulRep repGauge) :
    (hT.gaugeWeightDecomposition hmul).supp
      = Finset.univ.biUnion fun d : Fin 4 → Fin 2 =>
        ({wtWeight d} : Finset GaugeWeight) := rfl

/-- The gauge weights carried by a quad-fundamental `su(2)` family: the five weights of the
  fourth tensor power of the `su(2)` fundamental. Every one of them has vanishing colour
  and hypercharge, since the family carries weak isospin only. -/
lemma gaugeWeightDecomposition_supp (hmul : IsMulRep repGauge) :
    (hT.gaugeWeightDecomposition hmul).supp
      = {((0, 0, 4, 0) : GaugeWeight), (0, 0, 2, 0), (0, 0, 0, 0), (0, 0, -2, 0),
        (0, 0, -4, 0)} := by
  rw [hT.gaugeWeightDecomposition_supp_eq hmul]
  decide

/-!

## C.4. The zero-weight piece

A gauge invariant built from `T` is fixed by the torus, so it lies in the zero-weight
piece, which makes that piece worth describing explicitly. The weight of a component is the
sum of the isospin weights of its four indices, each `±1`, so it vanishes exactly when two
of the indices are `0` and two are `1`. That leaves six components, and the zero-weight
piece is the join of the six lines through them.

-/

/-- A component of a quad-fundamental family carries vanishing gauge weight precisely when
  two of its indices are `0` and two are `1`, the isospin weights then cancelling in
  pairs. -/
lemma wtWeight_eq_zero_iff (l : Fin 4 → Fin 2) :
    wtWeight l = 0 ↔ l = ![0, 0, 1, 1] ∨ l = ![1, 1, 0, 0] ∨ l = ![0, 1, 0, 1]
      ∨ l = ![1, 0, 1, 0] ∨ l = ![0, 1, 1, 0] ∨ l = ![1, 0, 0, 1] := by
  revert l
  decide

/-- The zero-weight piece of the gauge weight decomposition, explicitly: the join of the
  six lines through the components with two indices of each value, grouped into the three
  pairs that the Weyl element of section D exchanges. -/
lemma gaugeWeightDecomposition_piece_zero (hmul : IsMulRep repGauge) :
    (hT.gaugeWeightDecomposition hmul).piece 0
      = ((ℂ ∙ T ![0, 0, 1, 1] ⊔ ℂ ∙ T ![1, 1, 0, 0])
          ⊔ (ℂ ∙ T ![0, 1, 0, 1] ⊔ ℂ ∙ T ![1, 0, 1, 0]))
        ⊔ (ℂ ∙ T ![0, 1, 1, 0] ⊔ ℂ ∙ T ![1, 0, 0, 1]) := by
  rw [hT.gaugeWeightDecomposition_piece hmul]
  refine le_antisymm (iSup_le fun d => ?_) (sup_le (sup_le (sup_le ?_ ?_)
    (sup_le ?_ ?_)) (sup_le ?_ ?_))
  · split_ifs with hd
    · rcases (wtWeight_eq_zero_iff d).1 hd.symm with rfl | rfl | rfl | rfl | rfl | rfl
      · exact le_sup_of_le_left (le_sup_of_le_left le_sup_left)
      · exact le_sup_of_le_left (le_sup_of_le_left le_sup_right)
      · exact le_sup_of_le_left (le_sup_of_le_right le_sup_left)
      · exact le_sup_of_le_left (le_sup_of_le_right le_sup_right)
      · exact le_sup_of_le_right le_sup_left
      · exact le_sup_of_le_right le_sup_right
    · exact bot_le
  · exact le_iSup_of_le ![0, 0, 1, 1] (le_of_eq (if_pos (by decide)).symm)
  · exact le_iSup_of_le ![1, 1, 0, 0] (le_of_eq (if_pos (by decide)).symm)
  · exact le_iSup_of_le ![0, 1, 0, 1] (le_of_eq (if_pos (by decide)).symm)
  · exact le_iSup_of_le ![1, 0, 1, 0] (le_of_eq (if_pos (by decide)).symm)
  · exact le_iSup_of_le ![0, 1, 1, 0] (le_of_eq (if_pos (by decide)).symm)
  · exact le_iSup_of_le ![1, 0, 0, 1] (le_of_eq (if_pos (by decide)).symm)

/-- The first contraction lies in the zero-weight piece. It is gauge invariant, so in
  particular the torus fixes it. -/
lemma epsilonContraction₁₂_mem_piece_zero (hmul : IsMulRep repGauge) :
    hT.epsilonContraction₁₂ ∈ (hT.gaugeWeightDecomposition hmul).piece 0 :=
  GaugeWeightDecomposition.mem_zero_of_invariant _ hT.epsilonContraction₁₂_mem_span
    hT.repGauge_epsilonContraction₁₂

/-- The second contraction lies in the zero-weight piece. -/
lemma epsilonContraction₁₃_mem_piece_zero (hmul : IsMulRep repGauge) :
    hT.epsilonContraction₁₃ ∈ (hT.gaugeWeightDecomposition hmul).piece 0 :=
  GaugeWeightDecomposition.mem_zero_of_invariant _ hT.epsilonContraction₁₃_mem_span
    hT.repGauge_epsilonContraction₁₃

/-!

## D. The `SU(2)` permutation decomposition of the zero-weight piece

The gauge weight cannot separate the six zero-weight components: they all carry the same
weight. The Weyl element of the `SU(2)` factor separates them into three pairs. Its
fundamental matrix `!![0, -1; 1, 0]` exchanges the two doublet directions and carries a
sign with each `1` it meets, and a zero-weight component meets two of them, so the two
signs cancel and the Weyl element simply exchanges each component with the one obtained by
flipping all four of its indices.

Each of the three pairs is therefore graded into a grade-zero symmetric combination and a
grade-two antisymmetric one, and the grading of the whole zero-weight piece is the join of
the three. The grading is concentrated in the grades zero and two, as it must be for an
even number of doublet indices, and grade zero is the join of the three symmetric
combinations. Two of the three epsilon contractions are differences of those, so the sieve
is not yet sharp; section E closes the gap.

-/

/-- The Weyl grading of the plane spanned by a pair of vectors that the Weyl element
  exchanges: their sum has grade zero and their difference grade two. -/
noncomputable def swapPairSU2Perm {u v : B} (huv : repGauge gaugeSU2Perm u = v)
    (hvu : repGauge gaugeSU2Perm v = u) :
    SU2PermDecomposition repGauge (ℂ ∙ u ⊔ ℂ ∙ v) where
  piece k := if k = 0 then ℂ ∙ (u + v) else if k = 2 then ℂ ∙ (u - v) else ⊥
  piece_le := by
    intro k z hz
    rcases eq_or_ne k 0 with rfl | hk0
    · rw [if_pos rfl] at hz
      obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hz
      rw [map_smul, map_add, huv, hvu, su2PermSign_zero]
      module
    · rcases eq_or_ne k 2 with rfl | hk2
      · rw [if_neg hk0, if_pos rfl] at hz
        obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hz
        rw [map_smul, map_sub, huv, hvu, su2PermSign_two]
        module
      · rw [if_neg hk0, if_neg hk2, Submodule.mem_bot] at hz
        subst hz
        simp
  iSup_piece := by
    have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
    refine le_antisymm (iSup_le fun k => ?_) ?_
    · rcases hcases k with rfl | rfl | rfl | rfl
      · rw [if_pos rfl, Submodule.span_singleton_le_iff_mem]
        exact add_mem (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
          (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
      · rw [if_neg (by decide), if_pos rfl, Submodule.span_singleton_le_iff_mem]
        exact sub_mem (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
          (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
    · rw [← sup_span_sub_add u v]
      refine sup_le (le_iSup_of_le 2 (le_of_eq ?_)) (le_iSup_of_le 0 (le_of_eq ?_))
      · rw [if_neg (by decide : ¬(2 : ZMod 4) = 0), if_pos rfl]
      · rw [if_pos rfl]

/-- The Weyl element exchanges the two components of the first zero-weight pair. -/
lemma repGauge_gaugeSU2Perm_fst₁ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![0, 0, 1, 1]) = T ![1, 1, 0, 0] := by
  rw [hT.repGauge_T gaugeSU2Perm ![0, 0, 1, 1], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The Weyl element exchanges the two components of the first zero-weight pair, the other
  way round. -/
lemma repGauge_gaugeSU2Perm_snd₁ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![1, 1, 0, 0]) = T ![0, 0, 1, 1] := by
  rw [hT.repGauge_T gaugeSU2Perm ![1, 1, 0, 0], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The Weyl element exchanges the two components of the second zero-weight pair. -/
lemma repGauge_gaugeSU2Perm_fst₂ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![0, 1, 0, 1]) = T ![1, 0, 1, 0] := by
  rw [hT.repGauge_T gaugeSU2Perm ![0, 1, 0, 1], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The Weyl element exchanges the two components of the second zero-weight pair, the other
  way round. -/
lemma repGauge_gaugeSU2Perm_snd₂ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![1, 0, 1, 0]) = T ![0, 1, 0, 1] := by
  rw [hT.repGauge_T gaugeSU2Perm ![1, 0, 1, 0], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The Weyl element exchanges the two components of the third zero-weight pair. -/
lemma repGauge_gaugeSU2Perm_fst₃ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![0, 1, 1, 0]) = T ![1, 0, 0, 1] := by
  rw [hT.repGauge_T gaugeSU2Perm ![0, 1, 1, 0], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The Weyl element exchanges the two components of the third zero-weight pair, the other
  way round. -/
lemma repGauge_gaugeSU2Perm_snd₃ (hT : IsSU2QuadFundamental B repGauge T) :
    repGauge gaugeSU2Perm (T ![1, 0, 0, 1]) = T ![0, 1, 1, 0] := by
  rw [hT.repGauge_T gaugeSU2Perm ![1, 0, 0, 1], sum_pi_four]
  simp [Fin.sum_univ_two, Fin.prod_univ_four, toSU2_gaugeSU2Perm_apply]

/-- The symmetric combination of the first zero-weight pair. -/
def symComb₁ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 0, 1, 1] + T ![1, 1, 0, 0]

/-- The symmetric combination of the second zero-weight pair. -/
def symComb₂ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 1, 0, 1] + T ![1, 0, 1, 0]

/-- The symmetric combination of the third zero-weight pair. -/
def symComb₃ (hT : IsSU2QuadFundamental B repGauge T) : B :=
  T ![0, 1, 1, 0] + T ![1, 0, 0, 1]

/-- The second epsilon contraction is the difference of the first and third symmetric
  combinations. -/
lemma epsilonContraction₁₃_eq_sub (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₃ = hT.symComb₁ - hT.symComb₃ := by
  rw [epsilonContraction₁₃, symComb₁, symComb₃]
  abel

/-- The first epsilon contraction is the difference of the second and third symmetric
  combinations. -/
lemma epsilonContraction₁₂_eq_sub (hT : IsSU2QuadFundamental B repGauge T) :
    hT.epsilonContraction₁₂ = hT.symComb₂ - hT.symComb₃ := by
  rw [epsilonContraction₁₂, symComb₂, symComb₃]
  abel

/-- The `SU(2)` permutation decomposition of the zero-weight piece of the gauge weight
  decomposition: the Weyl element grades the six-dimensional space the gauge weight cannot
  split, one pair at a time. -/
noncomputable def zeroPieceSU2Perm (hT : IsSU2QuadFundamental B repGauge T)
    (hmul : IsMulRep repGauge) :
    SU2PermDecomposition repGauge ((hT.gaugeWeightDecomposition hmul).piece 0) :=
  SU2PermDecomposition.copy
    (((swapPairSU2Perm hT.repGauge_gaugeSU2Perm_fst₁
          hT.repGauge_gaugeSU2Perm_snd₁).sup
        (swapPairSU2Perm hT.repGauge_gaugeSU2Perm_fst₂
          hT.repGauge_gaugeSU2Perm_snd₂)).sup
      (swapPairSU2Perm hT.repGauge_gaugeSU2Perm_fst₃
        hT.repGauge_gaugeSU2Perm_snd₃))
    _ (hT.gaugeWeightDecomposition_piece_zero hmul)

/-- The grade-zero piece of the Weyl grading: the join of the three symmetric
  combinations. -/
lemma zeroPieceSU2Perm_piece_zero (hmul : IsMulRep repGauge) :
    (hT.zeroPieceSU2Perm hmul).piece 0
      = (ℂ ∙ hT.symComb₁ ⊔ ℂ ∙ hT.symComb₂) ⊔ ℂ ∙ hT.symComb₃ := rfl

/-- Every gauge invariant in the span of the components lies in the join of the three
  symmetric combinations. This is what the two gradings alone can see, and it is one
  dimension larger than the truth. -/
lemma mem_symComb_of_invariant (hmul : IsMulRep repGauge) {x : B} (hx : x ∈ hT.span)
    (hinv : ∀ g : GaugeGroupI, repGauge g x = x) :
    x ∈ (ℂ ∙ hT.symComb₁ ⊔ ℂ ∙ hT.symComb₂) ⊔ ℂ ∙ hT.symComb₃ := by
  rw [← hT.zeroPieceSU2Perm_piece_zero hmul]
  exact SU2PermDecomposition.mem_zero_of_invariant (hT.zeroPieceSU2Perm hmul)
    (GaugeWeightDecomposition.mem_zero_of_invariant _ hx hinv) hinv


/-!

## E. Cutting the sieve down to the epsilon contractions

The two gradings together leave the join of the three symmetric combinations, while section
B produced only two independent contractions inside it. The direction left over is the sum
of all three, the neutral state of the isospin-two multiplet in the fourth tensor power of
the fundamental, and no grading can discard it: a grading sees only an abelian subgroup,
and that state is fixed by the whole gauge torus and by the Weyl element alike.

The continuous symmetry does discard it. The rotation by a third of a turn about the
diagonal isospin axis cycles the three isospin axes, and the neutral states of the
isospin-two multiplet about three orthogonal axes sum to zero, being the three traceless
diagonal quadratic forms `diag (2, -1, -1)`, `diag (-1, 2, -1)` and `diag (-1, -1, 2)`.
Averaging over the cyclic group generated by that rotation therefore annihilates the extra
direction, while fixing the two contractions, and an invariant element is its own average.
This is the argument the Higgs sector runs at mass weight eight, where the same three
directions appear as the quartic monomials and the Fierz identity closes the orbit.

-/

/-- The coefficient family of the neutral state of the isospin-two multiplet: the
  indicator of the six components carrying two indices of each value. -/
def symCoeff (l : Fin 4 → Fin 2) : ℂ :=
  if (l 0).val + (l 1).val + (l 2).val + (l 3).val = 2 then 1 else 0

/-- A sum over families weighted by that indicator, written out: the second elementary
  symmetric function of the four pairs of matrix entries. -/
lemma sum_symCoeff_mul (M : Matrix (Fin 2) (Fin 2) ℂ) (b : Fin 4 → Fin 2) :
    ∑ l : Fin 4 → Fin 2, symCoeff l * ∏ i, M (b i) (l i)
      = M (b 0) 0 * M (b 1) 0 * M (b 2) 1 * M (b 3) 1
        + M (b 0) 0 * M (b 1) 1 * M (b 2) 0 * M (b 3) 1
        + M (b 0) 0 * M (b 1) 1 * M (b 2) 1 * M (b 3) 0
        + M (b 0) 1 * M (b 1) 0 * M (b 2) 0 * M (b 3) 1
        + M (b 0) 1 * M (b 1) 0 * M (b 2) 1 * M (b 3) 0
        + M (b 0) 1 * M (b 1) 1 * M (b 2) 0 * M (b 3) 0 := by
  rw [sum_pi_four]
  simp only [symCoeff, Fin.sum_univ_two, Fin.prod_univ_four, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.cons_val_three,
    Matrix.tail_cons, Fin.val_zero, Fin.val_one]
  norm_num
  ring

/-- The `SU(2)` matrix of the rotation by a third of a turn about the diagonal isospin
  axis, namely `(1 - i (σ₁ + σ₂ + σ₃)) / 2`. -/
noncomputable def cycMat : Matrix (Fin 2) (Fin 2) ℂ :=
  !![(1 - Complex.I) / 2, (-1 - Complex.I) / 2; (1 - Complex.I) / 2, (1 + Complex.I) / 2]

/-- The square of that matrix, the rotation by two thirds of a turn. -/
noncomputable def cycMatSq : Matrix (Fin 2) (Fin 2) ℂ :=
  !![(-1 - Complex.I) / 2, (-1 - Complex.I) / 2; (1 - Complex.I) / 2, (-1 + Complex.I) / 2]

/-- The rotation by a third of a turn is a special unitary matrix. -/
lemma cycMat_mem : cycMat ∈ specialUnitaryGroup (Fin 2) ℂ := by
  rw [Matrix.mem_specialUnitaryGroup_iff]
  refine ⟨?_, ?_⟩
  · rw [Matrix.mem_unitaryGroup_iff]
    ext a b
    fin_cases a <;> fin_cases b <;>
      simp [cycMat, Matrix.mul_apply, Fin.sum_univ_two, star_eq_conjTranspose,
        Matrix.conjTranspose_apply, map_div₀, map_ofNat, Complex.ext_iff] <;> norm_num
  · rw [cycMat, Matrix.det_fin_two_of]
    simp [Complex.ext_iff]
    norm_num

/-- The rotation by a third of a turn, as an element of the gauge group: trivial on colour
  and hypercharge. -/
noncomputable def cycGauge : GaugeGroupI := ⟨1, ⟨cycMat, cycMat_mem⟩, 1⟩

/-- The fundamental matrix of the rotation. -/
lemma toSU2_cycGauge : (GaugeGroupI.toSU2 cycGauge).1 = cycMat := rfl

/-- The fundamental matrix of its square. -/
lemma toSU2_cycGauge_mul_self :
    (GaugeGroupI.toSU2 (cycGauge * cycGauge)).1 = cycMatSq := by
  have h : (GaugeGroupI.toSU2 (cycGauge * cycGauge)).1 = cycMat * cycMat := by
    rw [map_mul]
    rfl
  rw [h]
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [cycMat, cycMatSq, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff] <;>
      norm_num

set_option maxHeartbeats 1000000 in
/-- The averaging identity, in coefficients. The neutral state of the isospin-two multiplet
  about the three isospin axes sums to zero, and the three summands here are that state
  about the third axis and its two images under the rotation. -/
lemma symCoeff_add_cyc_add_cycSq (a : Fin 4 → Fin 2) :
    symCoeff a + (∑ l : Fin 4 → Fin 2, symCoeff l * ∏ i, cycMat (a i) (l i))
      + ∑ l : Fin 4 → Fin 2, symCoeff l * ∏ i, cycMatSq (a i) (l i) = 0 := by
  obtain ⟨a₀, a₁, a₂, a₃, rfl⟩ : ∃ a₀ a₁ a₂ a₃, a = ![a₀, a₁, a₂, a₃] :=
    ⟨a 0, a 1, a 2, a 3, by funext i; fin_cases i <;> rfl⟩
  rw [sum_symCoeff_mul, sum_symCoeff_mul]
  fin_cases a₀ <;> fin_cases a₁ <;> fin_cases a₂ <;> fin_cases a₃ <;>
    simp [symCoeff, cycMat, cycMatSq, Complex.ext_iff] <;> norm_num

/-- The neutral state of the isospin-two multiplet, as a linear combination of the
  components: the sum of the three symmetric combinations. -/
lemma sum_symCoeff_smul (hT : IsSU2QuadFundamental B repGauge T) :
    ∑ l : Fin 4 → Fin 2, symCoeff l • T l
      = hT.symComb₁ + hT.symComb₂ + hT.symComb₃ := by
  rw [sum_pi_four, symComb₁, symComb₂, symComb₃]
  simp [symCoeff, Fin.sum_univ_two]
  abel

/-- Averaging over the cyclic group generated by the rotation by a third of a turn about
  the diagonal isospin axis. -/
noncomputable def cycAverage (repGauge : Representation ℂ GaugeGroupI B) : B →ₗ[ℂ] B :=
  LinearMap.id + repGauge cycGauge + repGauge (cycGauge * cycGauge)

/-- The average, written out. -/
lemma cycAverage_apply (x : B) :
    cycAverage repGauge x
      = x + repGauge cycGauge x + repGauge (cycGauge * cycGauge) x := rfl

/-- Averaging annihilates the neutral state of the isospin-two multiplet. -/
lemma cycAverage_symComb_sum (hT : IsSU2QuadFundamental B repGauge T) :
    cycAverage repGauge (hT.symComb₁ + hT.symComb₂ + hT.symComb₃) = 0 := by
  rw [← hT.sum_symCoeff_smul, cycAverage_apply, hT.repGauge_sum cycGauge symCoeff,
    hT.repGauge_sum (cycGauge * cycGauge) symCoeff]
  simp only [toSU2_cycGauge, toSU2_cycGauge_mul_self]
  rw [← Finset.sum_add_distrib, ← Finset.sum_add_distrib]
  refine Finset.sum_eq_zero fun a _ => ?_
  rw [← add_smul, ← add_smul, symCoeff_add_cyc_add_cycSq a, zero_smul]

/-- Averaging fixes a gauge invariant three times over. -/
lemma cycAverage_of_invariant {x : B} (hinv : ∀ g : GaugeGroupI, repGauge g x = x) :
    cycAverage repGauge x = (3 : ℂ) • x := by
  rw [cycAverage_apply, hinv, hinv]
  module

/-- Averaging sends the third symmetric combination to minus the sum of the two epsilon
  contractions. The three averages are then all in the plane the contractions span. -/
lemma cycAverage_symComb₃ (hT : IsSU2QuadFundamental B repGauge T) :
    cycAverage repGauge hT.symComb₃
      = -(hT.epsilonContraction₁₂ + hT.epsilonContraction₁₃) := by
  have h0 := hT.cycAverage_symComb_sum
  rw [map_add, map_add] at h0
  have e1 : cycAverage repGauge hT.symComb₁ - cycAverage repGauge hT.symComb₃
      = (3 : ℂ) • hT.epsilonContraction₁₃ := by
    rw [← map_sub, ← hT.epsilonContraction₁₃_eq_sub,
      cycAverage_of_invariant hT.repGauge_epsilonContraction₁₃]
  have e2 : cycAverage repGauge hT.symComb₂ - cycAverage repGauge hT.symComb₃
      = (3 : ℂ) • hT.epsilonContraction₁₂ := by
    rw [← map_sub, ← hT.epsilonContraction₁₂_eq_sub,
      cycAverage_of_invariant hT.repGauge_epsilonContraction₁₂]
  have h5 : (3 : ℂ) • cycAverage repGauge hT.symComb₃
      = (3 : ℂ) • (-(hT.epsilonContraction₁₂ + hT.epsilonContraction₁₃)) := by
    rw [show ((3 : ℂ) • cycAverage repGauge hT.symComb₃)
        = (cycAverage repGauge hT.symComb₁ + cycAverage repGauge hT.symComb₂
            + cycAverage repGauge hT.symComb₃)
          - (cycAverage repGauge hT.symComb₁ - cycAverage repGauge hT.symComb₃)
          - (cycAverage repGauge hT.symComb₂ - cycAverage repGauge hT.symComb₃)
        from by module, h0, e1, e2]
    module
  have h7 : ((3 : ℂ)⁻¹ * 3) • cycAverage repGauge hT.symComb₃
      = ((3 : ℂ)⁻¹ * 3) • (-(hT.epsilonContraction₁₂ + hT.epsilonContraction₁₃)) := by
    rw [mul_smul, mul_smul, h5]
  rwa [show ((3 : ℂ)⁻¹ * 3) = 1 from by norm_num, one_smul, one_smul] at h7

/-- Averaging sends the first symmetric combination into the plane spanned by the two
  epsilon contractions. -/
lemma cycAverage_symComb₁ (hT : IsSU2QuadFundamental B repGauge T) :
    cycAverage repGauge hT.symComb₁
      = (3 : ℂ) • hT.epsilonContraction₁₃
        - (hT.epsilonContraction₁₂ + hT.epsilonContraction₁₃) := by
  have e1 : cycAverage repGauge hT.symComb₁ - cycAverage repGauge hT.symComb₃
      = (3 : ℂ) • hT.epsilonContraction₁₃ := by
    rw [← map_sub, ← hT.epsilonContraction₁₃_eq_sub,
      cycAverage_of_invariant hT.repGauge_epsilonContraction₁₃]
  have h3 := hT.cycAverage_symComb₃
  have hsplit : cycAverage repGauge hT.symComb₁
      = (cycAverage repGauge hT.symComb₁ - cycAverage repGauge hT.symComb₃)
        + cycAverage repGauge hT.symComb₃ := by module
  rw [hsplit, e1, h3]
  module

/-- Averaging sends the second symmetric combination into the plane spanned by the two
  epsilon contractions. -/
lemma cycAverage_symComb₂ (hT : IsSU2QuadFundamental B repGauge T) :
    cycAverage repGauge hT.symComb₂
      = (3 : ℂ) • hT.epsilonContraction₁₂
        - (hT.epsilonContraction₁₂ + hT.epsilonContraction₁₃) := by
  have e2 : cycAverage repGauge hT.symComb₂ - cycAverage repGauge hT.symComb₃
      = (3 : ℂ) • hT.epsilonContraction₁₂ := by
    rw [← map_sub, ← hT.epsilonContraction₁₂_eq_sub,
      cycAverage_of_invariant hT.repGauge_epsilonContraction₁₂]
  have h3 := hT.cycAverage_symComb₃
  have hsplit : cycAverage repGauge hT.symComb₂
      = (cycAverage repGauge hT.symComb₂ - cycAverage repGauge hT.symComb₃)
        + cycAverage repGauge hT.symComb₃ := by module
  rw [hsplit, e2, h3]
  module

/-- Every gauge invariant in the span of the components is a combination of two of the
  three epsilon contractions. The gauge weight cuts the span down to the six components of
  vanishing weight, the Weyl element cuts those down to the three symmetric combinations,
  and averaging over the rotation cuts those down to the plane of the contractions. -/
lemma mem_sup_epsilonContraction_of_invariant (hmul : IsMulRep repGauge) {x : B}
    (hx : x ∈ hT.span) (hinv : ∀ g : GaugeGroupI, repGauge g x = x) :
    x ∈ ℂ ∙ hT.epsilonContraction₁₂ ⊔ ℂ ∙ hT.epsilonContraction₁₃ := by
  have hmem := hT.mem_symComb_of_invariant hmul hx hinv
  have hI₁₂ : hT.epsilonContraction₁₂
      ∈ ℂ ∙ hT.epsilonContraction₁₂ ⊔ ℂ ∙ hT.epsilonContraction₁₃ :=
    Submodule.mem_sup_left (Submodule.mem_span_singleton_self _)
  have hI₁₃ : hT.epsilonContraction₁₃
      ∈ ℂ ∙ hT.epsilonContraction₁₂ ⊔ ℂ ∙ hT.epsilonContraction₁₃ :=
    Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)
  have hmap : Submodule.map (cycAverage repGauge)
      ((ℂ ∙ hT.symComb₁ ⊔ ℂ ∙ hT.symComb₂) ⊔ ℂ ∙ hT.symComb₃)
      ≤ ℂ ∙ hT.epsilonContraction₁₂ ⊔ ℂ ∙ hT.epsilonContraction₁₃ := by
    simp only [Submodule.map_sup, Submodule.map_span, Set.image_singleton]
    refine sup_le (sup_le ?_ ?_) ?_ <;> rw [Submodule.span_singleton_le_iff_mem]
    · rw [hT.cycAverage_symComb₁]
      exact sub_mem (Submodule.smul_mem _ _ hI₁₃) (add_mem hI₁₂ hI₁₃)
    · rw [hT.cycAverage_symComb₂]
      exact sub_mem (Submodule.smul_mem _ _ hI₁₂) (add_mem hI₁₂ hI₁₃)
    · rw [hT.cycAverage_symComb₃]
      exact neg_mem (add_mem hI₁₂ hI₁₃)
  have hfin := hmap ⟨x, hmem, rfl⟩
  rw [cycAverage_of_invariant hinv] at hfin
  have hfin' := Submodule.smul_mem _ ((3 : ℂ)⁻¹) hfin
  rwa [smul_smul, show ((3 : ℂ)⁻¹ * 3) = 1 from by norm_num, one_smul] at hfin'

/-- Every gauge invariant in the span of the components is a linear combination of two of
  the three epsilon contractions, written out. -/
lemma exists_smul_epsilonContraction_of_invariant (hmul : IsMulRep repGauge) {x : B}
    (hx : x ∈ hT.span) (hinv : ∀ g : GaugeGroupI, repGauge g x = x) :
    ∃ c₁ c₂ : ℂ, x = c₁ • hT.epsilonContraction₁₂ + c₂ • hT.epsilonContraction₁₃ := by
  obtain ⟨y, hy, z, hz, rfl⟩ :=
    Submodule.mem_sup.1 (hT.mem_sup_epsilonContraction_of_invariant hmul hx hinv)
  obtain ⟨c₁, rfl⟩ := Submodule.mem_span_singleton.1 hy
  obtain ⟨c₂, rfl⟩ := Submodule.mem_span_singleton.1 hz
  exact ⟨c₁, c₂, rfl⟩

/-- The gauge invariants in the span of the components are exactly the combinations of the
  first two epsilon contractions. The three sieves of sections C, D and E bound them from
  above, and the contractions are themselves invariant and in the span, which bounds them
  from below. -/
lemma mem_span_and_invariant_iff (hmul : IsMulRep repGauge) (x : B) :
    (x ∈ hT.span ∧ ∀ g : GaugeGroupI, repGauge g x = x)
      ↔ x ∈ ℂ ∙ hT.epsilonContraction₁₂ ⊔ ℂ ∙ hT.epsilonContraction₁₃ := by
  refine ⟨fun h => hT.mem_sup_epsilonContraction_of_invariant hmul h.1 h.2, fun hx => ?_⟩
  obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.1 hx
  obtain ⟨c₁, rfl⟩ := Submodule.mem_span_singleton.1 hy
  obtain ⟨c₂, rfl⟩ := Submodule.mem_span_singleton.1 hz
  refine ⟨add_mem (Submodule.smul_mem _ _ hT.epsilonContraction₁₂_mem_span)
    (Submodule.smul_mem _ _ hT.epsilonContraction₁₃_mem_span), fun g => ?_⟩
  rw [map_add, map_smul, map_smul, hT.repGauge_epsilonContraction₁₂ g,
    hT.repGauge_epsilonContraction₁₃ g]

end Decomposition

end IsSU2QuadFundamental

end StandardModel
