/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.Jet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson.Basic
public import Mathlib.RingTheory.TensorProduct.Basic
public import Mathlib.LinearAlgebra.DirectSum.Finsupp
public import Physlib.Relativity.Tensors.ComplexTensor.Basic
public import Physlib.Mathematics.ConjModule
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
public import Physlib.Particles.LagrangianTheory.Basic
public import Physlib.Particles.StandardModel.Fermions.LeptonSinglet.JetAlgebra.MassDim
/-!
# Jet algebra for quantum electrodynamics

## i. Overview

The jet algebra of quantum electrodynamics: the algebra generated by the component
functions of the photon-like `U(1)` gauge boson (the B boson) and the charged
lepton, together with all their derivative coordinates. It is the tensor product of
the complexified B-boson jet algebra (a symmetric algebra, complexified so it can
be paired with the complex fermionic factor) and the charged-lepton jet algebra
(an exterior algebra).

The jet gauge group acts on each factor — by Maurer–Cartan substitutions on the
B-boson component functions, and linearly through the hypercharge character and its
derivatives on the lepton component functions — and hence on the full lepton–gauge-sector jet
algebra by the tensor product of the two actions.

-/

@[expose] public section

namespace LeptonGaugeSector
open TensorProduct StandardModel

inductive JetGenerators where
  | dB (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) : JetGenerators
  | dψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators
  | dbarψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators

abbrev JetAlgebra := (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] (LeptonSinglet.JetAlgebra)

namespace JetAlgebra

/-- The B-boson factor included into the lepton–gauge-sector jet algebra. -/
noncomputable abbrev inclB : (ℂ ⊗[ℝ] BBoson.JetAlgebra) →ₐ[ℂ] JetAlgebra :=
  Algebra.TensorProduct.includeLeft

/-- The charged-lepton factor included into the lepton–gauge-sector jet algebra. -/
noncomputable abbrev inclL : LeptonSinglet.JetAlgebra →ₐ[ℂ] JetAlgebra :=
  Algebra.TensorProduct.includeRight

/-- Polynomials pushed forward from the two tensor factors commute: the factors
  commute in the tensor product, and the polynomial variable is central. -/
lemma commute_mapAlgHom_inclB_inclL (p : Polynomial (ℂ ⊗[ℝ] BBoson.JetAlgebra))
    (q : Polynomial LeptonSinglet.JetAlgebra) :
    Commute (Polynomial.mapAlgHom inclB p) (Polynomial.mapAlgHom inclL q) := by
  induction p using Polynomial.induction_on' with
  | add p₁ p₂ h₁ h₂ => simpa [add_mul, mul_add] using h₁.add_left h₂
  | monomial m a =>
    induction q using Polynomial.induction_on' with
    | add q₁ q₂ h₁ h₂ => simpa [add_mul, mul_add] using h₁.add_right h₂
    | monomial n b =>
      show Polynomial.mapAlgHom inclB (Polynomial.monomial m a) *
          Polynomial.mapAlgHom inclL (Polynomial.monomial n b) = _
      simp only [Polynomial.mapAlgHom, AlgHom.coe_mk, Polynomial.coe_mapRingHom,
        Polynomial.map_monomial, Polynomial.monomial_mul_monomial]
      rw [Nat.add_comm m n]
      congr 1
      show (a ⊗ₜ[ℂ] (1 : LeptonSinglet.JetAlgebra)) * ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ₜ[ℂ] b)
        = ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ₜ[ℂ] b) * (a ⊗ₜ[ℂ] (1 : LeptonSinglet.JetAlgebra))
      rw [Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul,
        one_mul, mul_one, one_mul, mul_one]

/-!

## A. Elements associated with the generators

-/

noncomputable def ofGenerator (s : JetGenerators) : JetAlgebra :=
  match s with
  | JetGenerators.dB s μ =>
    (1 ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB s μ)) ⊗ₜ[ℂ] 1
  | JetGenerators.dψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dψ s α)
  | JetGenerators.dbarψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dbarψ s α)

scoped notation "[" s "]ₐ" => ofGenerator s

lemma ofGenerator_dψ_eq (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    ofGenerator (JetGenerators.dψ s α) =
      (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator
        (LeptonSinglet.JetGenerators.dψ s α) := rfl

lemma ofGenerator_B_eq (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) :
    ofGenerator (JetGenerators.dB s μ) =
      (1 ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator
        (BBoson.JetGenerators.dB s μ)) ⊗ₜ[ℂ] 1 := rfl

lemma ofGenerator_dbarψ_eq (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    ofGenerator (JetGenerators.dbarψ s α) =
      (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator
        (LeptonSinglet.JetGenerators.dbarψ s α) := rfl
end JetAlgebra

end LeptonGaugeSector
