/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.CovariantDeriv
/-!
# The covariant subalgebra of the lepton–gauge-sector jet algebra

The subalgebra generated by the covariant quantities of the theory — the derivatives of the
field strength and the covariant derivatives of the lepton and of its conjugate — together
with the linear-matter submodule and the covariant substitution used to study it.

The linear-matter submodule is spanned by a single matter component function times a B-boson
polynomial; the file records its closure under the total derivative and the covariant steps,
and the oddness of its elements in the fermionic case. The covariant substitution `covSubst`
replaces each plain fermionic generator by its covariant version, and is the change of
variables under which the covariant subalgebra is the image of the plain one.
-/

@[expose] public section


namespace LeptonGaugeSector
open TensorProduct StandardModel

namespace JetAlgebra

/-!

## A. The covariant subalgebra

The subalgebra generated by the covariant quantities of the theory: the derivatives of the
field strength — which for an abelian gauge field are already covariant, the field strength
being neutral — and the covariant derivatives of the lepton and of its conjugate.

Every gauge invariant lies in this subalgebra — that is
`mem_covariantAlgebra_of_forall_repJetGaugeGroupI_eq` — and conversely an element of it is
invariant as soon as it is fixed by the *constant* gauge transformations and by the Lorentz
group, since a jet of gauge transformations acts on these generators only through its value at
the base point.

-/

/-- The generators of the covariant subalgebra: the derivatives of the field strength together
  with the covariant derivatives of the lepton and of its conjugate. -/
noncomputable def invariantGenerators : Set JetAlgebra :=
  (Set.range fun p : Multiset (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) =>
      fieldStrengthDeriv p.1 p.2.1 p.2.2) ∪
    (Set.range fun p : List (Fin 1 ⊕ Fin 3) × Fin 2 => Dψ p.1 p.2) ∪
    (Set.range fun p : List (Fin 1 ⊕ Fin 3) × Fin 2 => Dbarψ p.1 p.2)

/-- The covariant subalgebra of the lepton–gauge-sector jet algebra: the subalgebra generated
  by the derivatives of the field strength and the covariant derivatives of the lepton and of
  its conjugate. -/
noncomputable def CovariantAlgebra : Subalgebra ℂ JetAlgebra :=
  Algebra.adjoin ℂ invariantGenerators

lemma mem_covariantAlgebra_iff {x : JetAlgebra} :
    x ∈ CovariantAlgebra ↔ x ∈ Algebra.adjoin ℂ invariantGenerators := Iff.rfl

lemma fieldStrengthDeriv_mem_covariantAlgebra (s : Multiset (Fin 1 ⊕ Fin 3))
    (μ ν : Fin 1 ⊕ Fin 3) : fieldStrengthDeriv s μ ν ∈ CovariantAlgebra :=
  Algebra.subset_adjoin (Or.inl (Or.inl ⟨(s, μ, ν), rfl⟩))

lemma Dψ_mem_covariantAlgebra (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dψ l α ∈ CovariantAlgebra :=
  Algebra.subset_adjoin (Or.inl (Or.inr ⟨(l, α), rfl⟩))

lemma Dbarψ_mem_covariantAlgebra (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dbarψ l α ∈ CovariantAlgebra :=
  Algebra.subset_adjoin (Or.inr ⟨(l, α), rfl⟩)

/-- Induction over the covariant subalgebra, with the three families of generators presented
  separately. This is the shape every proof about the covariant subalgebra wants: unfolding
  `Algebra.adjoin_induction` by hand forces the caller to take apart the union defining
  `invariantGenerators` at each use. -/
@[elab_as_elim]
lemma CovariantAlgebra.induction_on
    {motive : (x : JetAlgebra) → x ∈ CovariantAlgebra → Prop}
    (fieldStrength : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3),
      motive (fieldStrengthDeriv s μ ν) (fieldStrengthDeriv_mem_covariantAlgebra s μ ν))
    (lepton : ∀ (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2),
      motive (Dψ l α) (Dψ_mem_covariantAlgebra l α))
    (conjLepton : ∀ (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2),
      motive (Dbarψ l α) (Dbarψ_mem_covariantAlgebra l α))
    (algebraMap : ∀ r : ℂ, motive (algebraMap ℂ JetAlgebra r)
      (Subalgebra.algebraMap_mem CovariantAlgebra r))
    (add : ∀ (u v : JetAlgebra) (hu : u ∈ CovariantAlgebra) (hv : v ∈ CovariantAlgebra),
      motive u hu → motive v hv → motive (u + v) (Subalgebra.add_mem _ hu hv))
    (mul : ∀ (u v : JetAlgebra) (hu : u ∈ CovariantAlgebra) (hv : v ∈ CovariantAlgebra),
      motive u hu → motive v hv → motive (u * v) (Subalgebra.mul_mem _ hu hv))
    {x : JetAlgebra} (hx : x ∈ CovariantAlgebra) : motive x hx := by
  induction hx using Algebra.adjoin_induction with
  | mem z hz =>
    rcases hz with (⟨p, rfl⟩ | ⟨p, rfl⟩) | ⟨p, rfl⟩
    · exact fieldStrength p.1 p.2.1 p.2.2
    · exact lepton p.1 p.2
    · exact conjLepton p.1 p.2
  | algebraMap r => exact algebraMap r
  | add u v hu hv ihu ihv => exact add u v hu hv ihu ihv
  | mul u v hu hv ihu ihv => exact mul u v hu hv ihu ihv

/-!

## B. The linear-matter submodule

-/

/-- The linear-matter submodule: the elements of the jet algebra in which the
  matter coordinates appear exactly linearly, spanned by the products of a
  gauge-sector element with a single matter component function.

  The construction does not depend on the matter content. A jet algebra of this
  shape is `G ⊗[ℂ] ExteriorAlgebra ℂ M`, with `G` the gauge-sector algebra and
  `M` the space of matter component functions; the fermionic degree is the
  exterior grading of the second factor, and degree one is the image of
  `ExteriorAlgebra.ι`. For several matter species `M` is their direct sum and the
  same definition applies verbatim.

  This is the submodule the covariance argument for the covariant derivatives
  lives on. It is closed under the gauge group
  (`repJetGaugeGroupI_mem_LinearMatterSubmodule`), under the total derivative
  and under the covariant steps, and it is where the Maurer–Cartan anomaly
  operators close: in higher fermionic degree they do not, because the gauge
  action on the exterior algebra is an algebra map and so multiplies the
  hypercharge characters. -/
noncomputable def LinearMatterSubmodule : Submodule ℂ JetAlgebra :=
  Submodule.span ℂ {x : JetAlgebra | ∃ (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (m : LeptonSinglet.JetComponentSpace), x = p ⊗ⱼ ExteriorAlgebra.ι ℂ m}

/-- The spanning elements: a gauge-sector coefficient times a single matter
  component function. -/
lemma tmul_ι_mem_LinearMatterSubmodule (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (m : LeptonSinglet.JetComponentSpace) :
    p ⊗ⱼ ExteriorAlgebra.ι ℂ m ∈ LinearMatterSubmodule :=
  Submodule.subset_span ⟨p, m, rfl⟩

/-!

The remaining results in this section are specific to *fermionic* matter: they
express that the linear-matter elements are odd. Nothing above depends on them,
and nothing that follows — the closure of the submodule under the derivative,
the covariant steps, or the gauge group — does either. For bosonic matter the
matter factor is a symmetric rather than an exterior algebra, the same
definition of `LinearMatterSubmodule` applies with the corresponding canonical
inclusion, and only this anticommutation block is dropped.

-/

/-- Right distributivity on the jet algebra, with the multiplication forced to
  the `JetAlgebra` instance. Stating it explicitly keeps `rw` from having to
  match through the tensor-product instance path. -/
lemma distrib_add_mul (a b c : JetAlgebra) : (a + b) * c = a * c + b * c := by grind

/-- Left distributivity on the jet algebra; see `distrib_add_mul`. -/
lemma distrib_mul_add (a b c : JetAlgebra) : a * (b + c) = a * b + a * c := by grind

/-- Linear-matter elements anticommute against the spanning elements. -/
lemma tmul_ι_mul_add_swap_of_mem (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (m : LeptonSinglet.JetComponentSpace) {y : JetAlgebra}
    (hy : y ∈ LinearMatterSubmodule) :
    (p ⊗ⱼ ExteriorAlgebra.ι ℂ m) * y + y * (p ⊗ⱼ ExteriorAlgebra.ι ℂ m) = 0 := by
  have hd₁ := distrib_add_mul
  have hd₂ := distrib_mul_add
  have hz₁ : ∀ a : JetAlgebra, 0 * a = 0 := fun a => zero_mul a
  have hz₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  have hs₁ : ∀ (c : ℂ) (a b : JetAlgebra), (c • a) * b = c • (a * b) :=
    fun c a b => smul_mul_assoc c a b
  have hs₂ : ∀ (c : ℂ) (a b : JetAlgebra), a * (c • b) = c • (a * b) :=
    fun c a b => mul_smul_comm c a b
  induction hy using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨q, n, rfl⟩ := hz
    rw [tmul_mul_tmul, tmul_mul_tmul,
      mul_comm q p, tmul_add_tmul_right, ExteriorAlgebra.ι_add_mul_swap,
      tmul_zero]
  | zero => rw [hz₂, hz₁, add_zero]
  | add u v _ _ hu hv =>
    rw [hd₂, hd₁]
    calc (p ⊗ⱼ ExteriorAlgebra.ι ℂ m) * u + (p ⊗ⱼ ExteriorAlgebra.ι ℂ m) * v +
          (u * (p ⊗ⱼ ExteriorAlgebra.ι ℂ m) + v * (p ⊗ⱼ ExteriorAlgebra.ι ℂ m)) =
        ((p ⊗ⱼ ExteriorAlgebra.ι ℂ m) * u + u * (p ⊗ⱼ ExteriorAlgebra.ι ℂ m)) +
          ((p ⊗ⱼ ExteriorAlgebra.ι ℂ m) * v + v * (p ⊗ⱼ ExteriorAlgebra.ι ℂ m)) := by
          abel
      _ = 0 := by rw [hu, hv, add_zero]
  | smul c u _ hu =>
    rw [hs₂, hs₁, ← smul_add, hu, smul_zero]

/-- Linear-matter elements anticommute: they are odd. -/
lemma mul_add_swap_of_mem {x y : JetAlgebra} (hx : x ∈ LinearMatterSubmodule)
    (hy : y ∈ LinearMatterSubmodule) : x * y + y * x = 0 := by
  have hd₁ := distrib_add_mul
  have hd₂ := distrib_mul_add
  have hz₁ : ∀ a : JetAlgebra, 0 * a = 0 := fun a => zero_mul a
  have hz₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  have hs₁ : ∀ (c : ℂ) (a b : JetAlgebra), (c • a) * b = c • (a * b) :=
    fun c a b => smul_mul_assoc c a b
  have hs₂ : ∀ (c : ℂ) (a b : JetAlgebra), a * (c • b) = c • (a * b) :=
    fun c a b => mul_smul_comm c a b
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨p, m, rfl⟩ := hz
    exact tmul_ι_mul_add_swap_of_mem p m hy
  | zero => rw [hz₁, hz₂, add_zero]
  | add u v _ _ hu hv =>
    rw [hd₁, hd₂]
    calc u * y + v * y + (y * u + y * v) =
        (u * y + y * u) + (v * y + y * v) := by abel
      _ = 0 := by rw [hu, hv, add_zero]
  | smul c u _ hu =>
    rw [hs₁, hs₂, ← smul_add, hu, smul_zero]

/-- Linear-matter elements square to zero. -/
lemma mul_self_of_mem {x : JetAlgebra} (hx : x ∈ LinearMatterSubmodule) :
    x * x = 0 := by
  have h2 : (2 : ℂ) • (x * x) = 0 := by
    rw [two_smul]
    exact mul_add_swap_of_mem hx hx
  exact (smul_eq_zero.mp h2).resolve_left (by norm_num)

/-- The linear-matter submodule is preserved by the total derivative. -/
lemma jetDeriv_mem_LinearMatterSubmodule (μ : Fin 1 ⊕ Fin 3) {x : JetAlgebra}
    (hx : x ∈ LinearMatterSubmodule) : jetDeriv μ x ∈ LinearMatterSubmodule := by
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨p, m, rfl⟩ := hz
    rw [jetDeriv_tmul, LeptonSinglet.JetAlgebra.jetDeriv_ι]
    exact Submodule.add_mem _ (tmul_ι_mem_LinearMatterSubmodule _ _)
      (tmul_ι_mem_LinearMatterSubmodule _ _)
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | add u v _ _ hu hv => rw [map_add]; exact Submodule.add_mem _ hu hv
  | smul c u _ hu => rw [map_smul]; exact Submodule.smul_mem _ _ hu

/-- The linear-matter submodule is preserved by multiplication by a gauge-field
  generator, which lives in the bosonic factor. -/
lemma dB_mul_mem_LinearMatterSubmodule (μ : Fin 1 ⊕ Fin 3) {x : JetAlgebra}
    (hx : x ∈ LinearMatterSubmodule) :
    [JetGenerators.dB {} μ]ₐ * x ∈ LinearMatterSubmodule := by
  have hd₂ := distrib_mul_add
  have hz₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  have hs₂ : ∀ (c : ℂ) (a b : JetAlgebra), a * (c • b) = c • (a * b) :=
    fun c a b => mul_smul_comm c a b
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨p, m, rfl⟩ := hz
    rw [show ([JetGenerators.dB {} μ]ₐ : JetAlgebra) =
        ((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator
          (BBoson.JetGenerators.dB {} μ)) ⊗ⱼ
          (1 : LeptonSinglet.JetAlgebra) from rfl,
      tmul_mul_tmul, one_mul]
    exact tmul_ι_mem_LinearMatterSubmodule _ _
  | zero => rw [hz₂]; exact Submodule.zero_mem _
  | add u v _ _ hu hv => rw [hd₂]; exact Submodule.add_mem _ hu hv
  | smul c u _ hu => rw [hs₂]; exact Submodule.smul_mem _ _ hu

/-- The covariant derivatives of the lepton are linear in the matter fields. -/
lemma Dψ_mem_LinearMatterSubmodule (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dψ l α ∈ LinearMatterSubmodule := by
  induction l with
  | nil =>
    rw [show Dψ [] α = ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) ⊗ⱼ
      ExteriorAlgebra.ι ℂ (LeptonSinglet.JetComponentSpace.basis (.dψ {} α)) from rfl]
    exact tmul_ι_mem_LinearMatterSubmodule _ _
  | cons ν l ih =>
    simp only [Dψ_cons, covariantStep_apply]
    exact Submodule.sub_mem _ (jetDeriv_mem_LinearMatterSubmodule ν ih)
      (Submodule.smul_mem _ _ (dB_mul_mem_LinearMatterSubmodule ν ih))

/-- The covariant derivatives of the conjugate lepton are linear in the matter
  fields. -/
lemma Dbarψ_mem_LinearMatterSubmodule (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dbarψ l α ∈ LinearMatterSubmodule := by
  induction l with
  | nil =>
    rw [show Dbarψ [] α = ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) ⊗ⱼ
      ExteriorAlgebra.ι ℂ (LeptonSinglet.JetComponentSpace.basis (.dbarψ {} α)) from rfl]
    exact tmul_ι_mem_LinearMatterSubmodule _ _
  | cons ν l ih =>
    simp only [Dbarψ_cons, covariantStepBar_apply]
    exact Submodule.add_mem _ (jetDeriv_mem_LinearMatterSubmodule ν ih)
      (Submodule.smul_mem _ _ (dB_mul_mem_LinearMatterSubmodule ν ih))

/-- The covariant lepton derivatives anticommute with the conjugate covariant
  derivatives: both are odd elements of the linear-matter submodule. -/
lemma Dψ_mul_Dbarψ_anticomm (l l' : List (Fin 1 ⊕ Fin 3)) (α β : Fin 2) :
    Dψ l α * Dbarψ l' β = -(Dbarψ l' β * Dψ l α) :=
  eq_neg_of_add_eq_zero_left
    (mul_add_swap_of_mem (Dψ_mem_LinearMatterSubmodule l α)
      (Dbarψ_mem_LinearMatterSubmodule l' β))

lemma covGenerator_mem_LinearMatterSubmodule (g : LeptonSinglet.JetGenerators) :
    covGenerator g ∈ LinearMatterSubmodule := by
  cases g with
  | dψ s α => exact Dψ_mem_LinearMatterSubmodule (sortList s) α
  | dbarψ s α => exact Dbarψ_mem_LinearMatterSubmodule (sortList s) α

lemma covMap_mem_LinearMatterSubmodule (m : LeptonSinglet.JetComponentSpace) :
    covMap m ∈ LinearMatterSubmodule := by
  rw [covMap, Module.Basis.constr_apply]
  exact Submodule.sum_mem _ fun g _ =>
    Submodule.smul_mem _ _ (covGenerator_mem_LinearMatterSubmodule g)

lemma covMap_mul_self (m : LeptonSinglet.JetComponentSpace) :
    covMap m * covMap m = 0 :=
  mul_self_of_mem (covMap_mem_LinearMatterSubmodule m)

/-- The covariant substitution on the fermionic factor. -/
noncomputable def covExtHom : LeptonSinglet.JetAlgebra →ₐ[ℂ] JetAlgebra :=
  ExteriorAlgebra.lift ℂ ⟨covMap, covMap_mul_self⟩

@[simp]
lemma covExtHom_ι (m : LeptonSinglet.JetComponentSpace) :
    covExtHom (ExteriorAlgebra.ι ℂ m) = covMap m := by
  rw [covExtHom, ExteriorAlgebra.lift_ι_apply]

/-- Elements of the B-boson factor are central in the lepton–gauge-sector jet algebra. -/
lemma tmul_one_mul_comm (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) (y : JetAlgebra) :
    (p ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) * y =
      y * (p ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) := by
  have hd₁ : ∀ a b c : JetAlgebra, (a + b) * c = a * c + b * c := by grind
  have hd₂ := distrib_mul_add
  have hz₁ : ∀ a : JetAlgebra, 0 * a = 0 := fun a => zero_mul a
  have hz₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  induction y using JetAlgebra.induction_on with
  | zero => rw [hz₂, hz₁]
  | add a b ha hb => simp only [hd₁, hd₂, ha, hb]
  | tmul q l =>
    rw [tmul_mul_tmul, tmul_mul_tmul, mul_comm, one_mul, mul_one]

/-- The covariant substitution: the algebra endomorphism of the lepton–gauge-sector jet algebra
  fixing the B-boson factor and sending each plain fermionic generator to its
  covariant version. -/
noncomputable def covSubst : JetAlgebra →ₐ[ℂ] JetAlgebra :=
  Algebra.TensorProduct.lift Algebra.TensorProduct.includeLeft covExtHom
    (fun p y => (tmul_one_mul_comm p (covExtHom y)))

lemma covSubst_tmul (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) (l : LeptonSinglet.JetAlgebra) :
    covSubst (p ⊗ⱼ l) = (p ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) * covExtHom l := rfl

@[simp]
lemma covSubst_tmul_one (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) :
    covSubst (p ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) = p ⊗ⱼ 1 := by
  have h1 : covExtHom (1 : LeptonSinglet.JetAlgebra) = 1 := covExtHom.map_one
  have hmul : ∀ a : JetAlgebra, a * 1 = a := fun a => mul_one a
  rw [covSubst_tmul, h1, hmul]

@[simp]
lemma covSubst_one_tmul_ι (m : LeptonSinglet.JetComponentSpace) :
    covSubst ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ ExteriorAlgebra.ι ℂ m) =
      covMap m := by
  have hone : ∀ a : JetAlgebra, 1 * a = a := fun a => one_mul a
  rw [covSubst_tmul, covExtHom_ι, ← one_eq_tmul, hone]

end JetAlgebra

end LeptonGaugeSector
