/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Mathematics.TensorProduct
public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.GaugeAction
/-!
# The derivative-order filtration

The filtration of the lepton–gauge-sector jet algebra by the number of derivatives, the leading
behaviour of the covariant generators with respect to it, and the theorem that a
gauge-invariant element lies in the algebra generated by the invariant
generators, which the filtration is built to prove.
-/

@[expose] public section


namespace LeptonGaugeSector
open TensorProduct StandardModel

namespace JetAlgebra

/-!

### The derivative-degree filtration

The filtration of the lepton–gauge-sector jet algebra by the total derivative degree of the
fermionic factors: the span of B-coefficiented products of fermionic generators
of bounded total degree. The covariant substitution is unitriangular for this
filtration.

-/

/-- The generating set of the degree filtration. -/
def filtGen (d : ℕ) : Set JetAlgebra :=
  {z | ∃ (c : ℂ ⊗[ℝ] BBoson.JetAlgebra) (l : List LeptonSinglet.JetGenerators),
    (l.map genDeg).sum ≤ d ∧
    z = c ⊗ⱼ (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod}

/-- The generating set of the strict degree filtration. -/
def sfiltGen (d : ℕ) : Set JetAlgebra :=
  {z | ∃ (c : ℂ ⊗[ℝ] BBoson.JetAlgebra) (l : List LeptonSinglet.JetGenerators),
    (l.map genDeg).sum < d ∧
    z = c ⊗ⱼ (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod}

/-- The filtration of the lepton–gauge-sector jet algebra by total fermionic derivative degree. -/
noncomputable def filt (d : ℕ) : Submodule ℂ JetAlgebra :=
  Submodule.span ℂ (filtGen d)

/-- The strict filtration. -/
noncomputable def sfilt (d : ℕ) : Submodule ℂ JetAlgebra :=
  Submodule.span ℂ (sfiltGen d)

lemma filt_mono {d d' : ℕ} (h : d ≤ d') : filt d ≤ filt d' :=
  Submodule.span_mono fun z hz => by
    obtain ⟨c, l, hl, hze⟩ := hz
    exact ⟨c, l, hl.trans h, hze⟩

lemma sfilt_mono {d d' : ℕ} (h : d ≤ d') : sfilt d ≤ sfilt d' :=
  Submodule.span_mono fun z hz => by
    obtain ⟨c, l, hl, hze⟩ := hz
    exact ⟨c, l, hl.trans_le h, hze⟩

lemma sfilt_le_filt (d : ℕ) : sfilt d ≤ filt d :=
  Submodule.span_mono fun z hz => by
    obtain ⟨c, l, hl, hze⟩ := hz
    exact ⟨c, l, hl.le, hze⟩

lemma sfilt_zero : sfilt 0 = ⊥ := by
  rw [sfilt, show sfiltGen 0 = ∅ from Set.eq_empty_iff_forall_notMem.mpr (by
    rintro z ⟨c, l, hl, hze⟩
    omega), Submodule.span_empty]

lemma sfilt_succ (d : ℕ) : sfilt (d + 1) = filt d := by
  rw [sfilt, filt, show sfiltGen (d + 1) = filtGen d from Set.ext fun z =>
    ⟨fun ⟨c, l, hl, hze⟩ => ⟨c, l, Nat.lt_succ_iff.mp hl, hze⟩,
     fun ⟨c, l, hl, hze⟩ => ⟨c, l, Nat.lt_succ_iff.mpr hl, hze⟩⟩]

lemma mul_mem_filt {a b : ℕ} {x y : JetAlgebra} (hx : x ∈ filt a)
    (hy : y ∈ filt b) : x * y ∈ filt (a + b) := by
  have hd₁ : ∀ u v w : JetAlgebra, (u + v) * w = u * w + v * w := by grind
  have hd₂ : ∀ u v w : JetAlgebra, u * (v + w) = u * v + u * w := by grind
  have hz₁ : ∀ u : JetAlgebra, 0 * u = 0 := fun u => zero_mul u
  have hz₂ : ∀ u : JetAlgebra, u * 0 = 0 := fun u => mul_zero u
  have hs₁ : ∀ (r : ℂ) (u v : JetAlgebra), (r • u) * v = r • (u * v) :=
    fun r u v => smul_mul_assoc r u v
  have hs₂ : ∀ (r : ℂ) (u v : JetAlgebra), u * (r • v) = r • (u * v) :=
    fun r u v => mul_smul_comm r u v
  induction hx using Submodule.span_induction with
  | mem x' hx' =>
    induction hy using Submodule.span_induction with
    | mem y' hy' =>
      obtain ⟨c, l, hl, rfl⟩ := hx'
      obtain ⟨c', l', hl', rfl⟩ := hy'
      refine Submodule.subset_span ⟨c * c', l ++ l', ?_, ?_⟩
      · rw [List.map_append, List.sum_append]
        omega
      · rw [tmul_mul_tmul, List.map_append, List.prod_append]
    | zero => rw [hz₂]; exact zero_mem _
    | add u v hu hv ihu ihv => rw [hd₂]; exact add_mem ihu ihv
    | smul r u hu ih => rw [hs₂]; exact Submodule.smul_mem _ _ ih
  | zero => rw [hz₁]; exact zero_mem _
  | add u v hu hv ihu ihv => rw [hd₁]; exact add_mem ihu ihv
  | smul r u hu ih => rw [hs₁]; exact Submodule.smul_mem _ _ ih

lemma mul_mem_sfilt_left {a b : ℕ} {x y : JetAlgebra} (hx : x ∈ sfilt a)
    (hy : y ∈ filt b) : x * y ∈ sfilt (a + b) := by
  have hd₁ : ∀ u v w : JetAlgebra, (u + v) * w = u * w + v * w := by grind
  have hd₂ : ∀ u v w : JetAlgebra, u * (v + w) = u * v + u * w := by grind
  have hz₁ : ∀ u : JetAlgebra, 0 * u = 0 := fun u => zero_mul u
  have hz₂ : ∀ u : JetAlgebra, u * 0 = 0 := fun u => mul_zero u
  have hs₁ : ∀ (r : ℂ) (u v : JetAlgebra), (r • u) * v = r • (u * v) :=
    fun r u v => smul_mul_assoc r u v
  have hs₂ : ∀ (r : ℂ) (u v : JetAlgebra), u * (r • v) = r • (u * v) :=
    fun r u v => mul_smul_comm r u v
  induction hx using Submodule.span_induction with
  | mem x' hx' =>
    induction hy using Submodule.span_induction with
    | mem y' hy' =>
      obtain ⟨c, l, hl, rfl⟩ := hx'
      obtain ⟨c', l', hl', rfl⟩ := hy'
      refine Submodule.subset_span ⟨c * c', l ++ l', ?_, ?_⟩
      · rw [List.map_append, List.sum_append]
        omega
      · rw [tmul_mul_tmul, List.map_append, List.prod_append]
    | zero => rw [hz₂]; exact zero_mem _
    | add u v hu hv ihu ihv => rw [hd₂]; exact add_mem ihu ihv
    | smul r u hu ih => rw [hs₂]; exact Submodule.smul_mem _ _ ih
  | zero => rw [hz₁]; exact zero_mem _
  | add u v hu hv ihu ihv => rw [hd₁]; exact add_mem ihu ihv
  | smul r u hu ih => rw [hs₁]; exact Submodule.smul_mem _ _ ih

lemma mul_mem_sfilt_right {a b : ℕ} {x y : JetAlgebra} (hx : x ∈ filt a)
    (hy : y ∈ sfilt b) : x * y ∈ sfilt (a + b) := by
  have hd₁ : ∀ u v w : JetAlgebra, (u + v) * w = u * w + v * w := by grind
  have hd₂ : ∀ u v w : JetAlgebra, u * (v + w) = u * v + u * w := by grind
  have hz₁ : ∀ u : JetAlgebra, 0 * u = 0 := fun u => zero_mul u
  have hz₂ : ∀ u : JetAlgebra, u * 0 = 0 := fun u => mul_zero u
  have hs₁ : ∀ (r : ℂ) (u v : JetAlgebra), (r • u) * v = r • (u * v) :=
    fun r u v => smul_mul_assoc r u v
  have hs₂ : ∀ (r : ℂ) (u v : JetAlgebra), u * (r • v) = r • (u * v) :=
    fun r u v => mul_smul_comm r u v
  induction hx using Submodule.span_induction with
  | mem x' hx' =>
    induction hy using Submodule.span_induction with
    | mem y' hy' =>
      obtain ⟨c, l, hl, rfl⟩ := hx'
      obtain ⟨c', l', hl', rfl⟩ := hy'
      refine Submodule.subset_span ⟨c * c', l ++ l', ?_, ?_⟩
      · rw [List.map_append, List.sum_append]
        omega
      · rw [tmul_mul_tmul, List.map_append, List.prod_append]
    | zero => rw [hz₂]; exact zero_mem _
    | add u v hu hv ihu ihv => rw [hd₂]; exact add_mem ihu ihv
    | smul r u hu ih => rw [hs₂]; exact Submodule.smul_mem _ _ ih
  | zero => rw [hz₁]; exact zero_mem _
  | add u v hu hv ihu ihv => rw [hd₁]; exact add_mem ihu ihv
  | smul r u hu ih => rw [hs₁]; exact Submodule.smul_mem _ _ ih

lemma exists_forall_tmul_mem_filt (l : LeptonSinglet.JetAlgebra) :
    ∃ d, ∀ c : ℂ ⊗[ℝ] BBoson.JetAlgebra, c ⊗ⱼ l ∈ filt d := by
  induction l using ExteriorAlgebra.induction with
  | algebraMap r =>
    refine ⟨0, fun c => ?_⟩
    rw [Algebra.algebraMap_eq_smul_one, tmul_smul]
    refine Submodule.smul_mem _ _ (Submodule.subset_span ⟨c, [], by simp, ?_⟩)
    simp
  | ι m =>
    refine ⟨(LeptonSinglet.JetComponentSpace.basis.repr m).support.sup genDeg,
      fun c => ?_⟩
    have hm : ExteriorAlgebra.ι ℂ (M := LeptonSinglet.JetComponentSpace) m =
        (LeptonSinglet.JetComponentSpace.basis.repr m).sum
          (fun g r => r • LeptonSinglet.JetAlgebra.ofGenerator g) := by
      conv_lhs => rw [← LeptonSinglet.JetComponentSpace.basis.linearCombination_repr m]
      rw [Finsupp.linearCombination_apply, Finsupp.sum, Finsupp.sum, map_sum]
      refine Finset.sum_congr rfl fun g _ => ?_
      rw [map_smul]
      rfl
    rw [hm, Finsupp.sum, tmul_sum]
    refine Submodule.sum_mem _ fun g hg => ?_
    rw [tmul_smul]
    refine Submodule.smul_mem _ _ (filt_mono (Finset.le_sup hg)
      (Submodule.subset_span ⟨c, [g], by simp, ?_⟩))
    simp
  | mul x y hx hy =>
    obtain ⟨dx, hdx⟩ := hx
    obtain ⟨dy, hdy⟩ := hy
    refine ⟨dx + dy, fun c => ?_⟩
    rw [show c ⊗ⱼ (x * y) = (c ⊗ⱼ x) *
        ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ y) from by
      rw [tmul_mul_tmul, mul_one]]
    exact mul_mem_filt (hdx c) (hdy 1)
  | add x y hx hy =>
    obtain ⟨dx, hdx⟩ := hx
    obtain ⟨dy, hdy⟩ := hy
    refine ⟨max dx dy, fun c => ?_⟩
    rw [tmul_add]
    exact add_mem (filt_mono (le_max_left _ _) (hdx c))
      (filt_mono (le_max_right _ _) (hdy c))

/-- Every element of the lepton–gauge-sector jet algebra has bounded fermionic derivative
  degree. -/
lemma exists_mem_filt (x : JetAlgebra) : ∃ d, x ∈ filt d := by
  induction x using JetAlgebra.induction_on with
  | zero => exact ⟨0, zero_mem _⟩
  | add a b ha hb =>
    obtain ⟨d1, h1⟩ := ha
    obtain ⟨d2, h2⟩ := hb
    exact ⟨max d1 d2, add_mem (filt_mono (le_max_left _ _) h1)
      (filt_mono (le_max_right _ _) h2)⟩
  | tmul c l =>
    obtain ⟨d, hd⟩ := exists_forall_tmul_mem_filt l
    exact ⟨d, hd c⟩

/-- Strictly-lower-degree odd elements: B-coefficiented single fermionic
  generators of derivative degree less than `d`. -/
noncomputable def oddLow (d : ℕ) : Submodule ℂ JetAlgebra :=
  Submodule.span ℂ
    {z | ∃ (c : ℂ ⊗[ℝ] BBoson.JetAlgebra) (g : LeptonSinglet.JetGenerators),
      genDeg g < d ∧ z = c ⊗ⱼ LeptonSinglet.JetAlgebra.ofGenerator g}

lemma oddLow_le_sfilt (d : ℕ) : oddLow d ≤ sfilt d := by
  refine Submodule.span_le.mpr ?_
  rintro z ⟨c, g, hg, rfl⟩
  refine Submodule.subset_span ⟨c, [g], by simpa using hg, ?_⟩
  simp

lemma genDeg_shift (μ : Fin 1 ⊕ Fin 3) (g : LeptonSinglet.JetGenerators) :
    genDeg (LeptonSinglet.JetGenerators.shift μ g) = genDeg g + 1 := by
  cases g <;> simp [genDeg, LeptonSinglet.JetGenerators.shift]

/-- Multiplication by the gauge field acts on the B-boson coefficient of an odd
  element. -/
lemma dB_mul_tmul (μ : Fin 1 ⊕ Fin 3) (c : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (y : LeptonSinglet.JetAlgebra) :
    ([JetGenerators.dB {} μ]ₐ : JetAlgebra) * (c ⊗ⱼ y) =
      (((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB {} μ)) * c)
        ⊗ⱼ y := by
  have hone : ∀ z : LeptonSinglet.JetAlgebra, 1 * z = z := fun z => one_mul z
  rw [show ([JetGenerators.dB {} μ]ₐ : JetAlgebra) = ((1 : ℂ) ⊗ₜ[ℝ]
      BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB {} μ)) ⊗ⱼ
      (1 : LeptonSinglet.JetAlgebra) from rfl,
    tmul_mul_tmul, hone]

lemma covariantStep_mem_oddLow (μ : Fin 1 ⊕ Fin 3) {d : ℕ} {x : JetAlgebra}
    (hx : x ∈ oddLow d) : covariantStep μ x ∈ oddLow (d + 1) := by
  have hone : ∀ y : LeptonSinglet.JetAlgebra, 1 * y = y := fun y => one_mul y
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨c, g, hg, rfl⟩ := hz
    rw [covariantStep_apply, jetDeriv_tmul,
      LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator]
    refine sub_mem (add_mem ?_ ?_) (Submodule.smul_mem _ _ ?_)
    · exact Submodule.subset_span ⟨_, g, by omega, rfl⟩
    · exact Submodule.subset_span ⟨c, _, by rw [genDeg_shift]; omega, rfl⟩
    · rw [dB_mul_tmul]
      exact Submodule.subset_span ⟨_, g, by omega, rfl⟩
  | zero => rw [map_zero]; exact zero_mem _
  | add u v hu hv ihu ihv => rw [map_add]; exact add_mem ihu ihv
  | smul r u hu ih => rw [map_smul]; exact Submodule.smul_mem _ _ ih

lemma covariantStepBar_mem_oddLow (μ : Fin 1 ⊕ Fin 3) {d : ℕ} {x : JetAlgebra}
    (hx : x ∈ oddLow d) : covariantStepBar μ x ∈ oddLow (d + 1) := by
  have hone : ∀ y : LeptonSinglet.JetAlgebra, 1 * y = y := fun y => one_mul y
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨c, g, hg, rfl⟩ := hz
    rw [covariantStepBar_apply, jetDeriv_tmul,
      LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator]
    refine add_mem (add_mem ?_ ?_) (Submodule.smul_mem _ _ ?_)
    · exact Submodule.subset_span ⟨_, g, by omega, rfl⟩
    · exact Submodule.subset_span ⟨c, _, by rw [genDeg_shift]; omega, rfl⟩
    · rw [dB_mul_tmul]
      exact Submodule.subset_span ⟨_, g, by omega, rfl⟩
  | zero => rw [map_zero]; exact zero_mem _
  | add u v hu hv ihu ihv => rw [map_add]; exact add_mem ihu ihv
  | smul r u hu ih => rw [map_smul]; exact Submodule.smul_mem _ _ ih

/-- The covariant derivative of the lepton is its plain derivative generator up
  to strictly-lower-degree odd terms. -/
lemma Dψ_sub_mem_oddLow (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dψ l α - (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator (.dψ (↑l) α) ∈ oddLow l.length := by
  induction l with
  | nil =>
    rw [Dψ_nil, show ([JetGenerators.dψ {} α]ₐ : JetAlgebra) =
        (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ LeptonSinglet.JetAlgebra.ofGenerator
          (.dψ (↑([] : List (Fin 1 ⊕ Fin 3))) α) from by
      rw [Algebra.TensorProduct.one_def, Multiset.coe_nil, Multiset.empty_eq_zero]
      rfl, sub_self]
    exact zero_mem _
  | cons μ t ih =>
    set L : JetAlgebra := (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator (.dψ (↑t) α) with hL
    have hstep : Dψ (μ :: t) α = covariantStep μ L + covariantStep μ (Dψ t α - L) := by
      have h := (covariantStep μ).map_add L (Dψ t α - L)
      rw [add_sub_cancel] at h
      rw [Dψ_cons, h]
    have hleadEq : covariantStep μ L = (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
        LeptonSinglet.JetAlgebra.ofGenerator (.dψ (↑(μ :: t)) α) -
        ((6 : ℂ) * Complex.I) • (([JetGenerators.dB {} μ]ₐ : JetAlgebra) * L) := by
      rw [covariantStep_apply, hL, Algebra.TensorProduct.one_def, jetDeriv_tmul,
        LinearMap.baseChange_tmul, BBoson.JetAlgebra.jetDeriv_one,
        TensorProduct.tmul_zero, zero_tmul, zero_add,
        LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator,
        LeptonSinglet.JetGenerators.shift_dψ,
        show (↑t : Multiset (Fin 1 ⊕ Fin 3)) + {μ} = ↑(μ :: t) from by
          rw [add_comm, Multiset.singleton_add, Multiset.cons_coe]]
    have hmem1 : ([JetGenerators.dB {} μ]ₐ : JetAlgebra) * L ∈ oddLow (t.length + 1) := by
      rw [hL, dB_mul_tmul]
      refine Submodule.subset_span ⟨_, _, ?_, rfl⟩
      simp [genDeg, Multiset.coe_card]
    have hmem2 : covariantStep μ (Dψ t α - L) ∈ oddLow (t.length + 1) :=
      covariantStep_mem_oddLow μ ih
    have habel : ∀ A X Y : JetAlgebra, A - X + Y - A = Y - X := fun A X Y => by abel
    rw [hstep, hleadEq, habel]
    exact sub_mem hmem2 (Submodule.smul_mem _ _ hmem1)

/-- The covariant derivative of the conjugate lepton is its plain derivative
  generator up to strictly-lower-degree odd terms. -/
lemma Dbarψ_sub_mem_oddLow (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dbarψ l α - (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator (.dbarψ (↑l) α) ∈ oddLow l.length := by
  induction l with
  | nil =>
    rw [Dbarψ_nil, show ([JetGenerators.dbarψ {} α]ₐ : JetAlgebra) =
        (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ LeptonSinglet.JetAlgebra.ofGenerator
          (.dbarψ (↑([] : List (Fin 1 ⊕ Fin 3))) α) from by
      rw [Algebra.TensorProduct.one_def, Multiset.coe_nil, Multiset.empty_eq_zero]
      rfl, sub_self]
    exact zero_mem _
  | cons μ t ih =>
    set L : JetAlgebra := (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator (.dbarψ (↑t) α) with hL
    have hstep : Dbarψ (μ :: t) α =
        covariantStepBar μ L + covariantStepBar μ (Dbarψ t α - L) := by
      have h := (covariantStepBar μ).map_add L (Dbarψ t α - L)
      rw [add_sub_cancel] at h
      rw [Dbarψ_cons, h]
    have hleadEq : covariantStepBar μ L = (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
        LeptonSinglet.JetAlgebra.ofGenerator (.dbarψ (↑(μ :: t)) α) +
        ((6 : ℂ) * Complex.I) • (([JetGenerators.dB {} μ]ₐ : JetAlgebra) * L) := by
      rw [covariantStepBar_apply, hL, Algebra.TensorProduct.one_def, jetDeriv_tmul,
        LinearMap.baseChange_tmul, BBoson.JetAlgebra.jetDeriv_one,
        TensorProduct.tmul_zero, zero_tmul, zero_add,
        LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator,
        LeptonSinglet.JetGenerators.shift_dbarψ,
        show (↑t : Multiset (Fin 1 ⊕ Fin 3)) + {μ} = ↑(μ :: t) from by
          rw [add_comm, Multiset.singleton_add, Multiset.cons_coe]]
    have hmem1 : ([JetGenerators.dB {} μ]ₐ : JetAlgebra) * L ∈ oddLow (t.length + 1) := by
      rw [hL, dB_mul_tmul]
      refine Submodule.subset_span ⟨_, _, ?_, rfl⟩
      simp [genDeg, Multiset.coe_card]
    have hmem2 : covariantStepBar μ (Dbarψ t α - L) ∈ oddLow (t.length + 1) :=
      covariantStepBar_mem_oddLow μ ih
    have habel : ∀ A X Y : JetAlgebra, A + X + Y - A = X + Y := fun A X Y => by abel
    rw [hstep, hleadEq, habel]
    exact add_mem (Submodule.smul_mem _ _ hmem1) hmem2

/-- The covariant generator is the plain generator up to strictly-lower-degree
  odd terms. -/
lemma covGenerator_sub_mem_oddLow (g : LeptonSinglet.JetGenerators) :
    covGenerator g - (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator g ∈ oddLow (genDeg g) := by
  cases g with
  | dψ s α =>
    have h := Dψ_sub_mem_oddLow (sortList s) α
    rw [coe_sortList, length_sortList] at h
    exact h
  | dbarψ s α =>
    have h := Dbarψ_sub_mem_oddLow (sortList s) α
    rw [coe_sortList, length_sortList] at h
    exact h

lemma covGenerator_mem_filt (g : LeptonSinglet.JetGenerators) :
    covGenerator g ∈ filt (genDeg g) := by
  have h := sfilt_le_filt _ (oddLow_le_sfilt _ (covGenerator_sub_mem_oddLow g))
  have hA : (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator g ∈ filt (genDeg g) := by
    refine Submodule.subset_span ⟨1, [g], by simp, ?_⟩
    simp
  have h2 := add_mem hA h
  rwa [add_sub_cancel] at h2

lemma prod_covGenerator_mem_filt (l : List LeptonSinglet.JetGenerators) :
    (l.map covGenerator).prod ∈ filt ((l.map genDeg).sum) := by
  induction l with
  | nil =>
    simp only [List.map_nil, List.prod_nil, List.sum_nil]
    refine Submodule.subset_span ⟨1, [], by simp, ?_⟩
    rw [List.map_nil, List.prod_nil, one_eq_tmul]
  | cons g t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    exact mul_mem_filt (covGenerator_mem_filt g) ih

/-- The product of covariant generators is the corresponding product of plain
  generators up to strictly-lower-degree terms. -/
lemma prod_covGenerator_sub_mem_sfilt (l : List LeptonSinglet.JetGenerators) :
    (l.map covGenerator).prod - (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod ∈
      sfilt ((l.map genDeg).sum) := by
  induction l with
  | nil =>
    simp only [List.map_nil, List.prod_nil, List.sum_nil]
    rw [show ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ (1 : LeptonSinglet.JetAlgebra) :
        JetAlgebra) = 1 from (one_eq_tmul).symm, sub_self]
    exact zero_mem _
  | cons g t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    have hsub₁ : ∀ a b c : JetAlgebra, (a - b) * c = a * c - b * c := by grind
    have hsub₂ : ∀ a b c : JetAlgebra, a * (b - c) = a * b - a * c := by grind
    have hone : ∀ y : LeptonSinglet.JetAlgebra, 1 * y = y := fun y => one_mul y
    set A : JetAlgebra := (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator g with hA
    set Q : JetAlgebra := (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      (t.map LeptonSinglet.JetAlgebra.ofGenerator).prod with hQ
    have hAQ : A * Q = (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
        (LeptonSinglet.JetAlgebra.ofGenerator g *
          (t.map LeptonSinglet.JetAlgebra.ofGenerator).prod) := by
      rw [hA, hQ, tmul_mul_tmul, mul_one]
    have hkey : covGenerator g * (t.map covGenerator).prod -
        (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
          (LeptonSinglet.JetAlgebra.ofGenerator g *
            (t.map LeptonSinglet.JetAlgebra.ofGenerator).prod) =
        (covGenerator g - A) * (t.map covGenerator).prod +
          A * ((t.map covGenerator).prod - Q) := by
      rw [hsub₁, hsub₂, hAQ]
      abel
    rw [hkey]
    refine add_mem ?_ ?_
    · exact mul_mem_sfilt_left (oddLow_le_sfilt _ (covGenerator_sub_mem_oddLow g))
        (prod_covGenerator_mem_filt t)
    · have hAmem : A ∈ filt (genDeg g) := by
        rw [hA]
        refine Submodule.subset_span ⟨1, [g], by simp, ?_⟩
        simp
      exact mul_mem_sfilt_right hAmem ih

/-- Unitriangularity of the covariant substitution: it is the identity up to
  strictly-lower-degree terms. -/
lemma covSubst_sub_self_mem_sfilt {d : ℕ} {x : JetAlgebra} (hx : x ∈ filt d) :
    covSubst x - x ∈ sfilt d := by
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨c, l, hl, rfl⟩ := hz
    have hone : ∀ y : LeptonSinglet.JetAlgebra, 1 * y = y := fun y => one_mul y
    have honeB : ∀ p : ℂ ⊗[ℝ] BBoson.JetAlgebra, p * 1 = p := fun p => mul_one p
    have hgen : ∀ g : LeptonSinglet.JetGenerators,
        covExtHom (LeptonSinglet.JetAlgebra.ofGenerator g) = covGenerator g := by
      intro g
      rw [show LeptonSinglet.JetAlgebra.ofGenerator g = ExteriorAlgebra.ι ℂ
          (LeptonSinglet.JetComponentSpace.basis g) from rfl, covExtHom_ι, covMap_basis]
    have hlp : ∀ L : List LeptonSinglet.JetAlgebra,
        covExtHom L.prod = (L.map covExtHom).prod := by
      intro L
      induction L with
      | nil => exact covExtHom.map_one
      | cons a t iht =>
        have hm : covExtHom (a * t.prod) = covExtHom a * covExtHom t.prod :=
          map_mul covExtHom a t.prod
        rw [List.prod_cons, List.map_cons, List.prod_cons, hm, iht]
    have hcs : covSubst (c ⊗ⱼ (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod) =
        (c ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) * (l.map covGenerator).prod := by
      rw [covSubst_tmul]
      congr 1
      rw [hlp, List.map_map,
        show (⇑covExtHom ∘ LeptonSinglet.JetAlgebra.ofGenerator) = covGenerator from
          funext fun g => hgen g]
    have hz2 : c ⊗ⱼ (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod =
        (c ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) *
          ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
            (l.map LeptonSinglet.JetAlgebra.ofGenerator).prod) := by
      rw [tmul_mul_tmul, honeB, hone]
    have hsub₂ : ∀ a b c : JetAlgebra, a * (b - c) = a * b - a * c := by grind
    have hc1 : (c ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) ∈ filt 0 := by
      refine Submodule.subset_span ⟨c, [], by simp, ?_⟩
      simp
    have hfin := mul_mem_sfilt_right hc1 (prod_covGenerator_sub_mem_sfilt l)
    rw [zero_add] at hfin
    rw [hcs, hz2, ← hsub₂]
    exact sfilt_mono hl hfin
  | zero =>
    rw [map_zero, sub_zero]
    exact zero_mem _
  | add u v hu hv ihu ihv =>
    rw [map_add, show covSubst u + covSubst v - (u + v) =
      (covSubst u - u) + (covSubst v - v) from by abel]
    exact add_mem ihu ihv
  | smul r u hu ih =>
    rw [map_smul, show r • covSubst u - r • u = r • (covSubst u - u) from
      (smul_sub r _ _).symm]
    exact Submodule.smul_mem _ _ ih

lemma eq_zero_of_covSubst_eq_zero {d : ℕ} :
    ∀ {x : JetAlgebra}, x ∈ filt d → covSubst x = 0 → x = 0 := by
  induction d with
  | zero =>
    intro x hx h0
    have h := covSubst_sub_self_mem_sfilt hx
    rw [h0, zero_sub, sfilt_zero, Submodule.mem_bot, neg_eq_zero] at h
    exact h
  | succ d ih =>
    intro x hx h0
    have h := covSubst_sub_self_mem_sfilt hx
    rw [h0, zero_sub, sfilt_succ] at h
    exact ih (neg_mem_iff.mp h) h0

/-- The covariant substitution is injective. -/
lemma covSubst_injective : Function.Injective covSubst := by
  intro x y hxy
  obtain ⟨d, hd⟩ := exists_mem_filt (x - y)
  have h0 : covSubst (x - y) = 0 := by rw [map_sub, hxy, sub_self]
  exact sub_eq_zero.mp (eq_zero_of_covSubst_eq_zero hd h0)

lemma exists_covSubst_eq {d : ℕ} :
    ∀ {x : JetAlgebra}, x ∈ filt d → ∃ y, covSubst y = x := by
  induction d with
  | zero =>
    intro x hx
    have h := covSubst_sub_self_mem_sfilt hx
    rw [sfilt_zero, Submodule.mem_bot, sub_eq_zero] at h
    exact ⟨x, h⟩
  | succ d ih =>
    intro x hx
    have h := covSubst_sub_self_mem_sfilt hx
    rw [sfilt_succ] at h
    obtain ⟨y, hy⟩ := ih h
    exact ⟨x - y, by rw [map_sub, hy, sub_sub_cancel]⟩

/-- The covariant substitution is surjective. -/
lemma covSubst_surjective : Function.Surjective covSubst := by
  intro x
  obtain ⟨d, hd⟩ := exists_mem_filt x
  exact exists_covSubst_eq hd

/-- Every gauge invariant of the lepton–gauge-sector jet algebra lies in the algebra generated by
  the field-strength derivatives and the covariant derivatives of the lepton and
  its conjugate.

  After applying the covariant substitution, every `expUnitary` transformation with value `1` at
  the base point acts only on the complexified B-boson factor. The generic tensor fixed-submodule
  result extends the B-boson translation result across the lepton exterior-algebra factor. -/
lemma mem_covariantAlgebra_of_forall_repJetGaugeGroupI_eq
    (x : JetAlgebra) (hx : ∀ U, repJetGaugeGroupI U x = x) :
    x ∈ CovariantAlgebra := by
  classical
  obtain ⟨y, rfl⟩ := covSubst_surjective x
  -- The tensor inclusion and the B-boson field-strength generators, elaborated once: spelling
  -- either of them out at each use is what puts this proof over the default heartbeat budget.
  obtain ⟨mkT, hmkT⟩ : ∃ m, m = TensorProduct.mk ℂ (ℂ ⊗[ℝ] BBoson.JetAlgebra)
    LeptonSinglet.JetAlgebra := ⟨_, rfl⟩
  obtain ⟨Fs, hFs⟩ : ∃ s : Set (ℂ ⊗[ℝ] BBoson.JetAlgebra), s =
    Set.range fun p : Multiset (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) =>
      (1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.fieldStrengthDeriv p.1 p.2.1 p.2.2 := ⟨_, rfl⟩
  have hyU : ∀ (a : ℝ) (w : (Fin 1 ⊕ Fin 3) →₀ ℕ) (hw : w ≠ 0),
      TensorProduct.map (BBoson.JetAlgebra.complexRepJetGaugeGroupI
        (BBoson.JetAlgebra.expUnitary a w hw)) LinearMap.id y = y := by
    intro a w hw
    refine covSubst_injective ?_
    show covSubst (mapB (BBoson.JetAlgebra.complexRepJetGaugeGroupI
      (BBoson.JetAlgebra.expUnitary a w hw)) y) = covSubst y
    rw [← repJetGaugeGroupI_covSubst _ (BBoson.JetAlgebra.eval_expUnitary_u1 a w hw),
      hx]
  let Translation := {p : ℝ × ((Fin 1 ⊕ Fin 3) →₀ ℕ) // p.2 ≠ 0}
  let F : Translation → Module.End ℂ (ℂ ⊗[ℝ] BBoson.JetAlgebra) := fun p =>
    BBoson.JetAlgebra.complexRepJetGaugeGroupI
      (BBoson.JetAlgebra.expUnitary p.1.1 p.1.2 p.2)
  -- proved in the `rTensor` form the rewrite leaves behind, so that form is elaborated once
  have hyTensor : (show (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] LeptonSinglet.JetAlgebra from y) ∈
      Submodule.map₂ mkT (⨅ p : Translation, LinearMap.eqLocus (F p) LinearMap.id) ⊤ := by
    rw [hmkT, ← LinearMap.iInf_eqLocus_rTensor F]
    refine (Submodule.mem_iInf _).2 fun p => LinearMap.mem_eqLocus.mpr ?_
    simpa only [LinearMap.id_apply, LinearMap.rTensor_def, F] using hyU p.1.1 p.1.2 p.2
  have hB : (⨅ p : Translation, LinearMap.eqLocus (F p) LinearMap.id) ≤
      (Algebra.adjoin ℂ Fs).toSubmodule := by
    intro c hc
    rw [hFs]
    refine BBoson.JetAlgebra.mem_adjoin_of_forall_expUnitary_complex c fun a w hw => ?_
    simp only [Submodule.mem_iInf, LinearMap.mem_eqLocus, LinearMap.id_apply] at hc
    exact hc (⟨(a, w), hw⟩ : Translation)
  -- `obtain`, not `set`: `set` would rescan every hypothesis above for occurrences of this
  -- union, and the defeq checks that provokes are what exhausted the heartbeat budget.
  obtain ⟨S, hS⟩ : ∃ S : Set JetAlgebra, S = (Set.range fun p :
      Multiset (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) =>
        fieldStrengthDeriv p.1 p.2.1 p.2.2) ∪
    (Set.range fun g : LeptonSinglet.JetGenerators =>
      ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
        LeptonSinglet.JetAlgebra.ofGenerator g : JetAlgebra)) := ⟨_, rfl⟩
  have honeB : ∀ p : ℂ ⊗[ℝ] BBoson.JetAlgebra, p * 1 = p := fun p => mul_one p
  have honeL : ∀ l : LeptonSinglet.JetAlgebra, 1 * l = l := fun l => one_mul l
  have hone_tmul : ∀ l : LeptonSinglet.JetAlgebra,
      ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ l : JetAlgebra) ∈ Algebra.adjoin ℂ S := by
    intro l
    induction l using ExteriorAlgebra.induction with
    | algebraMap r =>
      rw [Algebra.algebraMap_eq_smul_one, tmul_smul]
      refine Subalgebra.smul_mem _ ?_ _
      rw [← one_eq_tmul]
      exact one_mem _
    | ι m =>
      have hm : ExteriorAlgebra.ι ℂ (M := LeptonSinglet.JetComponentSpace) m =
          (LeptonSinglet.JetComponentSpace.basis.repr m).sum
            (fun g r => r • LeptonSinglet.JetAlgebra.ofGenerator g) := by
        conv_lhs => rw [← LeptonSinglet.JetComponentSpace.basis.linearCombination_repr m]
        rw [Finsupp.linearCombination_apply, Finsupp.sum, Finsupp.sum, map_sum]
        refine Finset.sum_congr rfl fun g _ => ?_
        rw [map_smul]
        rfl
      rw [hm, Finsupp.sum, tmul_sum]
      refine sum_mem fun g _ => ?_
      rw [tmul_smul]
      refine Subalgebra.smul_mem _ (Algebra.subset_adjoin ?_) _
      rw [hS]
      exact Set.mem_union_right _ ⟨g, rfl⟩
    | mul u v hu hv =>
      rw [show ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ (u * v) : JetAlgebra) =
          ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ u) *
            ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ v) from by
        rw [tmul_mul_tmul, honeB]]
      exact mul_mem hu hv
    | add u v hu hv =>
      rw [tmul_add]
      exact add_mem hu hv
  have hleft : ∀ c ∈ Algebra.adjoin ℂ Fs,
      ((c ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) : JetAlgebra) ∈ Algebra.adjoin ℂ S := by
    intro c hc
    induction hc using Algebra.adjoin_induction with
    | mem z hz =>
      rw [hFs] at hz
      obtain ⟨p, rfl⟩ := hz
      refine Algebra.subset_adjoin ?_
      rw [hS]
      exact Set.mem_union_left _ ⟨p, rfl⟩
    | algebraMap z =>
      rw [Algebra.algebraMap_eq_smul_one, smul_tmul']
      refine Subalgebra.smul_mem _ ?_ _
      rw [← one_eq_tmul]
      exact one_mem _
    | add u v hu hv ihu ihv =>
      rw [add_tmul]
      exact add_mem ihu ihv
    | mul u v hu hv ihu ihv =>
      rw [show ((u * v) ⊗ⱼ (1 : LeptonSinglet.JetAlgebra) : JetAlgebra) =
          (u ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) *
            (v ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) from by
        rw [tmul_mul_tmul, honeL]]
      exact mul_mem ihu ihv
  -- the two inclusions are composed on the spot: naming the intermediate membership would cost
  -- another elaboration of the `map₂` type
  have hyMem : y ∈ Algebra.adjoin ℂ S := by
    apply (show Submodule.map₂ mkT (Algebra.adjoin ℂ Fs).toSubmodule ⊤ ≤
        (Algebra.adjoin ℂ S).toSubmodule from ?_) (Submodule.map₂_le_map₂_left hB hyTensor)
    rw [Submodule.map₂_le]
    intro c hc l _
    rw [hmkT]
    change c ⊗ⱼ l ∈ Algebra.adjoin ℂ S
    rw [show (c ⊗ⱼ l : JetAlgebra) =
        (c ⊗ⱼ (1 : LeptonSinglet.JetAlgebra)) *
          ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ l) from by
      rw [tmul_mul_tmul, honeB, honeL]]
    exact mul_mem (hleft c hc) (hone_tmul l)
  have himg : covSubst y ∈ (Algebra.adjoin ℂ S).map covSubst :=
    Subalgebra.mem_map.mpr ⟨y, hyMem, rfl⟩
  rw [AlgHom.map_adjoin] at himg
  refine Algebra.adjoin_le ?_ himg
  rintro z ⟨w, hw, rfl⟩
  rw [hS] at hw
  rcases hw with ⟨p, rfl⟩ | ⟨g, rfl⟩
  · show covSubst (fieldStrengthDeriv p.1 p.2.1 p.2.2) ∈
      Algebra.adjoin ℂ invariantGenerators
    rw [show (fieldStrengthDeriv p.1 p.2.1 p.2.2 : JetAlgebra) =
        ((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.fieldStrengthDeriv p.1 p.2.1 p.2.2) ⊗ⱼ
          (1 : LeptonSinglet.JetAlgebra) from rfl, covSubst_tmul_one]
    exact Algebra.subset_adjoin (show _ ∈ invariantGenerators from
      Set.mem_union_left _ (Set.mem_union_left _ ⟨p, rfl⟩))
  · show covSubst ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
      LeptonSinglet.JetAlgebra.ofGenerator g) ∈ Algebra.adjoin ℂ invariantGenerators
    rw [show ((1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ
        LeptonSinglet.JetAlgebra.ofGenerator g : JetAlgebra) =
        (1 : ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗ⱼ ExteriorAlgebra.ι ℂ
          (LeptonSinglet.JetComponentSpace.basis g) from rfl, covSubst_one_tmul_ι,
      covMap_basis]
    cases g with
    | dψ s α =>
      exact Algebra.subset_adjoin (show _ ∈ invariantGenerators from
        Set.mem_union_left _ (Set.mem_union_right _ ⟨(sortList s, α), rfl⟩))
    | dbarψ s α =>
      exact Algebra.subset_adjoin (show _ ∈ invariantGenerators from
        Set.mem_union_right _ ⟨(sortList s, α), rfl⟩)

end JetAlgebra

end LeptonGaugeSector
