/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.GaugeAction
/-!
# The invariant generators of the lepton–gauge-sector jet algebra

The generating set of the gauge invariants — the embedded field-strength
derivatives together with the covariant derivatives of the lepton and of its
conjugate — and the gauge action written as an algebra homomorphism, which is
what lets the invariance of a product be read off its factors.
-/

@[expose] public section

set_option maxHeartbeats 1000000

namespace LeptonGaugeSector
open TensorProduct StandardModel

namespace JetAlgebra

/-!

## Invariants of the lepton–gauge-sector jet algebra

The field strengths of the B boson, embedded in the lepton–gauge-sector jet algebra, are exactly
invariant; the covariant derivatives of the lepton and of its conjugate transform
by the hypercharge characters `u(0)^6` and `u(0)^{-6}` of the value of the gauge
jet at the base point. The gauge invariants of the lepton–gauge-sector jet algebra are contained
in the algebra generated by these three families.

-/

/-- The generating set of the invariants of the lepton–gauge-sector jet algebra: the embedded
  field-strength derivatives together with the covariant derivatives of the
  lepton and of its conjugate. -/
noncomputable def invariantGenerators : Set JetAlgebra :=
  (Set.range fun p : Multiset (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) × (Fin 1 ⊕ Fin 3) =>
      fieldStrengthDeriv p.1 p.2.1 p.2.2) ∪
    (Set.range fun p : List (Fin 1 ⊕ Fin 3) × Fin 2 => Dψ p.1 p.2) ∪
    (Set.range fun p : List (Fin 1 ⊕ Fin 3) × Fin 2 => Dbarψ p.1 p.2)

/-!

### The gauge action as an algebra homomorphism, and the intertwining

-/

/-- The complexified B-boson gauge action as an algebra homomorphism. -/
noncomputable def complexRepAlgHom (U : JetGaugeGroupI) :
    (ℂ ⊗[ℝ] BBoson.JetAlgebra) →ₐ[ℂ] (ℂ ⊗[ℝ] BBoson.JetAlgebra) :=
  AlgHom.ofLinearMap (BBoson.JetAlgebra.complexRepJetGaugeGroupI U)
    (by
      rw [Algebra.TensorProduct.one_def, BBoson.JetAlgebra.complexRepJetGaugeGroupI_tmul,
        BBoson.JetAlgebra.repJetGaugeGroupI_apply_one])
    (BBoson.JetAlgebra.complexRepJetGaugeGroupI_mul U)

@[simp]
lemma complexRepAlgHom_apply (U : JetGaugeGroupI) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) :
    complexRepAlgHom U p = BBoson.JetAlgebra.complexRepJetGaugeGroupI U p := rfl

/-- The gauge action as an algebra homomorphism. -/
noncomputable def repAlgHom (U : JetGaugeGroupI) : JetAlgebra →ₐ[ℂ] JetAlgebra :=
  Algebra.TensorProduct.map (complexRepAlgHom U)
    (ExteriorAlgebra.map (LeptonSinglet.JetComponentSpace.repJetGaugeGroupI U))

set_option maxHeartbeats 1000000 in
lemma repJetGaugeGroupI_eq_repAlgHom (U : JetGaugeGroupI) (x : JetAlgebra) :
    repJetGaugeGroupI U x = repAlgHom U x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add a b ha hb => rw [map_add, map_add, ha, hb]
  | tmul p l =>
    rw [show repJetGaugeGroupI U (p ⊗ₜ[ℂ] l) =
        (BBoson.JetAlgebra.complexRepJetGaugeGroupI U p) ⊗ₜ[ℂ]
          (LeptonSinglet.JetAlgebra.repJetGaugeGroupI U l) from by
      rw [repJetGaugeGroupI, Representation.tprod_apply, TensorProduct.map_tmul],
      repAlgHom, Algebra.TensorProduct.map_tmul, complexRepAlgHom_apply,
      LeptonSinglet.JetAlgebra.repJetGaugeGroupI_apply]

/-- The gauge action is multiplicative (term-level form avoiding elaboration
  blowups on the tensor stack). -/
lemma repJetGaugeGroupI_mul' (U : JetGaugeGroupI) (a b : JetAlgebra) :
    repJetGaugeGroupI U (a * b) =
      repJetGaugeGroupI U a * repJetGaugeGroupI U b :=
  (repJetGaugeGroupI_eq_repAlgHom U (a * b)).trans
    ((map_mul (repAlgHom U) a b).trans
      (congrArg₂ (· * ·) (repJetGaugeGroupI_eq_repAlgHom U a).symm
        (repJetGaugeGroupI_eq_repAlgHom U b).symm))

set_option maxHeartbeats 1000000 in
/-- On gauge jets with trivial value at the base point, the covariant elements
  are exactly invariant, so the gauge action intertwines the covariant
  substitution with the B-boson action alone. -/
lemma repJetGaugeGroupI_covSubst (U : JetGaugeGroupI) (hU : U.eval.2.2 = 1)
    (x : JetAlgebra) :
    repJetGaugeGroupI U (covSubst x) =
      covSubst (TensorProduct.map (BBoson.JetAlgebra.complexRepJetGaugeGroupI U)
        LinearMap.id x) := by
  have hcovfix : (repAlgHom U).comp covExtHom = covExtHom := by
    refine ExteriorAlgebra.hom_ext (LinearMap.ext fun m => ?_)
    simp only [AlgHom.comp_toLinearMap, LinearMap.coe_comp, Function.comp_apply,
      AlgHom.toLinearMap_apply, covExtHom_ι]
    have hlin : (repAlgHom U).toLinearMap ∘ₗ covMap = covMap := by
      refine LeptonSinglet.JetComponentSpace.basis.ext fun g => ?_
      rw [LinearMap.comp_apply, covMap_basis, AlgHom.toLinearMap_apply,
        ← repJetGaugeGroupI_eq_repAlgHom]
      cases g with
      | dψ s α =>
        rw [show covGenerator (.dψ s α) = Dψ (sortList s) α from rfl,
          repJetGaugeGroupI_Dψ, hU, one_pow, one_smul]
      | dbarψ s α =>
        rw [show covGenerator (.dbarψ s α) = Dbarψ (sortList s) α from rfl,
          repJetGaugeGroupI_Dbarψ, hU, star_one, one_pow, one_smul]
    exact LinearMap.congr_fun hlin m
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add a b ha hb => simp only [map_add, ha, hb]
  | tmul p l =>
    simp only [TensorProduct.map_tmul, LinearMap.id_coe, id_eq, covSubst_tmul]
    rw [repJetGaugeGroupI_eq_repAlgHom]
    have hm : repAlgHom U ((p ⊗ₜ[ℂ] (1 : LeptonSinglet.JetAlgebra)) * covExtHom l) =
        repAlgHom U (p ⊗ₜ[ℂ] (1 : LeptonSinglet.JetAlgebra)) *
          repAlgHom U (covExtHom l) := map_mul _ _ _
    have h1 : repAlgHom U (p ⊗ₜ[ℂ] (1 : LeptonSinglet.JetAlgebra)) =
        (BBoson.JetAlgebra.complexRepJetGaugeGroupI U p) ⊗ₜ[ℂ] 1 := by
      rw [repAlgHom, Algebra.TensorProduct.map_tmul, complexRepAlgHom_apply]
      congr 1
      exact (ExteriorAlgebra.map _).map_one
    have h2 : repAlgHom U (covExtHom l) = covExtHom l := AlgHom.congr_fun hcovfix l
    rw [hm, h1, h2]
end JetAlgebra

end LeptonGaugeSector
