/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.Grading.Hypercharge
/-!
# Where an invariant of mass weight eight lives

## i. Overview

A Lagrangian density of mass dimension four — mass weight eight — which is covariant is a
combination of terms drawn from exactly six sectors:

- the fermionic kinetic terms `D̄_μ ψ̄_α ψ_β` with the derivative on the conjugate lepton,
- the fermionic kinetic terms `ψ̄_α D_μ ψ_β` with the derivative on the lepton,
- the second derivatives of the field strength `∂_ρ ∂_τ F_{μν}`,
- the photon pairs `F_{μν} F_{μ'ν'}`,
- the like-species fermionic pairs `ψ_α D_μ ψ_β` and `ψ̄_α D̄_μ ψ̄_β`.

This is the sector decomposition. Only gauge covariance and the mass weight are used; each
sector is cut down to its invariants elsewhere, Lorentz invariance being what does that.

The last two sectors carry hypercharge `± 12`, so an invariant — being a charge singlet — has
no component in them, and the hypercharge grading removes them:
`mem_massDimFour_neutral_sectors_of_isInvariant` is the same statement with four sectors.

## ii. The argument

An invariant lies in the covariant subalgebra (`isInvariant_iff_mem_covariantAlgebra`), which
is generated by `∂_s F_{μν}`, `D_l ψ_α` and `D̄_l ψ̄_α`. These generators are homogeneous of
mass weights `4 + 2|s|`, `3 + 2|l|` and `3 + 2|l|`, so the subalgebra is spanned by monomials of
definite weight, `covWeightSpan`. Reading off the coefficient of `X ^ 8` of the mass-weight
polynomial — which on an element of weight eight returns the element itself — puts a covariant
term of weight eight in the span of the monomials of weight eight.

The weights of the generators are at least three, so such a monomial has at most two factors,
and the possible weight profiles are only `8`, `4 + 4` and `3 + 5`. A weight-`8` factor must be
bosonic, the fermionic weights being odd; `4 + 4` is a photon pair; and `3 + 5` is a pair of
fermionic generators, one undifferentiated and one carrying a single derivative, in one of the
four species pairings. There is no mixed profile: a bosonic factor of weight four and a
fermionic one of weight three sum to the odd number seven.

The two orders of each fermionic pair are traded for one another by anticommutativity, which is
why each of the four fermionic sectors is spanned by the products with the derivative on the
second factor alone.

The last step reads off the hypercharges. Only lists of length zero and one occur, so no
induction is needed: the field strength is neutral, lying in the B-boson factor, and
`Dψ_singleton` writes `D_μ ψ_α` as `∂_μ ψ_α - 6 i B_μ ψ_α`, both summands of charge `6` since
`B_μ` is neutral. Projecting the sector decomposition onto the charge singlets then fixes the
four neutral sectors and kills the two like-species ones.

## iii. Key results

- `JetAlgebra.covWeightSpan` : the span of the monomials of a given mass weight in the
  covariant generators.
- `JetAlgebra.mem_covWeightSpan_of_mem_covariantAlgebra` : an element of the covariant
  subalgebra which is homogeneous of mass weight `n` lies in the span of the monomials of
  weight `n`.
- `JetAlgebra.covWeightSpan_eight_le` : the weight-eight monomials are exhausted by the six
  families.
- `JetAlgebra.mem_massDimFour_sectors_of_isInvariant` : **the sector decomposition** — an
  invariant of mass weight eight lies in the join of the six sector spans.
- `JetAlgebra.Dψ_singleton_mem_hyperchargeSubmodule` and its three companions : the fermionic
  generators of weight three and five carry hypercharge `± 6`.
- `JetAlgebra.mem_massDimFour_neutral_sectors_of_isInvariant` : **the neutral sector
  decomposition** — an invariant of mass weight eight lies in the join of the four neutral
  sector spans.

## iv. Table of contents

- A. The covariant generators, indexed
- B. The span of the monomials of a given mass weight
- C. The mass-weight-eight monomials
- D. The sector decomposition
- E. The hypercharges of the covariant generators
- F. Removing the charged sectors

-/

@[expose] public section

namespace LeptonGaugeSector
open TensorProduct StandardModel

/-!

## A. The covariant generators, indexed

The generators of the covariant subalgebra form three families, and the classification below is
a case analysis on which family a factor comes from together with how many derivatives it
carries. An index type for the generators makes that case analysis available, and gives the
mass weight as a function of the index rather than of the element.

-/

/-- An index for the generators of the covariant subalgebra: a derivative of the field
  strength, a covariant derivative of the lepton, or a covariant derivative of the conjugate
  lepton. -/
inductive CovGen where
  /-- The field-strength derivative `∂_s F_{μν}`. -/
  | fieldStrength (s : Multiset (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) : CovGen
  /-- The covariant derivative `D_l ψ_α` of the lepton. -/
  | lepton (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) : CovGen
  /-- The covariant derivative `D̄_l ψ̄_α` of the conjugate lepton. -/
  | conjLepton (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) : CovGen

/-- The mass weight of a covariant generator: `4 + 2 |s|` for `∂_s F_{μν}`, and `3 + 2 |l|` for
  the covariant derivatives, matching `MassWeight`. -/
def CovGen.weight : CovGen → ℕ
  | .fieldStrength s _ _ => 4 + 2 * Multiset.card s
  | .lepton l _ => 3 + 2 * l.length
  | .conjLepton l _ => 3 + 2 * l.length

/-- Every covariant generator has mass weight at least three: this is what bounds the number of
  factors in a monomial of given weight. -/
lemma CovGen.three_le_weight (g : CovGen) : 3 ≤ g.weight := by
  cases g <;> simp only [CovGen.weight] <;> omega

namespace JetAlgebra

/-- The element of the jet algebra associated with a covariant-generator index. -/
noncomputable def covGenVal : CovGen → JetAlgebra
  | .fieldStrength s μ ν => fieldStrengthDeriv s μ ν
  | .lepton l α => Dψ l α
  | .conjLepton l α => Dbarψ l α

/-- The covariant generators generate the covariant subalgebra. -/
lemma covGenVal_mem_covariantAlgebra (g : CovGen) : covGenVal g ∈ CovariantAlgebra := by
  cases g with
  | fieldStrength s μ ν => exact fieldStrengthDeriv_mem_covariantAlgebra s μ ν
  | lepton l α => exact Dψ_mem_covariantAlgebra l α
  | conjLepton l α => exact Dbarψ_mem_covariantAlgebra l α

/-- Each covariant generator is homogeneous of its stated mass weight. -/
lemma covGenVal_mem_massWeightSubmodule (g : CovGen) :
    covGenVal g ∈ massWeightSubmodule g.weight := by
  cases g with
  | fieldStrength s μ ν => exact fieldStrengthDeriv_mem_massWeightSubmodule s μ ν
  | lepton l α => exact Dψ_mem_massWeightSubmodule l α
  | conjLepton l α => exact Dbarψ_mem_massWeightSubmodule l α

/-!

## B. The span of the monomials of a given mass weight

The covariant subalgebra is generated by homogeneous elements, so it is spanned by the monomials
of definite mass weight. Taking the weight-`n` part of an element of the subalgebra therefore
lands in the span of the weight-`n` monomials, and on an element which is already homogeneous of
weight `n` that operation is the identity.

-/

/-- The span of the products of covariant generators whose mass weights sum to `n`. -/
noncomputable def covWeightSpan (n : ℕ) : Submodule ℂ JetAlgebra :=
  Submodule.span ℂ {x : JetAlgebra | ∃ l : List CovGen, (l.map CovGen.weight).sum = n ∧
    x = (l.map covGenVal).prod}

/-- A product of covariant generators is homogeneous, of the sum of their weights. -/
lemma prod_covGenVal_mem_massWeightSubmodule (l : List CovGen) :
    (l.map covGenVal).prod ∈ massWeightSubmodule ((l.map CovGen.weight).sum) := by
  induction l with
  | nil =>
    simp only [List.map_nil, List.prod_nil, List.sum_nil]
    exact SetLike.GradedOne.one_mem
  | cons g t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    exact mul_mem_massWeightSubmodule (covGenVal_mem_massWeightSubmodule g) ih

/-- The monomials of weight `n` are homogeneous of mass weight `n`. -/
lemma covWeightSpan_le_massWeightSubmodule (n : ℕ) :
    covWeightSpan n ≤ massWeightSubmodule n := by
  refine Submodule.span_le.mpr ?_
  rintro x ⟨l, hl, rfl⟩
  exact hl ▸ prod_covGenVal_mem_massWeightSubmodule l

/-- The unit is a monomial of weight zero: the empty product. -/
lemma one_mem_covWeightSpan_zero : (1 : JetAlgebra) ∈ covWeightSpan 0 :=
  Submodule.subset_span ⟨[], by simp, by simp⟩

/-- A covariant generator is a monomial of its own weight. -/
lemma covGenVal_mem_covWeightSpan (g : CovGen) : covGenVal g ∈ covWeightSpan g.weight :=
  Submodule.subset_span ⟨[g], by simp, by simp⟩

/-- Weights add under multiplication of monomials: the index lists concatenate. -/
lemma mul_mem_covWeightSpan {m n : ℕ} {x y : JetAlgebra} (hx : x ∈ covWeightSpan m)
    (hy : y ∈ covWeightSpan n) : x * y ∈ covWeightSpan (m + n) := by
  have hd₁ : ∀ u v w : JetAlgebra, (u + v) * w = u * w + v * w := distrib_add_mul
  have hd₂ : ∀ u v w : JetAlgebra, u * (v + w) = u * v + u * w := distrib_mul_add
  have hz₁ : ∀ u : JetAlgebra, 0 * u = 0 := fun u => zero_mul u
  have hz₂ : ∀ u : JetAlgebra, u * 0 = 0 := fun u => mul_zero u
  have hs₁ : ∀ (r : ℂ) (u v : JetAlgebra), (r • u) * v = r • (u * v) :=
    fun r u v => smul_mul_assoc r u v
  have hs₂ : ∀ (r : ℂ) (u v : JetAlgebra), u * (r • v) = r • (u * v) :=
    fun r u v => mul_smul_comm r u v
  induction hx using Submodule.span_induction with
  | mem x' hx' =>
    induction hy using Submodule.span_induction with
    | mem y' hy' =>
      obtain ⟨l, hl, rfl⟩ := hx'
      obtain ⟨l', hl', rfl⟩ := hy'
      refine Submodule.subset_span ⟨l ++ l', ?_, ?_⟩
      · rw [List.map_append, List.sum_append, hl, hl']
      · rw [List.map_append, List.prod_append]
    | zero => rw [hz₂]; exact zero_mem _
    | add u v _ _ ihu ihv => rw [hd₂]; exact add_mem ihu ihv
    | smul r u _ ih => rw [hs₂]; exact Submodule.smul_mem _ _ ih
  | zero => rw [hz₁]; exact zero_mem _
  | add u v _ _ ihu ihv => rw [hd₁]; exact add_mem ihu ihv
  | smul r u _ ih => rw [hs₁]; exact Submodule.smul_mem _ _ ih

/-- The join of the monomial spans is closed under multiplication. -/
lemma mul_mem_iSup_covWeightSpan {x y : JetAlgebra} (hx : x ∈ ⨆ n, covWeightSpan n)
    (hy : y ∈ ⨆ n, covWeightSpan n) : x * y ∈ ⨆ n, covWeightSpan n := by
  have hd₁ : ∀ u v w : JetAlgebra, (u + v) * w = u * w + v * w := distrib_add_mul
  have hd₂ : ∀ u v w : JetAlgebra, u * (v + w) = u * v + u * w := distrib_mul_add
  induction hx using Submodule.iSup_induction' with
  | mem m u hu =>
    induction hy using Submodule.iSup_induction' with
    | mem n v hv => exact Submodule.mem_iSup_of_mem _ (mul_mem_covWeightSpan hu hv)
    | zero => rw [mul_zero]; exact zero_mem _
    | add v w _ _ ihv ihw => rw [hd₂]; exact add_mem ihv ihw
  | zero => rw [zero_mul]; exact zero_mem _
  | add u v _ _ ihu ihv => rw [hd₁]; exact add_mem ihu ihv

/-- Every element of the covariant subalgebra is a sum of monomials of definite mass weight. -/
lemma mem_iSup_covWeightSpan_of_mem_covariantAlgebra {x : JetAlgebra}
    (hx : x ∈ CovariantAlgebra) : x ∈ ⨆ n, covWeightSpan n := by
  induction hx using CovariantAlgebra.induction_on with
  | fieldStrength s μ ν =>
    exact Submodule.mem_iSup_of_mem _
      (covGenVal_mem_covWeightSpan (CovGen.fieldStrength s μ ν))
  | lepton l α =>
    exact Submodule.mem_iSup_of_mem _ (covGenVal_mem_covWeightSpan (CovGen.lepton l α))
  | conjLepton l α =>
    exact Submodule.mem_iSup_of_mem _ (covGenVal_mem_covWeightSpan (CovGen.conjLepton l α))
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one]
    exact Submodule.smul_mem _ _ (Submodule.mem_iSup_of_mem 0 one_mem_covWeightSpan_zero)
  | add u v _ _ ihu ihv => exact add_mem ihu ihv
  | mul u v _ _ ihu ihv => exact mul_mem_iSup_covWeightSpan ihu ihv

/-- Taking the weight-`m` part of a sum of monomials of definite weight leaves the monomial
  span: each summand either survives unchanged or is killed. -/
lemma coeff_massWeightPoly_mem_covWeightSpan {x : JetAlgebra}
    (hx : x ∈ ⨆ n, covWeightSpan n) (m : ℕ) :
    (massWeightPoly x).coeff m ∈ covWeightSpan m := by
  induction hx using Submodule.iSup_induction' with
  | mem n u hu =>
    by_cases hmn : m = n
    · subst hmn
      rwa [coeff_massWeightPoly_of_mem (covWeightSpan_le_massWeightSubmodule m hu)]
    · rw [coeff_massWeightPoly_of_mem_ne (fun h => hmn h.symm)
        (covWeightSpan_le_massWeightSubmodule n hu)]
      exact zero_mem _
  | zero => rw [map_zero, Polynomial.coeff_zero]; exact zero_mem _
  | add u v _ _ ihu ihv => rw [map_add, Polynomial.coeff_add]; exact add_mem ihu ihv

/-- An element of the covariant subalgebra which is homogeneous of mass weight `n` lies in the
  span of the monomials of weight `n`. -/
lemma mem_covWeightSpan_of_mem_covariantAlgebra {n : ℕ} {x : JetAlgebra}
    (hmem : x ∈ CovariantAlgebra) (hx : x ∈ massWeightSubmodule n) : x ∈ covWeightSpan n := by
  have h := coeff_massWeightPoly_mem_covWeightSpan
    (mem_iSup_covWeightSpan_of_mem_covariantAlgebra hmem) n
  rwa [coeff_massWeightPoly_of_mem hx] at h

/-!

## C. The mass-weight-eight monomials

Every generator has weight at least three, so a monomial of weight eight has at most two
factors. A single factor of weight eight must be a field strength, the fermionic weights being
odd; and eight splits as `4 + 4` or `3 + 5` only, a bosonic factor of weight four and a
fermionic one of weight three summing to the odd number seven. So the weight-eight monomials
are the second derivatives of the field strength, the photon pairs, and the products of an
undifferentiated fermionic generator with a singly-differentiated one, in each of the four
species pairings; the order of the two fermionic factors is normalised by anticommutativity.

-/

/-- The covariant lepton derivatives anticommute among themselves: they are odd elements of the
  linear-matter submodule. -/
lemma Dψ_mul_Dψ_anticomm (l l' : List (Fin 1 ⊕ Fin 3)) (α β : Fin 2) :
    Dψ l α * Dψ l' β = -(Dψ l' β * Dψ l α) :=
  eq_neg_of_add_eq_zero_left
    (mul_add_swap_of_mem (Dψ_mem_LinearMatterSubmodule l α)
      (Dψ_mem_LinearMatterSubmodule l' β))

/-- The conjugate covariant lepton derivatives anticommute among themselves. -/
lemma Dbarψ_mul_Dbarψ_anticomm (l l' : List (Fin 1 ⊕ Fin 3)) (α β : Fin 2) :
    Dbarψ l α * Dbarψ l' β = -(Dbarψ l' β * Dbarψ l α) :=
  eq_neg_of_add_eq_zero_left
    (mul_add_swap_of_mem (Dbarψ_mem_LinearMatterSubmodule l α)
      (Dbarψ_mem_LinearMatterSubmodule l' β))

/-- **The weight-eight monomials.** A monomial of mass weight eight in the covariant generators
  is a second derivative of the field strength, a photon pair, or a product of two fermionic
  generators one of which carries a single derivative. The six families are presented as
  membership hypotheses so that the caller may take the target submodule to be any join
  containing them. -/
lemma covWeightSpan_eight_le {W : Submodule ℂ JetAlgebra}
    (hbar : ∀ (α : Fin 2) (μ : Fin 1 ⊕ Fin 3) (β : Fin 2), Dbarψ [μ] α * Dψ [] β ∈ W)
    (hkin : ∀ (α : Fin 2) (μ : Fin 1 ⊕ Fin 3) (β : Fin 2), Dbarψ [] α * Dψ [μ] β ∈ W)
    (hdd : ∀ ρ τ μ ν : Fin 1 ⊕ Fin 3, fieldStrengthDeriv {ρ, τ} μ ν ∈ W)
    (hff : ∀ μ ν μ' ν' : Fin 1 ⊕ Fin 3,
      fieldStrengthDeriv {} μ ν * fieldStrengthDeriv {} μ' ν' ∈ W)
    (hpp : ∀ (α : Fin 2) (μ : Fin 1 ⊕ Fin 3) (β : Fin 2), Dψ [] α * Dψ [μ] β ∈ W)
    (hbb : ∀ (α : Fin 2) (μ : Fin 1 ⊕ Fin 3) (β : Fin 2), Dbarψ [] α * Dbarψ [μ] β ∈ W) :
    covWeightSpan 8 ≤ W := by
  refine Submodule.span_le.mpr ?_
  rintro x ⟨l, hl, rfl⟩
  rcases l with _ | ⟨a, _ | ⟨b, _ | ⟨c, t⟩⟩⟩
  · simp at hl
  · simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, add_zero] at hl
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      SetLike.mem_coe]
    cases a with
    | fieldStrength s μ ν =>
      have hs : Multiset.card s = 2 := by simp only [CovGen.weight] at hl; omega
      obtain ⟨ρ, τ, rfl⟩ := Multiset.card_eq_two.mp hs
      exact hdd ρ τ μ ν
    | lepton l α => exfalso; simp only [CovGen.weight] at hl; omega
    | conjLepton l α => exfalso; simp only [CovGen.weight] at hl; omega
  · simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil, add_zero] at hl
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      SetLike.mem_coe]
    have hpair : ∀ (l l' : List (Fin 1 ⊕ Fin 3)), 3 + 2 * l.length + (3 + 2 * l'.length) = 8 →
        (l = [] ∧ ∃ μ, l' = [μ]) ∨ ((∃ μ, l = [μ]) ∧ l' = []) := by
      intro l l' h
      by_cases hl0 : l.length = 0
      · exact Or.inl ⟨List.length_eq_zero_iff.mp hl0,
          List.length_eq_one_iff.mp (by omega)⟩
      · exact Or.inr ⟨List.length_eq_one_iff.mp (by omega),
          List.length_eq_zero_iff.mp (by omega)⟩
    cases a with
    | fieldStrength s μ ν =>
      cases b with
      | fieldStrength s' μ' ν' =>
        have hs : Multiset.card s = 0 ∧ Multiset.card s' = 0 := by
          simp only [CovGen.weight] at hl; omega
        obtain rfl := Multiset.card_eq_zero.mp hs.1
        obtain rfl := Multiset.card_eq_zero.mp hs.2
        exact hff μ ν μ' ν'
      | lepton l α => exfalso; simp only [CovGen.weight] at hl; omega
      | conjLepton l α => exfalso; simp only [CovGen.weight] at hl; omega
    | lepton l α =>
      cases b with
      | fieldStrength s' μ' ν' => exfalso; simp only [CovGen.weight] at hl; omega
      | lepton l' β =>
        show Dψ l α * Dψ l' β ∈ W
        simp only [CovGen.weight] at hl
        rcases hpair l l' (by omega) with ⟨rfl, ν, rfl⟩ | ⟨⟨ν, rfl⟩, rfl⟩
        · exact hpp α ν β
        · rw [Dψ_mul_Dψ_anticomm]
          exact neg_mem (hpp β ν α)
      | conjLepton l' β =>
        show Dψ l α * Dbarψ l' β ∈ W
        rw [Dψ_mul_Dbarψ_anticomm]
        refine neg_mem ?_
        simp only [CovGen.weight] at hl
        rcases hpair l' l (by omega) with ⟨rfl, ν, rfl⟩ | ⟨⟨ν, rfl⟩, rfl⟩
        · exact hkin β ν α
        · exact hbar β ν α
    | conjLepton l α =>
      cases b with
      | fieldStrength s' μ' ν' => exfalso; simp only [CovGen.weight] at hl; omega
      | lepton l' β =>
        show Dbarψ l α * Dψ l' β ∈ W
        simp only [CovGen.weight] at hl
        rcases hpair l l' (by omega) with ⟨rfl, ν, rfl⟩ | ⟨⟨ν, rfl⟩, rfl⟩
        · exact hkin α ν β
        · exact hbar α ν β
      | conjLepton l' β =>
        show Dbarψ l α * Dbarψ l' β ∈ W
        simp only [CovGen.weight] at hl
        rcases hpair l l' (by omega) with ⟨rfl, ν, rfl⟩ | ⟨⟨ν, rfl⟩, rfl⟩
        · exact hbb α ν β
        · rw [Dbarψ_mul_Dbarψ_anticomm]
          exact neg_mem (hbb β ν α)
  · exfalso
    have ha := a.three_le_weight
    have hb := b.three_le_weight
    have hc := c.three_le_weight
    simp only [List.map_cons, List.sum_cons] at hl
    omega

/-!

## D. The sector decomposition

Assembling the two halves: an invariant lies in the covariant subalgebra, so if it is
homogeneous of mass weight eight it lies in the span of the weight-eight monomials, and those
are exhausted by the six families.

The two like-species families `ψψ` and `ψ̄ψ̄` carry hypercharge `± 12` and so contain no
invariant; they are kept here because nothing but covariance and the mass weight has been used
to get this far.

-/

/-- **Where a covariant term of mass dimension four lives.** An element of the covariant
  subalgebra which is homogeneous of mass weight eight — mass dimension four — lies in the join
  of the six sector spans: the two fermionic kinetic sectors, the second derivatives of the
  field strength, the photon pairs, and the two like-species fermionic pairs. -/
theorem mem_massDimFour_sectors_of_mem_covariantAlgebra {x : JetAlgebra}
    (hmem : x ∈ CovariantAlgebra) (h8 : x ∈ massWeightSubmodule 8) :
    x ∈ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [μ] α * Dψ [] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dψ [μ] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ ρ τ μ ν, y = fieldStrengthDeriv {ρ, τ} μ ν}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ μ ν μ' ν',
          y = fieldStrengthDeriv {} μ ν * fieldStrengthDeriv {} μ' ν'}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dψ [] α * Dψ [μ] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dbarψ [μ] β} := by
  refine covWeightSpan_eight_le ?_ ?_ ?_ ?_ ?_ ?_
    (mem_covWeightSpan_of_mem_covariantAlgebra hmem h8)
  · exact fun α μ β => Submodule.mem_sup_left (Submodule.mem_sup_left
      (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_left
        (Submodule.subset_span ⟨α, μ, β, rfl⟩)))))
  · exact fun α μ β => Submodule.mem_sup_left (Submodule.mem_sup_left
      (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_right
        (Submodule.subset_span ⟨α, μ, β, rfl⟩)))))
  · exact fun ρ τ μ ν => Submodule.mem_sup_left (Submodule.mem_sup_left
      (Submodule.mem_sup_left (Submodule.mem_sup_right
        (Submodule.subset_span ⟨ρ, τ, μ, ν, rfl⟩))))
  · exact fun μ ν μ' ν' => Submodule.mem_sup_left (Submodule.mem_sup_left
      (Submodule.mem_sup_right (Submodule.subset_span ⟨μ, ν, μ', ν', rfl⟩)))
  · exact fun α μ β => Submodule.mem_sup_left (Submodule.mem_sup_right
      (Submodule.subset_span ⟨α, μ, β, rfl⟩))
  · exact fun α μ β => Submodule.mem_sup_right (Submodule.subset_span ⟨α, μ, β, rfl⟩)

/-- **Where an invariant of mass dimension four lives.** An invariant of mass weight eight —
  mass dimension four — lies in the join of the six sector spans.

  Only gauge invariance is used, and only through the covariant subalgebra
  (`isInvariant_iff_mem_covariantAlgebra`); Lorentz invariance plays no part here. It is what
  cuts each sector down to its invariants: the two kinetic sectors to the kinetic terms, the
  photon pairs to the Maxwell and theta terms, the second derivatives of the field strength to
  zero, and — by hypercharge — the two like-species sectors to zero. -/
theorem mem_massDimFour_sectors_of_isInvariant {x : JetAlgebra} (hx : IsInvariant x)
    (h8 : x ∈ massWeightSubmodule 8) :
    x ∈ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [μ] α * Dψ [] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dψ [μ] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ ρ τ μ ν, y = fieldStrengthDeriv {ρ, τ} μ ν}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ μ ν μ' ν',
          y = fieldStrengthDeriv {} μ ν * fieldStrengthDeriv {} μ' ν'}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dψ [] α * Dψ [μ] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dbarψ [μ] β} :=
  mem_massDimFour_sectors_of_mem_covariantAlgebra
    ((isInvariant_iff_mem_covariantAlgebra x).mp hx).1 h8

/-!

## E. The hypercharges of the covariant generators

To remove the two like-species sectors their hypercharge is needed, and hence the hypercharge
of each generator occurring in a weight-eight monomial. Those are few: the field-strength
derivatives, which lie in the neutral bosonic factor, and the covariant derivatives along a
list of length zero or one. The latter are written out by `Dψ_singleton` and `Dbarψ_singleton`
as a generator plus a gauge-field term, and the gauge field is neutral, so both summands carry
the charge of the fermionic generator. No induction along the list is needed, and hence no
statement that the total derivative preserves the hypercharge grading.

-/

/-- Hypercharges add, with the sum evaluated: this is `mul_mem_hyperchargeSubmodule` in the form
  the products below want it. -/
lemma mul_mem_hyperchargeSubmodule_of_add_eq {p q r : ℤ} (hr : p + q = r) {x y : JetAlgebra}
    (hx : x ∈ hyperchargeSubmodule p) (hy : y ∈ hyperchargeSubmodule q) :
    x * y ∈ hyperchargeSubmodule r :=
  hr ▸ mul_mem_hyperchargeSubmodule hx hy

/-- The lepton component function carries hypercharge `6`. -/
lemma Dψ_nil_mem_hyperchargeSubmodule (α : Fin 2) : Dψ [] α ∈ hyperchargeSubmodule 6 := by
  rw [Dψ_nil]
  exact ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dψ {} α)

/-- The first covariant derivative of the lepton carries hypercharge `6`: the gauge-field term
  `- 6 i B_μ ψ_α` it adds to `∂_μ ψ_α` is neutral times charge `6`. -/
lemma Dψ_singleton_mem_hyperchargeSubmodule (μ : Fin 1 ⊕ Fin 3) (α : Fin 2) :
    Dψ [μ] α ∈ hyperchargeSubmodule 6 := by
  rw [Dψ_singleton]
  refine Submodule.sub_mem _ (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dψ {μ} α))
    (Submodule.smul_mem _ _ (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num [Hypercharge])
      (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dB {} μ))
      (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dψ {} α))))

/-- The conjugate-lepton component function carries hypercharge `-6`. -/
lemma Dbarψ_nil_mem_hyperchargeSubmodule (α : Fin 2) :
    Dbarψ [] α ∈ hyperchargeSubmodule (-6) := by
  rw [Dbarψ_nil]
  exact ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dbarψ {} α)

/-- The first covariant derivative of the conjugate lepton carries hypercharge `-6`. -/
lemma Dbarψ_singleton_mem_hyperchargeSubmodule (μ : Fin 1 ⊕ Fin 3) (α : Fin 2) :
    Dbarψ [μ] α ∈ hyperchargeSubmodule (-6) := by
  rw [Dbarψ_singleton]
  refine Submodule.add_mem _
    (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dbarψ {μ} α))
    (Submodule.smul_mem _ _ (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num [Hypercharge])
      (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dB {} μ))
      (ofGenerator_mem_hyperchargeSubmodule (JetGenerators.dbarψ {} α))))

/-- Elements of the B-boson factor are neutral. -/
lemma inclB_mem_hyperchargeSubmodule (a : ℂ ⊗[ℝ] BBoson.JetAlgebra) :
    inclB a ∈ hyperchargeSubmodule 0 := by
  rw [mem_hyperchargeSubmodule, hyperchargePoly_inclB, LaurentPolynomial.T_zero, mul_one]

/-- The field strength is neutral: for an abelian gauge field it lies in the B-boson factor. -/
lemma fieldStrengthDeriv_mem_hyperchargeSubmodule (s : Multiset (Fin 1 ⊕ Fin 3))
    (μ ν : Fin 1 ⊕ Fin 3) : fieldStrengthDeriv s μ ν ∈ hyperchargeSubmodule 0 :=
  inclB_mem_hyperchargeSubmodule ((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.fieldStrengthDeriv s μ ν)

/-!

## F. Removing the charged sectors

An invariant is a charge singlet, so it is fixed by `chargeComponent 0`. Applying that
projection to the sector decomposition leaves the four neutral families untouched and kills the
two like-species ones, which are homogeneous of hypercharge `± 12`.

-/

/-- **Where an invariant of mass dimension four lives.** An invariant of mass weight eight —
  mass dimension four — lies in the join of the four neutral sector spans: the two fermionic
  kinetic sectors, the second derivatives of the field strength, and the photon pairs.

  This refines `mem_massDimFour_sectors_of_isInvariant` by the hypercharge grading: the two
  like-species fermionic sectors of that statement carry hypercharge `± 12`, and an invariant,
  being a charge singlet, has no component in them. -/
theorem mem_massDimFour_neutral_sectors_of_isInvariant {x : JetAlgebra} (hx : IsInvariant x)
    (h8 : x ∈ massWeightSubmodule 8) :
    x ∈ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [μ] α * Dψ [] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dψ [μ] β}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ ρ τ μ ν, y = fieldStrengthDeriv {ρ, τ} μ ν}
      ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ μ ν μ' ν',
          y = fieldStrengthDeriv {} μ ν * fieldStrengthDeriv {} μ' ν'} := by
  have hcov : x ∈ covWeightSpan 8 :=
    mem_covWeightSpan_of_mem_covariantAlgebra
      ((isInvariant_iff_mem_covariantAlgebra x).mp hx).1 h8
  have hle := covWeightSpan_eight_le
    (W := Submodule.comap (chargeComponent 0)
      (Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [μ] α * Dψ [] β}
        ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ α μ β, y = Dbarψ [] α * Dψ [μ] β}
        ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ ρ τ μ ν, y = fieldStrengthDeriv {ρ, τ} μ ν}
        ⊔ Submodule.span ℂ {y : JetAlgebra | ∃ μ ν μ' ν',
            y = fieldStrengthDeriv {} μ ν * fieldStrengthDeriv {} μ' ν'}))
    ?_ ?_ ?_ ?_ ?_ ?_
  · have h := hle hcov
    rwa [Submodule.mem_comap,
      chargeComponent_of_mem (mem_hyperchargeSubmodule_zero_of_isInvariant hx)] at h
  · intro α μ β
    rw [Submodule.mem_comap, chargeComponent_of_mem
      (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num)
        (Dbarψ_singleton_mem_hyperchargeSubmodule μ α) (Dψ_nil_mem_hyperchargeSubmodule β))]
    exact Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_left
      (Submodule.subset_span ⟨α, μ, β, rfl⟩)))
  · intro α μ β
    rw [Submodule.mem_comap, chargeComponent_of_mem
      (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num)
        (Dbarψ_nil_mem_hyperchargeSubmodule α) (Dψ_singleton_mem_hyperchargeSubmodule μ β))]
    exact Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_right
      (Submodule.subset_span ⟨α, μ, β, rfl⟩)))
  · intro ρ τ μ ν
    rw [Submodule.mem_comap,
      chargeComponent_of_mem (fieldStrengthDeriv_mem_hyperchargeSubmodule {ρ, τ} μ ν)]
    exact Submodule.mem_sup_left (Submodule.mem_sup_right
      (Submodule.subset_span ⟨ρ, τ, μ, ν, rfl⟩))
  · intro μ ν μ' ν'
    rw [Submodule.mem_comap, chargeComponent_of_mem
      (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num)
        (fieldStrengthDeriv_mem_hyperchargeSubmodule {} μ ν)
        (fieldStrengthDeriv_mem_hyperchargeSubmodule {} μ' ν'))]
    exact Submodule.mem_sup_right (Submodule.subset_span ⟨μ, ν, μ', ν', rfl⟩)
  · intro α μ β
    rw [Submodule.mem_comap, chargeComponent_of_mem_ne (show (12 : ℤ) ≠ 0 by norm_num)
      (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num)
        (Dψ_nil_mem_hyperchargeSubmodule α) (Dψ_singleton_mem_hyperchargeSubmodule μ β))]
    exact zero_mem _
  · intro α μ β
    rw [Submodule.mem_comap, chargeComponent_of_mem_ne (show (-12 : ℤ) ≠ 0 by norm_num)
      (mul_mem_hyperchargeSubmodule_of_add_eq (by norm_num)
        (Dbarψ_nil_mem_hyperchargeSubmodule α)
        (Dbarψ_singleton_mem_hyperchargeSubmodule μ β))]
    exact zero_mem _

end JetAlgebra

end LeptonGaugeSector

end
