/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Meta.TODO.Basic
/-!

# The axion

The axion is a hypothetical pseudo-Nambu-Goldstone boson arising from the spontaneous breaking of a
`U(1)` Peccei-Quinn symmetry, introduced to provide a dynamical solution to the strong CP problem.

This file currently only records future work on the axion.

-/

@[expose] public section

namespace Axion

TODO "Define the axion potential. The axion is a pseudo-Nambu-Goldstone boson of a spontaneously
  broken Peccei-Quinn `U(1)` symmetry; its effective potential, generated by non-perturbative QCD
  effects, is periodic in `a / f_a` (for example `V a = m_a ^ 2 * f_a ^ 2 * (1 - Real.cos (a / f_a))`)
  with a minimum at the CP-conserving value, realising the Peccei-Quinn solution to the strong CP
  problem."

end Axion
