/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Meta.TODO.Basic
/-!

# The Axion

The axion is a hypothetical pseudo-Nambu-Goldstone boson arising from a spontaneously broken
Peccei-Quinn `U(1)` symmetry, introduced to solve the strong CP problem.

This file is a placeholder for results about the axion.

-/

@[expose] public section

namespace Axion

TODO "Define the axion effective potential generated by QCD instantons, of the schematic form
  `V(a) = Λ⁴ (1 - cos(a / fₐ))` for an axion field `a`, decay constant `fₐ`, and
  non-perturbative scale `Λ`, and show that it is minimised at `a = 0` (CP conservation)."

end Axion
