/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Matter.JetComponentSpace.Basic
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
/-!
# The fermionic algebra of a matter field

## i. Overview

For a matter field valued in a complex vector space `V`, the *fermionic algebra* is the
exterior algebra on the jet component space `JetComponentSpace V`. It is the algebra in
which the `V`-part of a Lagrangian lives: the generators are the component functions
`∂_s ψ_α` and their conjugates `∂_s ψ̄_α`, and the exterior product implements the
anticommutativity of fermionic fields.

Everything the component space carries lifts to the fermionic algebra by functoriality of
the exterior algebra: the Lorentz action (`FermionicAlgebra.repLorentzGroup`), the jet
gauge action (`FermionicAlgebra.repJetGaugeGroupI`), and the formal total derivative
(`FermionicAlgebra.jetDeriv`), which extends as an even derivation rather than by
functoriality. Those live in the sibling files `LorentzAction`, `GaugeAction` and
`JetDeriv`.

## ii. Key results

- `FermionicAlgebra` : the exterior algebra on the jet component space.
- `FermionicAlgebra.adjoin_ι_eq_top` : the algebra is generated by the component functions.
- `FermionicAlgebra.ofField`, `FermionicAlgebra.ofConjField` : the field and its conjugate.

## iii. Table of contents

- A. The fermionic algebra
  - A.1. The generators of the fermionic algebra
  - A.2. The field and its conjugate

-/

@[expose] public section

namespace StandardModel

open TensorProduct

variable {V : Type} [AddCommGroup V] [Module ℂ V]

/-!

## A. The fermionic algebra

-/

/-- The fermionic algebra of a `V`-valued matter field: the exterior algebra on the space
  of component functions `∂_s ψ_α` and `∂_s ψ̄_α`. The exterior product is the product of
  fermionic fields, its anticommutativity the Fermi statistics. -/
abbrev FermionicAlgebra (V : Type) [AddCommGroup V] [Module ℂ V] : Type :=
  ExteriorAlgebra ℂ (JetComponentSpace V)

namespace FermionicAlgebra

/-!

### A.1. The generators of the fermionic algebra

-/

/-- **The fermionic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s ψ_α` and `∂_s ψ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (ExteriorAlgebra.ι ℂ (M := JetComponentSpace V))) = ⊤ :=
  CliffordAlgebra.adjoin_range_ι

/-- A component function squares to zero: no fermionic field appears twice. -/
lemma ι_sq_zero (x : JetComponentSpace V) :
    ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ x = (0 : FermionicAlgebra V) :=
  ExteriorAlgebra.ι_sq_zero x

/-- Two component functions anticommute. -/
lemma ι_mul_ι_swap (x y : JetComponentSpace V) :
    (ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ y : FermionicAlgebra V)
      = - (ExteriorAlgebra.ι ℂ y * ExteriorAlgebra.ι ℂ x) :=
  eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap (R := ℂ) x y)

/-!

### A.2. The field and its conjugate

The undifferentiated component functions sit inside the fermionic algebra as the two
inclusions below. A component function is a *covector* on the target space: `ofField φ` is
the component of the field `ψ` along `φ`, the element written `ψ_α` when `φ` is the `α`-th
coordinate. The conjugate field is a covector on `ConjModule V`, whose scalar action is
twisted by complex conjugation — that twist is exactly the statement that `ψ̄` transforms
by the conjugate of the representation carried by `ψ`.

Every other generator of the algebra is an iterated derivative of one of these, which is
the content of `FermionicAlgebra.adjoin_iteratedJetDeriv_eq_top`.

-/

/-- **The component function `ψ_φ` of the matter field** along the covector `φ` on `V`: the
  undifferentiated generator, sitting at the empty derivative label in the unconjugated half
  of the component space. -/
noncomputable def ofField : Module.Dual ℂ V →ₗ[ℂ] FermionicAlgebra V :=
  (ExteriorAlgebra.ι ℂ).comp
    ((LinearMap.inl ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ V) 1))

/-- **The component function `ψ̄_φ` of the conjugate matter field** along the covector `φ` on
  `ConjModule V`: the undifferentiated generator in the conjugate half of the component
  space. -/
noncomputable def ofConjField : Module.Dual ℂ (ConjModule V) →ₗ[ℂ] FermionicAlgebra V :=
  (ExteriorAlgebra.ι ℂ).comp
    ((LinearMap.inr ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ (ConjModule V)) 1))

lemma ofField_apply (φ : Module.Dual ℂ V) :
    ofField φ = ExteriorAlgebra.ι ℂ
      (((1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ, 0) : JetComponentSpace V) := rfl

lemma ofConjField_apply (φ : Module.Dual ℂ (ConjModule V)) :
    ofConjField φ = ExteriorAlgebra.ι ℂ
      ((0, (1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ) : JetComponentSpace V) := rfl

end FermionicAlgebra

end StandardModel
