/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.Basic
public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.TransformsInAdjoint
public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.FieldStrength
public import Physlib.Particles.StandardModel.GaugeGroup.MaurerCartan.Truncation
public import Mathlib.LinearAlgebra.Basis.Defs
public import Mathlib.LinearAlgebra.Dimension.Free
/-!

# The symmetrized field strength tensor

We define the symmetrized derivatives of the gauge field as
`sym(d_s A^a_μ) := (1/(|s|+1)) ∑_{ν ∈ s+μ} d_{(s+μ)−ν} A^a_ν`
The reason for this is two fold.

Firstly, the algebra generated by `d_s A^a_μ` is the same as the algebra generated by
`sym(d_s A^a_μ)` and `𝒟_s F^a_{μν}`.

Secondly, while the `0`th-truncated ker gauge group acts
trivially on `𝒟_s F^a_{μν}` and all other covariant derivatives it acts freely on `sym(d_s A^a_μ)`.
This means that this group can be used to gauge away the `sym(d_s A^a_μ)`.
This free action results from the map `symmetrizedMaurerCartanCoeff` which
is itself a bijection.

-/

@[expose] public section

namespace StandardModel
namespace IsGaugeField
open Matrix MatrixGroups TensorProduct MvPowerSeries
variable {B : Type} [Ring B] [Algebra ℂ B]
variable {V : Type} [AddCommGroup V] [Module ℂ V]

variable {repLorentz : Representation ℂ SL(2,ℂ) B}
variable {repGauge : Representation ℂ JetGaugeGroupI B}
variable {A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
variable {D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B}
variable [Lorentz.IsLorentzDeriv repLorentz D]
variable {D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ)}

noncomputable def symmetrizedDeriv (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B)
    (D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ))
    (s : Multiset (Fin 1 ⊕ Fin 3))
    (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) : B:=
  ((1/(s.card : ℝ) : ℝ) • (s.map fun μ =>
    (Lorentz.iteratedD D D_comm (s - {μ}) (A μ φ))).sum)

@[simp]
lemma symmetrizedDeriv_singleton (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B)
    (D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ))
    (μ : Fin 1 ⊕ Fin 3) (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv D D_comm ({μ}) A φ = A μ φ := by
  simp [symmetrizedDeriv, Lorentz.iteratedD]

@[simp]
lemma symmetrizedDeriv_empty (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B)
    (D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ))
    (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv D D_comm 0 A φ = 0 := by
  simp [symmetrizedDeriv]

/-- The recursion for the symmetrized derivative: peeling one direction off the
  multiset. The factor `card s / (card s + 1)` on the derivative term comes from the
  mismatch of the symmetrization factors `1/(card s + 1)` and `1/card s`. -/
lemma symmetrizedDeriv_cons (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B)
    (D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ))
    (s : Multiset (Fin 1 ⊕ Fin 3))
    (μ : Fin 1 ⊕ Fin 3)
    (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv D D_comm (μ ::ₘ s) A φ =
      (1/(s.card + 1 : ℝ) : ℝ) • (Lorentz.iteratedD D D_comm s (A μ φ))
    + ((s.card : ℝ)/(s.card + 1 : ℝ)) • D μ (symmetrizedDeriv D D_comm s A φ) := by
  by_cases hs : s = 0
  · subst hs
    simp [Lorentz.iteratedD_zero]
  · have hn : (s.card : ℝ) ≠ 0 :=
      Nat.cast_ne_zero.mpr fun h => hs (Multiset.card_eq_zero.mp h)
    have herase : ∀ ν ∈ s, (μ ::ₘ s).erase ν = μ ::ₘ s.erase ν := by
      intro ν hν
      rcases eq_or_ne ν μ with rfl | h
      · rw [Multiset.erase_cons_head, Multiset.cons_erase hν]
      · rw [Multiset.erase_cons_tail _ h.symm]
    rw [symmetrizedDeriv, symmetrizedDeriv, Multiset.map_cons, Multiset.sum_cons,
      Multiset.card_cons, Multiset.sub_singleton, Multiset.erase_cons_head,
      Multiset.map_congr rfl (fun ν hν => by
        rw [Multiset.sub_singleton, herase ν hν, Lorentz.iteratedD_cons,
          LinearMap.comp_apply, ← Multiset.sub_singleton]),
      show (s.map fun ν => D μ (Lorentz.iteratedD D D_comm (s - {ν}) (A ν φ))) =
          (s.map fun ν => Lorentz.iteratedD D D_comm (s - {ν}) (A ν φ)).map (⇑(D μ)) from
        (Multiset.map_map _ _ _).symm,
      ← map_multiset_sum, smul_add, LinearMap.map_smul_of_tower, smul_smul,
      show ((s.card + 1 : ℕ) : ℝ) = (s.card : ℝ) + 1 by push_cast; ring,
      show (s.card : ℝ)/((s.card : ℝ) + 1) * (1/(s.card : ℝ)) = 1/((s.card : ℝ) + 1) by
        field_simp]

lemma deriv_sub_symmetrizedDeriv_eq_sum (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B)
    (D_comm : ∀ μ ν, (D μ).comp (D ν) = (D ν).comp (D μ))
    (s : Multiset (Fin 1 ⊕ Fin 3))
    (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra)
    (μ : Fin 1 ⊕ Fin 3) :
    Lorentz.iteratedD D D_comm s (A μ φ) - symmetrizedDeriv D D_comm (μ ::ₘ s) A φ =
      ((1/(s.card + 1 : ℝ)) • ((s.map fun ν => Lorentz.iteratedD D D_comm s (A μ φ) -
        Lorentz.iteratedD D D_comm (μ ::ₘ s - {ν}) (A ν φ)).sum)) := by
  have hn1 : (s.card : ℝ) + 1 ≠ 0 := by positivity
  rw [symmetrizedDeriv, Multiset.map_cons, Multiset.sum_cons, Multiset.card_cons,
    Multiset.sub_singleton, Multiset.erase_cons_head, Multiset.sum_map_sub,
    Multiset.map_const', Multiset.sum_replicate,
    ← Nat.cast_smul_eq_nsmul ℝ s.card,
    show ((s.card + 1 : ℕ) : ℝ) = (s.card : ℝ) + 1 by push_cast; ring]
  match_scalars <;> (field_simp; try ring)

/-!

## The generation theorem: symbols = symmetrized symbols + field strength

The chain of lemmas below implements the outline in the module docstring, leading to

  `adjoin({ d_p A }) = adjoin({ sym(d_p A) } ∪ { 𝒟_q F })`.

Throughout, `D_mul` is the Leibniz rule for the total derivative — a property of `D`
on the algebra `B` that `IsGaugeField` does not currently record, taken here as an
explicit hypothesis.

-/

/-- The iterated covariant derivative `𝒟_l F` of an adjoint component family along a
  *list* of directions: covariant derivatives do not commute (their commutator is an
  `ad F` term), so the iteration is order-dependent and indexed by a list. -/
noncomputable def iteratedCovDerivAdjoint
    (A : (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (D : (Fin 1 ⊕ Fin 3) → B →ₗ[ℂ] B) :
    List (Fin 1 ⊕ Fin 3) → (Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B) →
      Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B
  | [], F => F
  | ρ :: l, F => covDerivAdjoint A (iteratedCovDerivAdjoint A D l F) D ρ


/-- Symbol subalgebras are monotone in the order bound. -/
lemma adjoin_symbols_mono {n m : ℕ} (hnm : n ≤ m) :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} ≤
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ m ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  refine Algebra.adjoin_mono fun b => ?_
  rintro ⟨p, μ, φ, h, rfl⟩
  exact ⟨p, μ, φ, h.trans hnm, rfl⟩

/-- The total derivative raises the order of a symbol polynomial by at most one:
  it maps the subalgebra of order-`n` symbols into the order-`n + 1` one, by the
  Leibniz rule. -/
lemma deriv_mem_adjoin_symbols
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (ρ : Fin 1 ⊕ Fin 3) {n : ℕ} {x : B}
    (hx : x ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)}) :
    D ρ x ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n + 1 ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb =>
      obtain ⟨p, κ, ψ, hpc, rfl⟩ := hb
      refine Algebra.subset_adjoin ⟨ρ ::ₘ p, κ, ψ, ?_, ?_⟩
      · simpa using Nat.succ_le_succ hpc
      · rw [Lorentz.iteratedD_cons]
        rfl
  | algebraMap c =>
      have h1 : D ρ (1 : B) = 0 := by
        have h := D_mul ρ 1 1
        simp only [one_mul, mul_one] at h
        have h3 : D ρ (1 : B) + 0 = D ρ 1 + D ρ 1 := by rw [add_zero]; exact h
        exact (add_left_cancel h3).symm
      rw [Algebra.algebraMap_eq_smul_one, map_smul, h1, smul_zero]
      exact zero_mem _
  | add x y hx hy ihx ihy =>
      rw [map_add]
      exact add_mem ihx ihy
  | mul x y hx hy ihx ihy =>
      rw [D_mul]
      exact add_mem (mul_mem ihx (adjoin_symbols_mono (Nat.le_succ n) hy))
        (mul_mem (adjoin_symbols_mono (Nat.le_succ n) hx) ihy)

/-- The bracket of two component families whose components are order-`n` symbol
  polynomials is again an order-`n` symbol polynomial, componentwise. -/
lemma bracketFam_mem_adjoin_symbols {n : ℕ}
    {f g : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
    (hf : ∀ ψ, f ψ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)})
    (hg : ∀ ψ, g ψ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)})
    (φ : Module.Dual ℝ GaugeAlgebra) :
    bracketFam f g φ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  rw [bracketFam_apply_eq_sum]
  refine Subalgebra.sum_mem _ fun j _ => Subalgebra.sum_mem _ fun k _ => ?_
  rw [← algebraMap_smul ℂ]
  exact Subalgebra.smul_mem _ (mul_mem (hf _) (hg _)) _

/-- Every iterated derivative of the field strength is a symbol polynomial of order
  one higher than the number of derivatives. -/
lemma iteratedD_fieldStrength_mem
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (q : Multiset (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    Lorentz.iteratedD D D_comm q (fieldStrength A D ν lam φ) ∈
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ q.card + 1 ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  rw [fieldStrength_apply, map_add, map_sub]
  refine add_mem (sub_mem ?_ ?_) ?_
  · rw [show Lorentz.iteratedD D D_comm q (D ν (A lam φ)) =
        Lorentz.iteratedD D D_comm (ν ::ₘ q) (A lam φ) from by
      rw [Lorentz.iteratedD_cons']; rfl]
    exact Algebra.subset_adjoin ⟨ν ::ₘ q, lam, φ, by simp, rfl⟩
  · rw [show Lorentz.iteratedD D D_comm q (D lam (A ν φ)) =
        Lorentz.iteratedD D D_comm (lam ::ₘ q) (A ν φ) from by
      rw [Lorentz.iteratedD_cons']; rfl]
    exact Algebra.subset_adjoin ⟨lam ::ₘ q, ν, φ, by simp, rfl⟩
  · exact adjoin_symbols_mono (Nat.le_succ q.card)
      (iteratedD_commutator_mem A D D_comm D_mul q ν lam φ)

/-- **Outline step 6** (unitriangularity of the covariant tower): the covariant and
  plain iterated derivatives of the field strength differ by an element of the
  subalgebra generated by lower-order symbols and lower-order plain derivatives of
  the field strength; consequently the two towers generate the same subalgebras.
  Stated as the membership needed for the induction. -/
lemma iteratedCovDerivAdjoint_sub_iteratedD_mem
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ -
        Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam φ) ∈
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ l.length ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  induction l generalizing φ with
  | nil =>
      simp only [iteratedCovDerivAdjoint,
        show (Multiset.ofList ([] : List (Fin 1 ⊕ Fin 3))) = 0 from rfl,
        Lorentz.iteratedD_zero, LinearMap.id_coe, id_eq, sub_self]
      exact zero_mem _
  | cons ρ l ih =>
      have hsplit : iteratedCovDerivAdjoint A D (ρ :: l) (fieldStrength A D ν lam) φ -
          Lorentz.iteratedD D D_comm (Multiset.ofList (ρ :: l)) (fieldStrength A D ν lam φ) =
        D ρ (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ -
            Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam φ)) +
          bracketFam (A ρ) (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam)) φ := by
        rw [show (Multiset.ofList (ρ :: l)) = ρ ::ₘ Multiset.ofList l from rfl,
          Lorentz.iteratedD_cons, LinearMap.comp_apply, map_sub,
          show iteratedCovDerivAdjoint A D (ρ :: l) (fieldStrength A D ν lam) φ =
            D ρ (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ) +
              bracketFam (A ρ) (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam)) φ
            from rfl]
        abel
      rw [hsplit]
      refine add_mem (deriv_mem_adjoin_symbols D_mul ρ (ih φ)) ?_
      refine bracketFam_mem_adjoin_symbols (fun ψ => ?_) (fun ψ => ?_) φ
      · exact Algebra.subset_adjoin ⟨0, ρ, ψ, by simp, by rw [Lorentz.iteratedD_zero]; rfl⟩
      · have h3 : iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) ψ =
            (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) ψ -
              Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam ψ)) +
            Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam ψ) := by
          abel
        rw [h3]
        refine add_mem (adjoin_symbols_mono (Nat.le_succ l.length) (ih ψ)) ?_
        simpa using iteratedD_fieldStrength_mem (A := A) D_mul (Multiset.ofList l) ν lam ψ

/-- **Outline step 7** (chaining the memberships): every derivative symbol of order
  `n + 1` lies in the subalgebra generated by its symmetrization, the covariant
  derivatives of the field strength of order `n`, and the symbols of order at most
  `n`. This is the inductive step of the generation theorem. -/
lemma iteratedD_mem_symFieldAdjoin_sup
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    Lorentz.iteratedD D D_comm s (A μ φ) ∈
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ s.card + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < s.card ∧
            b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) ⊔
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ (s.card - 1) ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
  rw [sub_eq_iff_eq_add.mp (deriv_sub_symmetrizedDeriv_eq_sum D D_comm s A φ μ)]
  refine add_mem ?_ ?_
  · -- the antisymmetric remainder: field strength plus lower-order terms
    rw [← algebraMap_smul ℂ ((1 : ℝ)/(s.card + 1 : ℝ))]
    refine Subalgebra.smul_mem _ ?_ _
    refine multiset_sum_mem _ fun x hx => ?_
    obtain ⟨ν, hν, rfl⟩ := Multiset.mem_map.mp hx
    have hpos : 0 < s.card :=
      Multiset.card_pos.mpr fun h => Multiset.notMem_zero ν (h ▸ hν)
    have hcard : (s - {ν}).card = s.card - 1 := by
      rw [Multiset.sub_singleton, Multiset.card_erase_of_mem hν, Nat.pred_eq_sub_one]
    rw [iteratedD_sub_pair D D_comm s hν μ A φ, pair_eq_fieldStrength_sub_commutator,
      map_sub]
    refine sub_mem ?_ ?_
    · -- the field-strength part, through the covariant tower
      set l := (s - {ν}).toList with hl'
      have hl : (Multiset.ofList l) = s - {ν} := Multiset.coe_toList _
      have hlen : l.length = s.card - 1 := by rw [← Multiset.coe_card, hl, hcard]
      rw [show Lorentz.iteratedD D D_comm (s - {ν}) (fieldStrength A D ν μ φ) =
          iteratedCovDerivAdjoint A D l (fieldStrength A D ν μ) φ -
            (iteratedCovDerivAdjoint A D l (fieldStrength A D ν μ) φ -
              Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν μ φ))
          from by rw [hl]; abel]
      refine sub_mem ?_ ?_
      · refine SetLike.le_def.mp le_sup_left
          (Algebra.subset_adjoin (Or.inr ⟨l, ν, μ, φ, ?_, rfl⟩))
        omega
      · refine SetLike.le_def.mp le_sup_right (adjoin_symbols_mono ?_
          (iteratedCovDerivAdjoint_sub_iteratedD_mem (D_mul := D_mul) l ν μ φ))
        omega
    · -- the commutator part is strictly lower order
      refine SetLike.le_def.mp le_sup_right (adjoin_symbols_mono ?_
        (iteratedD_commutator_mem A D D_comm D_mul (s - {ν}) ν μ φ))
      omega
  · -- the symmetrized symbol is a generator
    exact SetLike.le_def.mp le_sup_left
      (Algebra.subset_adjoin (Or.inl ⟨μ ::ₘ s, φ, Multiset.cons_ne_zero, by simp, rfl⟩))

/-- **The generation theorem** (outline final step, by strong induction on the
  order): the derivative symbols of order at most `n` and the symmetrized symbols
  together with the covariant field-strength tower generate the same subalgebra,

  `adjoin({ d_p A : |p| ≤ n }) = adjoin({ sym(d_p A) : |p| ≤ n } ∪ { 𝒟_q F : |q| < n })`. -/
theorem symbolAdjoin_eq_symFieldAdjoin
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (n : ℕ) :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} =
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
            b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) := by
  refine le_antisymm ?_ ?_
  · -- symbols are generated by symmetrized symbols and the covariant tower,
    -- by strong induction on the order
    have main : ∀ m, ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ m → m ≤ n →
        Lorentz.iteratedD D D_comm p (A μ φ) ∈ Algebra.adjoin ℂ
          ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
              r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
            {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
              (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
              b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) := by
      intro m
      induction m using Nat.strong_induction_on with
      | _ m ih =>
        intro p μ φ hpm hmn
        have hSF : Algebra.adjoin ℂ
            ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                r ≠ 0 ∧ r.card ≤ p.card + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
              {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                (φ : Module.Dual ℝ GaugeAlgebra), l.length < p.card ∧
                b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) ≤
            Algebra.adjoin ℂ
              ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                  r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
                {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                  (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
                  b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) := by
          refine Algebra.adjoin_mono ?_
          rintro b (⟨r, ψ, h0, hc, rfl⟩ | ⟨l, ν, lam, ψ, hl, rfl⟩)
          · exact Or.inl ⟨r, ψ, h0, by omega, rfl⟩
          · exact Or.inr ⟨l, ν, lam, ψ, by omega, rfl⟩
        have hAdj : Algebra.adjoin ℂ {b : B | ∃ (q : Multiset (Fin 1 ⊕ Fin 3))
            (κ : Fin 1 ⊕ Fin 3) (ψ : Module.Dual ℝ GaugeAlgebra), q.card ≤ (p.card - 1) ∧
            b = Lorentz.iteratedD D D_comm q (A κ ψ)} ≤
            Algebra.adjoin ℂ
              ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                  r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
                {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                  (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
                  b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) := by
          refine Algebra.adjoin_le ?_
          rintro b ⟨q, κ, ψ, hqc, rfl⟩
          rcases Nat.eq_zero_or_pos q.card with hq0 | hqpos
          · obtain rfl : q = 0 := Multiset.card_eq_zero.mp hq0
            rw [Lorentz.iteratedD_zero]
            refine Algebra.subset_adjoin (Or.inl ⟨{κ}, ψ, by simp, by simp, ?_⟩)
            rw [symmetrizedDeriv_singleton]
            rfl
          · exact ih q.card (by omega) q κ ψ (le_refl _) (by omega)
        exact sup_le hSF hAdj (iteratedD_mem_symFieldAdjoin_sup D_mul p μ φ)
    refine Algebra.adjoin_le ?_
    rintro b ⟨p, μ, φ, hpc, rfl⟩
    exact main n p μ φ hpc (le_refl n)
  · -- symmetrized symbols and the covariant tower are symbol polynomials
    refine Algebra.adjoin_le ?_
    rintro b (⟨r, φ, hr0, hrc, rfl⟩ | ⟨l, ν, lam, φ, hl, rfl⟩)
    · rw [symmetrizedDeriv, ← algebraMap_smul ℂ ((1 : ℝ)/(r.card : ℝ))]
      refine Subalgebra.smul_mem _ ?_ _
      refine multiset_sum_mem _ fun x hx => ?_
      obtain ⟨ν, hν, rfl⟩ := Multiset.mem_map.mp hx
      refine Algebra.subset_adjoin ⟨r - {ν}, ν, φ, ?_, rfl⟩
      have : (r - {ν}).card = r.card - 1 := by
        rw [Multiset.sub_singleton, Multiset.card_erase_of_mem hν, Nat.pred_eq_sub_one]
      omega
    · have h6 := iteratedCovDerivAdjoint_sub_iteratedD_mem (A := A) (D_comm := D_comm)
        D_mul l ν lam φ
      have hF := iteratedD_fieldStrength_mem (A := A) (D_comm := D_comm) D_mul
        (Multiset.ofList l) ν lam φ
      rw [show iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ =
          (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ -
            Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam φ)) +
          Lorentz.iteratedD D D_comm (Multiset.ofList l) (fieldStrength A D ν lam φ)
          from by abel]
      refine add_mem (adjoin_symbols_mono (by omega) h6)
        (adjoin_symbols_mono ?_ hF)
      simp only [Multiset.coe_card]
      omega

/-- **The generation theorem, unbounded version**: the derivative symbols of the gauge
  field of all orders, and the symmetrized symbols together with the full covariant
  field-strength tower, generate the same subalgebra of local expressions,

  `adjoin({ d_p A }) = adjoin({ sym(d_p A) } ∪ { 𝒟_q F })`.

  It follows from the graded version `symbolAdjoin_eq_symFieldAdjoin` since every
  generator on either side appears at some finite order. -/
theorem symbolAdjoin_eq_symFieldAdjoin_top
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂) :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), b = Lorentz.iteratedD D D_comm p (A μ φ)} =
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra),
            b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) := by
  refine le_antisymm (Algebra.adjoin_le ?_) (Algebra.adjoin_le ?_)
  · rintro b ⟨p, μ, φ, rfl⟩
    have h := (symbolAdjoin_eq_symFieldAdjoin (A := A) (D_comm := D_comm) D_mul p.card).le
      (Algebra.subset_adjoin ⟨p, μ, φ, le_refl _, rfl⟩)
    refine Algebra.adjoin_mono ?_ h
    rintro b (⟨r, ψ, h0, _, rfl⟩ | ⟨l, ν, lam, ψ, _, rfl⟩)
    · exact Or.inl ⟨r, ψ, h0, rfl⟩
    · exact Or.inr ⟨l, ν, lam, ψ, rfl⟩
  · have hmono : ∀ n : ℕ, Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
        (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} ≤
        Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra), b = Lorentz.iteratedD D D_comm p (A μ φ)} := by
      intro n
      refine Algebra.adjoin_mono ?_
      rintro b ⟨p, μ, ψ, _, rfl⟩
      exact ⟨p, μ, ψ, rfl⟩
    rintro b (⟨r, φ, hr0, rfl⟩ | ⟨l, ν, lam, φ, rfl⟩)
    · have hcard : 1 ≤ r.card :=
        Nat.one_le_iff_ne_zero.mpr fun h => hr0 (Multiset.card_eq_zero.mp h)
      exact hmono (r.card - 1)
        ((symbolAdjoin_eq_symFieldAdjoin (A := A) (D_comm := D_comm) D_mul (r.card - 1)).ge
          (Algebra.subset_adjoin (Or.inl ⟨r, φ, hr0, by omega, rfl⟩)))
    · exact hmono (l.length + 1)
        ((symbolAdjoin_eq_symFieldAdjoin (A := A) (D_comm := D_comm) D_mul (l.length + 1)).ge
          (Algebra.subset_adjoin (Or.inr ⟨l, ν, lam, φ, by omega, rfl⟩)))

/-!

## The group action on the symmetrized derivatives

-/


/-!

## The gauge action on the symmetrized derivatives

-/

/-- **The gauge transformation of the symmetrized derivatives**: averaging the
  transformation law `gauge_apply_deriv` of the individual derivative symbols over
  the multiset `s`, the homogeneous part is the symmetrized adjoint convolution and
  the inhomogeneous Maurer–Cartan shifts average to exactly the base-point value of
  the *symmetrized Maurer–Cartan form* of `U⁻¹`:

  `U • sym(d_s A)^φ = (1/|s|) ∑_{μ ∈ s} ∑_{x+y=s−μ} d_y A_μ^{∂_x Ad*(U⁻¹) φ}`
  `                   + φ( sym(mc(U⁻¹))_s |₀ )`.

  This is the symbol-level counterpart of `symmetrizedMaurerCartanForm`: the gauge
  group acts on the symmetrized derivative coordinates through the symmetrized
  Maurer–Cartan data. -/
lemma repGauge_symmetrizedDeriv (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (U : JetGaugeGroupI) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U (symmetrizedDeriv D D_comm s A φ) =
      (1/(s.card : ℝ)) • (s.map fun μ =>
        ((s - {μ}).antidiagonal.map fun p =>
          Lorentz.iteratedD D D_comm p.2 (A μ (adjointDualCoeff U⁻¹ p.1 φ))).sum).sum
      + algebraMap ℂ B (φ (JetGaugeAlgebra.eval (symmetrizedMaurerCartanForm U⁻¹ s))) := by
  set L : JetGaugeAlgebra →ₗ[ℝ] B :=
    (Algebra.linearMap ℂ B).restrictScalars ℝ ∘ₗ Algebra.linearMap ℝ ℂ ∘ₗ
      φ ∘ₗ JetGaugeAlgebra.eval.toLinearMap with hL
  rw [symmetrizedDeriv, LinearMap.map_smul_of_tower, map_multiset_sum, Multiset.map_map]
  simp only [Function.comp_def]
  rw [Multiset.map_congr rfl (fun μ _ => hA.gauge_apply_deriv U (s - {μ}) μ φ),
    Multiset.sum_map_add, smul_add]
  congr 1
  calc (1/(s.card : ℝ)) • (s.map fun μ => algebraMap ℂ B (φ (JetGaugeAlgebra.eval
        (JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ))))).sum
      = (1/(s.card : ℝ)) • (s.map fun μ =>
          L (JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ))).sum := rfl
    _ = L ((1/(s.card : ℝ)) • (s.map fun μ =>
          JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ)).sum) := by
        rw [map_smul, map_multiset_sum, Multiset.map_map]
        simp only [Function.comp_def]
    _ = algebraMap ℂ B (φ (JetGaugeAlgebra.eval (symmetrizedMaurerCartanForm U⁻¹ s))) := by
        rw [symmetrizedMaurerCartanForm]
        rfl

/-- **The action of the truncation kernel on the symmetrized derivatives is through
  the symmetrized Maurer–Cartan coefficients**: for a gauge jet `U` whose value at
  the base point is the identity, the inhomogeneous shift of `sym(d_s A)^φ` is the
  pairing of `φ` with the symmetrized Maurer–Cartan coefficient of `U⁻¹` at `s` —
  the very data that classifies pure jets (`symmetrizedMaurerCartanCoeff_injective`).
  This is the mechanism by which the truncation kernel can be used to gauge away the
  symmetrized derivative coordinates. -/
lemma repGauge_symmetrizedDeriv_truncationKer
    (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (U : JetGaugeGroupI.truncationKer 0) (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (symmetrizedDeriv D D_comm s A φ) =
      (1/(s.card : ℝ)) • (s.map fun μ =>
        ((s - {μ}).antidiagonal.map fun p =>
          Lorentz.iteratedD D D_comm p.2 (A μ (adjointDualCoeff (U.1)⁻¹ p.1 φ))).sum).sum
      + algebraMap ℂ B (φ (symmetrizedMaurerCartanCoeff U⁻¹ ⟨s, hs⟩)) := by
  rw [repGauge_symmetrizedDeriv hA U.1 s φ]
  rfl

/-- **The truncation kernel realizes arbitrary translations of the symmetrized
  derivative coordinates**: for any prescribed family `c` of gauge-algebra values,
  there is a gauge jet `U` in the kernel of the zeroth truncation whose action shifts
  every symmetrized derivative symbol by exactly `φ (c s)` — by the surjectivity of
  the symmetrized Maurer–Cartan coefficients.

  This is the freeness/transitivity statement behind "gauging away" the symmetrized
  coordinates: since the action of `U` is invertible on `B`, no symbol is literally
  sent to zero, but on any fixed field configuration (a point of `Spec B`) the shift
  `c` can be chosen to cancel the configuration's symmetrized derivative values. -/
lemma exists_repGauge_symmetrizedDeriv_shift
    (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (c : {r : Multiset (Fin 1 ⊕ Fin 3) // r ≠ 0} → GaugeAlgebra) :
    ∃ U : JetGaugeGroupI.truncationKer 0,
      ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0) (φ : Module.Dual ℝ GaugeAlgebra),
        repGauge U.1 (symmetrizedDeriv D D_comm s A φ) =
          (1/(s.card : ℝ)) • (s.map fun μ =>
            ((s - {μ}).antidiagonal.map fun p =>
              Lorentz.iteratedD D D_comm p.2 (A μ (adjointDualCoeff (U.1)⁻¹ p.1 φ))).sum).sum
          + algebraMap ℂ B (φ (c ⟨s, hs⟩)) := by
  obtain ⟨V, hV⟩ := symmetrizedMaurerCartanCoeff_surjective c
  refine ⟨V⁻¹, fun s hs φ => ?_⟩
  rw [repGauge_symmetrizedDeriv_truncationKer hA V⁻¹ s hs φ, inv_inv, hV]

/-!

## Centrality of the gauge-field symbols, and invariants of the truncation kernel

Throughout, `hc` is the hypothesis that all derivative symbols of the gauge field are
central in `B` — the statement that the gauge field is bosonic. Everything built from
the symbols by the total derivative and the bracket is then central as well.

-/

/-- Scalars are central. -/
lemma algebraMap_mem_center (c : ℂ) : algebraMap ℂ B c ∈ Subring.center B :=
  Subring.mem_center_iff.mpr fun b => (Algebra.commutes c b).symm

/-- Real multiples of central elements are central. -/
lemma smul_mem_center (r : ℝ) {x : B} (hx : x ∈ Subring.center B) :
    r • x ∈ Subring.center B := by
  rw [← algebraMap_smul ℂ r x, Algebra.smul_def]
  exact Subring.mul_mem _ (algebraMap_mem_center _) hx

/-- The total derivative of a central element is central, by the Leibniz rule. -/
lemma deriv_mem_center
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    {x : B} (hx : x ∈ Subring.center B) (ρ : Fin 1 ⊕ Fin 3) :
    D ρ x ∈ Subring.center B := by
  rw [Subring.mem_center_iff] at hx ⊢
  intro b
  have h := congrArg (D ρ) (hx b)
  rw [D_mul, D_mul, hx (D ρ b), add_comm (D ρ x * b)] at h
  exact add_left_cancel h

/-- The bracket of component families with central components is central. -/
lemma bracketFam_mem_center {f g : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
    (hf : ∀ ψ, f ψ ∈ Subring.center B) (hg : ∀ ψ, g ψ ∈ Subring.center B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    bracketFam f g φ ∈ Subring.center B := by
  rw [bracketFam_apply_eq_sum]
  refine Subring.sum_mem _ fun j _ => Subring.sum_mem _ fun k _ => ?_
  exact smul_mem_center _ (Subring.mul_mem _ (hf _) (hg _))

/-- **1.** If the derivative symbols of the gauge field are central, so are the
  covariant derivatives of the field strength. -/
lemma iteratedCovDerivAdjoint_fieldStrength_mem_center
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      Lorentz.iteratedD D D_comm p (A μ φ) ∈ Subring.center B)
    (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ ∈ Subring.center B := by
  have hc0 : ∀ (μ : Fin 1 ⊕ Fin 3) (ψ : Module.Dual ℝ GaugeAlgebra),
      A μ ψ ∈ Subring.center B := by
    intro μ ψ
    have := hc 0 μ ψ
    rwa [Lorentz.iteratedD_zero] at this
  induction l generalizing φ with
  | nil =>
      show fieldStrength A D ν lam φ ∈ Subring.center B
      rw [fieldStrength_apply, commutator_eq_bracketFam]
      exact Subring.add_mem _
        (Subring.sub_mem _ (deriv_mem_center D_mul (hc0 lam φ) ν)
          (deriv_mem_center D_mul (hc0 ν φ) lam))
        (bracketFam_mem_center (hc0 ν) (hc0 lam) φ)
  | cons ρ l ih =>
      rw [show iteratedCovDerivAdjoint A D (ρ :: l) (fieldStrength A D ν lam) φ =
          D ρ (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ) +
            bracketFam (A ρ) (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam)) φ
          from rfl]
      exact Subring.add_mem _ (deriv_mem_center D_mul (ih φ) ρ)
        (bracketFam_mem_center (hc0 ρ) (fun ψ => ih ψ) φ)

/-- **2.** If the derivative symbols of the gauge field are central, so are the
  symmetrized derivative symbols. -/
lemma symmetrizedDeriv_mem_center
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      Lorentz.iteratedD D D_comm p (A μ φ) ∈ Subring.center B)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv D D_comm s A φ ∈ Subring.center B := by
  rw [symmetrizedDeriv]
  refine smul_mem_center _ (multiset_sum_mem _ fun x hx => ?_)
  obtain ⟨μ, hμ, rfl⟩ := Multiset.mem_map.mp hx
  exact hc _ _ _

/-- **3.** Anything that transforms in the adjoint is invariant under the kernel of
  the zeroth truncation: at `s = 0` the transformation law is the dual adjoint action
  of the base-point value `U₀⁻¹ = 1`, which is trivial. -/
lemma TransformsInAdjoint.repGauge_eq_of_mem_truncationKer_zero
    {hA : IsGaugeField repLorentz repGauge A D D_comm}
    {F : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B} (hF : hA.TransformsInAdjoint F)
    (U : JetGaugeGroupI.truncationKer 0) (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (F φ) = F φ := by
  have hinv : ((U.1)⁻¹).eval = 1 := by
    rw [map_inv, JetGaugeGroupI.mem_truncationKer_zero_iff.mp U.2, inv_one]
  simpa [Lorentz.iteratedD_zero, adjointDualCoeff_zero_of_eval_eq_one hinv] using
    hF U.1 φ 0

/-- **4.** The covariant derivatives of the field strength are invariant under the
  kernel of the zeroth truncation: they transform in the adjoint, and the truncation
  kernel acts through the trivial base-point adjoint. -/
lemma repGauge_iteratedCovDerivAdjoint_fieldStrength_of_mem_truncationKer_zero
    (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (U : JetGaugeGroupI.truncationKer 0) (l : List (Fin 1 ⊕ Fin 3))
    (ν lam : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ) =
      iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ := by
  have hadj : hA.TransformsInAdjoint
      (iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam)) := by
    induction l with
    | nil => exact transformsInAdjoint_fieldStrength hA D_mul ν lam
    | cons ρ l ih => exact TransformsInAdjoint.covDerivAdjoint D_mul ih ρ
  exact hadj.repGauge_eq_of_mem_truncationKer_zero U φ

/-!

## The classification of invariants

The goal of this section is the classification theorem: a gauge-invariant element of
the subalgebra generated by the gauge-field symbols together with a set `S` of
`truncationKer 0`-fixed elements lies in the subalgebra generated by the covariant
field-strength tower together with `S` — assuming only that the gauge-field symbols
are central (bosonic), with **no algebraic-independence hypothesis**.

The strategy, by downward induction on the top symbol order `N` present in `x`:

* By the generation theorem (relativized to `S`), `x` is a polynomial expression in
  the symmetrized symbols of order `≤ N`, the covariant field-strength tower, and `S`.
* Using the surjectivity of the symmetrized Maurer–Cartan coefficients, choose gauge
  jets whose coefficients are supported at exactly order `N`. The Maurer–Cartan
  triangularity places such jets in the deep truncation kernel `truncationKer (N-1)`,
  which kills all dual adjoint coefficients of positive order `< N`. Consequently
  such a jet fixes every generator of order `< N`, fixes the covariant tower and `S`,
  and acts on the order-`N` symmetrized symbols by a *pure translation* with an
  arbitrary prescribable scalar family.
* The extraction step needs no independence: pick *any* representation of `x` as a
  polynomial in the top symbols over the fixed subalgebra. Invariance under all
  translations gives, for every shift vector, a polynomial identity; evaluating at
  sufficiently many shifts (a Vandermonde argument — pure linear algebra in `B`, no
  freeness) forces the top coefficient of *the chosen representation* to vanish, and
  downward induction kills every nonconstant coefficient. Hence `x` lies in the fixed
  subalgebra, completing the induction step.

-/

/-- The generation theorem relativized to an arbitrary set `S` of extra generators:
  a corollary of `symbolAdjoin_eq_symFieldAdjoin` since `adjoin (X ∪ S)` is
  determined by `adjoin X` and `S`. -/
theorem symbolAdjoin_union_eq_symFieldAdjoin_union
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (n : ℕ) (S : Set B) :
    Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = Lorentz.iteratedD D D_comm p (A μ φ)} ∪ S) =
      Algebra.adjoin ℂ
        (({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv D D_comm r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
            b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ}) ∪ S) := by
  sorry

/-- Finite order bound: membership in the subalgebra generated by all symbols and `S`
  uses only finitely many generators, hence symbols of some bounded order. -/
lemma exists_le_of_mem_adjoin_symbols_union (S : Set B) {x : B}
    (hx : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
      b = Lorentz.iteratedD D D_comm p (A μ φ)} ∪ S)) :
    ∃ n : ℕ, x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = Lorentz.iteratedD D D_comm p (A μ φ)} ∪ S) := by
  sorry

/-- **Maurer–Cartan triangularity** (suggested home:
  `GaugeGroup.MaurerCartan.Truncation`): a pure jet whose symmetrized Maurer–Cartan
  coefficients vanish up to order `n` lies in the `n`-th truncation kernel. -/
theorem mem_truncationKer_of_symmetrizedMaurerCartanCoeff_eq_zero
    (U : JetGaugeGroupI.truncationKer 0) (n : ℕ)
    (h : ∀ (r : Multiset (Fin 1 ⊕ Fin 3)) (hr : r ≠ 0), r.card ≤ n →
      symmetrizedMaurerCartanCoeff U ⟨r, hr⟩ = 0) :
    U.1 ∈ JetGaugeGroupI.truncationKer n := by
  sorry

/-- **Deep kernels kill the positive dual adjoint coefficients** (suggested home:
  `AlgebraValued.Basic`): for a jet trivial to order `n`, all derivatives of the
  adjoint action up to order `n` vanish. -/
theorem adjointDualCoeff_eq_zero_of_mem_truncationKer {U : JetGaugeGroupI} {n : ℕ}
    (hU : U ∈ JetGaugeGroupI.truncationKer n) {x : Multiset (Fin 1 ⊕ Fin 3)}
    (hx : x ≠ 0) (hxn : x.card ≤ n) :
    adjointDualCoeff U x = 0 := by
  sorry

/-- **Pure translation**: when all positive dual adjoint coefficients of `U⁻¹` below
  the order of `s` vanish, the adjoint convolution in the transformation of the
  symmetrized symbol collapses to the symbol itself, and the action is an honest
  translation by the symmetrized Maurer–Cartan coefficient. -/
theorem repGauge_symmetrizedDeriv_translation
    (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (U : JetGaugeGroupI.truncationKer 0) (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0)
    (hU : ∀ x : Multiset (Fin 1 ⊕ Fin 3), x ≠ 0 → x.card < s.card →
      adjointDualCoeff (U.1)⁻¹ x = 0)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (symmetrizedDeriv D D_comm s A φ) =
      symmetrizedDeriv D D_comm s A φ +
        algebraMap ℂ B (φ (symmetrizedMaurerCartanCoeff U⁻¹ ⟨s, hs⟩)) := by
  sorry

/-- **Realization of top-order translations**: any coefficient family supported at
  exactly order `N` is realized by a jet in the deep truncation kernel — surjectivity
  of the symmetrized Maurer–Cartan coefficients together with the triangularity and
  vanishing theorems above. -/
theorem exists_translation_of_support
    (N : ℕ) (c : {r : Multiset (Fin 1 ⊕ Fin 3) // r ≠ 0} → GaugeAlgebra)
    (hcN : ∀ r, r.1.card ≠ N → c r = 0) :
    ∃ U : JetGaugeGroupI.truncationKer 0,
      symmetrizedMaurerCartanCoeff U⁻¹ = c ∧
      ∀ x : Multiset (Fin 1 ⊕ Fin 3), x ≠ 0 → x.card < N →
        adjointDualCoeff (U.1)⁻¹ x = 0 := by
  sorry

/-- **The abstract extraction theorem** — pure ring theory, no gauge input and no
  independence hypothesis: if a family of unital ring endomorphisms fixes a
  subalgebra `R` pointwise and translates finitely many central elements `y i` by
  arbitrary prescribable scalars, then any element of the subalgebra generated by
  `R` and the `y i` that is invariant under the whole family lies in `R`.

  Proof idea: choose any representation of `x` as a polynomial in the `y i` over `R`;
  invariance at sufficiently many shift vectors and a Vandermonde argument force the
  nonconstant coefficients of the chosen representation to vanish, top degree first. -/
theorem mem_of_translationInvariant {ι : Type} [Fintype ι]
    (R : Subalgebra ℂ B) (y : ι → B)
    (hy : ∀ i, y i ∈ Subring.center B)
    (Φ : (ι → ℝ) → (B →+* B))
    (hΦR : ∀ t, ∀ z ∈ R, Φ t z = z)
    (hΦy : ∀ t i, Φ t (y i) = y i + algebraMap ℂ B (t i))
    {x : B} (hx : x ∈ R ⊔ Algebra.adjoin ℂ (Set.range y))
    (hinv : ∀ t, Φ t x = x) :
    x ∈ R := by
  sorry

/-- **The classification of invariants**: a gauge-invariant element of the subalgebra
  generated by the gauge-field symbols and a set `S` of `truncationKer 0`-fixed
  elements is a polynomial in the covariant derivatives of the field strength and the
  elements of `S`. Requires only centrality of the symbols (the gauge field is
  bosonic); no independence hypothesis. -/
theorem invariant_mem_adjoin_fieldStrength
    (hA : IsGaugeField repLorentz repGauge A D D_comm)
    (D_mul : ∀ (μ : Fin 1 ⊕ Fin 3) (b₁ b₂ : B),
      D μ (b₁ * b₂) = D μ b₁ * b₂ + b₁ * D μ b₂)
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      Lorentz.iteratedD D D_comm p (A μ φ) ∈ Subring.center B)
    (S : Set B)
    (hS : ∀ y ∈ S, ∀ U : JetGaugeGroupI.truncationKer 0, repGauge U.1 y = y)
    {x : B}
    (hx : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
      b = Lorentz.iteratedD D D_comm p (A μ φ)} ∪ S))
    (hinv : ∀ U : JetGaugeGroupI, repGauge U x = x) :
    x ∈ Algebra.adjoin ℂ ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      b = iteratedCovDerivAdjoint A D l (fieldStrength A D ν lam) φ} ∪ S) := by
  sorry

end IsGaugeField

end StandardModel
