/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.Jet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
public import Mathlib.RingTheory.TensorProduct.Basic
public import Physlib.Relativity.Tensors.ComplexTensor.Basic
public import Physlib.Mathematics.ConjModule
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
public import Physlib.Particles.LagrangianTheory.Basic
public import Physlib.Particles.StandardModel.Fermions.LeptonSinglet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
/-!
# Jet algebra for quantum electrodynamics

## i. Overview

The jet algebra of quantum electrodynamics: the algebra generated by the component
functions of the photon-like `U(1)` gauge boson (the B boson) and the charged
lepton, together with all their derivative coordinates. It is the tensor product of
the complexified B-boson jet algebra (a symmetric algebra, complexified so it can
be paired with the complex fermionic factor) and the charged-lepton jet algebra
(an exterior algebra).

The jet gauge group acts on each factor — by Maurer–Cartan substitutions on the
B-boson component functions, and linearly through the hypercharge character and its
derivatives on the lepton component functions — and hence on the full QED jet
algebra by the tensor product of the two actions.

-/

@[expose] public section

namespace QED
open TensorProduct StandardModel

inductive JetGenerators where
  | dB (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) : JetGenerators
  | dψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators
  | dbarψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators

abbrev JetAlgebra := (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] (LeptonSinglet.JetAlgebra)

namespace JetAlgebra

/-!

## A. Elements associated with the generators

-/

noncomputable def ofGenerator (s : JetGenerators) : JetAlgebra :=
  match s with
  | JetGenerators.dB s μ =>
    (1 ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB s μ)) ⊗ₜ[ℂ] 1
  | JetGenerators.dψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dψ s α)
  | JetGenerators.dbarψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dbarψ s α)

scoped notation "[" s "]ₐ" => ofGenerator s

/-!

## B. Representation of the gauge group

Gauge transformations act on the QED jet algebra
locally via the group `JetGaugeGroupI`.

-/

/-- The representation of the jet gauge group on the QED jet algebra: the
  Maurer–Cartan substitution action on the (complexified) B-boson factor tensored
  with the hypercharge action on the charged-lepton factor. -/
noncomputable def repJetGaugeGroupI : Representation ℂ JetGaugeGroupI JetAlgebra :=
  BBoson.JetAlgebra.complexRepJetGaugeGroupI.tprod LeptonSinglet.JetAlgebra.repJetGaugeGroupI

lemma repJetGaugeGroupI_tmul (U : JetGaugeGroupI) (c : ℂ) (b : BBoson.JetAlgebra)
    (l : LeptonSinglet.JetAlgebra) :
    repJetGaugeGroupI U ((c ⊗ₜ[ℝ] b) ⊗ₜ[ℂ] l) =
      (c ⊗ₜ[ℝ] BBoson.JetAlgebra.repJetGaugeGroupI U b) ⊗ₜ[ℂ]
        LeptonSinglet.JetAlgebra.repJetGaugeGroupI U l := rfl

/-!

## Jet derivatives

The formal total spacetime derivative `∂_μ` on the QED jet algebra: the Leibniz
extension of the total derivatives of the two factors. Both factor derivatives
are even derivations, so the total derivative is an even derivation on the full
jet algebra, with no Koszul signs.

-/

/-- The formal total spacetime derivative on the QED jet algebra in the
  direction `μ`: the Leibniz extension of the total derivatives of the B-boson
  and charged-lepton factors. -/
noncomputable def jetDeriv (μ : Fin 1 ⊕ Fin 3) : JetAlgebra →ₗ[ℂ] JetAlgebra :=
  TensorProduct.map (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ)) LinearMap.id +
    TensorProduct.map LinearMap.id (LeptonSinglet.JetAlgebra.jetDeriv μ)

lemma jetDeriv_tmul (μ : Fin 1 ⊕ Fin 3) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (l : LeptonSinglet.JetAlgebra) :
    jetDeriv μ (p ⊗ₜ[ℂ] l) =
      (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ) p) ⊗ₜ[ℂ] l +
        p ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.jetDeriv μ l := by
  simp [jetDeriv]

@[simp]
lemma jetDeriv_one (μ : Fin 1 ⊕ Fin 3) : jetDeriv μ (1 : JetAlgebra) = 0 := by
  rw [show (1 : JetAlgebra) = ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) ⊗ₜ[ℂ]
    (1 : LeptonSinglet.JetAlgebra) from rfl, jetDeriv_tmul, LinearMap.baseChange_tmul]
  simp

/-- The total derivative is an even derivation on the QED jet algebra: the
  Leibniz rule holds with no Koszul signs. -/
lemma jetDeriv_mul (μ : Fin 1 ⊕ Fin 3) (x y : JetAlgebra) :
    jetDeriv μ (x * y) = jetDeriv μ x * y + x * jetDeriv μ y := by
  have hdist₁ : ∀ a b c : JetAlgebra, (a + b) * c = a * c + b * c := by grind
  have hdist₂ : ∀ a b c : JetAlgebra, a * (b + c) = a * b + a * c := by grind
  have hzero₁ : ∀ a : JetAlgebra, 0 * a = 0 := fun a => zero_mul a
  have hzero₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  induction x using TensorProduct.induction_on with
  | zero => simp [hzero₁]
  | add a b ha hb =>
    simp only [hdist₁, map_add, ha, hb]
    abel
  | tmul p l =>
    induction y using TensorProduct.induction_on with
    | zero => simp [hzero₂]
    | add a' b' ha' hb' =>
      simp only [hdist₂, map_add, ha', hb']
      abel
    | tmul p' l' =>
      simp only [Algebra.TensorProduct.tmul_mul_tmul, jetDeriv_tmul,
        BBoson.JetAlgebra.jetDeriv_baseChange_mul, LeptonSinglet.JetAlgebra.jetDeriv_mul,
        TensorProduct.add_tmul, TensorProduct.tmul_add, hdist₁, hdist₂]
      abel

/-!

## Covariant derivatives

The covariant derivative `D_l ψ_α` of the charged lepton, indexed by an ordered
list `l` of spacetime directions: covariant derivatives do not commute — their
commutator is the field strength — so the index is a list rather than a
multiset, with the head of the list the outermost derivative.

The component functions of the lepton transform contragrediently, through the
hypercharge power series `u ^ 6`, so the covariant step on component functions
is `D_μ = ∂_μ + 6 i B_μ`: under a jet gauge transformation `∂_μ ψ_α` shifts by
`- 6 i mc_μ ψ_α` while `B_μ` shifts by `+ mc_μ`, and the two contributions
cancel. The step is defined on the whole jet algebra; applied repeatedly to the
zeroth-order component function of `ψ` it produces the covariant derivatives.

-/

/-- One covariant-derivative step `D_μ = ∂_μ + 6 i B_μ` on the QED jet algebra:
  the total spacetime derivative together with multiplication by the gauge field
  weighted by the hypercharge coupling. -/
noncomputable def covariantStep (μ : Fin 1 ⊕ Fin 3) : JetAlgebra →ₗ[ℂ] JetAlgebra :=
  jetDeriv μ + ((6 : ℂ) * Complex.I) • LinearMap.mulLeft ℂ [JetGenerators.dB {} μ]ₐ

/-- The covariant derivative `D_l ψ_α` of the charged lepton along the ordered
  list of directions `l`, with the head of the list the outermost derivative:
  the recursion `D_{μ :: l} ψ = (∂_μ + 6 i B_μ) (D_l ψ)` starting from the
  zeroth-order component function of `ψ`. -/
noncomputable def Dψ (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    JetAlgebra :=
  l.foldr (fun μ x => covariantStep μ x) [JetGenerators.dψ {} α]ₐ

/-- The zeroth covariant derivative is the lepton component function itself. -/
@[simp]
lemma Dψ_nil (α : Fin 2) :
    Dψ [] α = [JetGenerators.dψ {} α]ₐ := rfl

@[simp]
lemma Dψ_cons (μ : Fin 1 ⊕ Fin 3) (l : List (Fin 1 ⊕ Fin 3))
    (α : Fin 2) :
    Dψ (μ :: l) α = covariantStep μ (Dψ l α) :=
  rfl

/-- The first covariant derivative: `D_μ ψ_α = ∂_μ ψ_α + 6 i B_μ ψ_α`. -/
lemma Dψ_singleton (μ : Fin 1 ⊕ Fin 3) (α : Fin 2) :
    Dψ [μ] α = [JetGenerators.dψ {μ} α]ₐ +
      ((6 : ℂ) * Complex.I) • ([JetGenerators.dB {} μ]ₐ * [JetGenerators.dψ {} α]ₐ) := by
  rw [Dψ_cons, Dψ_nil, covariantStep,
    LinearMap.add_apply, LinearMap.smul_apply, LinearMap.mulLeft_apply]
  congr 1
  simp only [ofGenerator]
  rw [jetDeriv_tmul, LinearMap.baseChange_tmul]
  simp only [BBoson.JetAlgebra.jetDeriv_one, TensorProduct.tmul_zero,
    TensorProduct.zero_tmul, zero_add, LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator,
    LeptonSinglet.JetGenerators.shift_dψ, Multiset.empty_eq_zero]


end JetAlgebra

end QED
