/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.Jet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
public import Mathlib.RingTheory.TensorProduct.Basic
public import Physlib.Relativity.Tensors.ComplexTensor.Basic
public import Physlib.Mathematics.ConjModule
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
public import Physlib.Particles.LagrangianTheory.Basic
public import Physlib.Particles.StandardModel.Fermions.LeptonSinglet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
/-!
# Jet algebra for quantum electrodynamics

## i. Overview

The jet algebra of quantum electrodynamics: the algebra generated by the component
functions of the photon-like `U(1)` gauge boson (the B boson) and the charged
lepton, together with all their derivative coordinates. It is the tensor product of
the complexified B-boson jet algebra (a symmetric algebra, complexified so it can
be paired with the complex fermionic factor) and the charged-lepton jet algebra
(an exterior algebra).

The jet gauge group acts on each factor — by Maurer–Cartan substitutions on the
B-boson component functions, and linearly through the hypercharge character and its
derivatives on the lepton component functions — and hence on the full QED jet
algebra by the tensor product of the two actions.

-/

@[expose] public section

namespace QED
open TensorProduct StandardModel

inductive JetGenerators where
  | dB (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) : JetGenerators
  | dψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators
  | dbarψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators

abbrev JetAlgebra := (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] (LeptonSinglet.JetAlgebra)

namespace JetAlgebra

/-!

## A. Elements associated with the generators

-/

noncomputable def ofGenerator (s : JetGenerators) : JetAlgebra :=
  match s with
  | JetGenerators.dB s μ =>
    (1 ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB s μ)) ⊗ₜ[ℂ] 1
  | JetGenerators.dψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dψ s α)
  | JetGenerators.dbarψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dbarψ s α)

scoped notation "[" s "]ₐ" => ofGenerator s

/-!

## B. Representation of the gauge group

Gauge transformations act on the QED jet algebra
locally via the group `JetGaugeGroupI`.

-/

/-- The representation of the jet gauge group on the QED jet algebra: the
  Maurer–Cartan substitution action on the (complexified) B-boson factor tensored
  with the hypercharge action on the charged-lepton factor. -/
noncomputable def repJetGaugeGroupI : Representation ℂ JetGaugeGroupI JetAlgebra :=
  BBoson.JetAlgebra.complexRepJetGaugeGroupI.tprod LeptonSinglet.JetAlgebra.repJetGaugeGroupI

lemma repJetGaugeGroupI_tmul (U : JetGaugeGroupI) (c : ℂ) (b : BBoson.JetAlgebra)
    (l : LeptonSinglet.JetAlgebra) :
    repJetGaugeGroupI U ((c ⊗ₜ[ℝ] b) ⊗ₜ[ℂ] l) =
      (c ⊗ₜ[ℝ] BBoson.JetAlgebra.repJetGaugeGroupI U b) ⊗ₜ[ℂ]
        LeptonSinglet.JetAlgebra.repJetGaugeGroupI U l := rfl

/-!

## Jet derivatives

The formal total spacetime derivative `∂_μ` on the QED jet algebra: the Leibniz
extension of the total derivatives of the two factors. Both factor derivatives
are even derivations, so the total derivative is an even derivation on the full
jet algebra, with no Koszul signs.

-/

/-- The formal total spacetime derivative on the QED jet algebra in the
  direction `μ`: the Leibniz extension of the total derivatives of the B-boson
  and charged-lepton factors. -/
noncomputable def jetDeriv (μ : Fin 1 ⊕ Fin 3) : JetAlgebra →ₗ[ℂ] JetAlgebra :=
  TensorProduct.map (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ)) LinearMap.id +
    TensorProduct.map LinearMap.id (LeptonSinglet.JetAlgebra.jetDeriv μ)

lemma jetDeriv_tmul (μ : Fin 1 ⊕ Fin 3) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (l : LeptonSinglet.JetAlgebra) :
    jetDeriv μ (p ⊗ₜ[ℂ] l) =
      (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ) p) ⊗ₜ[ℂ] l +
        p ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.jetDeriv μ l := by
  simp [jetDeriv]

@[simp]
lemma jetDeriv_one (μ : Fin 1 ⊕ Fin 3) : jetDeriv μ (1 : JetAlgebra) = 0 := by
  rw [show (1 : JetAlgebra) = ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) ⊗ₜ[ℂ]
    (1 : LeptonSinglet.JetAlgebra) from rfl, jetDeriv_tmul, LinearMap.baseChange_tmul]
  simp

/-- The total derivative is an even derivation on the QED jet algebra: the
  Leibniz rule holds with no Koszul signs. -/
lemma jetDeriv_mul (μ : Fin 1 ⊕ Fin 3) (x y : JetAlgebra) :
    jetDeriv μ (x * y) = jetDeriv μ x * y + x * jetDeriv μ y := by
  have hdist₁ : ∀ a b c : JetAlgebra, (a + b) * c = a * c + b * c := by grind
  have hdist₂ : ∀ a b c : JetAlgebra, a * (b + c) = a * b + a * c := by grind
  have hzero₁ : ∀ a : JetAlgebra, 0 * a = 0 := fun a => zero_mul a
  have hzero₂ : ∀ a : JetAlgebra, a * 0 = 0 := fun a => mul_zero a
  induction x using TensorProduct.induction_on with
  | zero => simp [hzero₁]
  | add a b ha hb =>
    simp only [hdist₁, map_add, ha, hb]
    abel
  | tmul p l =>
    induction y using TensorProduct.induction_on with
    | zero => simp [hzero₂]
    | add a' b' ha' hb' =>
      simp only [hdist₂, map_add, ha', hb']
      abel
    | tmul p' l' =>
      simp only [Algebra.TensorProduct.tmul_mul_tmul, jetDeriv_tmul,
        BBoson.JetAlgebra.jetDeriv_baseChange_mul, LeptonSinglet.JetAlgebra.jetDeriv_mul,
        TensorProduct.add_tmul, TensorProduct.tmul_add, hdist₁, hdist₂]
      abel

/-!

## Covariant derivatives

The covariant derivative `D_l ψ_α` of the charged lepton, indexed by an ordered
list `l` of spacetime directions: covariant derivatives do not commute — their
commutator is the field strength — so the index is a list rather than a
multiset, with the head of the list the outermost derivative.

The component functions of the lepton transform contragrediently, through the
hypercharge power series `u ^ 6`, so the covariant step on component functions
is `D_μ = ∂_μ + 6 i B_μ`: under a jet gauge transformation `∂_μ ψ_α` shifts by
`- 6 i mc_μ ψ_α` while `B_μ` shifts by `+ mc_μ`, and the two contributions
cancel. The step is defined on the whole jet algebra; applied repeatedly to the
zeroth-order component function of `ψ` it produces the covariant derivatives.

-/

/-- One covariant-derivative step `D_μ = ∂_μ + 6 i B_μ` on the QED jet algebra:
  the total spacetime derivative together with multiplication by the gauge field
  weighted by the hypercharge coupling. -/
noncomputable def covariantStep (μ : Fin 1 ⊕ Fin 3) : JetAlgebra →ₗ[ℂ] JetAlgebra :=
  jetDeriv μ + ((6 : ℂ) * Complex.I) • LinearMap.mulLeft ℂ [JetGenerators.dB {} μ]ₐ

/-- The covariant derivative `D_l ψ_α` of the charged lepton along the ordered
  list of directions `l`, with the head of the list the outermost derivative:
  the recursion `D_{μ :: l} ψ = (∂_μ + 6 i B_μ) (D_l ψ)` starting from the
  zeroth-order component function of `ψ`. -/
noncomputable def Dψ (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    JetAlgebra :=
  l.foldr (fun μ x => covariantStep μ x) [JetGenerators.dψ {} α]ₐ

/-- The zeroth covariant derivative is the lepton component function itself. -/
@[simp]
lemma Dψ_nil (α : Fin 2) :
    Dψ [] α = [JetGenerators.dψ {} α]ₐ := rfl

@[simp]
lemma Dψ_cons (μ : Fin 1 ⊕ Fin 3) (l : List (Fin 1 ⊕ Fin 3))
    (α : Fin 2) :
    Dψ (μ :: l) α = covariantStep μ (Dψ l α) :=
  rfl

/-- The first covariant derivative: `D_μ ψ_α = ∂_μ ψ_α + 6 i B_μ ψ_α`. -/
lemma Dψ_singleton (μ : Fin 1 ⊕ Fin 3) (α : Fin 2) :
    Dψ [μ] α = [JetGenerators.dψ {μ} α]ₐ +
      ((6 : ℂ) * Complex.I) • ([JetGenerators.dB {} μ]ₐ * [JetGenerators.dψ {} α]ₐ) := by
  rw [Dψ_cons, Dψ_nil, covariantStep,
    LinearMap.add_apply, LinearMap.smul_apply, LinearMap.mulLeft_apply]
  congr 1
  simp only [ofGenerator]
  rw [jetDeriv_tmul, LinearMap.baseChange_tmul]
  simp only [BBoson.JetAlgebra.jetDeriv_one, TensorProduct.tmul_zero,
    TensorProduct.zero_tmul, zero_add, LeptonSinglet.JetAlgebra.jetDeriv_ofGenerator,
    LeptonSinglet.JetGenerators.shift_dψ, Multiset.empty_eq_zero]

/-!

## Covariance of the covariant derivatives

The covariant derivatives of the charged lepton transform through the
hypercharge character of the value of the gauge jet at the base point alone:
`ρ_U (D_l ψ_α) = u(0)⁶ • D_l ψ_α`, with no derivative contributions.

The proof works on the lepton-linear model of the `ψ`-sector: B-boson
polynomials tensored with a single unconjugated lepton component function. On
this model the gauge action `ρ`, the covariant step `D_μ`, and a family of
Maurer–Cartan anomaly operators `N_{s,μ}` satisfy a closed commutation algebra:

* `ρ ∘ D_μ = D_μ ∘ ρ + ρ ∘ N_{[],μ}`,
* `N_{s,μ} ∘ D_ν = D_ν ∘ N_{s,μ} + N_{ν::s,μ}`,
* `N_{s,μ} ψ = 0` and `ρ ψ = u(0)⁶ • ψ`,

so by induction every anomaly operator annihilates every covariant derivative,
and covariance propagates along the covariant-derivative recursion.

-/

/-- The unconjugated lepton component functions. -/
abbrev LeptonComponent : Type :=
  SymmetricAlgebra ℂ (Module.Dual ℂ Lorentz.CoℂModule) ⊗[ℂ]
    Module.Dual ℂ LeptonSinglet

/-- The lepton-linear elements: B-boson polynomials tensored with a single
  unconjugated lepton component function. The covariant derivatives of `ψ` are
  the images of such elements in the jet algebra. -/
abbrev LeptonLinear : Type := (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] LeptonComponent

/-- The derivative action of a jet on the lepton component functions, acting on
  the derivative symbols. -/
noncomputable def actionC (χ : JetRing) : LeptonComponent →ₗ[ℂ] LeptonComponent :=
  TensorProduct.map (DerivAlgebraComplex.jetRingAction χ) LinearMap.id

/-- The derivative-symbol shift on the lepton component functions. -/
noncomputable def shiftC (ν : Fin 1 ⊕ Fin 3) : LeptonComponent →ₗ[ℂ] LeptonComponent :=
  TensorProduct.map (DerivAlgebraComplex.deriv ν) LinearMap.id

lemma actionC_shiftC (χ : JetRing) (ν : Fin 1 ⊕ Fin 3) (a : LeptonComponent) :
    actionC χ (shiftC ν a) =
      shiftC ν (actionC χ a) + actionC (MvPowerSeries.pderiv ℂ ν χ) a := by
  have h : (actionC χ) ∘ₗ (shiftC ν) =
      (shiftC ν) ∘ₗ (actionC χ) + actionC (MvPowerSeries.pderiv ℂ ν χ) := by
    simp only [actionC, shiftC]
    rw [← TensorProduct.map_comp, ← TensorProduct.map_comp, LinearMap.id_comp,
      show (DerivAlgebraComplex.jetRingAction χ) ∘ₗ (DerivAlgebraComplex.deriv ν) =
        (DerivAlgebraComplex.deriv ν) ∘ₗ (DerivAlgebraComplex.jetRingAction χ) +
          DerivAlgebraComplex.jetRingAction (MvPowerSeries.pderiv ℂ ν χ) from
        LinearMap.ext fun b => DerivAlgebraComplex.jetRingAction_deriv χ ν b,
      TensorProduct.map_add_left]
  exact LinearMap.congr_fun h a

lemma actionC_comm (χ ψ : JetRing) (a : LeptonComponent) :
    actionC χ (actionC ψ a) = actionC ψ (actionC χ a) := by
  have h : (actionC χ) ∘ₗ (actionC ψ) = (actionC ψ) ∘ₗ (actionC χ) := by
    simp only [actionC]
    rw [← TensorProduct.map_comp, ← TensorProduct.map_comp,
      show (DerivAlgebraComplex.jetRingAction χ) ∘ₗ (DerivAlgebraComplex.jetRingAction ψ) =
        (DerivAlgebraComplex.jetRingAction ψ) ∘ₗ (DerivAlgebraComplex.jetRingAction χ) from
        LinearMap.ext fun b => DerivAlgebraComplex.jetRingAction_comm χ ψ b]
  exact LinearMap.congr_fun h a

lemma actionC_mul (χ ψ : JetRing) (a : LeptonComponent) :
    actionC (χ * ψ) a = actionC χ (actionC ψ a) := by
  have h : actionC (χ * ψ) = (actionC χ) ∘ₗ (actionC ψ) := by
    simp only [actionC]
    rw [← TensorProduct.map_comp, LinearMap.id_comp,
      DerivAlgebraComplex.jetRingAction_mul]
  exact LinearMap.congr_fun h a

lemma actionC_C (c : ℂ) (a : LeptonComponent) :
    actionC (MvPowerSeries.C c : JetRing) a = c • a := by
  have h : actionC (MvPowerSeries.C c : JetRing) = c • LinearMap.id := by
    rw [actionC, DerivAlgebraComplex.jetRingAction_C, TensorProduct.map_smul_left,
      TensorProduct.map_id]
  rw [h]
  rfl

/-- The embedding of a lepton component function into the lepton jet algebra. -/
noncomputable def leptonComponentIncl :
    LeptonComponent →ₗ[ℂ] LeptonSinglet.JetAlgebra :=
  (ExteriorAlgebra.ι ℂ) ∘ₗ (LinearMap.inl ℂ LeptonComponent
    (SymmetricAlgebra ℂ (Module.Dual ℂ Lorentz.CoℂModule) ⊗[ℂ]
      Module.Dual ℂ (ConjModule LeptonSinglet)))

lemma leptonComponentIncl_apply (a : LeptonComponent) :
    leptonComponentIncl a =
      ExteriorAlgebra.ι ℂ ((a, 0) : LeptonSinglet.JetComponentSpace) := rfl

/-- The inclusion of the lepton-linear elements into the QED jet algebra. -/
noncomputable def leptonLinearIncl : LeptonLinear →ₗ[ℂ] JetAlgebra :=
  TensorProduct.map LinearMap.id leptonComponentIncl

lemma leptonLinearIncl_tmul (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) (a : LeptonComponent) :
    leptonLinearIncl (p ⊗ₜ[ℂ] a) = p ⊗ₜ[ℂ] leptonComponentIncl a := by
  simp [leptonLinearIncl]

/-- The covariant-derivative step `D_μ = ∂_μ + 6 i B_μ` on lepton-linear
  elements. -/
noncomputable def covariantStepAux (μ : Fin 1 ⊕ Fin 3) :
    LeptonLinear →ₗ[ℂ] LeptonLinear :=
  TensorProduct.map (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ))
      LinearMap.id +
    TensorProduct.map LinearMap.id (shiftC μ) +
    ((6 : ℂ) * Complex.I) •
      TensorProduct.map (LinearMap.mulLeft ℂ ((1 : ℂ) ⊗ₜ[ℝ]
        BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB {} μ))) LinearMap.id

lemma covariantStepAux_tmul (μ : Fin 1 ⊕ Fin 3) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (a : LeptonComponent) :
    covariantStepAux μ (p ⊗ₜ[ℂ] a) =
      (LinearMap.baseChange ℂ (BBoson.JetAlgebra.jetDeriv μ) p) ⊗ₜ[ℂ] a +
        p ⊗ₜ[ℂ] shiftC μ a +
        ((6 : ℂ) * Complex.I) • ((((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator
          (BBoson.JetGenerators.dB {} μ)) * p) ⊗ₜ[ℂ] a) := by
  simp [covariantStepAux]

/-- The gauge action on lepton-linear elements. -/
noncomputable def repAux (U : JetGaugeGroupI) : LeptonLinear →ₗ[ℂ] LeptonLinear :=
  TensorProduct.map (BBoson.JetAlgebra.complexRepJetGaugeGroupI U)
    (actionC (((U.2.2 : unitary JetRing) : JetRing) ^ 6))

lemma repAux_tmul (U : JetGaugeGroupI) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra)
    (a : LeptonComponent) :
    repAux U (p ⊗ₜ[ℂ] a) =
      (BBoson.JetAlgebra.complexRepJetGaugeGroupI U p) ⊗ₜ[ℂ]
        actionC (((U.2.2 : unitary JetRing) : JetRing) ^ 6) a := by
  simp [repAux]

/-- The Maurer–Cartan anomaly operators on lepton-linear elements: the
  obstruction to the gauge action commuting with the covariant step, indexed by
  the derivative history of the step. -/
noncomputable def anomalyAux (U : JetGaugeGroupI) (s : List (Fin 1 ⊕ Fin 3))
    (μ : Fin 1 ⊕ Fin 3) : LeptonLinear →ₗ[ℂ] LeptonLinear :=
  TensorProduct.map (LinearMap.baseChange ℂ
      (BBoson.JetAlgebra.mcDeriv U (↑s + {μ}))) LinearMap.id +
    ((6 : ℂ) * Complex.I * ((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
      (BBoson.JetGenerators.dB ↑s μ)) : ℝ) : ℂ)) • LinearMap.id -
    ((6 : ℂ) * Complex.I) •
      TensorProduct.map LinearMap.id (actionC (BBoson.maurerCartanU1Deriv U μ s))

lemma anomalyAux_tmul (U : JetGaugeGroupI) (s : List (Fin 1 ⊕ Fin 3))
    (μ : Fin 1 ⊕ Fin 3) (p : ℂ ⊗[ℝ] BBoson.JetAlgebra) (a : LeptonComponent) :
    anomalyAux U s μ (p ⊗ₜ[ℂ] a) =
      (LinearMap.baseChange ℂ (BBoson.JetAlgebra.mcDeriv U (↑s + {μ})) p) ⊗ₜ[ℂ] a +
        ((6 : ℂ) * Complex.I * ((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
          (BBoson.JetGenerators.dB ↑s μ)) : ℝ) : ℂ)) • (p ⊗ₜ[ℂ] a) -
        ((6 : ℂ) * Complex.I) • (p ⊗ₜ[ℂ] actionC (BBoson.maurerCartanU1Deriv U μ s) a) := by
  simp [anomalyAux]

/-- The zeroth-order lepton component as a lepton-linear element. -/
noncomputable def ψAux (α : Fin 2) : LeptonLinear :=
  ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) ⊗ₜ[ℂ]
    ((1 : SymmetricAlgebra ℂ (Module.Dual ℂ Lorentz.CoℂModule)) ⊗ₜ[ℂ]
      LeptonSinglet.basis.dualBasis α)

/-- The covariant derivative as a lepton-linear element. -/
noncomputable def DψAux (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) : LeptonLinear :=
  l.foldr (fun μ x => covariantStepAux μ x) (ψAux α)

/-- The derivative actions of the Maurer–Cartan series and of a hypercharge
  power commute. -/
lemma actionC_maurerCartanU1_pow (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3) (q : ℕ)
    (a : LeptonComponent) :
    actionC (maurerCartanU1 U μ) (actionC ((U.2.2 : JetRing) ^ q) a) =
      actionC ((U.2.2 : JetRing) ^ q) (actionC (maurerCartanU1 U μ) a) :=
  actionC_comm _ _ a

/-- The derivative action of a jet on the zeroth-order lepton component: the
  scalar action of its value at the base point. -/
lemma actionC_one_tmul (χ : JetRing) (φ : Module.Dual ℂ LeptonSinglet) :
    actionC χ ((1 : SymmetricAlgebra ℂ (Module.Dual ℂ Lorentz.CoℂModule)) ⊗ₜ[ℂ] φ) =
      MvPowerSeries.constantCoeff χ •
        ((1 : SymmetricAlgebra ℂ (Module.Dual ℂ Lorentz.CoℂModule)) ⊗ₜ[ℂ] φ) := by
  rw [actionC, TensorProduct.map_tmul, DerivAlgebraComplex.jetRingAction_apply_one,
    LinearMap.id_coe, id_eq, TensorProduct.smul_tmul']

/-- The gauge action commutes with the covariant step up to the gauge action of
  the zeroth anomaly operator. -/
lemma repAux_covariantStepAux (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3)
    (x : LeptonLinear) :
    repAux U (covariantStepAux μ x) =
      covariantStepAux μ (repAux U x) + repAux U (anomalyAux U [] μ x) := by
  have h0 : (↑([] : List (Fin 1 ⊕ Fin 3)) : Multiset (Fin 1 ⊕ Fin 3)) + {μ} =
      ({μ} : Multiset (Fin 1 ⊕ Fin 3)) := by
    rw [Multiset.coe_nil, zero_add]
  have hone : ∀ z : ℂ ⊗[ℝ] BBoson.JetAlgebra,
      ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) * z = z := by
    intro z
    induction z using TensorProduct.induction_on with
    | zero => simp
    | add a b ha hb => simp only [mul_add, ha, hb]
    | tmul c b => simp [Algebra.TensorProduct.tmul_mul_tmul]
  have key : (repAux U) ∘ₗ (covariantStepAux μ) =
      (covariantStepAux μ) ∘ₗ (repAux U) + (repAux U) ∘ₗ (anomalyAux U [] μ) := by
    refine TensorProduct.ext' fun p a => ?_
    simp only [LinearMap.comp_apply, LinearMap.add_apply, covariantStepAux_tmul,
      anomalyAux_tmul, BBoson.maurerCartanU1Deriv_nil, map_add, map_smul, map_sub,
      repAux_tmul, Multiset.coe_nil, Multiset.empty_eq_zero, zero_add]
    simp only [BBoson.JetAlgebra.complexRepJetGaugeGroupI_baseChange_jetDeriv,
      actionC_shiftC, BBoson.pderiv_pow_unitary, actionC_mul, actionC_C,
      BBoson.JetAlgebra.complexRepJetGaugeGroupI_mul,
      BBoson.JetAlgebra.complexRepJetGaugeGroupI_ofGenerator,
      actionC_maurerCartanU1_pow]
    have hdist : ((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator
          (BBoson.JetGenerators.dB 0 μ) +
        ((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
          (BBoson.JetGenerators.dB 0 μ)) : ℝ) : ℂ) •
          ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra))) *
        BBoson.JetAlgebra.complexRepJetGaugeGroupI U p =
        ((1 : ℂ) ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB 0 μ)) *
          BBoson.JetAlgebra.complexRepJetGaugeGroupI U p +
        ((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
          (BBoson.JetGenerators.dB 0 μ)) : ℝ) : ℂ) •
          BBoson.JetAlgebra.complexRepJetGaugeGroupI U p := by
      rw [add_mul, smul_mul_assoc, hone]
    simp only [hdist]
    simp only [TensorProduct.tmul_add, TensorProduct.add_tmul, ← TensorProduct.smul_tmul',
      TensorProduct.tmul_smul, smul_add, smul_smul]
    push_cast
    module
  exact LinearMap.congr_fun key x

/-- The anomaly operators commute with the covariant step up to the anomaly
  operator with the derivative direction appended to its history. -/
lemma anomalyAux_covariantStepAux (U : JetGaugeGroupI) (s : List (Fin 1 ⊕ Fin 3))
    (μ ν : Fin 1 ⊕ Fin 3) (x : LeptonLinear) :
    anomalyAux U s μ (covariantStepAux ν x) =
      covariantStepAux ν (anomalyAux U s μ x) + anomalyAux U (ν :: s) μ x := by
  have hT : ((↑s : Multiset (Fin 1 ⊕ Fin 3)) + {μ}) + {ν} =
      (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) + {μ} := by
    rw [show (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) = {ν} + ↑s from by
      rw [Multiset.singleton_add, Multiset.cons_coe]]
    ac_rfl
  have hshift : BBoson.JetGenerators.shiftMulti ((↑s : Multiset (Fin 1 ⊕ Fin 3)) + {μ})
      (BBoson.JetGenerators.dB {} ν) =
      BBoson.JetGenerators.dB ((↑s : Multiset (Fin 1 ⊕ Fin 3)) + {μ}) ν := by
    rw [BBoson.JetGenerators.shiftMulti_dB]
    congr 1
  have hm : BBoson.mcPairing U (BBoson.JetComponentSpace.basis
      (BBoson.JetGenerators.dB ((↑s : Multiset (Fin 1 ⊕ Fin 3)) + {μ}) ν)) =
      BBoson.mcPairing U (BBoson.JetComponentSpace.basis
        (BBoson.JetGenerators.dB (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) μ)) := by
    rw [BBoson.mcPairing_basis_dB_symm, show (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) =
      ↑s + {ν} from by rw [show (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) = {ν} + ↑s from by
        rw [Multiset.singleton_add, Multiset.cons_coe]]; ac_rfl]
  have key : (anomalyAux U s μ) ∘ₗ (covariantStepAux ν) =
      (covariantStepAux ν) ∘ₗ (anomalyAux U s μ) + anomalyAux U (ν :: s) μ := by
    refine TensorProduct.ext' fun p a => ?_
    simp only [LinearMap.comp_apply, LinearMap.add_apply, covariantStepAux_tmul,
      anomalyAux_tmul, map_add, map_smul, map_sub, BBoson.maurerCartanU1Deriv_cons]
    simp only [BBoson.JetAlgebra.mcDeriv_baseChange_jetDeriv, hT, actionC_shiftC,
      BBoson.JetAlgebra.mcDeriv_baseChange_mul,
      BBoson.JetAlgebra.mcDeriv_baseChange_ofGenerator, hshift, hm]
    have hone : ∀ z : ℂ ⊗[ℝ] BBoson.JetAlgebra,
        ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra)) * z = z := by
      intro z
      induction z using TensorProduct.induction_on with
      | zero => simp
      | add a b ha hb => simp only [mul_add, ha, hb]
      | tmul c b => simp [Algebra.TensorProduct.tmul_mul_tmul]
    have hdist : (((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
          (BBoson.JetGenerators.dB (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) μ)) : ℝ) : ℂ) •
          ((1 : ℂ) ⊗ₜ[ℝ] (1 : BBoson.JetAlgebra))) * p =
        ((BBoson.mcPairing U (BBoson.JetComponentSpace.basis
          (BBoson.JetGenerators.dB (↑(ν :: s) : Multiset (Fin 1 ⊕ Fin 3)) μ)) : ℝ) : ℂ) •
          p := by
      rw [smul_mul_assoc, hone]
    simp only [hdist]
    simp only [TensorProduct.tmul_add, TensorProduct.add_tmul, ← TensorProduct.smul_tmul',
      smul_add, smul_smul]
    module
  exact LinearMap.congr_fun key x

/-- The anomaly operators annihilate the zeroth-order lepton component: the
  constant coefficient of the iterated Maurer–Cartan derivative is the
  Maurer–Cartan shift. -/
lemma anomalyAux_ψAux (U : JetGaugeGroupI) (s : List (Fin 1 ⊕ Fin 3))
    (μ : Fin 1 ⊕ Fin 3) (α : Fin 2) :
    anomalyAux U s μ (ψAux α) = 0 := by
  rw [ψAux, anomalyAux_tmul, LinearMap.baseChange_tmul]
  simp only [BBoson.JetAlgebra.mcDeriv_one, TensorProduct.tmul_zero,
    TensorProduct.zero_tmul, actionC_one_tmul, BBoson.constantCoeff_maurerCartanU1Deriv,
    TensorProduct.tmul_smul, smul_smul, zero_add, sub_self]

/-- The gauge action on the zeroth-order lepton component is the hypercharge
  character of the value of the jet at the base point. -/
lemma repAux_ψAux (U : JetGaugeGroupI) (α : Fin 2) :
    repAux U (ψAux α) =
      MvPowerSeries.constantCoeff (((U.2.2 : unitary JetRing) : JetRing) ^ 6) •
        ψAux α := by
  rw [ψAux, repAux_tmul, BBoson.JetAlgebra.complexRepJetGaugeGroupI_tmul]
  simp only [BBoson.JetAlgebra.repJetGaugeGroupI_one, actionC_one_tmul,
    TensorProduct.tmul_smul]

/-- Every anomaly operator annihilates every covariant derivative of the charged
  lepton. -/
lemma anomalyAux_DψAux (U : JetGaugeGroupI) (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    ∀ (s : List (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3),
      anomalyAux U s μ (DψAux l α) = 0 := by
  induction l with
  | nil => exact fun s μ => anomalyAux_ψAux U s μ α
  | cons ν l ih =>
    intro s μ
    rw [show DψAux (ν :: l) α = covariantStepAux ν (DψAux l α) from rfl,
      anomalyAux_covariantStepAux, ih s μ, map_zero, zero_add, ih (ν :: s) μ]

/-- Covariance of the covariant derivatives on the lepton-linear model. -/
lemma repAux_DψAux (U : JetGaugeGroupI) (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    repAux U (DψAux l α) =
      MvPowerSeries.constantCoeff (((U.2.2 : unitary JetRing) : JetRing) ^ 6) •
        DψAux l α := by
  induction l with
  | nil => exact repAux_ψAux U α
  | cons ν l ih =>
    rw [show DψAux (ν :: l) α = covariantStepAux ν (DψAux l α) from rfl,
      repAux_covariantStepAux, ih, map_smul, anomalyAux_DψAux U l α [] ν, map_zero,
      add_zero]

/-- The inclusion intertwines the covariant steps. -/
lemma covariantStep_leptonLinearIncl (μ : Fin 1 ⊕ Fin 3) (x : LeptonLinear) :
    covariantStep μ (leptonLinearIncl x) = leptonLinearIncl (covariantStepAux μ x) := by
  have key : (covariantStep μ) ∘ₗ leptonLinearIncl =
      leptonLinearIncl ∘ₗ (covariantStepAux μ) := by
    refine TensorProduct.ext' fun p a => ?_
    simp only [LinearMap.comp_apply, leptonLinearIncl_tmul, covariantStepAux_tmul,
      leptonComponentIncl_apply, covariantStep, LinearMap.add_apply,
      LinearMap.smul_apply, LinearMap.mulLeft_apply, map_add, map_smul,
      jetDeriv_tmul, LeptonSinglet.JetAlgebra.jetDeriv_ι,
      LeptonSinglet.JetComponentSpace.jetDeriv_inl', ofGenerator, shiftC,
      Algebra.TensorProduct.tmul_mul_tmul, one_mul]
  exact LinearMap.congr_fun key x

/-- The inclusion intertwines the gauge actions. -/
lemma repJetGaugeGroupI_leptonLinearIncl (U : JetGaugeGroupI) (x : LeptonLinear) :
    repJetGaugeGroupI U (leptonLinearIncl x) = leptonLinearIncl (repAux U x) := by
  have key : (repJetGaugeGroupI U) ∘ₗ leptonLinearIncl =
      leptonLinearIncl ∘ₗ (repAux U) := by
    refine TensorProduct.ext' fun p a => ?_
    simp only [LinearMap.comp_apply, leptonLinearIncl_tmul, repAux_tmul,
      leptonComponentIncl_apply, repJetGaugeGroupI, Representation.tprod_apply,
      TensorProduct.map_tmul, LeptonSinglet.JetAlgebra.repJetGaugeGroupI_apply,
      ExteriorAlgebra.map_apply_ι, LeptonSinglet.JetComponentSpace.repJetGaugeGroupI_inl',
      actionC]
  exact LinearMap.congr_fun key x

/-- The covariant derivatives are the images of their lepton-linear models. -/
lemma Dψ_eq_leptonLinearIncl (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    Dψ l α = leptonLinearIncl (DψAux l α) := by
  induction l with
  | nil =>
    rw [Dψ_nil, show DψAux [] α = ψAux α from rfl, ψAux, leptonLinearIncl_tmul,
      leptonComponentIncl_apply]
    simp only [ofGenerator, LeptonSinglet.JetAlgebra.ofGenerator,
      LeptonSinglet.JetComponentSpace.basis_dψ_nil]
  | cons ν l ih =>
    rw [Dψ_cons, ih, covariantStep_leptonLinearIncl]
    rfl

/-- Covariance of the covariant derivatives of the charged lepton: a jet of
  gauge transformations acts on `D_l ψ_α` through the hypercharge character of
  its value at the base point alone, with no derivative contributions. This is
  the statement that the covariant derivative of a charged field is again a
  charged field of the same charge. -/
lemma repJetGaugeGroupI_Dψ (U : JetGaugeGroupI) (l : List (Fin 1 ⊕ Fin 3)) (α : Fin 2) :
    repJetGaugeGroupI U (Dψ l α) = U.eval.2.2 ^ 6 • Dψ l α := by
  have hval : ((U.eval.2.2 : unitary ℂ) : ℂ) =
      MvPowerSeries.constantCoeff ((U.2.2 : unitary JetRing) : JetRing) := rfl
  rw [Dψ_eq_leptonLinearIncl, repJetGaugeGroupI_leptonLinearIncl, repAux_DψAux,
    map_smul, ← Dψ_eq_leptonLinearIncl, Submonoid.smul_def, SubmonoidClass.coe_pow,
    hval, map_pow]

end JetAlgebra

end QED
