/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.Jet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
public import Mathlib.RingTheory.TensorProduct.Basic
public import Physlib.Relativity.Tensors.ComplexTensor.Basic
public import Physlib.Mathematics.ConjModule
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basis
public import Physlib.Particles.LagrangianTheory.Basic
public import Physlib.Particles.StandardModel.Fermions.LeptonSinglet
public import Physlib.Particles.StandardModel.GaugeBosons.BBoson
/-!
# Jet algebra for quantum electrodynamics

## i. Overview

The jet algebra of quantum electrodynamics: the algebra generated by the component
functions of the photon-like `U(1)` gauge boson (the B boson) and the charged
lepton, together with all their derivative coordinates. It is the tensor product of
the complexified B-boson jet algebra (a symmetric algebra, complexified so it can
be paired with the complex fermionic factor) and the charged-lepton jet algebra
(an exterior algebra).

The jet gauge group acts on each factor — by Maurer–Cartan substitutions on the
B-boson component functions, and linearly through the hypercharge character and its
derivatives on the lepton component functions — and hence on the full QED jet
algebra by the tensor product of the two actions.

-/

@[expose] public section

namespace QED
open TensorProduct StandardModel

inductive JetGenerators where
  | dB (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) : JetGenerators
  | dψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators
  | dbarψ (s : Multiset (Fin 1 ⊕ Fin 3)) (α : Fin 2) : JetGenerators

abbrev JetAlgebra := (ℂ ⊗[ℝ] BBoson.JetAlgebra) ⊗[ℂ] (LeptonSinglet.JetAlgebra)

namespace JetAlgebra

/-!

## A. Elements associated with the generators

-/

noncomputable def ofGenerator (s : JetGenerators) : JetAlgebra :=
  match s with
  | JetGenerators.dB s μ =>
      (1 ⊗ₜ[ℝ] BBoson.JetAlgebra.ofGenerator (BBoson.JetGenerators.dB s μ)) ⊗ₜ[ℂ] 1
  | JetGenerators.dψ s α =>
      (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dψ s α)
  | JetGenerators.dbarψ s α =>
    (1 ⊗ₜ[ℝ] 1) ⊗ₜ[ℂ] LeptonSinglet.JetAlgebra.ofGenerator (LeptonSinglet.JetGenerators.dbarψ s α)

scoped notation "[" s "]ₐ" => ofGenerator s

/-!

## B. Representations of the group

-/

/-- The representation of the jet gauge group on the QED jet algebra: the
  Maurer–Cartan substitution action on the (complexified) B-boson factor tensored
  with the hypercharge action on the charged-lepton factor. -/
noncomputable def repJetGaugeGroupI : Representation ℂ JetGaugeGroupI JetAlgebra :=
  BBoson.JetAlgebra.complexRepJetGaugeGroupI.tprod LeptonSinglet.JetAlgebra.repJetGaugeGroupI

lemma repJetGaugeGroupI_tmul (U : JetGaugeGroupI) (c : ℂ) (b : BBoson.JetAlgebra)
    (l : LeptonSinglet.JetAlgebra) :
    repJetGaugeGroupI U ((c ⊗ₜ[ℝ] b) ⊗ₜ[ℂ] l) =
      (c ⊗ₜ[ℝ] BBoson.JetAlgebra.repJetGaugeGroupI U b) ⊗ₜ[ℂ]
        LeptonSinglet.JetAlgebra.repJetGaugeGroupI U l := rfl


end JetAlgebra

end QED
