/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module
public import Physlib.Particles.StandardModel.AlgebraRealization.CovariantDeriv
/-!
# The covariant field algebra

## i. Overview

The matter towers of `AlgebraRealization.CovariantDeriv` commute with the gauge-field
symbols and are fixed by pure gauge jets, so the abstract classification
`IsGaugeField.invariant_mem_adjoin_fieldStrength` applies to the field algebra written in
terms of the covariant towers: a jet-gauge invariant is a polynomial in the covariant
towers of the field strength and of the matter fields, gauge invariance having eliminated
the bare gauge-field symbols. `covFieldAlgebra` names the algebra those covariant towers
generate, and `invariant_mem_adjoin_covDeriv` is the classification.

## ii. Key results

- `AlgebraRealization.covFieldAlgebra` : the algebra generated by the covariant derivative
  of the field strength and the covariant derivatives of the ten matter species.
- `AlgebraRealization.invariant_mem_adjoin_covDeriv` : the classification of jet-gauge
  invariants of the field algebra: a `repJet`-invariant element of the field algebra lies
  in `covFieldAlgebra`.

## iii. Table of contents

- A. The covariant field algebra and its classification of gauge invariants

-/

@[expose] public section

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 1000000
set_option synthInstance.maxSize 2048
set_option maxRecDepth 8000

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace AlgebraRealization

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repJet : Representation ℂ JetGaugeGroupI B}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : AlgebraRealization B repJet repLorentz massWeightPoly)

/-!

## A. The covariant field algebra and its classification of gauge invariants

-/

/-- The covariant field algebra: the algebra generated by the covariant derivative of the
  field strength and the covariant derivatives of the ten matter species. It is the
  covariant analogue of `fieldAlgebra`, and the target of the classification of jet-gauge
  invariants, `invariant_mem_adjoin_covDeriv`. -/
noncomputable def covFieldAlgebra : Subalgebra ℂ B :=
  Algebra.adjoin ℂ
    ((⋃ (l : List (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) (ν : Fin 1 ⊕ Fin 3),
        Set.range (h.covDerivFieldStrength l μ ν)) ∪
      (⋃ (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)),
        Set.range (h.covDerivH l) ∪ Set.range (h.covDerivBarH l)) ∪
      (⋃ (i : Fin 3) (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)),
        Set.range (h.covDerivD i l) ∪ Set.range (h.covDerivBarD i l) ∪
        Set.range (h.covDerivU i l) ∪ Set.range (h.covDerivBarU i l) ∪
        Set.range (h.covDerivQ i l) ∪ Set.range (h.covDerivBarQ i l) ∪
        Set.range (h.covDerivL i l) ∪ Set.range (h.covDerivBarL i l) ∪
        Set.range (h.covDerivE i l) ∪ Set.range (h.covDerivBarE i l)))

/-- The classification of gauge invariants of the field algebra: a `repJet`-invariant
  element of the field algebra lies in the covariant field algebra — it is a polynomial in
  the covariant derivatives of the field strength and the covariant derivatives of the
  matter fields. -/
theorem invariant_mem_adjoin_covDeriv {x : B}
    (hx : x ∈ h.fieldAlgebra)
    (hinv : ∀ U : JetGaugeGroupI, repJet U x = x) :
    x ∈ h.covFieldAlgebra := by
  show x ∈ Algebra.adjoin ℂ
    ((⋃ (l : List (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) (ν : Fin 1 ⊕ Fin 3),
        Set.range (h.covDerivFieldStrength l μ ν)) ∪
      (⋃ (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)),
        Set.range (h.covDerivH l) ∪ Set.range (h.covDerivBarH l)) ∪
      (⋃ (i : Fin 3) (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)),
        Set.range (h.covDerivD i l) ∪ Set.range (h.covDerivBarD i l) ∪
        Set.range (h.covDerivU i l) ∪ Set.range (h.covDerivBarU i l) ∪
        Set.range (h.covDerivQ i l) ∪ Set.range (h.covDerivBarQ i l) ∪
        Set.range (h.covDerivL i l) ∪ Set.range (h.covDerivBarL i l) ∪
        Set.range (h.covDerivE i l) ∪ Set.range (h.covDerivBarE i l)))
  -- the matter towers commute with the gauge-field symbols
  have hcS : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) (ψ : Module.Dual ℝ GaugeAlgebra),
      ∀ y ∈ h.matterTowers, Commute y (h.A p μ ψ) := by
    intro p μ ψ y hy
    refine h.matterTowers_induction (fun y => Commute y (h.A p μ ψ)) hy
      ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_
    · exact fun n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A h.A_comm_H n l φ p μ ψ
    · exact fun n l φ =>
        IsGaugeField.commute_covDerivIter _ _ h.A_comm_A h.A_comm_barH n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_d s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_bard s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_u s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_baru s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_Q s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_barQ s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_L s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_barL s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_e s μ ψ i s' φ) n l φ p μ ψ
    · exact fun i n l φ => IsGaugeField.commute_covDerivIter _ _ h.A_comm_A
        (fun s μ ψ s' φ => h.A_comm_bare s μ ψ i s' φ) n l φ p μ ψ
  -- the matter towers are fixed by pure gauge jets
  have hS : ∀ y ∈ h.matterTowers, ∀ U : JetGaugeGroupI.truncationKer 0, repJet U.1 y = y := by
    intro y hy U
    exact h.matterTowers_induction (fun y => repJet U.1 y = y) hy
      (fun _ l φ => h.repJet_covDerivH_of_mem_truncationKer_zero l U φ)
      (fun _ l φ => h.repJet_covDerivBarH_of_mem_truncationKer_zero l U φ)
      (fun i _ l φ => h.repJet_covDerivD_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivBarD_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivU_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivBarU_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivQ_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivBarQ_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivL_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivBarL_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivE_of_mem_truncationKer_zero i l U φ)
      (fun i _ l φ => h.repJet_covDerivBarE_of_mem_truncationKer_zero i l U φ)
  -- the invariant lies in the algebra of the gauge-field symbols over the matter towers
  have hx' : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (ψ : Module.Dual ℝ GaugeAlgebra), b = h.A p μ ψ} ∪ h.matterTowers) := by
    rw [h.fieldAlgebra_eq_covDeriv, Set.union_assoc] at hx
    refine Algebra.adjoin_mono ?_ hx
    rintro b (hA | hb)
    · simp only [Set.mem_iUnion, Set.mem_range] at hA
      obtain ⟨s, μ, ψ, rfl⟩ := hA
      exact Or.inl ⟨s, μ, ψ, rfl⟩
    · exact Or.inr hb
  -- the abstract classification
  rw [Set.union_assoc]
  refine Algebra.adjoin_mono ?_ (IsGaugeField.invariant_mem_adjoin_fieldStrength h.repJet_A
    h.A_comm_A h.matterTowers hcS hS hx' hinv)
  rintro b (⟨l, ν, lam, φ, rfl⟩ | hb)
  · exact Or.inl (Set.mem_iUnion_of_mem l (Set.mem_iUnion_of_mem ν
      (Set.mem_iUnion_of_mem lam ⟨φ, rfl⟩)))
  · exact Or.inr hb

end AlgebraRealization

end StandardModel
