/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.HiggsBoson.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.Jet.Basic
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.JetDeriv
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.LorentzAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.GaugeAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.MassDim
public import Mathlib.LinearAlgebra.TensorProduct.Pi
public import Mathlib.Analysis.Normed.Lp.Matrix
public import Mathlib.RingTheory.TensorProduct.Maps
/-!
# The algebra valued Higgs boson

We suppose that we have an equivariant map
under the global gauge group, and the Lorentz group
`H : Module.dual HiggsSpace →ₗ[ℂ] B`
and
`barH : Module.dual (Conj HiggsSpace) →ₗ[ℂ] B`
from the dual of the Higgs space to some algebra `B`.

We define `IsHiggsAlgebraValued` to be the property that these maps are equivariant under
the gauge group and the Lorentz group, and there images commute with one another.

We let `higgsSubModule` be the submodule of `B` generated by the images of `H`,
and `barHiggsSubModule` be the submodule of `B` generated by the images of `barH`.

The algebra `B` carries a grading due to hypercharge, through its representation
of the global gauge group. This grading can be used to eliminate
a large collection of the possible terms in the lagrangian.

We want to consider invariants within
- `higgsSubModule * barHiggsSubModule`

We also want to consider derivatives.

The invariance involving the Higgs fields, up to
mass-dimension 4 are given by:
`H^† D_μ D_μ H`,`H D_μ D_μ H^†`, `D_μ H D_μ H^†`, `H H^†` and `(H^† H)^2`.
-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix


end StandardModel
