/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.HiggsBoson.Basic
public import Physlib.Relativity.IsLorentzDeriv
public import Physlib.Particles.StandardModel.GaugeGroup.Jet.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.HyperchargeDecomposition
public import Physlib.Particles.StandardModel.GaugeGroup.SU2PermDecomposition
public import Physlib.Particles.StandardModel.GaugeGroup.IsospinDecomposition
public import Physlib.Particles.StandardModel.GaugeGroup.GaugeWeightDecomposition
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.JetDeriv
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.LorentzAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.GaugeAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.MassDim
public import Mathlib.LinearAlgebra.TensorProduct.Pi
public import Mathlib.Analysis.Normed.Lp.Matrix
public import Mathlib.RingTheory.TensorProduct.Maps
/-!
# The algebra valued Higgs boson

We suppose that we have an equivariant map
under the global gauge group, and the Lorentz group
`H : Module.Dual ℂ HiggsVec →ₗ[ℂ] B`
and
`barH : Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B`
from the dual of the Higgs space to some algebra `B`. The Higgs is a Lorentz scalar, so
Lorentz equivariance carries no content for `H` itself and is not recorded as a field.

We define `IsHiggsAlgebraValued` to be the property that these maps are equivariant under
the gauge group and the Lorentz group, and there images commute with one another.

We let `higgsSubModule` be the submodule of `B` generated by the images of `H`,
and `barHiggsSubModule` be the submodule of `B` generated by the images of `barH`.

The algebra `B` carries a grading due to hypercharge, through its representation
of the global gauge group. This grading can be used to eliminate
a large collection of the possible terms in the lagrangian.

We want to consider invariants within
- `higgsSubModule * barHiggsSubModule`

We also want to consider derivatives.

The invariance involving the Higgs fields, up to
mass-dimension 4 are given by:
`H^† D_μ D_μ H`,`H D_μ D_μ H^†`, `D_μ H D_μ H^†`, `H H^†` and `(H^† H)^2`.
-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix


/-- The pair of symbol maps `H`, `barH` in the algebra `B` is an *algebra-valued Higgs* for
  the gauge representation `rep` when it satisfies the defining properties of the physicists'
  Higgs doublet:

  * the symbol `H_φ` transforms contragrediently to `HiggsVec` — under a gauge transformation
    `g` it is acted on by the dual representation `HiggsVec.repGaugeGroupI.dual`
    (`H_equivariant`), and `barH_φ` by the conjugate-dual (`barH_equivariant`). These are the
    physicists' `H ↦ g H` and `H^† ↦ H^† g^†`, read on the component functions;
  * the Higgs is a *boson*, so all of its component symbols commute with one another
    (`H_comm_H`, `H_comm_barH`, `barH_comm_barH`). This is what distinguishes an
    algebra-valued Higgs from an algebra-valued fermion, whose symbols anticommute. -/
structure IsHiggsAlgebraValued (B : Type*) [Semiring B] [Algebra ℂ B]
    (rep : Representation ℂ GaugeGroupI B) (H : Module.Dual ℂ HiggsVec →ₗ[ℂ] B)
    (barH : Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B)
    (massWeightPoly : B →ₐ[ℂ] Polynomial B) : Prop where
  /-- The Higgs symbol carries the dual of the gauge representation on `HiggsVec`: the
    `SU(2)` index transforms contragrediently, and the hypercharge character by `u⁻³`. -/
  H_equivariant : ∀ (g : GaugeGroupI) (φ : Module.Dual ℂ HiggsVec),
    rep g (H φ) = H (HiggsVec.repGaugeGroupI.dual g φ)
  /-- The conjugate Higgs symbol carries the conjugate-dual of the gauge representation:
    the physicists' `H^† ↦ H^† g^†`. -/
  barH_equivariant : ∀ (g : GaugeGroupI) (φ : Module.Dual ℂ (ConjModule HiggsVec)),
    rep g (barH φ) = barH (HiggsVec.repGaugeGroupI.conj.dual g φ)
  /-- The Higgs is bosonic: two Higgs symbols commute. -/
  H_comm_H : ∀ φ ψ, Commute (H φ) (H ψ)
  /-- A Higgs symbol commutes with a conjugate Higgs symbol. -/
  H_comm_barH : ∀ φ ψ, Commute (H φ) (barH ψ)
  /-- Two conjugate Higgs symbols commute. -/
  barH_comm_barH : ∀ φ ψ, Commute (barH φ) (barH ψ)
  H_massWeight : ∀ φ, massWeightPoly (H φ) = Polynomial.monomial 2 (H φ)
  barH_massWeight : ∀ φ, massWeightPoly (barH φ) = Polynomial.monomial 2 (barH φ)


namespace IsHiggsAlgebraValued

variable {B : Type*} [Ring B] [Algebra ℂ B]
  {rep : Representation ℂ GaugeGroupI B} {H : Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsHiggsAlgebraValued B rep H barH massWeightPoly)


/-!

## The generators

Written in coordinates, a Lagrangian is a polynomial in the component symbols `H^α` and
`H̄^α`. These are the values of `H` and `barH` on the dual of the standard orthonormal basis
of `HiggsVec` — and, for the conjugate, on the dual of its conjugated basis
`Module.Basis.conj`.

-/

set_option linter.unusedVariables false in
/-- The component symbol `H^i` of the Higgs: the value of the symbol map on the `i`-th
  covector of the standard basis of `HiggsVec`. -/
noncomputable def higgsComponent (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) (i : Fin 2) : B :=
  H (HiggsVec.orthonormBasis.toBasis.dualBasis i)

lemma rep_higgsComponent (g : GaugeGroupI) (i : Fin 2) :
    rep g (h.higgsComponent i) =
      ∑ j, (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j) • h.higgsComponent j := by
  have key : HiggsVec.repGaugeGroupI.dual g (HiggsVec.orthonormBasis.toBasis.dualBasis i)
      = ∑ j, (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j) •
          HiggsVec.orthonormBasis.toBasis.dualBasis j := by
    refine HiggsVec.orthonormBasis.toBasis.ext fun k => ?_
    rw [LinearMap.sum_apply]
    simp only [LinearMap.smul_apply, smul_eq_mul, Module.Basis.dualBasis_apply_self,
      mul_ite, mul_one, mul_zero, Finset.sum_ite_eq]
    simp [Representation.dual, HiggsVec.repGaugeGroupI_apply, HiggsVec.orthonormBasis,
      Submonoid.smul_def, -inv_pow]
  rw [higgsComponent, h.H_equivariant, key, map_sum]
  exact Finset.sum_congr rfl fun j _ => by rw [map_smul]; rfl

set_option linter.unusedVariables false in
/-- The component symbol `H̄^i` of the conjugate Higgs. -/
noncomputable def barHiggsComponent (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) (i : Fin 2) : B :=
  barH (HiggsVec.orthonormBasis.toBasis.conj.dualBasis i)

lemma rep_barHiggsComponent (g : GaugeGroupI) (i : Fin 2) :
    rep g (h.barHiggsComponent i) =
      ∑ j, (starRingEnd ℂ (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j)) •
        h.barHiggsComponent j := by
  have key : HiggsVec.repGaugeGroupI.conj.dual g
        (HiggsVec.orthonormBasis.toBasis.conj.dualBasis i)
      = ∑ j, (starRingEnd ℂ (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j)) •
          HiggsVec.orthonormBasis.toBasis.conj.dualBasis j := by
    refine HiggsVec.orthonormBasis.toBasis.conj.ext fun k => ?_
    rw [LinearMap.sum_apply]
    simp only [LinearMap.smul_apply, smul_eq_mul, Module.Basis.dualBasis_apply_self,
      mul_ite, mul_one, mul_zero, Finset.sum_ite_eq]
    simp [Representation.dual, Representation.conj_apply, HiggsVec.repGaugeGroupI_apply,
      HiggsVec.orthonormBasis, Submonoid.smul_def, -inv_pow]
  rw [barHiggsComponent, h.barH_equivariant, key, map_sum]
  exact Finset.sum_congr rfl fun j _ => by rw [map_smul]; rfl

/-!

## The submodules

Everything below is stated relative to a fixed `h : IsHiggsAlgebraValued B rep H barH`, and
takes it as its first explicit argument, so that the submodules and terms are reached by dot
notation — `h.higgsSubmodule`, `h.massTerm` — and the data `B`, `rep`, `H` and `barH` are
recovered from `h` rather than passed by hand.

-/

set_option linter.unusedVariables false in
/-- The submodule of `B` spanned by the Higgs symbols `H_φ`: the terms of mass dimension one
  and hypercharge `+3`. -/
def higgsSubmodule (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) : Submodule ℂ B :=
  LinearMap.range H

lemma higgsSubmodule_eq_span_higgsComponents :
    h.higgsSubmodule = Submodule.span ℂ (Set.range h.higgsComponent) := by
  rw [higgsSubmodule, LinearMap.range_eq_map,
    ← (HiggsVec.orthonormBasis.toBasis.dualBasis).span_eq, Submodule.map_span,
    ← Set.range_comp]
  rfl

lemma higgsComponent_mem_higgsSubmodule (i : Fin 2) :
    h.higgsComponent i ∈ h.higgsSubmodule :=
  LinearMap.mem_range_self _ _

set_option linter.unusedVariables false in
/-- The submodule of `B` spanned by the conjugate Higgs symbols `H̄_φ`: the terms of mass
  dimension one and hypercharge `-3`. -/
def barHiggsSubmodule (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) : Submodule ℂ B :=
  LinearMap.range barH

lemma barHiggsSubmodule_eq_span_barHiggsComponents :
    h.barHiggsSubmodule = Submodule.span ℂ (Set.range h.barHiggsComponent) := by
  rw [barHiggsSubmodule, LinearMap.range_eq_map,
    ← (HiggsVec.orthonormBasis.toBasis.conj.dualBasis).span_eq, Submodule.map_span,
    ← Set.range_comp]
  rfl

lemma barHiggsComponent_mem_barHiggsSubmodule (i : Fin 2) :
    h.barHiggsComponent i ∈ h.barHiggsSubmodule :=
  LinearMap.mem_range_self _ _

/-- The terms of mass dimension exactly one: a Higgs symbol or a conjugate Higgs symbol. -/
def scalarSubmoduleOne : Submodule ℂ B := h.higgsSubmodule ⊔ h.barHiggsSubmodule

/-- **All terms of mass dimension at most `n`** built from the Higgs and its conjugate. -/
def scalarSubmodule (n : ℕ) : Submodule ℂ B :=
  ∑ k ∈ Finset.range (n + 1), h.scalarSubmoduleOne ^ k

@[simp]
lemma scalarSubmodule_zero : h.scalarSubmodule 0 = 1 := by
  rw [scalarSubmodule]
  simp

/-- Raising the mass dimension by one adjoins the products of `n + 1` symbols. -/
lemma scalarSubmodule_succ (n : ℕ) :
    h.scalarSubmodule (n + 1) = h.scalarSubmodule n ⊔ h.scalarSubmoduleOne ^ (n + 1) := by
  rw [scalarSubmodule, scalarSubmodule, Finset.sum_range_succ, Submodule.add_eq_sup]

lemma scalarSubmoduleOne_pow_le_scalarSubmodule {k n : ℕ} (hk : k ≤ n) :
    h.scalarSubmoduleOne ^ k ≤ h.scalarSubmodule n := by
  rw [scalarSubmodule]
  exact Finset.single_le_sum (f := fun k => h.scalarSubmoduleOne ^ k)
    (fun _ _ => bot_le) (Finset.mem_range.mpr (Nat.lt_succ_of_le hk))

lemma scalarSubmoduleOne_le_scalarSubmodule {n : ℕ} (hn : 1 ≤ n) :
    h.scalarSubmoduleOne ≤ h.scalarSubmodule n := by
  rw [← pow_one h.scalarSubmoduleOne]
  exact h.scalarSubmoduleOne_pow_le_scalarSubmodule hn

/-- All terms in the algebra made from up to four combinations
  of `H` and `barH` -/
def scalarPotentialSubmodule : Submodule ℂ B := h.scalarSubmodule 4

/-!

## Closure under the gauge action

Each of the submodules above is *stable* under the gauge action on `B`: a gauge
transformation moves a Higgs symbol to a combination of Higgs symbols and nothing else. For
the two spans of symbols and their join this is exactly the equivariance recorded in
`IsHiggsAlgebraValued`. For the higher mass dimensions it needs, in addition, that a gauge
transformation acts on `B` by an *algebra* map; that is not among the fields of
`IsHiggsAlgebraValued`, so it is taken as the hypothesis `rep_mul` below — the analogue of
`IsGaugeField.gauge_mul` — and packaged as `repAlgHom`, after which `Submodule.mapHom`
carries the closure through products, powers and sums.

-/

lemma higgsSubmodule_map_le (g : GaugeGroupI) :
    h.higgsSubmodule.map (rep g) ≤ h.higgsSubmodule := by
  rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
  exact ⟨HiggsVec.repGaugeGroupI.dual g φ, (h.H_equivariant g φ).symm⟩

lemma barHiggsSubmodule_map_le (g : GaugeGroupI) :
    h.barHiggsSubmodule.map (rep g) ≤ h.barHiggsSubmodule := by
  rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
  exact ⟨HiggsVec.repGaugeGroupI.conj.dual g φ, (h.barH_equivariant g φ).symm⟩

/-- The Higgs symbols are closed under the gauge action.-/
lemma higgsSubmodule_closure (g : GaugeGroupI) :
    h.higgsSubmodule.map (rep g) = h.higgsSubmodule :=
  le_antisymm (h.higgsSubmodule_map_le g) fun b hb =>
    ⟨rep g⁻¹ b, h.higgsSubmodule_map_le g⁻¹ ⟨b, hb, rfl⟩, rep.self_inv_apply g b⟩

/-- The conjugate Higgs symbols are closed under the gauge action. -/
lemma barHiggsSubmodule_closure (g : GaugeGroupI) :
    h.barHiggsSubmodule.map (rep g) = h.barHiggsSubmodule :=
  le_antisymm (h.barHiggsSubmodule_map_le g) fun b hb =>
    ⟨rep g⁻¹ b, h.barHiggsSubmodule_map_le g⁻¹ ⟨b, hb, rfl⟩, rep.self_inv_apply g b⟩

/-- The mass-dimension-one terms are closed under the gauge action. -/
lemma scalarSubmoduleOne_closure (g : GaugeGroupI) :
    h.scalarSubmoduleOne.map (rep g) = h.scalarSubmoduleOne := by
  rw [scalarSubmoduleOne, Submodule.map_sup, h.higgsSubmodule_closure g,
    h.barHiggsSubmodule_closure g]

variable (rep_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
  rep g (b₁ * b₂) = rep g b₁ * rep g b₂)
include rep_mul

set_option linter.unusedVariables false in
/-- A gauge transformation as an algebra homomorphism of `B`. Only linearity is built into
  `Representation`; `rep_mul` supplies multiplicativity, and the unit is preserved because a
  gauge transformation is invertible. -/
def repAlgHom (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) (g : GaugeGroupI) : B →ₐ[ℂ] B :=
  AlgHom.ofLinearMap (rep g)
    (by
      obtain ⟨c, hc⟩ := (rep.apply_bijective g).2 1
      calc rep g 1 = rep g 1 * rep g c := by rw [hc, mul_one]
        _ = rep g (1 * c) := (rep_mul g 1 c).symm
        _ = 1 := by rw [one_mul, hc])
    (rep_mul g)

lemma repAlgHom_toLinearMap (g : GaugeGroupI) :
    (h.repAlgHom rep_mul g).toLinearMap = rep g := rfl

/-- The terms of mass dimension at most `n` are closed under the gauge action. -/
lemma scalarSubmodule_closure (g : GaugeGroupI) (n : ℕ) :
    (h.scalarSubmodule n).map (rep g) = h.scalarSubmodule n := by
  have hmap : ∀ S : Submodule ℂ B,
      S.map (rep g) = Submodule.mapHom (h.repAlgHom rep_mul g) S := fun _ => rfl
  rw [scalarSubmodule, hmap, map_sum]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_pow, ← hmap, h.scalarSubmoduleOne_closure g]

/-- The scalar potential terms are closed under the gauge action. -/
lemma scalarPotentialSubmodule_closure (g : GaugeGroupI) :
    (h.scalarPotentialSubmodule).map (rep g) = h.scalarPotentialSubmodule :=
  h.scalarSubmodule_closure rep_mul g 4

omit rep_mul in
/-- **The scalar potential terms, written out.** `scalarSubmodule 4` is the join of the
  powers `scalarSubmoduleOne ^ k` for `k ≤ 4`; expanding each power distributes over the
  join, and the Higgs and conjugate-Higgs symbols commute, so every ordered product equals
  the one with all `H` factors to the left. -/
lemma scalarPotentialSubmodule_eq_higgs (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    h.scalarPotentialSubmodule =
    1 ⊔ h.higgsSubmodule
      ⊔ h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule
      ⊔ h.higgsSubmodule * h.barHiggsSubmodule
      ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule
      ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule
      ⊔ h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule
      ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
  have hcomm : h.higgsSubmodule * h.barHiggsSubmodule = h.barHiggsSubmodule * h.higgsSubmodule := by
    refine le_antisymm (Submodule.mul_le.mpr fun m hm n hn => ?_)
      (Submodule.mul_le.mpr fun m hm n hn => ?_)
    · obtain ⟨φ, rfl⟩ := hm
      obtain ⟨ψ, rfl⟩ := hn
      rw [(h.H_comm_barH φ ψ).eq]
      exact Submodule.mul_mem_mul (LinearMap.mem_range_self _ _) (LinearMap.mem_range_self _ _)
    · obtain ⟨ψ, rfl⟩ := hm
      obtain ⟨φ, rfl⟩ := hn
      rw [← (h.H_comm_barH φ ψ).eq]
      exact Submodule.mul_mem_mul (LinearMap.mem_range_self _ _) (LinearMap.mem_range_self _ _)
  have hcm : Commute h.higgsSubmodule h.barHiggsSubmodule := hcomm
  have hCCA : Commute (h.barHiggsSubmodule * h.barHiggsSubmodule) h.higgsSubmodule := hcm.symm.mul_left hcm.symm
  have s1 : h.higgsSubmodule * h.barHiggsSubmodule * h.higgsSubmodule = h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule := by
    rw [mul_assoc, hcm.symm.eq, ← mul_assoc]
  have s2 : h.barHiggsSubmodule * h.barHiggsSubmodule * h.higgsSubmodule = h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [hCCA.eq, ← mul_assoc]
  have s3 : h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule * h.higgsSubmodule = h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule := by
    rw [mul_assoc (h.higgsSubmodule * h.higgsSubmodule) h.barHiggsSubmodule h.higgsSubmodule, hcm.symm.eq, ← mul_assoc]
  have s4 : h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.higgsSubmodule = h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [mul_assoc h.higgsSubmodule h.barHiggsSubmodule h.barHiggsSubmodule, mul_assoc h.higgsSubmodule (h.barHiggsSubmodule * h.barHiggsSubmodule) h.higgsSubmodule, hCCA.eq, ← mul_assoc,
      ← mul_assoc]
  have s5 : h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.higgsSubmodule = h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [(hCCA.mul_left hcm.symm).eq, ← mul_assoc, ← mul_assoc]
  have e2 : h.scalarSubmoduleOne ^ 2
      = h.higgsSubmodule * h.higgsSubmodule ⊔ h.higgsSubmodule * h.barHiggsSubmodule ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [pow_two, scalarSubmoduleOne, Submodule.sup_mul, Submodule.mul_sup, Submodule.mul_sup,
      ← hcomm]
    simp only [sup_assoc, sup_left_idem]
  have e3 : h.scalarSubmoduleOne ^ 3
      = h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule ⊔ h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule ⊔ h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [pow_succ, e2, scalarSubmoduleOne, Submodule.sup_mul, Submodule.sup_mul,
      Submodule.mul_sup, Submodule.mul_sup, Submodule.mul_sup, s1, s2]
    simp only [sup_assoc, sup_left_idem]
  have e4 : h.scalarSubmoduleOne ^ 4
      = h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule ⊔ h.higgsSubmodule * h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule ⊔ h.higgsSubmodule * h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule
        ⊔ h.higgsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule ⊔ h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule * h.barHiggsSubmodule := by
    rw [pow_succ, e3, scalarSubmoduleOne, Submodule.sup_mul, Submodule.sup_mul,
      Submodule.sup_mul, Submodule.mul_sup, Submodule.mul_sup, Submodule.mul_sup,
      Submodule.mul_sup, s3, s4, s5]
    simp only [sup_assoc, sup_left_idem]
  rw [scalarPotentialSubmodule, scalarSubmodule, Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_one, Submodule.add_eq_sup,
    Submodule.add_eq_sup, Submodule.add_eq_sup, Submodule.add_eq_sup, pow_zero, pow_one,
    e2, e3, e4, scalarSubmoduleOne]
  simp only [sup_assoc]


/-!

## Gauge weight decomposition

-/

omit rep_mul in
/-- The component symbol `H^0` is a joint eigenvector of all four torus generators, at the
  gauge weight `(0, 0, -1, -3)`. The Higgs is a colour singlet, so both colour exponents
  vanish; the symbol transforms contragrediently to the doublet, so its isospin weight is
  `-1` and its hypercharge `-3`. -/
lemma rep_gaugeTorusGen_higgsComponent_zero (i : Fin 4) :
    rep (gaugeTorusGen i) (h.higgsComponent 0)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, -3) i) • h.higgsComponent 0 := by
  have hstar : ((starRingEnd ℂ) (expI : ℂ)) ^ 3 = (((expI : ℂ)) ^ 3)⁻¹ := by
    rw [← inv_pow]
    congr 1
    exact expI_inv_eq_star.symm
  rw [h.rep_higgsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, expI_inv_eq_star, Matrix.one_apply, Unitary.coe_inv, hstar]
  rfl

omit rep_mul in
/-- The component symbol `H^1` is a joint eigenvector of all four torus generators, at the
  gauge weight `(0, 0, 1, -3)`. -/
lemma rep_gaugeTorusGen_higgsComponent_one (i : Fin 4) :
    rep (gaugeTorusGen i) (h.higgsComponent 1)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, -3) i) • h.higgsComponent 1 := by
  have hstar : ((starRingEnd ℂ) (expI : ℂ)) ^ 3 = (((expI : ℂ)) ^ 3)⁻¹ := by
    rw [← inv_pow]
    congr 1
    exact expI_inv_eq_star.symm
  rw [h.rep_higgsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, expI_inv_eq_star, Matrix.one_apply, Unitary.coe_inv, hstar]
  rfl

omit rep_mul in
/-- The gauge weight decomposition on the submodule `higgsSubmodule`.

  The Higgs is a colour singlet of hypercharge `-3`, but it is *not* of pure isospin: the
  submodule splits into the two component lines `span {H^0}` and `span {H^1}`, at the gauge
  weights `(0, 0, -1, -3)` and `(0, 0, 1, -3)`.

  In particular the zero-weight piece is `⊥`, so `mem_zero_of_invariant` says here that no
  nonzero term linear in the Higgs is gauge invariant. -/
noncomputable def higgsSubmoduleGaugeWeight (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    GaugeWeightDecomposition rep h.higgsSubmodule where
  piece := fun w =>
    if w = (0, 0, -1, -3) then Submodule.span ℂ {h.higgsComponent 0}
    else if w = (0, 0, 1, -3) then Submodule.span ℂ {h.higgsComponent 1} else ⊥
  supp := {(0, 0, -1, -3), (0, 0, 1, -3)}
  piece_le := by
    have hz : ∀ i : Fin 4, Submodule.span ℂ {h.higgsComponent 0}
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, -3) i) := fun i =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_higgsComponent_zero i))
    have ho : ∀ i : Fin 4, Submodule.span ℂ {h.higgsComponent 1}
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, -3) i) := fun i =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_higgsComponent_one i))
    intro w x hx i
    rcases eq_or_ne w (0, 0, -1, -3) with rfl | hw0
    · rw [if_pos rfl] at hx
      exact Module.End.mem_eigenspace_iff.mp (hz i hx)
    · rcases eq_or_ne w (0, 0, 1, -3) with rfl | hw1
      · rw [if_neg hw0, if_pos rfl] at hx
        exact Module.End.mem_eigenspace_iff.mp (ho i hx)
      · rw [if_neg hw0, if_neg hw1, Submodule.mem_bot] at hx
        subst hx
        simp
  piece_eq_bot := by
    intro w hw
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hw
    rw [if_neg hw.1, if_neg hw.2]
  iSup_piece := by
    refine le_antisymm (iSup_le fun w => ?_) ?_
    · rcases eq_or_ne w (0, 0, -1, -3) with rfl | hw0
      · rw [if_pos rfl]
        exact (Submodule.span_singleton_le_iff_mem _ _).mpr
          (h.higgsComponent_mem_higgsSubmodule 0)
      · rcases eq_or_ne w (0, 0, 1, -3) with rfl | hw1
        · rw [if_neg hw0, if_pos rfl]
          exact (Submodule.span_singleton_le_iff_mem _ _).mpr
            (h.higgsComponent_mem_higgsSubmodule 1)
        · rw [if_neg hw0, if_neg hw1]
          exact bot_le
    · rw [h.higgsSubmodule_eq_span_higgsComponents, Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      fin_cases j
      · refine Submodule.mem_iSup_of_mem (0, 0, -1, -3) ?_
        rw [if_pos rfl]
        exact Submodule.mem_span_singleton_self _
      · refine Submodule.mem_iSup_of_mem (0, 0, 1, -3) ?_
        rw [if_neg (by decide), if_pos rfl]
        exact Submodule.mem_span_singleton_self _

omit rep_mul in
/-- The conjugate component symbol `H̄^0` is a joint eigenvector of all four torus
  generators, at the gauge weight `(0, 0, 1, 3)`. Conjugation negates every exponent, so the
  weights here are the negatives of those of `H^0` and `H^1` — with the isospin weights
  exchanged between the two components. -/
lemma rep_gaugeTorusGen_barHiggsComponent_zero (i : Fin 4) :
    rep (gaugeTorusGen i) (h.barHiggsComponent 0)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, 3) i) • h.barHiggsComponent 0 := by
  have hc : (starRingEnd ℂ) (expI : ℂ) = ((expI : ℂ))⁻¹ := expI_inv_eq_star.symm
  rw [h.rep_barHiggsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, Matrix.one_apply, Unitary.coe_inv, hc]
  rfl

omit rep_mul in
/-- The conjugate component symbol `H̄^1` is a joint eigenvector of all four torus
  generators, at the gauge weight `(0, 0, -1, 3)`. -/
lemma rep_gaugeTorusGen_barHiggsComponent_one (i : Fin 4) :
    rep (gaugeTorusGen i) (h.barHiggsComponent 1)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, 3) i) • h.barHiggsComponent 1 := by
  have hc : (starRingEnd ℂ) (expI : ℂ) = ((expI : ℂ))⁻¹ := expI_inv_eq_star.symm
  rw [h.rep_barHiggsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, Matrix.one_apply, Unitary.coe_inv, hc]
  rfl

omit rep_mul in
/-- The gauge weight decomposition on the submodule `barHiggsSubmodule`.

  The conjugate Higgs is a colour singlet of hypercharge `+3`, and its two component symbols
  carry isospin weights `+1` and `-1`; so the submodule splits into the two weight lines
  `span {H̄^0}` and `span {H̄^1}`, at `(0, 0, 1, 3)` and `(0, 0, -1, 3)`.

  As for `higgsSubmoduleGaugeWeight` the zero-weight piece is `⊥`, so no nonzero term linear
  in the conjugate Higgs is gauge invariant. -/
noncomputable def barHiggsSubmoduleGaugeWeight (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    GaugeWeightDecomposition rep h.barHiggsSubmodule where
  piece := fun w =>
    if w = (0, 0, 1, 3) then Submodule.span ℂ {h.barHiggsComponent 0}
    else if w = (0, 0, -1, 3) then Submodule.span ℂ {h.barHiggsComponent 1} else ⊥
  supp := {(0, 0, 1, 3), (0, 0, -1, 3)}
  piece_le := by
    have hz : ∀ i : Fin 4, Submodule.span ℂ {h.barHiggsComponent 0}
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, 3) i) := fun i =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_barHiggsComponent_zero i))
    have ho : ∀ i : Fin 4, Submodule.span ℂ {h.barHiggsComponent 1}
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, 3) i) := fun i =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_barHiggsComponent_one i))
    intro w x hx i
    rcases eq_or_ne w (0, 0, 1, 3) with rfl | hw0
    · rw [if_pos rfl] at hx
      exact Module.End.mem_eigenspace_iff.mp (hz i hx)
    · rcases eq_or_ne w (0, 0, -1, 3) with rfl | hw1
      · rw [if_neg hw0, if_pos rfl] at hx
        exact Module.End.mem_eigenspace_iff.mp (ho i hx)
      · rw [if_neg hw0, if_neg hw1, Submodule.mem_bot] at hx
        subst hx
        simp
  piece_eq_bot := by
    intro w hw
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hw
    rw [if_neg hw.1, if_neg hw.2]
  iSup_piece := by
    refine le_antisymm (iSup_le fun w => ?_) ?_
    · rcases eq_or_ne w (0, 0, 1, 3) with rfl | hw0
      · rw [if_pos rfl]
        exact (Submodule.span_singleton_le_iff_mem _ _).mpr
          (h.barHiggsComponent_mem_barHiggsSubmodule 0)
      · rcases eq_or_ne w (0, 0, -1, 3) with rfl | hw1
        · rw [if_neg hw0, if_pos rfl]
          exact (Submodule.span_singleton_le_iff_mem _ _).mpr
            (h.barHiggsComponent_mem_barHiggsSubmodule 1)
        · rw [if_neg hw0, if_neg hw1]
          exact bot_le
    · rw [h.barHiggsSubmodule_eq_span_barHiggsComponents, Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      fin_cases j
      · refine Submodule.mem_iSup_of_mem (0, 0, 1, 3) ?_
        rw [if_pos rfl]
        exact Submodule.mem_span_singleton_self _
      · refine Submodule.mem_iSup_of_mem (0, 0, -1, 3) ?_
        rw [if_neg (by decide), if_pos rfl]
        exact Submodule.mem_span_singleton_self _

omit rep_mul in
lemma higgsSubmoduleGaugeWeight_supp (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    (h.higgsSubmoduleGaugeWeight).supp = {(0, 0, -1, -3), (0, 0, 1, -3)} := by
  rfl

omit rep_mul in
lemma barHiggsSubmoduleGaugeWeight_supp (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    (h.barHiggsSubmoduleGaugeWeight).supp = {(0, 0, 1, 3), (0, 0, -1, 3)} := by
  rfl

/-- **The gauge weight decomposition of the scalar potential terms.** Read straight off
  `scalarPotentialSubmodule_eq_higgs`: the unit contributes `one`, the two symbol spans
  contribute their own decompositions, every product of them is handled by `mul`, and the
  fifteen summands are joined by `sup`. -/
noncomputable def scalarPotentialSubmoduleGaugeWeight (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    GaugeWeightDecomposition rep h.scalarPotentialSubmodule :=
  let d := h.higgsSubmoduleGaugeWeight
  let d' := h.barHiggsSubmoduleGaugeWeight
  (((((((((((((((GaugeWeightDecomposition.one (fun g => map_one (h.repAlgHom rep_mul g))).sup
      d).sup
      d').sup
      (d.mul rep_mul d)).sup
      (d.mul rep_mul d')).sup
      (d'.mul rep_mul d')).sup
      ((d.mul rep_mul d).mul rep_mul d)).sup
      ((d.mul rep_mul d).mul rep_mul d')).sup
      ((d.mul rep_mul d').mul rep_mul d')).sup
      ((d'.mul rep_mul d').mul rep_mul d')).sup
      (((d.mul rep_mul d).mul rep_mul d).mul rep_mul d)).sup
      (((d.mul rep_mul d).mul rep_mul d).mul rep_mul d')).sup
      (((d.mul rep_mul d).mul rep_mul d').mul rep_mul d')).sup
      (((d.mul rep_mul d').mul rep_mul d').mul rep_mul d')).sup
      (((d'.mul rep_mul d').mul rep_mul d').mul rep_mul d')).copy _
    h.scalarPotentialSubmodule_eq_higgs

def higgsQuadraticZeroGaugeWeight (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) : Submodule ℂ B :=
   Submodule.span ℂ
      {h.higgsComponent 0 * h.barHiggsComponent 0, h.higgsComponent 1 * h.barHiggsComponent 1}

open GaugeWeightDecomposition in
lemma scalarPotentialSubmoduleGaugeWeight_peice_zero (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    let H2 :=  Submodule.span ℂ
      {h.higgsComponent 0 * h.barHiggsComponent 0, h.higgsComponent 1 * h.barHiggsComponent 1}
    (h.scalarPotentialSubmoduleGaugeWeight rep_mul).piece 0 =
    1 ⊔ H2 ⊔ H2 * H2 := by
  dsimp only [scalarPotentialSubmoduleGaugeWeight, GaugeWeightDecomposition.copy_piece,
    GaugeWeightDecomposition.sup_piece, GaugeWeightDecomposition.one_piece, ↓dreduceIte,
    Submodule.zero_eq_bot]
  simp (disch := (try simp only [higgsSubmoduleGaugeWeight, barHiggsSubmoduleGaugeWeight,
    GaugeWeightDecomposition.one, GaugeWeightDecomposition.mul_supp]; try decide)) only
    [GaugeWeightDecomposition.piece_eq_zero_of_not_mem_supp, sup_bot_eq]
  simp only [GaugeWeightDecomposition.mul_piece_eq_sub', barHiggsSubmoduleGaugeWeight_supp
  , higgsSubmoduleGaugeWeight_supp, Finset.iSup_insert, Finset.iSup_singleton]
  simp (disch := (try simp only [higgsSubmoduleGaugeWeight, barHiggsSubmoduleGaugeWeight,
    GaugeWeightDecomposition.one, GaugeWeightDecomposition.mul_supp]; try decide))
    [GaugeWeightDecomposition.piece_eq_zero_of_not_mem_supp]
  simp [barHiggsSubmoduleGaugeWeight,  higgsSubmoduleGaugeWeight, Submodule.span_mul_span]
  rw [← Submodule.span_mul_span, Submodule.span_insert]
  simp only [Submodule.sup_mul, Submodule.mul_sup, Submodule.span_mul_span,
    Set.singleton_mul_singleton]
  have hHH : ∀ i j, h.higgsComponent i * h.higgsComponent j
      = h.higgsComponent j * h.higgsComponent i := fun i j => (h.H_comm_H _ _).eq
  have hbH : ∀ i j, h.barHiggsComponent i * h.higgsComponent j
      = h.higgsComponent j * h.barHiggsComponent i := fun i j => (h.H_comm_barH _ _).symm.eq
  have hbb : ∀ i j, h.barHiggsComponent i * h.barHiggsComponent j
      = h.barHiggsComponent j * h.barHiggsComponent i := fun i j => (h.barH_comm_barH _ _).eq
  have hHH' : ∀ i j (x : B), h.higgsComponent i * (h.higgsComponent j * x)
      = h.higgsComponent j * (h.higgsComponent i * x) := fun i j x => by
    rw [← mul_assoc, hHH, mul_assoc]
  have hbH' : ∀ i j (x : B), h.barHiggsComponent i * (h.higgsComponent j * x)
      = h.higgsComponent j * (h.barHiggsComponent i * x) := fun i j x => by
    rw [← mul_assoc, hbH, mul_assoc]
  simp only [mul_assoc, hHH, hHH', hbH', hbb]
  simp only [sup_idem]


/-!

## SU(2) permutation decomposition

-/

omit rep_mul in
/-- The Weyl element sends `H⁰` to `H¹`. -/
lemma rep_gaugeSU2Perm_higgsComponent_zero :
    rep gaugeSU2Perm (h.higgsComponent 0) = h.higgsComponent 1 := by
  rw [h.rep_higgsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe,
    Fin.sum_univ_two]

omit rep_mul in
/-- The Weyl element sends `H¹` to `-H⁰`. -/
lemma rep_gaugeSU2Perm_higgsComponent_one :
    rep gaugeSU2Perm (h.higgsComponent 1) = -h.higgsComponent 0 := by
  rw [h.rep_higgsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe,
    Fin.sum_univ_two]

omit rep_mul in
/-- The Weyl element sends `H̄⁰` to `H̄¹`. -/
lemma rep_gaugeSU2Perm_barHiggsComponent_zero :
    rep gaugeSU2Perm (h.barHiggsComponent 0) = h.barHiggsComponent 1 := by
  rw [h.rep_barHiggsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe,
    Fin.sum_univ_two]

omit rep_mul in
/-- The Weyl element sends `H̄¹` to `-H̄⁰`. -/
lemma rep_gaugeSU2Perm_barHiggsComponent_one :
    rep gaugeSU2Perm (h.barHiggsComponent 1) = -h.barHiggsComponent 0 := by
  rw [h.rep_barHiggsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe,
    Fin.sum_univ_two]

/-- **The Weyl decomposition of the zero-weight quadratic.** The Weyl element exchanges
  `H⁰H̄⁰` and `H¹H̄¹`, so the two-dimensional space `higgsQuadraticZeroGaugeWeight` splits
  into the even line spanned by `H⁰H̄⁰ + H¹H̄¹` — this is `H†H`, the genuine invariant — and
  the odd line spanned by `H⁰H̄⁰ - H¹H̄¹`, which is `H†σ³H`, the neutral component of the
  isospin triplet. Only the first survives `mem_zero_of_invariant`. -/
noncomputable def higgsQuadraticZeroGaugeWeightSU2Perm (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    SU2PermDecomposition rep h.higgsQuadraticZeroGaugeWeight where
  piece := fun w =>
    if w = 0 then Submodule.span ℂ {h.higgsComponent 0 * h.barHiggsComponent 0
        + h.higgsComponent 1 * h.barHiggsComponent 1}
    else if w = 2 then Submodule.span ℂ {h.higgsComponent 0 * h.barHiggsComponent 0
        - h.higgsComponent 1 * h.barHiggsComponent 1}
    else ⊥
  piece_le := by
    have hplus : rep gaugeSU2Perm (h.higgsComponent 0 * h.barHiggsComponent 0
        + h.higgsComponent 1 * h.barHiggsComponent 1)
        = h.higgsComponent 0 * h.barHiggsComponent 0
          + h.higgsComponent 1 * h.barHiggsComponent 1 := by
      rw [map_add, rep_mul, rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
        h.rep_gaugeSU2Perm_barHiggsComponent_zero, h.rep_gaugeSU2Perm_higgsComponent_one,
        h.rep_gaugeSU2Perm_barHiggsComponent_one, neg_mul_neg, add_comm]
    have hminus : rep gaugeSU2Perm (h.higgsComponent 0 * h.barHiggsComponent 0
        - h.higgsComponent 1 * h.barHiggsComponent 1)
        = -(h.higgsComponent 0 * h.barHiggsComponent 0
          - h.higgsComponent 1 * h.barHiggsComponent 1) := by
      rw [map_sub, rep_mul, rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
        h.rep_gaugeSU2Perm_barHiggsComponent_zero, h.rep_gaugeSU2Perm_higgsComponent_one,
        h.rep_gaugeSU2Perm_barHiggsComponent_one, neg_mul_neg, neg_sub]
    intro k x hx
    rcases eq_or_ne k 0 with rfl | hk0
    · rw [if_pos rfl, Submodule.mem_span_singleton] at hx
      obtain ⟨c, rfl⟩ := hx
      rw [map_smul, hplus, su2PermSign_zero, one_smul]
    · rcases eq_or_ne k 2 with rfl | hk2
      · rw [if_neg hk0, if_pos rfl, Submodule.mem_span_singleton] at hx
        obtain ⟨c, rfl⟩ := hx
        rw [map_smul, hminus, su2PermSign_two, smul_neg, neg_smul, one_smul]
      · rw [if_neg hk0, if_neg hk2, Submodule.mem_bot] at hx
        subst hx
        simp
  iSup_piece := by
    have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
    refine le_antisymm (iSup_le fun k => ?_) ?_
    · rcases hcases k with rfl | rfl | rfl | rfl
      · rw [if_pos rfl, higgsQuadraticZeroGaugeWeight, Submodule.span_le,
          Set.singleton_subset_iff]
        exact Submodule.add_mem _ (Submodule.subset_span (by simp))
          (Submodule.subset_span (by simp))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
      · rw [if_neg (by decide), if_pos rfl, higgsQuadraticZeroGaugeWeight, Submodule.span_le,
          Set.singleton_subset_iff]
        exact Submodule.sub_mem _ (Submodule.subset_span (by simp))
          (Submodule.subset_span (by simp))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
    · refine le_trans ?_ (sup_le (le_iSup _ (0 : ZMod 4)) (le_iSup _ (2 : ZMod 4)))
      rw [if_pos rfl, if_neg (by decide : ¬(2 : ZMod 4) = 0), if_pos rfl,
        higgsQuadraticZeroGaugeWeight, Submodule.span_le]
      have hp := Submodule.mem_sup_left (S := Submodule.span ℂ
        {h.higgsComponent 0 * h.barHiggsComponent 0
          + h.higgsComponent 1 * h.barHiggsComponent 1})
        (T := Submodule.span ℂ {h.higgsComponent 0 * h.barHiggsComponent 0
          - h.higgsComponent 1 * h.barHiggsComponent 1})
        (Submodule.mem_span_singleton_self _)
      have hm := Submodule.mem_sup_right (S := Submodule.span ℂ
        {h.higgsComponent 0 * h.barHiggsComponent 0
          + h.higgsComponent 1 * h.barHiggsComponent 1})
        (T := Submodule.span ℂ {h.higgsComponent 0 * h.barHiggsComponent 0
          - h.higgsComponent 1 * h.barHiggsComponent 1})
        (Submodule.mem_span_singleton_self _)
      rintro x (rfl | rfl)
      · have hs := Submodule.smul_mem _ (2⁻¹ : ℂ) (Submodule.add_mem _ hp hm)
        rwa [show (2⁻¹ : ℂ) • ((h.higgsComponent 0 * h.barHiggsComponent 0
          + h.higgsComponent 1 * h.barHiggsComponent 1)
          + (h.higgsComponent 0 * h.barHiggsComponent 0
            - h.higgsComponent 1 * h.barHiggsComponent 1))
          = h.higgsComponent 0 * h.barHiggsComponent 0 from by module] at hs
      · have hs := Submodule.smul_mem _ (2⁻¹ : ℂ) (Submodule.sub_mem _ hp hm)
        rwa [show (2⁻¹ : ℂ) • ((h.higgsComponent 0 * h.barHiggsComponent 0
          + h.higgsComponent 1 * h.barHiggsComponent 1)
          - (h.higgsComponent 0 * h.barHiggsComponent 0
            - h.higgsComponent 1 * h.barHiggsComponent 1))
          = h.higgsComponent 1 * h.barHiggsComponent 1 from by module] at hs

/-- **The Weyl decomposition of the invariant candidates.** Read straight off
  `scalarPotentialSubmoduleGaugeWeight_peice_zero`: the constants contribute `one`, the
  quadratic `H†H` sector contributes `higgsQuadraticZeroGaugeWeightSU2Perm`, the quartic
  sector is its `mul` with itself, and the three are joined by `sup`. -/
noncomputable def scalarPotentialSubmoduleGaugeWeightZeroSU2Perm
    (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    SU2PermDecomposition rep ((h.scalarPotentialSubmoduleGaugeWeight rep_mul).piece 0) :=
  let d := h.higgsQuadraticZeroGaugeWeightSU2Perm rep_mul
  (((SU2PermDecomposition.one (fun g => map_one (h.repAlgHom rep_mul g))).sup d).sup
      (d.mul rep_mul d)).copy _
    (h.scalarPotentialSubmoduleGaugeWeight_peice_zero rep_mul)

/-- The gauge-invariant quadratic `H†H`, the Higgs mass term. -/
noncomputable def massTerm : B := h.higgsComponent 0 * h.barHiggsComponent 0
        + h.higgsComponent 1 * h.barHiggsComponent 1

/-- The neutral component `H†σ³H` of the isospin triplet. It has gauge weight zero and is
  odd under the Weyl element, so it is discarded by `SU2PermDecomposition`; its *square* is
  even, and survives both sieves without being gauge invariant. -/
noncomputable def tripletTerm : B := h.higgsComponent 0 * h.barHiggsComponent 0
        - h.higgsComponent 1 * h.barHiggsComponent 1

/-- **The mass term is gauge invariant.** `H†H` is fixed by every gauge transformation:
  the hypercharge phases cancel between `H` and `H̄`, and the `SU(2)` matrix cancels against
  its conjugate by unitarity. -/
lemma massTerm_invariant (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) (g : GaugeGroupI) :
    rep g h.massTerm = h.massTerm := by
  have hu : ((g⁻¹).toU1 : ℂ) * (starRingEnd ℂ) ((g⁻¹).toU1 : ℂ) = 1 :=
    Unitary.mul_star_self_of_mem (g⁻¹).toU1.2
  have hM : star ((g⁻¹).toSU2.1) * (g⁻¹).toSU2.1 = 1 :=
    Matrix.mem_unitaryGroup_iff'.mp (g⁻¹).toSU2.2.1
  have hM00 := congrFun (congrFun hM 0) 0
  have hM01 := congrFun (congrFun hM 0) 1
  have hM10 := congrFun (congrFun hM 1) 0
  have hM11 := congrFun (congrFun hM 1) 1
  simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, star_eq_conjTranspose,
    Matrix.conjTranspose_apply, reduceIte, Complex.star_def,
    show ¬((0 : Fin 2) = 1) from by decide,
    show ¬((1 : Fin 2) = 0) from by decide] at hM00 hM01 hM10 hM11
  have hM01' := congrArg (starRingEnd ℂ) hM01
  have hM10' := congrArg (starRingEnd ℂ) hM10
  simp only [map_add, map_mul, Complex.conj_conj, map_zero] at hM01' hM10'
  have hu3 : ((g⁻¹).toU1 : ℂ) ^ 3 * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3) = 1 := by
    rw [map_pow, ← mul_pow, hu, one_pow]
  have key : ∀ a b : ℂ, (((g⁻¹).toU1 : ℂ) ^ 3 * a) * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3 * b)
      = a * (starRingEnd ℂ) b := by
    intro a b
    rw [map_mul]
    calc (((g⁻¹).toU1 : ℂ) ^ 3 * a) * ((starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3)
          * (starRingEnd ℂ) b)
        = (((g⁻¹).toU1 : ℂ) ^ 3 * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3))
          * (a * (starRingEnd ℂ) b) := by ring
      _ = a * (starRingEnd ℂ) b := by rw [hu3, one_mul]
  rw [massTerm, map_add, rep_mul, rep_mul, h.rep_higgsComponent, h.rep_barHiggsComponent,
    h.rep_higgsComponent, h.rep_barHiggsComponent]
  simp only [Fin.sum_univ_two, add_mul, mul_add, smul_mul_smul_comm, key]
  match_scalars
  · linear_combination hM00
  · linear_combination hM10'
  · linear_combination hM01'
  · linear_combination hM11

/-- **The even part of the weight-zero potential terms.** Note the fourth generator: the
  quartic sector contributes `odd * odd` as well as `even * even`, so `(H†σ³H)²` is here
  alongside `1`, `H†H` and `(H†H)²`. -/
lemma scalarPotentialSubmoduleGaugeWeightZeroSU2Perm_piece_zero
    (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) :
    (h.scalarPotentialSubmoduleGaugeWeightZeroSU2Perm rep_mul).piece 0 =
    Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm,
      h.tripletTerm * h.tripletTerm} := by
  dsimp only [scalarPotentialSubmoduleGaugeWeightZeroSU2Perm, SU2PermDecomposition.copy_piece,
    SU2PermDecomposition.sup_piece, SU2PermDecomposition.one_piece]
  rw [SU2PermDecomposition.mul_piece_eq]
  dsimp only [higgsQuadraticZeroGaugeWeightSU2Perm]
  simp only [show ((0 : ZMod 4) - 1) = 3 from by decide,
    show ((0 : ZMod 4) - 2) = 2 from by decide, show ((0 : ZMod 4) - 3) = 1 from by decide,
    show ¬((1 : ZMod 4) = 0) from by decide, show ¬((1 : ZMod 4) = 2) from by decide,
    show ¬((2 : ZMod 4) = 0) from by decide, show ¬((3 : ZMod 4) = 0) from by decide,
    show ¬((3 : ZMod 4) = 2) from by decide,
    reduceIte, Submodule.mul_bot, sup_bot_eq,
    Submodule.span_mul_span, Set.singleton_mul_singleton]
  rw [massTerm, tripletTerm, Submodule.one_eq_span]
  simp only [Submodule.span_insert, sup_assoc]

lemma invariant_mem_span_massTerm_of_mem_scalarPotentialSubmodule
    (h : IsHiggsAlgebraValued B rep H barH massWeightPoly) (x : B)
    (hx : x ∈ h.scalarPotentialSubmodule) (x_inv : ∀ g, rep g x = x) :
    x ∈ Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm} := by
  have hmem : !![(1 - Complex.I) / 2, (-1 - Complex.I) / 2;
      (1 - Complex.I) / 2, (1 + Complex.I) / 2] ∈ specialUnitaryGroup (Fin 2) ℂ := by
    rw [Matrix.mem_specialUnitaryGroup_iff]
    refine ⟨?_, ?_⟩
    · rw [Matrix.mem_unitaryGroup_iff]
      ext a b
      fin_cases a <;> fin_cases b <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two, star_eq_conjTranspose,
          Matrix.conjTranspose_apply, map_div₀, map_ofNat,
          Complex.ext_iff] <;> norm_num
    · rw [Matrix.det_fin_two_of]
      simp [Complex.ext_iff]
      norm_num
  set g : GaugeGroupI := ⟨1, ⟨_, hmem⟩, 1⟩ with hg
  have hginv : ((g⁻¹).toSU2 : Matrix (Fin 2) (Fin 2) ℂ)
      = !![(1 + Complex.I)/2, (1 + Complex.I)/2; (-1 + Complex.I)/2, (1 - Complex.I)/2] := by
    rw [map_inv, ← Matrix.star_eq_inv, Matrix.specialUnitaryGroup.coe_star]
    ext a b
    fin_cases a <;> fin_cases b <;>
      simp [hg, GaugeGroupI.toSU2, Complex.conj_I, Complex.ext_iff]
  have hU1 : ((g⁻¹).toU1 : ℂ) = 1 := by simp [hg, GaugeGroupI.toU1]
  have hH0 : rep g (h.higgsComponent 0)
      = ((1 + Complex.I)/2) • h.higgsComponent 0 + ((1 + Complex.I)/2) • h.higgsComponent 1 := by
    rw [h.rep_higgsComponent, Fin.sum_univ_two, hU1, hginv]
    simp
  have hH1 : rep g (h.higgsComponent 1)
      = ((-1 + Complex.I)/2) • h.higgsComponent 0 + ((1 - Complex.I)/2) • h.higgsComponent 1 := by
    rw [h.rep_higgsComponent, Fin.sum_univ_two, hU1, hginv]
    simp
  have hB0 : rep g (h.barHiggsComponent 0)
      = ((1 - Complex.I)/2) • h.barHiggsComponent 0
        + ((1 - Complex.I)/2) • h.barHiggsComponent 1 := by
    rw [h.rep_barHiggsComponent, Fin.sum_univ_two, hU1, hginv]
    simp [map_div₀, Complex.conj_I, map_ofNat]
    module
  have hB1 : rep g (h.barHiggsComponent 1)
      = ((-1 - Complex.I)/2) • h.barHiggsComponent 0
        + ((1 + Complex.I)/2) • h.barHiggsComponent 1 := by
    rw [h.rep_barHiggsComponent, Fin.sum_univ_two, hU1, hginv]
    simp [map_div₀, Complex.conj_I, map_ofNat]
    module
  have hn3 : rep g h.tripletTerm = h.higgsComponent 0 * h.barHiggsComponent 1
      + h.higgsComponent 1 * h.barHiggsComponent 0 := by
    rw [tripletTerm, map_sub, rep_mul, rep_mul, hH0, hB0, hH1, hB1]
    simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm]
    match_scalars <;> simp [Complex.ext_iff] <;> norm_num
  have hn1 : rep g (h.higgsComponent 0 * h.barHiggsComponent 1
      + h.higgsComponent 1 * h.barHiggsComponent 0)
      = Complex.I • (h.higgsComponent 0 * h.barHiggsComponent 1
        - h.higgsComponent 1 * h.barHiggsComponent 0) := by
    rw [map_add, rep_mul, rep_mul, hH0, hB0, hH1, hB1]
    simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm, smul_sub]
    match_scalars <;> simp [Complex.ext_iff] <;> norm_num
  have hHH : ∀ i j, h.higgsComponent i * h.higgsComponent j
      = h.higgsComponent j * h.higgsComponent i := fun i j => (h.H_comm_H _ _).eq
  have hbH : ∀ i j, h.barHiggsComponent i * h.higgsComponent j
      = h.higgsComponent j * h.barHiggsComponent i := fun i j => (h.H_comm_barH _ _).symm.eq
  have hbb : ∀ i j, h.barHiggsComponent i * h.barHiggsComponent j
      = h.barHiggsComponent j * h.barHiggsComponent i := fun i j => (h.barH_comm_barH _ _).eq
  have hHH' : ∀ i j (y : B), h.higgsComponent i * (h.higgsComponent j * y)
      = h.higgsComponent j * (h.higgsComponent i * y) := fun i j y => by
    rw [← mul_assoc, hHH, mul_assoc]
  have hbH' : ∀ i j (y : B), h.barHiggsComponent i * (h.higgsComponent j * y)
      = h.higgsComponent j * (h.barHiggsComponent i * y) := fun i j y => by
    rw [← mul_assoc, hbH, mul_assoc]
  have fierz : h.tripletTerm * h.tripletTerm
      + (h.higgsComponent 0 * h.barHiggsComponent 1 + h.higgsComponent 1 * h.barHiggsComponent 0)
        * (h.higgsComponent 0 * h.barHiggsComponent 1
          + h.higgsComponent 1 * h.barHiggsComponent 0)
      + (Complex.I • (h.higgsComponent 0 * h.barHiggsComponent 1
          - h.higgsComponent 1 * h.barHiggsComponent 0))
        * (Complex.I • (h.higgsComponent 0 * h.barHiggsComponent 1
          - h.higgsComponent 1 * h.barHiggsComponent 0))
      = h.massTerm * h.massTerm := by
    rw [tripletTerm, massTerm]
    simp only [sub_mul, mul_sub, add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
      mul_assoc, hHH', hbH', hbb]
    match_scalars <;> simp [Complex.ext_iff]
  have hT3 : ∀ y : B, rep (g * g) y = rep g (rep g y) := by
    intro y
    rw [map_mul]
    rfl
  have e1 : rep g (h.tripletTerm * h.tripletTerm)
      = (h.higgsComponent 0 * h.barHiggsComponent 1 + h.higgsComponent 1 * h.barHiggsComponent 0)
        * (h.higgsComponent 0 * h.barHiggsComponent 1
          + h.higgsComponent 1 * h.barHiggsComponent 0) := by
    rw [rep_mul, hn3]
  have e2 : rep (g * g) (h.tripletTerm * h.tripletTerm)
      = (Complex.I • (h.higgsComponent 0 * h.barHiggsComponent 1
          - h.higgsComponent 1 * h.barHiggsComponent 0))
        * (Complex.I • (h.higgsComponent 0 * h.barHiggsComponent 1
          - h.higgsComponent 1 * h.barHiggsComponent 0)) := by
    rw [hT3, e1, rep_mul, hn1]
  have hone : ∀ k : GaugeGroupI, rep k (1 : B) = 1 := fun k => map_one (h.repAlgHom rep_mul k)
  have hm : ∀ k : GaugeGroupI, rep k h.massTerm = h.massTerm := massTerm_invariant rep_mul h
  have hmm : ∀ k : GaugeGroupI, rep k (h.massTerm * h.massTerm) = h.massTerm * h.massTerm :=
    fun k => by rw [rep_mul, hm]
  -- the two sieves put `x` in a four-generator span
  have hspan : x ∈ Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm,
      h.tripletTerm * h.tripletTerm} := by
    rw [← h.scalarPotentialSubmoduleGaugeWeightZeroSU2Perm_piece_zero rep_mul]
    exact SU2PermDecomposition.mem_zero_of_invariant _
      (GaugeWeightDecomposition.mem_zero_of_invariant _ hx x_inv) x_inv
  -- averaging over the three axes maps that span into the three-generator one
  have s1 : (1 : B) ∈ Submodule.span ℂ ({1, h.massTerm, h.massTerm * h.massTerm} : Set B) :=
    Submodule.subset_span (by simp)
  have s2 : h.massTerm ∈ Submodule.span ℂ ({1, h.massTerm, h.massTerm * h.massTerm} : Set B) :=
    Submodule.subset_span (by simp)
  have s3 : h.massTerm * h.massTerm
      ∈ Submodule.span ℂ ({1, h.massTerm, h.massTerm * h.massTerm} : Set B) :=
    Submodule.subset_span (by simp)
  set T : B →ₗ[ℂ] B := LinearMap.id + rep g + rep (g * g) with hT
  have hTapp : ∀ y : B, T y = y + rep g y + rep (g * g) y := fun y => rfl
  have hmaple : Submodule.map T (Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm,
        h.tripletTerm * h.tripletTerm})
      ≤ Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm} := by
    rw [Submodule.map_span_le]
    rintro y (rfl | rfl | rfl | rfl) <;> rw [hTapp]
    · rw [hone, hone]
      exact Submodule.add_mem _ (Submodule.add_mem _ s1 s1) s1
    · rw [hm, hm]
      exact Submodule.add_mem _ (Submodule.add_mem _ s2 s2) s2
    · rw [hmm, hmm]
      exact Submodule.add_mem _ (Submodule.add_mem _ s3 s3) s3
    · rw [e1, e2, fierz]
      exact s3
  have hx3 : T x = (3 : ℂ) • x := by
    rw [hTapp, x_inv, x_inv]
    module
  have hfin : (3 : ℂ) • x ∈ Submodule.span ℂ {1, h.massTerm, h.massTerm * h.massTerm} := by
    rw [← hx3]
    exact hmaple ⟨x, hspan, rfl⟩
  have hfin' := Submodule.smul_mem _ ((3 : ℂ)⁻¹) hfin
  rwa [smul_smul, inv_mul_cancel₀ (by norm_num : (3 : ℂ) ≠ 0), one_smul] at hfin'

end IsHiggsAlgebraValued

end StandardModel
