/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization.Basic
public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization.Symmetrized
/-!
# The gauge invariants of a realization

## i. Overview

For a free package, the classification of invariants of
`Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization.Symmetrized`
applies to every realization of the gauge-boson jet algebra: a gauge invariant of the
subalgebra generated by the gauge-field symbols and a set `S` of elements fixed by the pure
jets is a polynomial in the covariant derivatives of the field strength and the elements of
`S`. The commutation hypotheses on the gauge-field symbols are automatic for a realization,
since the symbols are images of a commutative algebra; only the commutation of `S` with the
symbols remains to be supplied. The jet algebra itself is the case of the identity
realization.

## ii. Key results

- `GaugeAlgebraRealization.invariant_mem_adjoin_fieldStrength` : the classification of
  invariants for a realization.
- `GaugeJetAlgebra.invariant_mem_adjoin_fieldStrength` : the classification for the jet
  algebra itself.

## iii. Table of contents

- A. The classification for a realization
- B. The classification for the jet algebra

-/

@[expose] public section

set_option linter.unusedSectionVars false

variable {G : Type} [Group G] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]
variable {G₀ : Type} [Group G₀] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
variable {jets : LocalGaugeData G 𝔤 G₀ 𝔤J}

open TensorProduct Matrix MatrixGroups

/-!

## A. The classification for a realization

-/

namespace GaugeAlgebraRealization

variable {B : Type} [Ring B] [Algebra ℂ B] {repJet : Representation ℂ G B}
  {repLorentz : Representation ℂ SL(2,ℂ) B} (h : GaugeAlgebraRealization jets B repJet repLorentz)

/-- The classification of gauge invariants of a realization: for a free package, a
  gauge-invariant element of the subalgebra generated by the gauge-field symbols and a set
  `S` of elements fixed by the pure jets and commuting with the symbols is a polynomial in
  the covariant derivatives of the field strength and the elements of `S`. -/
theorem invariant_mem_adjoin_fieldStrength [jets.Free] (S : Set B)
    (hcS : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      ∀ y ∈ S, Commute y (h.A p μ φ))
    (hS : ∀ y ∈ S, ∀ U : jets.truncationKer 0, repJet U.1 y = y)
    {x : B} (hx : x ∈ Algebra.adjoin ℂ (IsGaugeField.symbols h.A ∪ S))
    (hinv : ∀ U : G, repJet U x = x) :
    x ∈ Algebra.adjoin ℂ (IsGaugeField.tower h.A ∪ S) :=
  IsGaugeField.invariant_mem_adjoin_fieldStrength h.isGaugeField h.commute_A S hcS hS hx hinv

end GaugeAlgebraRealization

/-!

## B. The classification for the jet algebra

-/

namespace GaugeJetAlgebra

variable (jets) in
/-- The classification of gauge invariants of the gauge-boson jet algebra: for a free
  package, a gauge-invariant element of the subalgebra generated by the gauge-field symbols
  `∂_s A_μ^φ` and a set `S` of elements fixed by the pure jets — for instance the covariant
  towers of matter fields — is a polynomial in the covariant derivatives of the field
  strength and the elements of `S`. This is the covariance reduction of the gauge sector:
  invariance eliminates the bare gauge-field symbols in favour of the field strength and
  its covariant derivatives. -/
theorem invariant_mem_adjoin_fieldStrength [jets.Free] (S : Set (ℂ ⊗[ℝ] GaugeJetAlgebra 𝔤))
    (hS : ∀ y ∈ S, ∀ U : jets.truncationKer 0, complexRepJet jets U.1 y = y)
    {x : ℂ ⊗[ℝ] GaugeJetAlgebra 𝔤}
    (hx : x ∈ Algebra.adjoin ℂ ({b : ℂ ⊗[ℝ] GaugeJetAlgebra 𝔤 |
      ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      b = gaugeField 𝔤 p μ φ} ∪ S))
    (hinv : ∀ U : G, complexRepJet jets U x = x) :
    x ∈ Algebra.adjoin ℂ ({b : ℂ ⊗[ℝ] GaugeJetAlgebra 𝔤 |
      ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      b = IsGaugeField.iteratedCovDerivAdjoint (gaugeField 𝔤) l
        (IsGaugeField.fieldStrength (gaugeField 𝔤) ν lam) 0 φ} ∪ S) :=
  IsGaugeField.invariant_mem_adjoin_fieldStrength (isGaugeField jets)
    (fun _ _ _ _ _ _ => Commute.all _ _)
    S (fun _ _ _ _ _ => Commute.all _ _) hS hx hinv

end GaugeJetAlgebra
