/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.Mathematics.TensorProduct
public import Physlib.Particles.StandardModel.GaugeBosons.Gluons.JetCompleteness.FiniteHeight
/-!
# All-orders and full-group completeness

## i. Overview

This file removes the height bound from `FiniteHeight` and then passes from based jets
to the whole jet gauge
group.  The two statements are

```text
A fixed by based jets = C
A fixed by the full jet group = C fixed by constant SU(3)
```

where `A` is `OrdinaryJets`'s all-orders ordinary gluon jet algebra on the physical
traceless-hermitian
colour carrier and `C = covAlgebra` is `CovariantTower`'s subalgebra generated by the symmetrized
covariant
curvature derivatives `D^r F`.

## ii. Removing the height bound

No new machinery is needed.  An element of a symmetric algebra is a polynomial, so its image under
`OrdinaryJets`'s `toPoly` has a finite variable set; the largest derivative degree occurring in that
set is a
height bound, which is `FiniteHeight`'s `mem_heightAlgebra_vars_sup`.
`FiniteHeight` then identifies the based
invariants of that height with the truncated covariant algebra, which sits inside `covAlgebra`.

## iii. The full group

The second theorem does **not** say that every element of `covAlgebra` is invariant: an
uncontracted `covCurv` component transforms covariantly, and a constant colour rotation generally
moves it.  Only the globally `SU(3)`-invariant combinations are fixed by the whole jet group.  The
reverse inclusion uses `CovariantTower`'s `gaugePull_eq_ofConstantSU`, which replaces the action of
an arbitrary
jet on the covariant subalgebra by the action of the constant jet of its base-point value.  No
ordered product decomposition of a jet is constructed, and the contravariant composition law
`gaugePull (U * V) = gaugePull V ∘ gaugePull U` is never inverted.

## iv. Results

* `fixed_by_based_eq_covAlgebra` — the all-orders based fixed-algebra theorem;
* `fixed_by_jetGroup_eq_invariant_covAlgebra` — the full-group theorem.

-/

@[expose] public section

namespace StandardModel

open Matrix Module MvPolynomial
open scoped TensorProduct

namespace SU3Jet

/-!

## A. Removing the height bound

-/

/-- **All-orders based completeness.**  The elements of the all-orders ordinary gluon jet algebra
fixed by every *based* `SU(3)` gauge jet are exactly the elements of the subalgebra generated by
the symmetrized covariant curvature derivatives.

The forward direction bounds the derivative height of a single polynomial by the largest
derivative degree among its finitely many variables and applies `FiniteHeight` at that
height; the reverse
direction is `CovariantTower`'s `gaugePull_eq_self_of_based`. -/
lemma fixed_by_based_eq_covAlgebra :
    {P : JetAlgebra | ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U P = P} =
      (covAlgebra : Set JetAlgebra) := by
  ext P
  simp only [Set.mem_setOf_eq, SetLike.mem_coe]
  constructor
  · intro hP
    have hmem : P ∈ {Q : JetAlgebra | Q ∈ heightAlgebra ((toPoly P).vars.sup genDeg) ∧
        ∀ U : specialUnitaryGroup (Fin 3) JetRing,
          JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U Q = Q} :=
      ⟨mem_heightAlgebra_vars_sup P, hP⟩
    rw [fixed_by_based_height_eq_covAlgebraAt] at hmem
    exact covAlgebraAt_le_covAlgebra _ hmem
  · intro hP U hU
    exact gaugePull_eq_self_of_based U hU hP

/-!

## B. The full jet gauge group

-/

/-- **The full-group theorem.**  The elements of the all-orders ordinary gluon jet algebra fixed by
the *whole* `SU(3)` jet gauge group are the constant-`SU(3)`-invariant elements of the covariant
curvature algebra.

Membership in the covariant algebra alone is not enough: an uncontracted covariant curvature
component is only covariant, and a constant colour rotation generally moves it.  The reverse
inclusion works because on the covariant subalgebra an arbitrary gauge jet acts exactly as the
constant jet of its base-point value. -/
lemma fixed_by_jetGroup_eq_invariant_covAlgebra :
    {P : JetAlgebra | ∀ U : specialUnitaryGroup (Fin 3) JetRing, gaugePull U P = P} =
      {P : JetAlgebra | P ∈ covAlgebra ∧
        ∀ g : specialUnitaryGroup (Fin 3) ℂ,
          gaugePull (JetGaugeGroupI.ofConstantSU (Fin 3) g) P = P} := by
  ext P
  simp only [Set.mem_setOf_eq]
  constructor
  · intro hP
    refine ⟨?_, fun g => hP _⟩
    have hbased : P ∈ {Q : JetAlgebra | ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U Q = Q} := fun U _ => hP U
    rw [fixed_by_based_eq_covAlgebra] at hbased
    exact hbased
  · rintro ⟨hadj, hconst⟩ U
    rw [gaugePull_eq_ofConstantSU U hadj]
    exact hconst _

/-!

## C. Extension by an unchanged tensor factor

The based completeness result extends to a tensor product when the gauge pull acts only on the
gluon factor. The generic fixed-submodule result in `Physlib.Mathematics.TensorProduct` reduces
this statement to `fixed_by_based_eq_covAlgebra`, without repeating the coefficient decomposition
or the gluon elimination argument.

-/

/-- The tensor extension of the covariant gluon subalgebra by an arbitrary real module `C`. -/
noncomputable def covTensor (C : Type*) [AddCommGroup C] [Module ℝ C] :
    Submodule ℝ (JetAlgebra ⊗[ℝ] C) :=
  Submodule.map₂ (TensorProduct.mk ℝ JetAlgebra C) covAlgebra.toSubmodule ⊤

/-- After tensoring on the right by a free real module, the elements fixed by every based gauge
pull acting on the gluon factor are exactly the tensor extension of `covAlgebra`. -/
lemma fixed_by_based_tensor_eq_covTensor
    (C : Type*) [AddCommGroup C] [Module ℝ C] [Module.Free ℝ C] :
    {z : JetAlgebra ⊗[ℝ] C | ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 →
          (gaugePull U).toLinearMap.rTensor C z = z} =
      (covTensor C : Set (JetAlgebra ⊗[ℝ] C)) := by
  classical
  let BasedJet := {U : specialUnitaryGroup (Fin 3) JetRing //
    JetGaugeGroupI.evalSU (Fin 3) U = 1}
  let F : BasedJet → Module.End ℝ JetAlgebra := fun U => (gaugePull U.1).toLinearMap
  have hbase : (⨅ U : BasedJet, LinearMap.eqLocus (F U) LinearMap.id) =
      covAlgebra.toSubmodule := by
    ext P
    rw [Submodule.mem_iInf]
    change (∀ U : BasedJet, gaugePull U.1 P = P) ↔ P ∈ covAlgebra
    have hP := Set.ext_iff.mp fixed_by_based_eq_covAlgebra P
    simpa only [Set.mem_setOf_eq, SetLike.mem_coe, Subtype.forall, BasedJet] using hP
  have h := LinearMap.iInf_eqLocus_rTensor (C := C) F
  rw [hbase] at h
  ext z
  have hz := SetLike.ext_iff.mp h z
  simpa only [Submodule.mem_iInf, LinearMap.mem_eqLocus, LinearMap.id_apply,
    Set.mem_setOf_eq, SetLike.mem_coe, Subtype.forall, BasedJet, F, covTensor] using hz

end SU3Jet

end StandardModel
