/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.Gluons.JetCompleteness.GaugeAction
/-!
# Finite-order completeness

## i. Overview

This file proves the two theorems the later modules consume:

```text
A₁ fixed by based gauge jets = the algebra generated by the field strength
A₁ fixed by the full jet gauge group = the constant-SU(3)-invariant part of that.
```

The second does **not** say that every element of the curvature algebra is invariant: a curvature
component is conjugated by a constant colour rotation, and only the globally invariant combinations
survive; an uncontracted curvature component is generally moved by a constant colour rotation.

## ii. The elimination

The elimination is **top-down**, as the proof strategy requires.

1. Order-two based jets (`exists_based_two`) translate a single symmetric derivative coordinate and
   fix everything else. `MvPolynomial.notMem_vars_of_forall_aeval_add_eq` therefore removes every
   symmetric coordinate from an invariant.
2. On what is left — the subalgebra supported on the connection and curvature coordinates —
   order-one based jets (`SU3Jet.exists_based_mcCoeff`, from `ColourBasis`) translate a single
   connection
   coordinate and fix the curvature coordinates. They do *not* fix the symmetric coordinates, which
   is exactly why the elimination must run in this order; the two substitutions agree only on the
   subalgebra reached after step 1, and that is enough.
3. What remains is supported on the curvature coordinates, and `MvPolynomial.supported_eq_adjoin_X`
   turns that into membership in the curvature subalgebra.

The polynomial input is `MvPolynomial.notMem_vars_of_forall_aeval_add_eq` together with
`MvPolynomial.supported_eq_adjoin_X`, needed here. The headline theorem
`mem_adjoin_range_X_sub_X_of_forall_aeval_add_eq` of `MvPolynomialTranslation` is **not** used: its
fiberwise common-shift hypothesis matches the abelian field strength, and the nonabelian one is not
a difference of coordinates.

## iii. Results

* `covAct` — the gauge action read in the covariant coordinates of `CoordinateChange`;
* `covAct_curv_of_based`, `covAct_conn_of_based`, `covAct_sym_of_based_two` — the three generator
  transformation laws the elimination uses;
* `fixed_by_based_eq_adjoin_curv` — the first completeness theorem;
* `fixed_by_jetGroup_eq_invariant_curv` — the full-group theorem.

-/

@[expose] public section

namespace StandardModel

open Matrix Module MvPolynomial

namespace SU3Jet

/-!

## A. The gauge action in covariant coordinates

-/

/-- The local gauge action read through the `CoordinateChange` coordinate change. -/
noncomputable def covAct (U : specialUnitaryGroup (Fin 3) JetRing) : A₁cov →ₐ[ℝ] A₁cov :=
  oldToNew.comp ((gaugeAct U).comp newToOld)

lemma covAct_apply (U : specialUnitaryGroup (Fin 3) JetRing) (Q : A₁cov) :
    covAct U Q = oldToNew (gaugeAct U (newToOld Q)) := rfl

lemma covAct_oldToNew (U : specialUnitaryGroup (Fin 3) JetRing) (P : A₁) :
    covAct U (oldToNew P) = oldToNew (gaugeAct U P) := by
  rw [covAct_apply, newToOld_oldToNew_apply]

/-!

### A.1. The three generator transformation laws

-/

/-- **Curvature is covariant.** In the covariant coordinates the curvature block transforms by the
  matrix of the adjoint action of the base-point value of the jet. -/
lemma covAct_curv (U : specialUnitaryGroup (Fin 3) JetRing) (q : CurvPair) (c : Col) :
    covAct U (X (CovCoord.curv q c)) =
      ∑ c', C (adCoef (JetGaugeGroupI.evalSU (Fin 3) U) c c') * X (CovCoord.curv q c') := by
  rw [covAct_apply, newToOld_curv, gaugeAct_curvPoly, map_sum]
  refine Finset.sum_congr rfl fun c' _ => ?_
  rw [map_mul, algHom_C, ← newToOld_curv q c', oldToNew_newToOld_apply]

/-- **Based jets fix the curvature coordinates.** -/
lemma covAct_curv_of_based {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : JetGaugeGroupI.evalSU (Fin 3) U = 1) (q : CurvPair) (c : Col) :
    covAct U (X (CovCoord.curv q c)) = X (CovCoord.curv q c) := by
  rw [covAct_curv, hU]
  exact adP_one (fun c' => X (CovCoord.curv q c')) c

/-- **Order-one based jets translate the connection coordinates.** -/
lemma covAct_conn_of_based {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : JetGaugeGroupI.evalSU (Fin 3) U = 1) (μ : Lor) (c : Col) :
    covAct U (X (CovCoord.conn μ c)) = X (CovCoord.conn μ c) + C (coordC c (mcC U μ)) := by
  rw [covAct_apply, newToOld_conn, gaugeAct_conn, hU, map_add, algHom_constP]
  congr 1
  rw [adP_one]
  exact oldToNew_conn μ c

/-- On a jet based to order one the second Maurer–Cartan coefficient is symmetric: this is
  `mc2C_sub` with a vanishing first coefficient. -/
lemma mc2C_symm_of_based {U : specialUnitaryGroup (Fin 3) JetRing} (hm : ∀ ρ, mcC U ρ = 0)
    (ν μ : Lor) : mc2C U ν μ = mc2C U μ ν := by
  have h := mc2C_sub U ν μ
  rw [hm ν, map_zero, LinearMap.zero_apply, neg_zero, sub_eq_zero] at h
  exact h

/-- **Order-two based jets translate the ordinary derivative coordinates by a constant.** This is
  the hypothesis of "Why the triangular strategy works": no field-dependent commutator survives. -/
lemma gaugeAct_der_of_based_two {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : JetGaugeGroupI.evalSU (Fin 3) U = 1) (hm : ∀ ρ, mcC U ρ = 0) (ν μ : Lor) (c : Col) :
    gaugeAct U (X (Coord.der ν μ c)) = X (Coord.der ν μ c) + C (coordC c (mc2C U ν μ)) := by
  rw [gaugeAct_der, hU, adP_one, hm ν, constP_zero, brP_zero_left, sub_zero]
  rfl

/-- **Order-two based jets translate the symmetric derivative coordinates by a constant.** -/
lemma covAct_sym_of_based_two {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : JetGaugeGroupI.evalSU (Fin 3) U = 1) (hm : ∀ ρ, mcC U ρ = 0) (ν μ : Lor) (c : Col) :
    covAct U (X (CovCoord.sym s(ν, μ) c)) =
      X (CovCoord.sym s(ν, μ) c) + C (coordC c (mc2C U ν μ)) := by
  have ht : mc2C U μ ν = mc2C U ν μ := (mc2C_symm_of_based hm ν μ).symm
  have key : gaugeAct U (symOld c s(ν, μ)) =
      symOld c s(ν, μ) + C (coordC c (mc2C U ν μ)) := by
    rw [symOld_mk, map_smul, map_add, gaugeAct_der_of_based_two hU hm,
      gaugeAct_der_of_based_two hU hm, ht]
    module
  rw [covAct_apply, newToOld_sym, key, map_add, algHom_C,
    show oldToNew (symOld c s(ν, μ)) = X (CovCoord.sym s(ν, μ) c) from by
      rw [← newToOld_sym s(ν, μ) c, oldToNew_newToOld_apply]]

/-!

## B. Realizing the two translations in coordinates

-/

lemma coordC_smul_basis (r : ℝ) (c₀ c : Col) :
    coordC c (r • colourBasis c₀) = if c = c₀ then r else 0 := by
  rw [map_smul, smul_eq_mul, coordC_apply, Basis.repr_self_apply]
  by_cases h : c = c₀
  · rw [if_pos h, if_pos h.symm, mul_one]
  · rw [if_neg h, if_neg fun hc => h hc.symm, mul_zero]

/-- **Order-one realizability, in colour coordinates.** From `SU3Jet.exists_based_mcCoeff`. -/
lemma exists_based_one (μ₀ : Lor) (c₀ : Col) (r : ℝ) :
    ∃ U : specialUnitaryGroup (Fin 3) JetRing,
      JetGaugeGroupI.evalSU (Fin 3) U = 1 ∧
        ∀ ν, mcC U ν = if ν = μ₀ then r • colourBasis c₀ else 0 := by
  obtain ⟨U, hU, hmc⟩ := SU3Jet.exists_based_mcCoeff μ₀ (r • colourBasis c₀)
  refine ⟨U, hU, fun ν => ?_⟩
  by_cases h : ν = μ₀
  · rw [if_pos h]
    exact Subtype.ext (by rw [show (mcC U ν).1 = Gluon.mcCoeff U ν from rfl, hmc ν, if_pos h])
  · rw [if_neg h]
    exact Subtype.ext (by rw [show (mcC U ν).1 = Gluon.mcCoeff U ν from rfl, hmc ν, if_neg h]; rfl)

/-!

## C. The elimination

-/

private lemma ite_sym (s s' : Sym2 Lor) (c c' : Col) (r : ℝ) :
    (if s = s' then (if c = c' then r else 0) else 0) =
      if (CovCoord.sym s c : CovCoord) = CovCoord.sym s' c' then r else 0 := by
  by_cases h1 : s = s' <;> by_cases h2 : c = c' <;> simp_all

private lemma ite_conn (μ μ' : Lor) (c c' : Col) (r : ℝ) :
    (if μ = μ' then (if c = c' then r else 0) else 0) =
      if (CovCoord.conn μ c : CovCoord) = CovCoord.conn μ' c' then r else 0 := by
  by_cases h1 : μ = μ' <;> by_cases h2 : c = c' <;> simp_all

/-- **The first completeness theorem.** The elements of the first-order gluon jet algebra fixed by
  every *based* gauge jet are exactly the polynomials in the field strength.

  The forward direction is the top-down elimination: order-two based jets remove the symmetric
  derivative coordinates, then order-one based jets remove the connection coordinates. The reverse
  direction is `gaugeAct_curvPoly` at `u = 1`. -/
lemma fixed_by_based_eq_adjoin_curv :
    {P : A₁ | ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugeAct U P = P} =
      (Algebra.adjoin ℝ (Set.range fun q : Lor × Lor × Col => curvPoly q.1 q.2.1 q.2.2) :
        Set A₁) := by
  classical
  ext P
  simp only [Set.mem_setOf_eq, SetLike.mem_coe]
  constructor
  · intro hP
    have hQfix : ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → covAct U (oldToNew P) = oldToNew P := by
      intro U hU
      rw [covAct_oldToNew, hP U hU]
    -- Step 1: no symmetric derivative coordinates.
    have hstep1 : ∀ (s : Sym2 Lor) (c : Col), CovCoord.sym s c ∉ (oldToNew P).vars := by
      intro s c₀
      refine MvPolynomial.notMem_vars_of_forall_aeval_add_eq _ (CovCoord.sym s c₀) fun r => ?_
      obtain ⟨U, hU, hm, hmc2⟩ := exists_based_two s c₀ r
      have hagree : covAct U =
          aeval (fun i => X i + C (if i = CovCoord.sym s c₀ then r else 0)) := by
        refine algHom_ext fun i => ?_
        rw [aeval_X]
        cases i with
        | conn μ c => rw [covAct_conn_of_based hU, hm μ]; simp
        | sym s' c =>
            induction s' using Sym2.ind with
            | _ ν μ =>
              rw [covAct_sym_of_based_two hU hm, hmc2 ν μ]
              by_cases h1 : s(ν, μ) = s
              · rw [if_pos h1, coordC_smul_basis, ← ite_sym, if_pos h1]
              · rw [if_neg h1, map_zero, ← ite_sym, if_neg h1]
        | curv q c => rw [covAct_curv_of_based hU]; simp
      rw [← hagree]
      exact hQfix U hU
    -- Step 2: no connection coordinates.
    have hsupp1 : oldToNew P ∈
        MvPolynomial.supported ℝ {i : CovCoord | ∀ s c, i ≠ CovCoord.sym s c} := by
      rw [mem_supported]
      intro i hi s c
      rintro rfl
      exact hstep1 s c (Finset.mem_coe.mp hi)
    rw [supported_eq_adjoin_X] at hsupp1
    have hstep2 : ∀ (μ : Lor) (c : Col), CovCoord.conn μ c ∉ (oldToNew P).vars := by
      intro μ₀ c₀
      refine MvPolynomial.notMem_vars_of_forall_aeval_add_eq _ (CovCoord.conn μ₀ c₀) fun r => ?_
      obtain ⟨U, hU, hmc⟩ := exists_based_one μ₀ c₀ r
      have hmem : oldToNew P ∈ AlgHom.equalizer (covAct U)
          (aeval (fun i => X i + C (if i = CovCoord.conn μ₀ c₀ then r else 0))) := by
        refine Algebra.adjoin_le ?_ hsupp1
        rintro _ ⟨i, hi, rfl⟩
        show covAct U (X i) = _
        rw [aeval_X]
        cases i with
        | conn μ c =>
            rw [covAct_conn_of_based hU, hmc μ]
            by_cases h1 : μ = μ₀
            · rw [if_pos h1, coordC_smul_basis, ← ite_conn, if_pos h1]
            · rw [if_neg h1, map_zero, ← ite_conn, if_neg h1]
        | sym s c => exact absurd rfl (hi s c)
        | curv q c => rw [covAct_curv_of_based hU]; simp
      have heq : covAct U (oldToNew P) =
          aeval (fun i => X i + C (if i = CovCoord.conn μ₀ c₀ then r else 0)) (oldToNew P) := hmem
      rw [← heq]
      exact hQfix U hU
    -- Step 3: what is left is supported on the curvature coordinates.
    have hsupp2 : oldToNew P ∈
        MvPolynomial.supported ℝ {i : CovCoord | ∃ q c, i = CovCoord.curv q c} := by
      rw [mem_supported]
      intro i hi
      cases i with
      | conn μ c => exact absurd (Finset.mem_coe.mp hi) (hstep2 μ c)
      | sym s c => exact absurd (Finset.mem_coe.mp hi) (hstep1 s c)
      | curv q c => exact ⟨q, c, rfl⟩
    rw [supported_eq_adjoin_X] at hsupp2
    have hmem2 : newToOld (oldToNew P) ∈
        (Algebra.adjoin ℝ (X '' {i : CovCoord | ∃ q c, i = CovCoord.curv q c})).map newToOld :=
      Subalgebra.mem_map.mpr ⟨oldToNew P, hsupp2, rfl⟩
    rw [AlgHom.map_adjoin, newToOld_oldToNew_apply] at hmem2
    refine Algebra.adjoin_mono ?_ hmem2
    rintro _ ⟨_, ⟨i, ⟨q, c, rfl⟩, rfl⟩, rfl⟩
    exact ⟨(q.1.1, q.1.2, c), (newToOld_curv q c).symm⟩
  · intro hP U hU
    have hmem : P ∈ AlgHom.equalizer (gaugeAct U) (AlgHom.id ℝ A₁) := by
      refine Algebra.adjoin_le ?_ hP
      rintro _ ⟨⟨ν, μ, c⟩, rfl⟩
      show gaugeAct U (curvPoly ν μ c) = _
      rw [gaugeAct_curvPoly, hU]
      exact adP_one (curvPoly ν μ) c
    exact hmem

/-- **The full-group theorem.** The elements of the first-order gluon jet algebra fixed by the
  *whole* jet gauge group are the constant-`SU(3)`-invariant elements of the curvature algebra.

  Membership in the curvature algebra alone is not enough: an uncontracted field strength is only
  covariant. The reverse inclusion works because on the curvature subalgebra an arbitrary gauge jet
  acts exactly as the constant jet of its base-point value. -/
lemma fixed_by_jetGroup_eq_invariant_curv :
    {P : A₁ | ∀ U : specialUnitaryGroup (Fin 3) JetRing, gaugeAct U P = P} =
      {P : A₁ |
        P ∈ Algebra.adjoin ℝ (Set.range fun q : Lor × Lor × Col => curvPoly q.1 q.2.1 q.2.2) ∧
        ∀ g : specialUnitaryGroup (Fin 3) ℂ,
          gaugeAct (JetGaugeGroupI.ofConstantSU (Fin 3) g) P = P} := by
  ext P
  simp only [Set.mem_setOf_eq]
  constructor
  · intro hP
    refine ⟨?_, fun g => hP _⟩
    have hbased : P ∈ {P : A₁ | ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugeAct U P = P} := fun U _ => hP U
    rw [fixed_by_based_eq_adjoin_curv] at hbased
    exact hbased
  · rintro ⟨hadj, hconst⟩ U
    have hmem : P ∈ AlgHom.equalizer (gaugeAct U)
        (gaugeAct (JetGaugeGroupI.ofConstantSU (Fin 3) (JetGaugeGroupI.evalSU (Fin 3) U))) := by
      refine Algebra.adjoin_le ?_ hadj
      rintro _ ⟨⟨ν, μ, c⟩, rfl⟩
      show gaugeAct U (curvPoly ν μ c) = _
      rw [gaugeAct_curvPoly, gaugeAct_curvPoly, SU3Jet.evalSU_ofConstantSU]
    have heq : gaugeAct U P =
        gaugeAct (JetGaugeGroupI.ofConstantSU (Fin 3) (JetGaugeGroupI.evalSU (Fin 3) U)) P := hmem
    rw [heq, hconst]

end SU3Jet

end StandardModel
