/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.Gluons.JetCompleteness.Triangular
/-!
# Finite-height completeness

## i. Overview

This file proves the uniform finite-height completeness theorem: for every derivative height `N`, an
ordinary jet polynomial of height at most `N` that is fixed by every *based* `SU(3)` gauge jet lies
in the truncated algebra generated by those symmetrized covariant curvature derivatives whose
leading connection derivative fits inside that height, and conversely.

## ii. Why the elimination needs a coordinate change

A based jet translates *every* ordinary generator of one fibre `(s + ∂_μ, c)` by the *same*
constant (`HighestLayer` `gaugeSubstGen_eq_add_layerShift`), so no single ordinary variable can be
removed.
The fibrewise translation theorem `MvPolynomial.mem_adjoin_range_X_sub_X_of_forall_aeval_add_eq`
is *not* usable here: its hypothesis quantifies over every fibre of the representative map,
including the singleton fibres of the strictly lower generators, and those are provably *fixed*,
not translated.  Moving the lower generators into the coefficient ring does not help either, since
the theorem then asks for translations by arbitrary coefficient polynomials whereas a gauge jet
translates by a constant.  `FiniteHeight` therefore uses `FiniteCompleteness`'s route —
`notMem_vars_of_forall_aeval_add_eq`
together with `supported_eq_adjoin_X` — one representative variable at a time, inside the
covariant coordinate system built below.

## iii. The covariant coordinate system

`linSubst` is the fibrewise **linear** change of variables that puts the weighted symmetric
average `symConn w c` in the distinguished slot of each fibre and the hook difference in every
other supported slot.  It is invertible, with the explicit inverse `invLinSubst` read off
`Triangular`'s
weighted-average identity, so the resulting family is genuinely algebraically independent: no
independence hypothesis is assumed anywhere.  Composing with `Triangular`'s nonlinear
`triangularSubst`
gives `covSubst`, whose generator images are exactly

```text
covSubst (∂_s A_μ)  =  symConn (s + ∂_μ) c      if μ is the distinguished direction
                    =  covHook (s + ∂_μ, μ) c   otherwise.
```

In these coordinates a jet based through order `r`

* fixes every hook coordinate, at *every* derivative degree (`CovariantTower`, since `covHook ∈
  covAlgebra`);
* fixes `symConn w c` for `lorDeg w ≤ r`;
* translates `symConn w c` for `lorDeg w = r + 1` by an arbitrary independently realizable
  constant (`HighestLayer`).

The elimination is then one descending sweep removing the symmetric coordinates layer by layer.
No coefficient is ever extracted, and no global commutation law between `triangularSubst` and
`gaugePull` is asserted.

## iv. Results

* `heightAlgebra`, `covAlgebraAt` — the finite-height carrier and the truncated covariant algebra;
* `linSubst`, `invLinSubst`, `linSubst_injective` — the invertible fibrewise linear change;
* `covSubst`, `covCoordGen`, `covCoordHom_injective` — the covariant coordinate system;
* `heightAlgebra_le_covCoordAlgebra` — every ordinary generator is a polynomial in the covariant
  coordinates of its own derivative degree;
* `gaugePull_covCoordGen_of_isSymSlot`, `gaugePull_covCoordGen_of_not_isSymSlot` — the based
  action in covariant coordinates;
* `fixed_by_based_height_eq_covAlgebraAt` — the headline finite-height completeness theorem.

-/

@[expose] public section

namespace StandardModel

open Matrix Module MvPolynomial

namespace SU3Jet

/-!

## A. The finite derivative height carrier

-/

/-- The ordinary generators whose derivative degree is at most `N`. -/
def heightGen (N : ℕ) : Set JetAlgebra :=
  {P | ∃ g : JetGenerators, genDeg g ≤ N ∧ P = ofGen g}

/-- **The finite-height ordinary jet algebra**: the subalgebra generated by the connection and its
ordinary derivatives up to derivative degree `N`. -/
noncomputable def heightAlgebra (N : ℕ) : Subalgebra ℝ JetAlgebra :=
  Algebra.adjoin ℝ (heightGen N)

lemma ofGen_mem_heightAlgebra {N : ℕ} {g : JetGenerators} (hg : genDeg g ≤ N) :
    ofGen g ∈ heightAlgebra N := Algebra.subset_adjoin ⟨g, hg, rfl⟩

lemma heightAlgebra_mono {M N : ℕ} (h : M ≤ N) : heightAlgebra M ≤ heightAlgebra N :=
  Algebra.adjoin_mono fun _ hP => by
    obtain ⟨g, hg, hPg⟩ := hP
    exact ⟨g, hg.trans h, hPg⟩

private lemma jetDeriv_mem_heightAlgebra_aux (nu : Lor) {N : ℕ} {P : JetAlgebra}
    (hP : P ∈ Algebra.adjoin ℝ (heightGen N)) : jetDeriv nu P ∈ heightAlgebra (N + 1) := by
  induction hP using Algebra.adjoin_induction with
  | mem P hP =>
      obtain ⟨g, hg, rfl⟩ := hP
      rw [jetDeriv_ofGen]
      exact ofGen_mem_heightAlgebra (by rw [genDeg_shift]; omega)
  | algebraMap r =>
      rw [Algebra.algebraMap_eq_smul_one, map_smul, jetDeriv_one, smul_zero]
      exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | mul x y hxm hym hx hy =>
      rw [jetDeriv_mul]
      exact add_mem (mul_mem hx (heightAlgebra_mono (Nat.le_succ N) hym))
        (mul_mem (heightAlgebra_mono (Nat.le_succ N) hxm) hy)

/-- The total derivative raises the derivative height by exactly one. -/
lemma jetDeriv_mem_heightAlgebra (nu : Lor) {N : ℕ} {P : JetAlgebra}
    (hP : P ∈ heightAlgebra N) : jetDeriv nu P ∈ heightAlgebra (N + 1) :=
  jetDeriv_mem_heightAlgebra_aux nu hP

lemma brR_mem_heightAlgebra {N : ℕ} {p q : Col → JetAlgebra}
    (hp : ∀ c, p c ∈ heightAlgebra N) (hq : ∀ c, q c ∈ heightAlgebra N) (c : Col) :
    brR p q c ∈ heightAlgebra N := by
  rw [brR]
  exact sum_mem fun a _ => sum_mem fun b _ =>
    mul_mem (Subalgebra.algebraMap_mem _ _) (mul_mem (hp a) (hq b))

lemma connVec_mem_heightAlgebra (N : ℕ) (mu : Lor) (c : Col) :
    connVec mu c ∈ heightAlgebra N :=
  ofGen_mem_heightAlgebra (by
    show lorDeg (0 : DIdx) ≤ N
    rw [(lorDeg_eq_zero_iff 0).2 rfl]
    omega)

lemma curvVec_mem_heightAlgebra (nu mu : Lor) (c : Col) :
    curvVec nu mu c ∈ heightAlgebra 1 := by
  rw [curvVec]
  refine add_mem (sub_mem (jetDeriv_mem_heightAlgebra nu (connVec_mem_heightAlgebra 0 mu c))
    (jetDeriv_mem_heightAlgebra mu (connVec_mem_heightAlgebra 0 nu c))) ?_
  exact brR_mem_heightAlgebra (connVec_mem_heightAlgebra 1 nu) (connVec_mem_heightAlgebra 1 mu) c

lemma covD_mem_heightAlgebra (rho : Lor) {N : ℕ} {X : Col → JetAlgebra}
    (hX : ∀ c, X c ∈ heightAlgebra N) (c : Col) : covD rho X c ∈ heightAlgebra (N + 1) := by
  rw [covD]
  exact add_mem (jetDeriv_mem_heightAlgebra rho (hX c))
    (brR_mem_heightAlgebra (connVec_mem_heightAlgebra (N + 1) rho)
      (fun c' => heightAlgebra_mono (Nat.le_succ N) (hX c')) c)

lemma covIter_mem_heightAlgebra (r : ℕ) (t : Fin r → Lor) (nu mu : Lor) (c : Col) :
    covIter r t (curvVec nu mu) c ∈ heightAlgebra (r + 1) := by
  induction r generalizing c with
  | zero => exact curvVec_mem_heightAlgebra nu mu c
  | succ n ih =>
      rw [covIter_succ]
      exact covD_mem_heightAlgebra (t 0) (fun c' => ih (fun i => t i.succ) c') c

/-- The symmetrized covariant curvature derivative `D^r F` has derivative height `r + 1`. -/
lemma covCurv_mem_heightAlgebra {r : ℕ} (t : Fin r → Lor) (nu mu : Lor) (c : Col) :
    covCurv t nu mu c ∈ heightAlgebra (r + 1) := by
  rw [covCurv]
  refine Subalgebra.smul_mem _ ?_ _
  exact sum_mem fun sigma _ => covIter_mem_heightAlgebra r (t ∘ sigma) nu mu c

/-- **Every ordinary jet polynomial has a finite derivative height.**  The bound is the largest
derivative degree occurring among its polynomial variables. -/
lemma mem_heightAlgebra_vars_sup (P : JetAlgebra) :
    P ∈ heightAlgebra ((toPoly P).vars.sup genDeg) := by
  classical
  have hsupp : toPoly P ∈
      MvPolynomial.supported ℝ {g : JetGenerators | genDeg g ≤ (toPoly P).vars.sup genDeg} := by
    rw [mem_supported]
    intro g hg
    show genDeg g ≤ (toPoly P).vars.sup genDeg
    exact Finset.le_sup (Finset.mem_coe.mp hg)
  rw [supported_eq_adjoin_X] at hsupp
  have hmem : toPoly.symm (toPoly P) ∈
      (Algebra.adjoin ℝ
        (X '' {g : JetGenerators | genDeg g ≤ (toPoly P).vars.sup genDeg})).map
          toPoly.symm.toAlgHom := Subalgebra.mem_map.mpr ⟨_, hsupp, rfl⟩
  rw [AlgHom.map_adjoin, AlgEquiv.symm_apply_apply] at hmem
  refine Algebra.adjoin_mono ?_ hmem
  rintro _ ⟨_, ⟨g, hg, rfl⟩, rfl⟩
  exact ⟨g, hg, toPoly_symm_X g⟩

lemma exists_mem_heightAlgebra (P : JetAlgebra) : ∃ N, P ∈ heightAlgebra N :=
  ⟨_, mem_heightAlgebra_vars_sup P⟩

/-!

## B. The truncated covariant curvature algebra

-/

/-- The components of the covariant curvature tower whose leading ordinary connection derivative
has derivative degree at most `N`. -/
def covTowerAt (N : ℕ) : Set JetAlgebra :=
  {P | ∃ (r : ℕ) (t : Fin r → Lor) (nu mu : Lor) (c : Col), r + 1 ≤ N ∧ P = covCurv t nu mu c}

/-- **The truncated covariant curvature algebra** available inside derivative height `N`. -/
noncomputable def covAlgebraAt (N : ℕ) : Subalgebra ℝ JetAlgebra := Algebra.adjoin ℝ (covTowerAt N)

lemma covCurv_mem_covAlgebraAt {N r : ℕ} (hr : r + 1 ≤ N) (t : Fin r → Lor) (nu mu : Lor)
    (c : Col) : covCurv t nu mu c ∈ covAlgebraAt N :=
  Algebra.subset_adjoin ⟨r, t, nu, mu, c, hr, rfl⟩

lemma covAlgebraAt_mono {M N : ℕ} (h : M ≤ N) : covAlgebraAt M ≤ covAlgebraAt N :=
  Algebra.adjoin_mono fun _ hP => by
    obtain ⟨r, t, nu, mu, c, hr, hPc⟩ := hP
    exact ⟨r, t, nu, mu, c, hr.trans h, hPc⟩

lemma covAlgebraAt_le_covAlgebra (N : ℕ) : covAlgebraAt N ≤ covAlgebra := by
  refine Algebra.adjoin_le ?_
  rintro P ⟨r, t, nu, mu, c, _, rfl⟩
  exact covCurv_mem_covAlgebra t nu mu c

lemma covAlgebraAt_le_heightAlgebra (N : ℕ) : covAlgebraAt N ≤ heightAlgebra N := by
  refine Algebra.adjoin_le ?_
  rintro P ⟨r, t, nu, mu, c, hr, rfl⟩
  exact heightAlgebra_mono hr (covCurv_mem_heightAlgebra t nu mu c)

lemma covHook_mem_covAlgebra (i : AllHookIdx) (c : Col) : covHook i c ∈ covAlgebra :=
  covCurv_mem_covAlgebra _ _ _ _

lemma covHook_mem_covAlgebraAt {N : ℕ} (i : AllHookIdx) (hi : lorDeg i.w ≤ N + 1) (c : Col) :
    covHook i c ∈ covAlgebraAt N := by
  refine covCurv_mem_covAlgebraAt ?_ (didxTuple (hookRest i)) (layerDir i.w) i.mu c
  have h1 := didxList_length (hookRest i)
  have h2 := lorDeg_hookRest i
  omega

/-!

## C. Symmetric and hook slots

Each nonzero total multi-index `w` labels one fibre of ordinary generators, namely the supported
components `∂_(w - ∂_ν) A_ν`.  The slot of the distinguished direction `layerDir w` is where the
fully symmetric coordinate will live; every other supported slot carries a hook coordinate.

-/

/-- The generator slot carrying the fully symmetric coordinate of the fibre `w`. -/
noncomputable def symGen (w : DIdx) (c : Col) : JetGenerators :=
  .dA (layerPred w) (layerDir w) c

lemma layerPred_eq_predAt (w : DIdx) : layerPred w = predAt w (layerDir w) := rfl

lemma genDeg_symGen (w : DIdx) (c : Col) : genDeg (symGen w c) = lorDeg (layerPred w) := rfl

/-- The fibre of a generator: the total multi-index obtained by adjoining its connection
direction. -/
noncomputable def genFibre : JetGenerators → DIdx
  | .dA s mu _ => s + Finsupp.single mu 1

/-- The colour index of a generator. -/
def genCol : JetGenerators → Col
  | .dA _ _ c => c

@[simp]
lemma genFibre_dA (s : DIdx) (mu : Lor) (c : Col) :
    genFibre (.dA s mu c) = s + Finsupp.single mu 1 := rfl

@[simp]
lemma genCol_dA (s : DIdx) (mu : Lor) (c : Col) : genCol (.dA s mu c) = c := rfl

lemma genFibre_ne_zero (g : JetGenerators) : genFibre g ≠ 0 := by
  obtain ⟨s, mu, c⟩ := g
  exact total_add_single_ne_zero s mu

lemma lorDeg_genFibre (g : JetGenerators) : lorDeg (genFibre g) = genDeg g + 1 := by
  obtain ⟨s, mu, c⟩ := g
  rw [genFibre_dA, lorDeg_add, lorDeg_single, genDeg_dA]

lemma genFibre_symGen {w : DIdx} (hw : w ≠ 0) (c : Col) : genFibre (symGen w c) = w :=
  layerPred_add_single hw

lemma genCol_symGen (w : DIdx) (c : Col) : genCol (symGen w c) = c := rfl

/-- A generator is a **symmetric slot** when its connection direction is the distinguished
direction of its fibre. -/
noncomputable def IsSymSlot : JetGenerators → Prop
  | .dA s mu _ => mu = layerDir (s + Finsupp.single mu 1)

@[simp]
lemma isSymSlot_dA (s : DIdx) (mu : Lor) (c : Col) :
    IsSymSlot (.dA s mu c) ↔ mu = layerDir (s + Finsupp.single mu 1) := Iff.rfl

lemma isSymSlot_symGen {w : DIdx} (hw : w ≠ 0) (c : Col) : IsSymSlot (symGen w c) := by
  show layerDir w = layerDir (layerPred w + Finsupp.single (layerDir w) 1)
  rw [layerPred_add_single hw]

lemma eq_symGen_of_isSymSlot {g : JetGenerators} (hg : IsSymSlot g) :
    g = symGen (genFibre g) (genCol g) := by
  obtain ⟨s, mu, c⟩ := g
  have h : mu = layerDir (s + Finsupp.single mu 1) := hg
  show JetGenerators.dA s mu c =
    JetGenerators.dA (layerPred (s + Finsupp.single mu 1))
      (layerDir (s + Finsupp.single mu 1)) c
  rw [← h, layerPred_eq_predAt, ← h, predAt_add_single_eq]

lemma symGen_inj {w w' : DIdx} (hw : w ≠ 0) (hw' : w' ≠ 0) {c c' : Col}
    (h : symGen w c = symGen w' c') : w = w' ∧ c = c' := by
  have hf : genFibre (symGen w c) = genFibre (symGen w' c') := by rw [h]
  rw [genFibre_symGen hw, genFibre_symGen hw'] at hf
  refine ⟨hf, ?_⟩
  have := congrArg genCol h
  rwa [genCol_symGen, genCol_symGen] at this

/-- The symmetric slot value of the fibre `w`. -/
noncomputable def symSlot (w : DIdx) (c : Col) : JetAlgebra := totalComponent w (layerDir w) c

/-- The hook slot value of the fibre `w` in the direction `nu`; it is zero in the distinguished
direction. -/
noncomputable def hookSlot (w : DIdx) (nu : Lor) (c : Col) : JetAlgebra :=
  if nu = layerDir w then 0 else totalComponent w nu c

/-- The weighted average of the hook slots of a fibre; this is the correction appearing in
  `Triangular`'s
explicit inverse coordinate formula. -/
noncomputable def slotAverage (w : DIdx) (c : Col) : JetAlgebra :=
  (lorDeg w : ℝ)⁻¹ • ∑ nu : Lor, (w nu : ℝ) • hookSlot w nu c

lemma symSlot_eq_ofGen (w : DIdx) (c : Col) : symSlot w c = ofGen (symGen w c) := rfl

lemma lorDeg_cast_ne_zero {w : DIdx} (hw : w ≠ 0) : (lorDeg w : ℝ) ≠ 0 := by
  exact_mod_cast Nat.ne_of_gt ((lorDeg_pos_iff w).2 hw)

lemma sum_coeff_eq_lorDeg (w : DIdx) : ∑ nu : Lor, (w nu : ℝ) = (lorDeg w : ℝ) := by
  rw [lorDeg]
  norm_cast

lemma sum_weighted_hookSlot {w : DIdx} (hw : w ≠ 0) (c : Col) :
    ∑ nu : Lor, (w nu : ℝ) • hookSlot w nu c = (lorDeg w : ℝ) • slotAverage w c := by
  rw [slotAverage, smul_smul, mul_inv_cancel₀ (lorDeg_cast_ne_zero hw), one_smul]

/-!

## D. The invertible fibrewise linear coordinate change

-/

/-- Generator form of the fibrewise linear change of variables: the distinguished slot of a fibre
receives the weighted symmetric average, every other slot its hook difference. -/
noncomputable def linCoordGen : JetGenerators → JetAlgebra
  | .dA s mu c =>
      if mu = layerDir (s + Finsupp.single mu 1) then symConn (s + Finsupp.single mu 1) c
      else
        totalComponent (s + Finsupp.single mu 1) mu c -
          totalComponent (s + Finsupp.single mu 1) (layerDir (s + Finsupp.single mu 1)) c

/-- Generator form of the inverse fibrewise linear change of variables, read off
  `Triangular`'s explicit
weighted-average inverse. -/
noncomputable def invLinCoordGen : JetGenerators → JetAlgebra
  | .dA s mu c =>
      symSlot (s + Finsupp.single mu 1) c + hookSlot (s + Finsupp.single mu 1) mu c -
        slotAverage (s + Finsupp.single mu 1) c

/-- The fibrewise linear coordinate change on the ordinary jet algebra. -/
noncomputable def linSubst : JetAlgebra →ₐ[ℝ] JetAlgebra :=
  (MvPolynomial.aeval linCoordGen).comp toPoly.toAlgHom

/-- The inverse fibrewise linear coordinate change. -/
noncomputable def invLinSubst : JetAlgebra →ₐ[ℝ] JetAlgebra :=
  (MvPolynomial.aeval invLinCoordGen).comp toPoly.toAlgHom

@[simp]
lemma linSubst_ofGen (g : JetGenerators) : linSubst (ofGen g) = linCoordGen g := by
  show MvPolynomial.aeval linCoordGen (toPoly (ofGen g)) = _
  rw [toPoly_ofGen, aeval_X]

@[simp]
lemma invLinSubst_ofGen (g : JetGenerators) : invLinSubst (ofGen g) = invLinCoordGen g := by
  show MvPolynomial.aeval invLinCoordGen (toPoly (ofGen g)) = _
  rw [toPoly_ofGen, aeval_X]

lemma invLinSubst_totalComponent {w : DIdx} {nu : Lor} (hnu : w nu ≠ 0) (c : Col) :
    invLinSubst (totalComponent w nu c) =
      symSlot w c + hookSlot w nu c - slotAverage w c := by
  rw [totalComponent, invLinSubst_ofGen]
  show symSlot (predAt w nu + Finsupp.single nu 1) c +
      hookSlot (predAt w nu + Finsupp.single nu 1) nu c -
      slotAverage (predAt w nu + Finsupp.single nu 1) c = _
  rw [predAt_add_single hnu]

lemma invLinSubst_symConn {w : DIdx} (hw : w ≠ 0) (c : Col) :
    invLinSubst (symConn w c) = symSlot w c := by
  have hdeg : (lorDeg w : ℝ) ≠ 0 := lorDeg_cast_ne_zero hw
  have hterm : ∀ nu : Lor, invLinSubst ((w nu : ℝ) • totalComponent w nu c) =
      (w nu : ℝ) • (symSlot w c + hookSlot w nu c - slotAverage w c) := by
    intro nu
    by_cases hnu : w nu = 0
    · rw [hnu, Nat.cast_zero, zero_smul, zero_smul, map_zero]
    · rw [map_smul, invLinSubst_totalComponent hnu]
  have hkey : ∑ nu : Lor, (w nu : ℝ) • (symSlot w c + hookSlot w nu c - slotAverage w c) =
      (lorDeg w : ℝ) • symSlot w c := by
    simp_rw [smul_sub, smul_add]
    rw [Finset.sum_sub_distrib, Finset.sum_add_distrib, ← Finset.sum_smul, ← Finset.sum_smul,
      sum_coeff_eq_lorDeg, sum_weighted_hookSlot hw]
    abel
  rw [symConn, map_smul, map_sum, Finset.sum_congr rfl fun nu _ => hterm nu, hkey, smul_smul,
    inv_mul_cancel₀ hdeg, one_smul]

/-- **The linear coordinate change is invertible.**  This is where `Triangular`'s
  explicit weighted-average
inverse is consumed; no algebraic independence is assumed. -/
lemma invLinSubst_linCoordGen (g : JetGenerators) : invLinSubst (linCoordGen g) = ofGen g := by
  obtain ⟨s, mu, c⟩ := g
  have hw : s + Finsupp.single mu 1 ≠ 0 := total_add_single_ne_zero s mu
  have hmu := total_add_single_apply_ne_zero s mu
  have hdir := layerDir_coeff_ne_zero hw
  by_cases h : mu = layerDir (s + Finsupp.single mu 1)
  · rw [linCoordGen, if_pos h, invLinSubst_symConn hw, symSlot, ← h, totalComponent_add_single]
  · rw [linCoordGen, if_neg h, map_sub, invLinSubst_totalComponent hmu,
      invLinSubst_totalComponent hdir, hookSlot, if_neg h, hookSlot, if_pos rfl,
      ← totalComponent_add_single s mu c]
    abel

lemma invLinSubst_linSubst (P : JetAlgebra) : invLinSubst (linSubst P) = P := by
  have h : invLinSubst.comp linSubst = AlgHom.id ℝ JetAlgebra :=
    jetAlgHom_ext fun g => by
      rw [AlgHom.comp_apply, linSubst_ofGen, invLinSubst_linCoordGen, AlgHom.id_apply]
  have h2 := DFunLike.congr_fun h P
  simpa using h2

lemma linSubst_injective : Function.Injective linSubst :=
  Function.LeftInverse.injective invLinSubst_linSubst

/-!

## E. The covariant coordinate system

Composing the fibrewise linear change with `Triangular`'s triangular substitution
replaces every hook
difference by the matching symmetrized covariant curvature derivative while keeping the fully
symmetric connection coordinate.  Injectivity is inherited from both factors, so the resulting
family of coordinates is genuinely algebraically independent.

-/

lemma AllHookIdx.ext' {i j : AllHookIdx} (hw : i.w = j.w) (hmu : i.mu = j.mu) : i = j := by
  obtain ⟨w, mu, h1, h2, h3⟩ := i
  obtain ⟨w', mu', h1', h2', h3'⟩ := j
  simp only at hw hmu
  subst hw
  subst hmu
  rfl

/-- Generator form of the covariant coordinate system: the distinguished slot of each fibre
carries the fully symmetric connection coordinate, every other supported slot carries the matching
symmetrized covariant curvature derivative. -/
noncomputable def covCoordGen : JetGenerators → JetAlgebra
  | .dA s mu c =>
      if h : mu = layerDir (s + Finsupp.single mu 1) then symConn (s + Finsupp.single mu 1) c
      else
        covHook ⟨s + Finsupp.single mu 1, mu, total_add_single_ne_zero s mu,
          total_add_single_apply_ne_zero s mu, h⟩ c

lemma covCoordGen_dA (s : DIdx) (mu : Lor) (c : Col) :
    covCoordGen (.dA s mu c) =
      if h : mu = layerDir (s + Finsupp.single mu 1) then symConn (s + Finsupp.single mu 1) c
      else
        covHook ⟨s + Finsupp.single mu 1, mu, total_add_single_ne_zero s mu,
          total_add_single_apply_ne_zero s mu, h⟩ c := rfl

/-- **The covariant coordinate substitution**: `Triangular`'s triangular map after the
  fibrewise linear
change of variables. -/
noncomputable def covSubst : JetAlgebra →ₐ[ℝ] JetAlgebra := triangularSubst.comp linSubst

@[simp]
lemma covSubst_ofGen (g : JetGenerators) : covSubst (ofGen g) = covCoordGen g := by
  obtain ⟨s, mu, c⟩ := g
  rw [covSubst, AlgHom.comp_apply, linSubst_ofGen, linCoordGen, covCoordGen_dA]
  by_cases h : mu = layerDir (s + Finsupp.single mu 1)
  · rw [if_pos h, dif_pos h, triangularSubst_symConn (total_add_single_ne_zero s mu)]
  · rw [if_neg h, dif_neg h]
    exact triangularSubst_hookDiff ⟨_, _, _, _, h⟩ c

lemma covSubst_injective : Function.Injective covSubst := by
  intro P Q h
  have h' : triangularSubst (linSubst P) = triangularSubst (linSubst Q) := h
  exact linSubst_injective (triangularSubst_injective h')

/-- The covariant coordinates read as a polynomial substitution. -/
noncomputable def covCoordHom : MvPolynomial JetGenerators ℝ →ₐ[ℝ] JetAlgebra :=
  MvPolynomial.aeval covCoordGen

@[simp]
lemma covCoordHom_X (g : JetGenerators) : covCoordHom (X g) = covCoordGen g := aeval_X _ _

@[simp]
lemma covCoordHom_C (v : ℝ) : covCoordHom (C v) = algebraMap ℝ JetAlgebra v := aeval_C _ _

lemma covCoordHom_comp_X :
    (⇑covCoordHom ∘ (X : JetGenerators → MvPolynomial JetGenerators ℝ)) = covCoordGen :=
  funext fun g => covCoordHom_X g

lemma covCoordHom_eq_comp : covCoordHom = covSubst.comp toPoly.symm.toAlgHom :=
  MvPolynomial.algHom_ext fun g => by
    rw [covCoordHom_X, AlgHom.comp_apply]
    show covCoordGen g = covSubst (toPoly.symm (X g))
    rw [toPoly_symm_X, covSubst_ofGen]

/-- **The covariant coordinates are algebraically independent.**  Nothing is assumed here: the
injectivity comes from `Triangular`'s triangular inverse together with the explicit
inverse of the
fibrewise linear change. -/
lemma covCoordHom_injective : Function.Injective covCoordHom := by
  intro p q h
  rw [covCoordHom_eq_comp] at h
  have h' : covSubst (toPoly.symm p) = covSubst (toPoly.symm q) := h
  exact toPoly.symm.injective (covSubst_injective h')

lemma covCoordGen_symGen {w : DIdx} (hw : w ≠ 0) (c : Col) :
    covCoordGen (symGen w c) = symConn w c := by
  have hfib : layerPred w + Finsupp.single (layerDir w) 1 = w := layerPred_add_single hw
  rw [symGen, covCoordGen_dA,
    dif_pos (show layerDir w = layerDir (layerPred w + Finsupp.single (layerDir w) 1) by
      rw [hfib]), hfib]

lemma covCoordGen_predAt (i : AllHookIdx) (c : Col) :
    covCoordGen (.dA (predAt i.w i.mu) i.mu c) = covHook i c := by
  have hfib : predAt i.w i.mu + Finsupp.single i.mu 1 = i.w := predAt_add_single i.mu_supported
  have hne : ¬ (i.mu = layerDir (predAt i.w i.mu + Finsupp.single i.mu 1)) := by
    rw [hfib]
    exact i.mu_ne_dir
  rw [covCoordGen_dA, dif_neg hne]
  exact congrArg (fun j => covHook j c) (AllHookIdx.ext' hfib rfl)

lemma covCoordGen_mem_covAlgebra_of_not_isSymSlot {g : JetGenerators} (hg : ¬ IsSymSlot g) :
    covCoordGen g ∈ covAlgebra := by
  obtain ⟨s, mu, c⟩ := g
  have hg' : ¬ (mu = layerDir (s + Finsupp.single mu 1)) := hg
  rw [covCoordGen_dA, dif_neg hg']
  exact covHook_mem_covAlgebra _ c

lemma covCoordGen_mem_covAlgebraAt_of_not_isSymSlot {N : ℕ} {g : JetGenerators}
    (hg : ¬ IsSymSlot g) (hd : genDeg g ≤ N) : covCoordGen g ∈ covAlgebraAt N := by
  obtain ⟨s, mu, c⟩ := g
  have hg' : ¬ (mu = layerDir (s + Finsupp.single mu 1)) := hg
  rw [covCoordGen_dA, dif_neg hg']
  refine covHook_mem_covAlgebraAt _ ?_ c
  show lorDeg (s + Finsupp.single mu 1) ≤ N + 1
  have hs : lorDeg s ≤ N := hd
  rw [lorDeg_add, lorDeg_single]
  omega

/-- The subalgebra generated by the covariant coordinates of derivative degree at most `N`. -/
noncomputable def covCoordAlgebra (N : ℕ) : Subalgebra ℝ JetAlgebra :=
  Algebra.adjoin ℝ (covCoordGen '' {g : JetGenerators | genDeg g ≤ N})

lemma covCoordGen_mem_covCoordAlgebra {N : ℕ} {g : JetGenerators} (hg : genDeg g ≤ N) :
    covCoordGen g ∈ covCoordAlgebra N := Algebra.subset_adjoin ⟨g, hg, rfl⟩

lemma covCoordAlgebra_mono {M N : ℕ} (h : M ≤ N) : covCoordAlgebra M ≤ covCoordAlgebra N :=
  Algebra.adjoin_mono (Set.image_mono fun _ hg => le_trans hg h)

/-- **A hook difference is a covariant coordinate up to strictly lower terms.**  The correction
`covHook - hookDiff` lies in the strict filtration by `Triangular`, so it is covered by
the inductive
hypothesis packaged as `hsfilt`. -/
private lemma hookDiff_mem_covCoordAlgebra {m : ℕ}
    (hsfilt : ∀ P ∈ sfilt m, P ∈ covCoordAlgebra m) (i : AllHookIdx)
    (hi : lorDeg (predAt i.w i.mu) = m) (c : Col) : hookDiff i c ∈ covCoordAlgebra m := by
  have h1 : covHook i c ∈ covCoordAlgebra m := by
    rw [← covCoordGen_predAt i c]
    exact covCoordGen_mem_covCoordAlgebra (le_of_eq hi)
  have h2 : covHook i c - hookDiff i c ∈ covCoordAlgebra m := by
    refine hsfilt _ ?_
    rw [← hi]
    exact covHook_sub_hookDiff_mem_sfilt i c
  have h3 := sub_mem h1 h2
  rwa [sub_sub_cancel] at h3

/-- The inductive step: once every strictly lower monomial is a polynomial in the covariant
coordinates, so is every ordinary generator of derivative degree `m`. -/
private lemma ofGen_mem_covCoordAlgebra_step {m : ℕ}
    (hsfilt : ∀ P ∈ sfilt m, P ∈ covCoordAlgebra m) :
    ∀ g : JetGenerators, genDeg g = m → ofGen g ∈ covCoordAlgebra m := by
  rintro ⟨s, mu, c⟩ hgm
  have hgm' : lorDeg s = m := hgm
  have hw : s + Finsupp.single mu 1 ≠ 0 := total_add_single_ne_zero s mu
  have hmu := total_add_single_apply_ne_zero s mu
  have hwdeg : lorDeg (s + Finsupp.single mu 1) = m + 1 := by
    rw [lorDeg_add, lorDeg_single, hgm']
  have hsym : symConn (s + Finsupp.single mu 1) c ∈ covCoordAlgebra m := by
    rw [← covCoordGen_symGen hw c]
    refine covCoordGen_mem_covCoordAlgebra ?_
    show lorDeg (layerPred (s + Finsupp.single mu 1)) ≤ m
    have h1 := lorDeg_layerPred hw
    omega
  have hhook : ∀ nu : Lor, ((s + Finsupp.single mu 1 : DIdx)) nu ≠ 0 →
      nu ≠ layerDir (s + Finsupp.single mu 1) →
      totalComponent (s + Finsupp.single mu 1) nu c -
          totalComponent (s + Finsupp.single mu 1) (layerDir (s + Finsupp.single mu 1)) c ∈
        covCoordAlgebra m := by
    intro nu hnu hne
    obtain ⟨i, hiw, himu⟩ : ∃ i : AllHookIdx, i.w = s + Finsupp.single mu 1 ∧ i.mu = nu :=
      ⟨⟨s + Finsupp.single mu 1, nu, hw, hnu, hne⟩, rfl, rfl⟩
    have hgoal : hookDiff i c =
        totalComponent (s + Finsupp.single mu 1) nu c -
          totalComponent (s + Finsupp.single mu 1) (layerDir (s + Finsupp.single mu 1)) c := by
      rw [hookDiff, hiw, himu]
    rw [← hgoal]
    refine hookDiff_mem_covCoordAlgebra hsfilt i ?_ c
    rw [hiw, himu]
    have h1 := lorDeg_predAt hnu
    omega
  have havg : hookAverage (s + Finsupp.single mu 1) c ∈ covCoordAlgebra m := by
    rw [hookAverage]
    refine Subalgebra.smul_mem _ ?_ _
    refine sum_mem fun nu _ => ?_
    by_cases hnu : ((s + Finsupp.single mu 1 : DIdx)) nu = 0
    · rw [hnu, Nat.cast_zero, zero_smul]
      exact zero_mem _
    · by_cases hne : nu = layerDir (s + Finsupp.single mu 1)
      · rw [hne, sub_self, smul_zero]
        exact zero_mem _
      · exact Subalgebra.smul_mem _ (hhook nu hnu hne) _
  rw [← totalComponent_add_single s mu c, totalComponent_eq_symConn_add_hook_sub hw hmu c]
  refine sub_mem (add_mem hsym ?_) havg
  by_cases hne : mu = layerDir (s + Finsupp.single mu 1)
  · have hzero : totalComponent (s + Finsupp.single mu 1) mu c =
        totalComponent (s + Finsupp.single mu 1) (layerDir (s + Finsupp.single mu 1)) c := by
      rw [← hne]
    rw [hzero, sub_self]
    exact zero_mem _
  · exact hhook mu hmu hne

/-- Every monomial of bounded additive derivative degree is a polynomial in the covariant
coordinates, provided each of its generators already is. -/
private lemma filt_mem_covCoordAlgebra {m : ℕ}
    (ih : ∀ k, k < m → ∀ g : JetGenerators, genDeg g = k → ofGen g ∈ covCoordAlgebra k)
    {d : ℕ} (hd : d < m) : ∀ P ∈ filt d, P ∈ covCoordAlgebra m := by
  intro P hP
  induction hP using Submodule.span_induction with
  | mem P hP =>
      obtain ⟨l, hl, rfl⟩ := hP
      refine list_prod_mem ?_
      intro x hx
      obtain ⟨h, hhl, rfl⟩ := List.mem_map.mp hx
      have hdeg : genDeg h ≤ d :=
        le_trans (List.single_le_sum (fun _ _ => Nat.zero_le _) _ (List.mem_map_of_mem hhl)) hl
      exact covCoordAlgebra_mono (le_of_lt (lt_of_le_of_lt hdeg hd))
        (ih (genDeg h) (lt_of_le_of_lt hdeg hd) h rfl)
  | zero => exact zero_mem _
  | add x y _ _ hx hy => exact add_mem hx hy
  | smul r x _ hx => exact Subalgebra.smul_mem _ hx r

private lemma ofGen_mem_covCoordAlgebra_aux (m : ℕ) :
    ∀ g : JetGenerators, genDeg g = m → ofGen g ∈ covCoordAlgebra m := by
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    refine ofGen_mem_covCoordAlgebra_step ?_
    cases m with
    | zero =>
        intro P hP
        rw [sfilt_zero, Submodule.mem_bot] at hP
        rw [hP]
        exact zero_mem _
    | succ n =>
        intro P hP
        rw [sfilt_succ] at hP
        exact filt_mem_covCoordAlgebra ih (Nat.lt_succ_self n) P hP

lemma ofGen_mem_covCoordAlgebra (g : JetGenerators) : ofGen g ∈ covCoordAlgebra (genDeg g) :=
  ofGen_mem_covCoordAlgebra_aux (genDeg g) g rfl

/-- **Finite height is preserved by the covariant coordinate change.**  Every ordinary generator is
a polynomial in the covariant coordinates of its own derivative degree, so a jet polynomial of
height at most `N` is a polynomial in the covariant coordinates of height at most `N`. -/
lemma heightAlgebra_le_covCoordAlgebra (N : ℕ) : heightAlgebra N ≤ covCoordAlgebra N := by
  refine Algebra.adjoin_le ?_
  rintro P ⟨g, hg, rfl⟩
  exact covCoordAlgebra_mono hg (ofGen_mem_covCoordAlgebra g)

/-!

## F. The based gauge action in covariant coordinates

A jet based through order `r` fixes every hook coordinate at every derivative degree, because the
hook coordinates are covariant curvature components; and on the symmetric coordinates it is a pure
translation of the top layer, because of `HighestLayer`.  This is the exact input of the
per-variable
polynomial translation lemma.

-/

lemma coordC_smul_colourBasis (a : ℝ) (c₀ c : Col) :
    coordC c (a • colourBasis c₀) = if c = c₀ then a else 0 := by
  rw [map_smul, smul_eq_mul, coordC_apply, Basis.repr_self_apply]
  by_cases h : c = c₀
  · rw [if_pos h, if_pos h.symm, mul_one]
  · rw [if_neg h, if_neg fun hc => h hc.symm, mul_zero]

/-- Below the top layer of a jet based through order `r` there is no shift at all. -/
lemma layerShift_eq_zero_of_lorDeg_le {r : ℕ} {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : BasedTo r U) {w : DIdx} (hw : w ≠ 0) (h : lorDeg w ≤ r) : layerShift U w = 0 := by
  have hlt : lorDeg (layerPred w) < r := by
    have h1 := lorDeg_layerPred hw
    omega
  rw [layerShift, dif_neg hw, mcCoeffCAt_eq_zero_of_lt hU hlt (layerDir w), smul_zero]

/-- **Every ordinary component of a fibre of derivative degree at most `r` is translated by the
same constant.**  Below the top layer that constant vanishes, so this one statement covers both the
fixed and the translated layers. -/
lemma gaugePull_totalComponent {r : ℕ} {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : BasedTo r U) {w : DIdx} {nu : Lor} (hnu : w nu ≠ 0) (hwr : lorDeg w ≤ r + 1) (c : Col) :
    gaugePull U (totalComponent w nu c) = totalComponent w nu c + constR (layerShift U w) c := by
  have hw : w ≠ 0 := fun h => hnu (by simp [h])
  have hpred := lorDeg_predAt hnu
  rw [totalComponent, gaugePull_ofGen]
  rcases eq_or_lt_of_le hwr with heq | hlt
  · have hs : lorDeg (predAt w nu) = r := by omega
    rw [gaugeSubstGen_eq_add_layerShift hU hs nu c, predAt_add_single hnu]
  · have hs : lorDeg (predAt w nu) < r := by omega
    rw [gaugeSubstGen_eq_ofGen_of_lt hU hs nu c,
      layerShift_eq_zero_of_lorDeg_le hU hw (by omega)]
    simp [constR]

/-- **The fully symmetric coordinate is purely translated.**  The weighted average of a fibre moves
by exactly the common constant of that fibre. -/
lemma gaugePull_symConn {r : ℕ} {U : specialUnitaryGroup (Fin 3) JetRing} (hU : BasedTo r U)
    {w : DIdx} (hw : w ≠ 0) (hwr : lorDeg w ≤ r + 1) (c : Col) :
    gaugePull U (symConn w c) = symConn w c + constR (layerShift U w) c := by
  have hdeg : (lorDeg w : ℝ) ≠ 0 := lorDeg_cast_ne_zero hw
  have hterm : ∀ nu : Lor, gaugePull U ((w nu : ℝ) • totalComponent w nu c) =
      (w nu : ℝ) • (totalComponent w nu c + constR (layerShift U w) c) := by
    intro nu
    by_cases hnu : w nu = 0
    · rw [hnu, Nat.cast_zero, zero_smul, zero_smul, map_zero]
    · rw [map_smul, gaugePull_totalComponent hU hnu hwr]
  rw [symConn, map_smul, map_sum, Finset.sum_congr rfl fun nu _ => hterm nu]
  simp_rw [smul_add]
  rw [Finset.sum_add_distrib, ← Finset.sum_smul, sum_coeff_eq_lorDeg, smul_add, smul_smul,
    inv_mul_cancel₀ hdeg, one_smul]

/-- **Based jets fix every hook coordinate**, at every derivative degree: these are covariant
curvature components, so this is `CovariantTower`. -/
lemma gaugePull_covCoordGen_of_not_isSymSlot {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : JetGaugeGroupI.evalSU (Fin 3) U = 1) {g : JetGenerators} (hg : ¬ IsSymSlot g) :
    gaugePull U (covCoordGen g) = covCoordGen g :=
  gaugePull_eq_self_of_based U hU (covCoordGen_mem_covAlgebra_of_not_isSymSlot hg)

/-- **Based jets translate the symmetric coordinates of their own layer and below by a
constant.** -/
lemma gaugePull_covCoordGen_of_isSymSlot {r : ℕ} {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : BasedTo r U) {g : JetGenerators} (hg : IsSymSlot g) (hd : genDeg g ≤ r) :
    gaugePull U (covCoordGen g) =
      covCoordGen g + constR (layerShift U (genFibre g)) (genCol g) := by
  obtain ⟨s, mu, c⟩ := g
  have hmu : mu = layerDir (s + Finsupp.single mu 1) := hg
  have hw : s + Finsupp.single mu 1 ≠ 0 := total_add_single_ne_zero s mu
  have hs : lorDeg s ≤ r := hd
  rw [covCoordGen_dA, dif_pos hmu, genFibre_dA, genCol_dA]
  refine gaugePull_symConn hU hw ?_ c
  rw [lorDeg_add, lorDeg_single]
  omega

/-!

## G. The descending elimination

-/

/-- The variables that survive after the symmetric coordinates of derivative degree at least `k`
have been eliminated inside derivative height `M`. -/
def slotSupport (M k : ℕ) : Set JetGenerators :=
  {g | genDeg g ≤ M ∧ (¬ IsSymSlot g ∨ genDeg g < k)}

lemma slotSupport_zero (M : ℕ) :
    slotSupport M 0 = {g : JetGenerators | genDeg g ≤ M ∧ ¬ IsSymSlot g} := by
  ext g
  constructor
  · rintro ⟨h1, h2 | h2⟩
    · exact ⟨h1, h2⟩
    · omega
  · rintro ⟨h1, h2⟩
    exact ⟨h1, Or.inl h2⟩

/-- The constant by which a realizing jet moves a symmetric coordinate is the delta function of the
selected fibre and colour.  This is the exact translation pattern the per-variable polynomial lemma
consumes. -/
private lemma constR_layerShift_eq_ite {k : ℕ} {U : specialUnitaryGroup (Fin 3) JetRing}
    (hU : BasedTo k U) {w : DIdx} (hw : lorDeg w = k + 1) {c₀ : Col} {a : ℝ}
    (h1 : layerShift U w = a • colourBasis c₀)
    (h0 : ∀ w', lorDeg w' = k + 1 → w' ≠ w → layerShift U w' = 0)
    {g : JetGenerators} (hg : IsSymSlot g) (hd : genDeg g ≤ k) :
    constR (layerShift U (genFibre g)) (genCol g) =
      algebraMap ℝ JetAlgebra (if g = symGen w c₀ then a else 0) := by
  have hw0 : w ≠ 0 := by
    rw [← lorDeg_pos_iff, hw]
    omega
  have hfg : genFibre g ≠ 0 := genFibre_ne_zero g
  have hfdeg : lorDeg (genFibre g) = genDeg g + 1 := lorDeg_genFibre g
  have hgdeg : genDeg (symGen w c₀) = k := by
    have hlp := lorDeg_layerPred hw0
    rw [genDeg_symGen]
    omega
  rcases eq_or_lt_of_le hd with heq | hlt
  · have hfk : lorDeg (genFibre g) = k + 1 := by omega
    by_cases hfw : genFibre g = w
    · have hiff : (genCol g = c₀) ↔ (g = symGen w c₀) := by
        constructor
        · intro hc
          calc g = symGen (genFibre g) (genCol g) := eq_symGen_of_isSymSlot hg
            _ = symGen w c₀ := by rw [hfw, hc]
        · intro hgs
          have hcol := congrArg genCol hgs
          rwa [genCol_symGen] at hcol
      rw [hfw, h1, constR, coordC_smul_colourBasis, if_congr hiff rfl rfl]
    · have hne : g ≠ symGen w c₀ := by
        intro hgs
        exact hfw (by rw [hgs, genFibre_symGen hw0])
      rw [h0 _ hfk hfw, if_neg hne]
      simp [constR]
  · have hle : lorDeg (genFibre g) ≤ k := by omega
    have hne : g ≠ symGen w c₀ := by
      intro hgs
      have hdd : genDeg g = genDeg (symGen w c₀) := by rw [hgs]
      omega
    rw [layerShift_eq_zero_of_lorDeg_le hU hfg hle, if_neg hne]
    simp [constR]

/-- **One symmetric coordinate of the top surviving layer is removed.**  The realizing jet of
  `HighestLayer`
translates exactly that variable and fixes every other variable in the current support, so
`FiniteCompleteness`'s
per-variable translation lemma applies. -/
private lemma notMem_vars_symGen {M k : ℕ} {Q : MvPolynomial JetGenerators ℝ}
    (hfix : ∀ U : specialUnitaryGroup (Fin 3) JetRing,
      JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U (covCoordHom Q) = covCoordHom Q)
    (hQ : Q ∈ supported ℝ (slotSupport M (k + 1)))
    {w : DIdx} (hw : lorDeg w = k + 1) (c₀ : Col) : symGen w c₀ ∉ Q.vars := by
  classical
  have hw0 : w ≠ 0 := by
    rw [← lorDeg_pos_iff, hw]
    omega
  refine MvPolynomial.notMem_vars_of_forall_aeval_add_eq Q (symGen w c₀) fun a => ?_
  obtain ⟨U, hUb, hU1, hU0⟩ := exists_basedTo_layerShift hw c₀ a
  set f : JetGenerators → MvPolynomial JetGenerators ℝ :=
    fun i => X i + C (if i = symGen w c₀ then a else 0) with hfdef
  have hagree : ∀ g ∈ slotSupport M (k + 1),
      covCoordHom (aeval (R := ℝ) f (X g)) = gaugePull U (covCoordHom (X g)) := by
    intro g hg
    have hfg : aeval (R := ℝ) f (X g) = X g + C (if g = symGen w c₀ then a else 0) := by
      rw [aeval_X, hfdef]
    rw [hfg, map_add, covCoordHom_X, covCoordHom_C]
    by_cases hs : IsSymSlot g
    · have hd : genDeg g ≤ k := by
        rcases hg.2 with h | h
        · exact absurd hs h
        · omega
      rw [gaugePull_covCoordGen_of_isSymSlot hUb hs hd,
        constR_layerShift_eq_ite hUb hw hU1 hU0 hs hd]
    · have hne : g ≠ symGen w c₀ := fun hgs => hs (hgs ▸ isSymSlot_symGen hw0 c₀)
      rw [if_neg hne, map_zero, add_zero,
        gaugePull_covCoordGen_of_not_isSymSlot (basedTo_evalSU hUb) hs]
  have hQ' : Q ∈ Algebra.adjoin ℝ (X '' slotSupport M (k + 1)) := by
    rwa [← supported_eq_adjoin_X]
  have hmem : Q ∈ AlgHom.equalizer (covCoordHom.comp (aeval (R := ℝ) f))
      ((gaugePull U).comp covCoordHom) := by
    refine Algebra.adjoin_le ?_ hQ'
    rintro _ ⟨g, hg, rfl⟩
    exact hagree g hg
  have heq : covCoordHom (aeval (R := ℝ) f Q) = gaugePull U (covCoordHom Q) := hmem
  rw [hfix U (basedTo_evalSU hUb)] at heq
  exact covCoordHom_injective heq

/-- One step of the descending elimination: the whole symmetric layer of derivative degree `k`
disappears from the support. -/
private lemma supported_step {M k : ℕ} {Q : MvPolynomial JetGenerators ℝ}
    (hfix : ∀ U : specialUnitaryGroup (Fin 3) JetRing,
      JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U (covCoordHom Q) = covCoordHom Q)
    (hQ : Q ∈ supported ℝ (slotSupport M (k + 1))) : Q ∈ supported ℝ (slotSupport M k) := by
  classical
  have hsub := mem_supported.mp hQ
  rw [mem_supported]
  intro g hg
  have hg' := hsub hg
  refine ⟨hg'.1, ?_⟩
  rcases hg'.2 with h | h
  · exact Or.inl h
  · rcases Nat.lt_succ_iff_lt_or_eq.mp h with h2 | h2
    · exact Or.inr h2
    · by_cases hs : IsSymSlot g
      · exfalso
        have hfib : lorDeg (genFibre g) = k + 1 := by rw [lorDeg_genFibre, h2]
        have hnot := notMem_vars_symGen hfix hQ hfib (genCol g)
        rw [← eq_symGen_of_isSymSlot hs] at hnot
        exact hnot (Finset.mem_coe.mp hg)
      · exact Or.inl hs

/-- The full descending elimination: every symmetric coordinate is removed, layer by layer, from
the top of the height down to the connection. -/
private lemma supported_descend {M : ℕ} {Q : MvPolynomial JetGenerators ℝ}
    (hfix : ∀ U : specialUnitaryGroup (Fin 3) JetRing,
      JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U (covCoordHom Q) = covCoordHom Q) :
    ∀ k, Q ∈ supported ℝ (slotSupport M k) → Q ∈ supported ℝ (slotSupport M 0) := by
  intro k
  induction k with
  | zero => exact fun h => h
  | succ k ih => exact fun h => ih (supported_step hfix h)

/-- **Finite-height completeness.**  Inside every finite derivative height `N`, the ordinary jet
polynomials fixed by every based `SU(3)` gauge jet are exactly the elements of the truncated
algebra generated by the covariant curvature derivatives available at that height.

The forward direction is the descending elimination in the covariant coordinates of section E; the
reverse direction is `CovariantTower`'s fixation of the covariant subalgebra together with the
height bound of
section B. -/
lemma fixed_by_based_height_eq_covAlgebraAt (N : ℕ) :
    {P : JetAlgebra | P ∈ heightAlgebra N ∧
        ∀ U : specialUnitaryGroup (Fin 3) JetRing,
          JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U P = P} =
      (covAlgebraAt N : Set JetAlgebra) := by
  classical
  ext P
  simp only [Set.mem_setOf_eq, SetLike.mem_coe]
  constructor
  · rintro ⟨hPh, hPfix⟩
    have h1 : P ∈ covCoordAlgebra N := heightAlgebra_le_covCoordAlgebra N hPh
    have himg : (Algebra.adjoin ℝ (X '' {g : JetGenerators | genDeg g ≤ N})).map covCoordHom =
        covCoordAlgebra N := by
      rw [AlgHom.map_adjoin, covCoordAlgebra, ← Set.image_comp, covCoordHom_comp_X]
    rw [← himg] at h1
    obtain ⟨Q, hQ, hQP⟩ := Subalgebra.mem_map.mp h1
    rw [← supported_eq_adjoin_X] at hQ
    have hfixQ : ∀ U : specialUnitaryGroup (Fin 3) JetRing,
        JetGaugeGroupI.evalSU (Fin 3) U = 1 → gaugePull U (covCoordHom Q) = covCoordHom Q := by
      intro U hU
      rw [hQP]
      exact hPfix U hU
    have hstart : Q ∈ supported ℝ (slotSupport N (N + 1)) := by
      have hsub := mem_supported.mp hQ
      rw [mem_supported]
      intro g hg
      have hd : genDeg g ≤ N := hsub hg
      exact ⟨hd, Or.inr (by omega)⟩
    have hend := supported_descend hfixQ (N + 1) hstart
    rw [slotSupport_zero, supported_eq_adjoin_X] at hend
    have hmem : P ∈ (Algebra.adjoin ℝ
        (X '' {g : JetGenerators | genDeg g ≤ N ∧ ¬ IsSymSlot g})).map covCoordHom :=
      Subalgebra.mem_map.mpr ⟨Q, hend, hQP⟩
    rw [AlgHom.map_adjoin, ← Set.image_comp, covCoordHom_comp_X] at hmem
    refine Algebra.adjoin_le ?_ hmem
    rintro _ ⟨g, ⟨hd, hs⟩, rfl⟩
    exact covCoordGen_mem_covAlgebraAt_of_not_isSymSlot hs hd
  · intro hP
    exact ⟨covAlgebraAt_le_heightAlgebra N hP,
      fun U hU => gaugePull_eq_self_of_based U hU (covAlgebraAt_le_covAlgebra N hP)⟩

end SU3Jet

end StandardModel
