/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.Gluons.JetCompleteness.SeriesGaugeAction
/-!
# The all-orders ordinary gluon jet algebra

## i. Overview

This file builds the ordinary gluon jet algebra at *arbitrary* finite derivative order: the
commutative
real algebra generated by the colour components of the connection `A_μ` and of all of its ordinary
symmetric derivatives `∂_s A_μ` at a point.  It carries

* the formal total derivative `jetDeriv`;
* the all-orders local jet-gauge substitution `gaugePull`, obtained as the coefficient
  transcription of `GaugeAction` and `SeriesGaugeAction`'s power-series action `actPot U A μ = U A_μ
  ⋆U + mcH U μ`.

## ii. Conventions

Hermitian throughout, matching the Physlib gluon convention and `CoordinateChange` through
`HookBianchi`.  The colour carrier is `ColourBasis`'s traceless
hermitian `ColourSpace` with basis index `Col = Fin 8`; the colour bracket is
`brMat M N = i (M N - N M)`.

## iii. The factorial normalization

The derivative multi-index is `DIdx = Lor →₀ ℕ`; `facI s = ∏_ρ (s ρ)!` is its factorial.  A
generator means an **ordinary derivative**, not a Taylor coefficient:

```text
dA s μ c  ↝  coordC c (∂_s A_μ (0)),        ∂_s A_μ (0) = facI s • coeffMat s (A μ).
```

This is the normalization forced by asking `jetDeriv` to append the derivative index with
coefficient one.  At `s = 0` and `s = single ν 1` the factor is `1`, so the convention agrees with
`GaugeAction`'s `Coord.conn` and `Coord.der` on the nose.

## iv. The composition orientation

`GaugeAction`'s `gaugeAct U` is substitution by the *transformed point*, `eval x (gaugeAct U P) =
eval (actPt U x) P`.  Since `actPot` is a **left** action on potentials, the raw polynomial
substitution is contravariant, and the law proved below is

```text
gaugePull (U * V) = (gaugePull V).comp (gaugePull U).
```

No covariant composition law is asserted.  A literal `MulAction` through inverse jets is *not*
packaged: `CovariantTower`'s covariance statement and `GaugeAction` compatibility both want the raw
substitution.

## v. Results

* `JetGenerators`, `JetComponentSpace.basis`, `JetAlgebra`, `ofGen` — the carrier;
* `jetDeriv`, `jetDeriv_ofGen`, `jetDeriv_one`, `jetDeriv_mul`, `jetDeriv_comm_apply`;
* `brR`, `adR`, `constR` — the colour-vector calculus over an arbitrary commutative `ℝ`-algebra,
  with the same structure constants `cstruct` and `adCoef` as `CoordinateChange`/`GaugeAction`;
* `conjC` — the `t`-th Taylor coefficient of conjugation by a gauge jet, a colour endomorphism;
* `gaugeSubstGen`, `gaugePull` — the all-orders substitution;
* `evalA_gaugePull` — faithfulness: substituting is pulling back along the honest affine action;
* `gaugePull_one`, `gaugePull_mul` — the identity and (contravariant) composition laws;
* `gaugeSubstGen_zero`, `gaugeSubstGen_single` — degree-zero and degree-one agreement with
  `GaugeAction`.

-/

@[expose] public section

namespace StandardModel

open Matrix Module MvPolynomial

open scoped TensorProduct

namespace SU3Jet

/-!

## A. The ordinary generators

-/

/-- The symmetric ordinary derivative multi-index.  This is the `Lor →₀ ℕ` form of a multiset of
  spacetime directions; it is the index type of `MvPowerSeries.coeff`, `coeffMat` and
  `mcCoeffCAt`, which is why it is preferred to `Multiset Lor` here. -/
abbrev DIdx : Type := Lor →₀ ℕ

/-- The multiset form of a derivative multi-index, recording the equivalence with the
  `Multiset Lor` presentation. -/
noncomputable def didxMultiset : DIdx ≃ Multiset Lor := Multiset.toFinsupp.toEquiv.symm

/-- An ordinary generator: the colour-`c` component of the `s`-th ordinary derivative of the
  connection in the direction `μ`. -/
inductive JetGenerators where
  /-- The generator `(∂_s A_μ)^c`. -/
  | dA (s : DIdx) (μ : Lor) (c : Col) : JetGenerators
deriving DecidableEq

namespace JetGenerators

/-- The generator with one further ordinary derivative in the direction `ν`. -/
noncomputable def shift (ν : Lor) : JetGenerators → JetGenerators
  | dA s μ c => dA (s + Finsupp.single ν 1) μ c

@[simp]
lemma shift_dA (ν : Lor) (s : DIdx) (μ : Lor) (c : Col) :
    shift ν (dA s μ c) = dA (s + Finsupp.single ν 1) μ c := rfl

/-- **Ordinary derivatives commute.**  The derivative index really is symmetric: shifting by `μ`
  and then `ν` is shifting by `ν` and then `μ`. -/
lemma shift_comm (ν ρ : Lor) (g : JetGenerators) : shift ν (shift ρ g) = shift ρ (shift ν g) := by
  cases g with
  | dA s μ c => rw [shift_dA, shift_dA, shift_dA, shift_dA, add_right_comm]

/-- The generators are the derivative multi-index, the Lorentz index and the colour index. -/
def equiv : JetGenerators ≃ DIdx × Lor × Col where
  toFun := fun (dA s μ c) => (s, μ, c)
  invFun := fun p => dA p.1 p.2.1 p.2.2
  left_inv := fun (dA _ _ _) => rfl
  right_inv := fun _ => rfl

end JetGenerators

/-!

## B. The component space and the polynomial carrier

The component space is the house-style tensor product of the real derivative-symbol algebra with
the dual of the connection components, following `BBoson.JetComponentSpace`.  The colour factor is
the dual of `ColourBasis`'s physical traceless hermitian `ColourSpace`.

-/

/-- The space of component functions of an ordinary gluon jet: derivative symbols tensored with
  the dual of a Lorentz index and the dual of a colour direction. -/
def JetComponentSpace : Type :=
  DerivAlgebraReal ⊗[ℝ] (Module.Dual ℝ Lorentz.CoVector ⊗[ℝ] Module.Dual ℝ ColourSpace)

noncomputable instance : AddCommGroup JetComponentSpace :=
  inferInstanceAs (AddCommGroup
    (DerivAlgebraReal ⊗[ℝ] (Module.Dual ℝ Lorentz.CoVector ⊗[ℝ] Module.Dual ℝ ColourSpace)))

noncomputable instance : Module ℝ JetComponentSpace :=
  inferInstanceAs (Module ℝ
    (DerivAlgebraReal ⊗[ℝ] (Module.Dual ℝ Lorentz.CoVector ⊗[ℝ] Module.Dual ℝ ColourSpace)))

/-- The explicit basis of the ordinary jet component space, indexed by the ordinary generators. -/
noncomputable def JetComponentSpace.basis : Basis JetGenerators ℝ JetComponentSpace :=
  (Lorentz.CoVector.basis.dualBasis.symmetricAlgebra.tensorProduct
    (Lorentz.CoVector.basis.dualBasis.tensorProduct colourBasis.dualBasis)).reindex
      JetGenerators.equiv.symm

/-- The all-orders ordinary gluon jet algebra. -/
def JetAlgebra : Type := SymmetricAlgebra ℝ JetComponentSpace

noncomputable instance : CommRing JetAlgebra :=
  inferInstanceAs (CommRing (SymmetricAlgebra ℝ JetComponentSpace))

noncomputable instance : Algebra ℝ JetAlgebra :=
  inferInstanceAs (Algebra ℝ (SymmetricAlgebra ℝ JetComponentSpace))

/-- The generator of the jet algebra attached to an ordinary generator. -/
noncomputable def ofGen (g : JetGenerators) : JetAlgebra :=
  SymmetricAlgebra.ι ℝ JetComponentSpace (JetComponentSpace.basis g)

/-- The polynomial coordinates of the ordinary jet algebra. -/
noncomputable def toPoly : JetAlgebra ≃ₐ[ℝ] MvPolynomial JetGenerators ℝ :=
  SymmetricAlgebra.equivMvPolynomial JetComponentSpace.basis

@[simp]
lemma toPoly_ofGen (g : JetGenerators) : toPoly (ofGen g) = X g :=
  SymmetricAlgebra.equivMvPolynomial_ι_apply _ _

@[simp]
lemma toPoly_symm_X (g : JetGenerators) : toPoly.symm (X g) = ofGen g :=
  SymmetricAlgebra.equivMvPolynomial_symm_X _ _

/-- Two algebra maps out of the jet algebra agreeing on every generator are equal. -/
lemma jetAlgHom_ext {A : Type*} [CommSemiring A] [Algebra ℝ A] {f g : JetAlgebra →ₐ[ℝ] A}
    (h : ∀ i : JetGenerators, f (ofGen i) = g (ofGen i)) : f = g :=
  SymmetricAlgebra.algHom_ext (JetComponentSpace.basis.ext h)

/-- Evaluation of a jet polynomial at a point of the ordinary coordinate space. -/
noncomputable def evalA (x : JetGenerators → ℝ) : JetAlgebra →ₐ[ℝ] ℝ :=
  (MvPolynomial.aeval x).comp toPoly.toAlgHom

lemma evalA_eq_eval (x : JetGenerators → ℝ) (P : JetAlgebra) :
    evalA x P = MvPolynomial.eval x (toPoly P) := rfl

@[simp]
lemma evalA_ofGen (x : JetGenerators → ℝ) (g : JetGenerators) : evalA x (ofGen g) = x g := by
  rw [evalA_eq_eval, toPoly_ofGen, eval_X]

/-- Elements of the jet algebra agreeing at every point of the coordinate space are equal;
  legitimate because `ℝ` is an infinite integral domain. -/
lemma jetAlgebra_funext {P Q : JetAlgebra} (h : ∀ x, evalA x P = evalA x Q) : P = Q := by
  apply toPoly.injective
  exact MvPolynomial.funext fun x => by
    have hx := h x
    rwa [evalA_eq_eval, evalA_eq_eval] at hx

/-!

## C. The formal total derivative

Following `BBoson.JetAlgebra.jetDeriv`: the derivation appending the derivative index, built
through the polynomial coordinates rather than postulated.

-/

/-- The derivative substitution on polynomial coordinates. -/
noncomputable def polyDeriv (ν : Lor) :
    Derivation ℝ (MvPolynomial JetGenerators ℝ) (MvPolynomial JetGenerators ℝ) :=
  MvPolynomial.mkDerivation ℝ fun g : JetGenerators =>
    (X (JetGenerators.shift ν g) : MvPolynomial JetGenerators ℝ)

@[simp]
lemma polyDeriv_X (ν : Lor) (g : JetGenerators) :
    polyDeriv ν (X g) = X (JetGenerators.shift ν g) :=
  MvPolynomial.mkDerivation_X _ _ _

lemma polyDeriv_comm (ν ρ : Lor) (p : MvPolynomial JetGenerators ℝ) :
    polyDeriv ν (polyDeriv ρ p) = polyDeriv ρ (polyDeriv ν p) := by
  induction p using MvPolynomial.induction_on with
  | C a =>
      rw [← algebraMap_eq, Derivation.map_algebraMap, map_zero, Derivation.map_algebraMap,
        map_zero]
  | add p q hp hq => rw [map_add, map_add, map_add, map_add, hp, hq]
  | mul_X p g hp =>
      simp only [Derivation.leibniz, polyDeriv_X, smul_eq_mul, map_add]
      rw [JetGenerators.shift_comm, hp]
      ring

/-- **The formal total spacetime derivative** on the ordinary jet algebra: the derivation sending
  each component function `∂_s A_μ` to `∂_{s + ν} A_μ`. -/
noncomputable def jetDeriv (ν : Lor) : JetAlgebra →ₗ[ℝ] JetAlgebra :=
  toPoly.symm.toLinearMap ∘ₗ (polyDeriv ν).toLinearMap ∘ₗ toPoly.toLinearMap

lemma toPoly_jetDeriv (ν : Lor) (P : JetAlgebra) :
    toPoly (jetDeriv ν P) = polyDeriv ν (toPoly P) := by
  simp only [jetDeriv, LinearMap.coe_comp, Function.comp_apply, AlgEquiv.toLinearMap_apply,
    Derivation.coeFn_coe, AlgEquiv.apply_symm_apply]

/-- **The total derivative appends the derivative index.** -/
@[simp]
lemma jetDeriv_ofGen (ν : Lor) (g : JetGenerators) :
    jetDeriv ν (ofGen g) = ofGen (JetGenerators.shift ν g) := by
  apply toPoly.injective
  rw [toPoly_jetDeriv, toPoly_ofGen, polyDeriv_X, toPoly_ofGen]

@[simp]
lemma jetDeriv_one (ν : Lor) : jetDeriv ν (1 : JetAlgebra) = 0 := by
  apply toPoly.injective
  simp only [toPoly_jetDeriv, map_one, map_zero, Derivation.map_one_eq_zero]

/-- **The Leibniz rule** for the total derivative. -/
lemma jetDeriv_mul (ν : Lor) (P Q : JetAlgebra) :
    jetDeriv ν (P * Q) = jetDeriv ν P * Q + P * jetDeriv ν Q := by
  apply toPoly.injective
  simp only [toPoly_jetDeriv, map_mul, map_add, Derivation.leibniz, smul_eq_mul]
  ring

/-- **Total derivatives commute.** -/
lemma jetDeriv_comm_apply (ν ρ : Lor) (P : JetAlgebra) :
    jetDeriv ν (jetDeriv ρ P) = jetDeriv ρ (jetDeriv ν P) := by
  apply toPoly.injective
  rw [toPoly_jetDeriv, toPoly_jetDeriv, toPoly_jetDeriv, toPoly_jetDeriv, polyDeriv_comm]

/-!

## D. Colour vectors over an arbitrary commutative real algebra

`CoordinateChange`'s `brP`, `GaugeAction`'s `adP` and `constP` are stated for `MvPolynomial ι ℝ`.
The ordinary carrier is a
`SymmetricAlgebra`, and the evaluation dictionary below lands in a power-series ring, so the same
formulas are restated over an arbitrary commutative `ℝ`-algebra.  The structure constants are
`CoordinateChange`'s `cstruct` and `GaugeAction`'s `adCoef` unchanged: nothing is re-expanded by
hand.

-/

section ColourAlg

variable {R S : Type*} [CommRing R] [Algebra ℝ R] [CommRing S] [Algebra ℝ S]

/-- The colour bracket of two colour vectors valued in a commutative `ℝ`-algebra. -/
noncomputable def brR (p q : Col → R) : Col → R :=
  fun c => ∑ a, ∑ b, algebraMap ℝ R (cstruct a b c) * (p a * q b)

/-- The adjoint action of a constant colour rotation on a colour vector. -/
noncomputable def adR (u : specialUnitaryGroup (Fin 3) ℂ) (p : Col → R) : Col → R :=
  fun c => ∑ c', algebraMap ℝ R (adCoef u c c') * p c'

/-- A constant colour vector. -/
noncomputable def constR (Y : ColourSpace) : Col → R := fun c => algebraMap ℝ R (coordC c Y)

lemma brR_swap (p q : Col → R) (c : Col) : brR p q c = -brR q p c := by
  have key : (brR q p c : R) = ∑ a, ∑ b, -(algebraMap ℝ R (cstruct a b c) * (p a * q b)) := by
    rw [brR, Finset.sum_comm]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ => ?_
    rw [cstruct_swap b a c, map_neg]
    ring
  rw [key, brR]
  simp [Finset.sum_neg_distrib]

lemma brR_self (p : Col → R) (c : Col) : brR p p c = 0 := by
  have h : (2 : ℝ) • brR p p c = 0 := by
    rw [two_smul]
    nth_rewrite 1 [brR_swap p p c]
    exact neg_add_cancel _
  have h2 := congrArg (fun x : R => (2⁻¹ : ℝ) • x) h
  simpa [smul_smul] using h2

lemma brR_add_left (p p' q : Col → R) (c : Col) :
    brR (p + p') q c = brR p q c + brR p' q c := by
  simp only [brR, Pi.add_apply, add_mul, mul_add, Finset.sum_add_distrib]

lemma brR_add_right (p q q' : Col → R) (c : Col) :
    brR p (q + q') c = brR p q c + brR p q' c := by
  simp only [brR, Pi.add_apply, mul_add, Finset.sum_add_distrib]

lemma adR_one (p : Col → R) (c : Col) : adR 1 p c = p c := by
  rw [adR]
  have h : ∀ c' : Col, (algebraMap ℝ R (adCoef 1 c c')) * p c' = if c = c' then p c' else 0 := by
    intro c'
    rw [adCoef_one]
    by_cases hc : c = c' <;> simp [hc]
  rw [Finset.sum_congr rfl fun c' (_ : c' ∈ Finset.univ) => h c']
  simp

lemma algHom_brR (φ : R →ₐ[ℝ] S) (p q : Col → R) (c : Col) :
    φ (brR p q c) = brR (fun a => φ (p a)) (fun b => φ (q b)) c := by
  rw [brR, brR, map_sum]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [map_sum]
  exact Finset.sum_congr rfl fun b _ => by rw [map_mul, map_mul, AlgHom.commutes]

lemma algHom_adR (φ : R →ₐ[ℝ] S) (u : specialUnitaryGroup (Fin 3) ℂ) (p : Col → R) (c : Col) :
    φ (adR u p c) = adR u (fun a => φ (p a)) c := by
  rw [adR, adR, map_sum]
  exact Finset.sum_congr rfl fun c' _ => by rw [map_mul, AlgHom.commutes]

lemma algHom_constR (φ : R →ₐ[ℝ] S) (Y : ColourSpace) (c : Col) :
    φ (constR Y c) = constR Y c := AlgHom.commutes _ _

end ColourAlg

/-- On the polynomial carrier the general colour bracket is `CoordinateChange`'s `brP`. -/
lemma brP_eq_brR {ι : Type*} (p q : Col → MvPolynomial ι ℝ) (c : Col) :
    brP p q c = brR p q c := by
  rw [brP, brR]
  simp only [MvPolynomial.algebraMap_eq]

/-- On the polynomial carrier the general adjoint action is `GaugeAction`'s `adP`. -/
lemma adP_eq_adR {ι : Type*} (u : specialUnitaryGroup (Fin 3) ℂ) (p : Col → MvPolynomial ι ℝ)
    (c : Col) : adP u p c = adR u p c := by
  rw [adP, adR]
  simp only [MvPolynomial.algebraMap_eq]

/-- On the polynomial carrier the general constant colour vector is `GaugeAction`'s `constP`. -/
lemma constP_eq_constR {ι : Type*} (Y : ColourSpace) (c : Col) :
    (constP Y c : MvPolynomial ι ℝ) = constR Y c := by
  rw [constP, constR, MvPolynomial.algebraMap_eq]

/-!

## E. Coefficients of a conjugated constant colour matrix

The generalized Leibniz rule for `∂_s (U A_μ ⋆U)` is carried entirely by power-series
multiplication.  The only new object needed is the `t`-th Taylor coefficient of the conjugate of a
*constant* matrix by the gauge jet.  It preserves the physical colour carrier: hermiticity because
the two outer factors enter symmetrically, and tracelessness because `⋆U U = 1` makes the trace of
the conjugate a constant series.

-/

/-- A constant complex matrix, viewed as a matrix of jets. -/
noncomputable def constMat (M : Matrix (Fin 3) (Fin 3) ℂ) : Matrix (Fin 3) (Fin 3) JetRing :=
  M.map (MvPowerSeries.C : ℂ →+* JetRing)

@[simp]
lemma constMat_apply (M : Matrix (Fin 3) (Fin 3) ℂ) (i j : Fin 3) :
    constMat M i j = (MvPowerSeries.C (M i j) : JetRing) := rfl

lemma constMat_add (M N : Matrix (Fin 3) (Fin 3) ℂ) :
    constMat (M + N) = constMat M + constMat N :=
  Matrix.ext fun i j => by
    show (MvPowerSeries.C (M i j + N i j) : JetRing) = _
    rw [map_add]; rfl

lemma smul_C_jet (r : ℝ) (z : ℂ) :
    (MvPowerSeries.C ((r • z : ℂ)) : JetRing) = r • (MvPowerSeries.C z : JetRing) := by
  ext k
  rw [(MvPowerSeries.coeff k).map_smul_of_tower, MvPowerSeries.coeff_C, MvPowerSeries.coeff_C]
  split_ifs <;> simp

lemma constMat_smul (r : ℝ) (M : Matrix (Fin 3) (Fin 3) ℂ) :
    constMat (r • M) = r • constMat M :=
  Matrix.ext fun i j => by
    show (MvPowerSeries.C ((r • M i j : ℂ)) : JetRing) = _
    rw [smul_C_jet]; rfl

lemma star_constMat (M : Matrix (Fin 3) (Fin 3) ℂ) : star (constMat M) = constMat (star M) :=
  Matrix.ext fun i j => by
    show star (MvPowerSeries.C (M j i) : JetRing) = MvPowerSeries.C (star (M j i))
    rw [JetRing.star_C]

lemma trace_constMat (M : Matrix (Fin 3) (Fin 3) ℂ) :
    trace (constMat M) = (MvPowerSeries.C (trace M) : JetRing) := by
  rw [Matrix.trace, Matrix.trace, map_sum]
  exact Finset.sum_congr rfl fun i _ => rfl

lemma coeffMat_add (k : DIdx) (M N : Matrix (Fin 3) (Fin 3) JetRing) :
    coeffMat k (M + N) = coeffMat k M + coeffMat k N :=
  Matrix.ext fun i j => by
    show MvPowerSeries.coeff k (M i j + N i j) = _
    rw [map_add]
    rfl

lemma coeffMat_smul (k : DIdx) (r : ℝ) (M : Matrix (Fin 3) (Fin 3) JetRing) :
    coeffMat k (r • M) = r • coeffMat k M :=
  Matrix.ext fun i j => by
    show MvPowerSeries.coeff k (r • M i j) = _
    rw [(MvPowerSeries.coeff k).map_smul_of_tower]
    rfl

lemma star_coeffMat (k : DIdx) (M : Matrix (Fin 3) (Fin 3) JetRing) :
    star (coeffMat k M) = coeffMat k (star M) :=
  Matrix.ext fun i j => (JetRing.coeff_star k (M j i)).symm

lemma coeffMat_zero_eq_jetValue (M : Matrix (Fin 3) (Fin 3) JetRing) :
    coeffMat 0 M = Gluon.jetValue M :=
  Matrix.ext fun i j => MvPowerSeries.coeff_zero_eq_constantCoeff_apply (M i j)

/-- **The `t`-th Taylor coefficient of a conjugated constant colour matrix.** -/
noncomputable def conjCoeffM (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx)
    (M : Matrix (Fin 3) (Fin 3) ℂ) : Matrix (Fin 3) (Fin 3) ℂ :=
  coeffMat t (U.1 * constMat M * star U.1)

lemma conjCoeffM_add (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx)
    (M N : Matrix (Fin 3) (Fin 3) ℂ) :
    conjCoeffM U t (M + N) = conjCoeffM U t M + conjCoeffM U t N := by
  rw [conjCoeffM, conjCoeffM, conjCoeffM, constMat_add, Matrix.mul_add, Matrix.add_mul,
    coeffMat_add]

lemma conjCoeffM_smul (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx) (r : ℝ)
    (M : Matrix (Fin 3) (Fin 3) ℂ) :
    conjCoeffM U t (r • M) = r • conjCoeffM U t M := by
  rw [conjCoeffM, conjCoeffM, constMat_smul, Matrix.mul_smul, Matrix.smul_mul, coeffMat_smul]

/-- The conjugate of a hermitian matrix stays hermitian at every Taylor order. -/
lemma star_conjCoeffM (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx)
    {M : Matrix (Fin 3) (Fin 3) ℂ} (hM : star M = M) :
    star (conjCoeffM U t M) = conjCoeffM U t M := by
  rw [conjCoeffM, star_coeffMat, star_mul, star_mul, star_star, star_constMat, hM,
    Matrix.mul_assoc]

/-- The trace of the conjugate is a constant series: this is where `⋆U U = 1` is used. -/
lemma trace_conjCoeffM (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx)
    (M : Matrix (Fin 3) (Fin 3) ℂ) :
    trace (conjCoeffM U t M) =
      MvPowerSeries.coeff t (MvPowerSeries.C (trace M) : JetRing) := by
  rw [conjCoeffM, trace_coeffMat, Matrix.trace_mul_cycle, coe_star_mul_self, Matrix.one_mul,
    trace_constMat]

lemma trace_conjCoeffM_of_traceless (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx)
    {M : Matrix (Fin 3) (Fin 3) ℂ} (hM : trace M = 0) : trace (conjCoeffM U t M) = 0 := by
  rw [trace_conjCoeffM, hM, map_zero, map_zero]

/-- **The coefficient conjugation operator on the physical colour carrier.** -/
noncomputable def conjC (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx) :
    ColourSpace →ₗ[ℝ] ColourSpace where
  toFun X := mkCM (conjCoeffM U t (cmat X)) (star_conjCoeffM U t (cmat_star X))
    (trace_conjCoeffM_of_traceless U t (cmat_trace X))
  map_add' X Y := cmat_injective (by
    show conjCoeffM U t (cmat (X + Y)) = conjCoeffM U t (cmat X) + conjCoeffM U t (cmat Y)
    rw [cmat_add, conjCoeffM_add])
  map_smul' r X := cmat_injective (by
    show conjCoeffM U t (cmat (r • X)) = r • conjCoeffM U t (cmat X)
    rw [cmat_smul, conjCoeffM_smul])

@[simp]
lemma cmat_conjC (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx) (X : ColourSpace) :
    cmat (conjC U t X) = conjCoeffM U t (cmat X) := rfl

/-- At derivative order zero the coefficient conjugation is the adjoint action of the base-point
  value of the gauge jet. -/
lemma conjC_zero (U : specialUnitaryGroup (Fin 3) JetRing) (X : ColourSpace) :
    conjC U 0 X = adC (JetGaugeGroupI.evalSU (Fin 3) U) X := by
  apply cmat_injective
  rw [cmat_conjC, cmat_adC, conjCoeffM, coeffMat_zero_eq_jetValue, Gluon.jetValue_mul,
    Gluon.jetValue_mul, Gluon.jetValue_star, constMat, jetValue_map_C, jetValue_coe_eq,
    star_eq_conjTranspose]

/-!

## F. The factorial normalization and the colour-potential dictionary

`facI s` is the factorial of a derivative multi-index, so that `∂_s A_μ(0) = facI s • coeff_s A_μ`.
A generator is the *ordinary derivative*, which is the convention forced by asking `jetDeriv` to
append the derivative index with coefficient one.

-/

/-- The factorial of a spacetime derivative multi-index. -/
noncomputable def facI (s : DIdx) : ℝ := ∏ ρ, (Nat.factorial (s ρ) : ℝ)

lemma facI_pos (s : DIdx) : 0 < facI s :=
  Finset.prod_pos fun ρ _ => by exact_mod_cast Nat.factorial_pos (s ρ)

lemma facI_ne_zero (s : DIdx) : facI s ≠ 0 := ne_of_gt (facI_pos s)

@[simp]
lemma facI_zero : facI (0 : DIdx) = 1 :=
  Finset.prod_eq_one fun ρ _ => by simp

/-- Appending one derivative index multiplies the factorial by the new multiplicity. -/
lemma facI_add_single (s : DIdx) (ν : Lor) :
    facI (s + Finsupp.single ν 1) = ((s ν : ℝ) + 1) * facI s := by
  classical
  rw [facI, facI,
    show (∏ ρ : Lor, (Nat.factorial (((s + Finsupp.single ν 1) : DIdx) ρ) : ℝ)) =
        ∏ ρ : Lor, ((if ρ = ν then ((s ν : ℝ) + 1) else 1) * (Nat.factorial (s ρ) : ℝ)) from
      Finset.prod_congr rfl fun ρ _ => by
        rcases eq_or_ne ρ ν with rfl | h
        · rw [Finsupp.add_apply, Finsupp.single_eq_same, Nat.factorial_succ, if_pos rfl]
          push_cast
          ring
        · rw [Finsupp.add_apply, Finsupp.single_eq_of_ne h, add_zero, if_neg h, one_mul],
    Finset.prod_mul_distrib, Finset.prod_ite_eq' Finset.univ ν]
  simp

@[simp]
lemma facI_single (ν : Lor) : facI (Finsupp.single ν 1) = 1 := by
  have h := facI_add_single 0 ν
  rw [zero_add, facI_zero, mul_one, Finsupp.coe_zero, Pi.zero_apply] at h
  rw [h]
  norm_num

/-- A jet with prescribed Taylor coefficients. -/
def mkJet (f : DIdx → ℂ) : JetRing := f

@[simp]
lemma coeff_mkJet (f : DIdx → ℂ) (k : DIdx) : MvPowerSeries.coeff k (mkJet f) = f k := rfl

lemma cmat_sum {ι : Type*} (t : Finset ι) (f : ι → ColourSpace) :
    cmat (∑ i ∈ t, f i) = ∑ i ∈ t, cmat (f i) := by
  classical
  induction t using Finset.induction with
  | empty => rw [Finset.sum_empty, Finset.sum_empty, cmat_zero]
  | insert a t ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, cmat_add, ih]

lemma star_eq_self_of_coeffMat {M : Matrix (Fin 3) (Fin 3) JetRing}
    (h : ∀ k, star (coeffMat k M) = coeffMat k M) : star M = M := by
  refine Matrix.ext fun i j => MvPowerSeries.ext fun k => ?_
  have hk := congrFun (congrFun (h k) i) j
  show MvPowerSeries.coeff k (star (M j i)) = MvPowerSeries.coeff k (M i j)
  rw [JetRing.coeff_star]
  exact hk

lemma trace_eq_zero_of_coeffMat {M : Matrix (Fin 3) (Fin 3) JetRing}
    (h : ∀ k, trace (coeffMat k M) = 0) : trace M = 0 := by
  refine MvPowerSeries.ext fun k => ?_
  rw [map_zero, ← trace_coeffMat, h k]

/-- A gluon potential jet all of whose Taylor coefficients lie in the physical traceless hermitian
  colour carrier. -/
structure ColourPot where
  /-- The underlying matrix-of-jets potential. -/
  pot : Potential
  /-- Hermiticity, at every Taylor order. -/
  star_pot : ∀ μ, star (pot μ) = pot μ
  /-- Tracelessness, at every Taylor order. -/
  trace_pot : ∀ μ, trace (pot μ) = 0

lemma ColourPot.ext' {A B : ColourPot} (h : A.pot = B.pot) : A = B := by
  cases A
  cases B
  subst h
  rfl

/-- The `s`-th Taylor coefficient of a colour potential, in the colour carrier. -/
noncomputable def ColourPot.coeffC (A : ColourPot) (s : DIdx) (μ : Lor) : ColourSpace :=
  mkCM (coeffMat s (A.pot μ)) (by rw [star_coeffMat, A.star_pot])
    (by rw [trace_coeffMat, A.trace_pot, map_zero])

@[simp]
lemma ColourPot.cmat_coeffC (A : ColourPot) (s : DIdx) (μ : Lor) :
    cmat (A.coeffC s μ) = coeffMat s (A.pot μ) := rfl

/-- **The point of the ordinary coordinate space described by a colour potential.**  The generator
  `∂_s A_μ` reads off the *ordinary derivative*, which is `facI s` times the Taylor
  coefficient. -/
noncomputable def potPt (A : ColourPot) : JetGenerators → ℝ
  | .dA s μ c => facI s * coordC c (A.coeffC s μ)

/-- The colour vector of the `s`-th ordinary derivative of the connection at a coordinate
  point. -/
noncomputable def cfgC (x : JetGenerators → ℝ) (s : DIdx) (μ : Lor) : ColourSpace :=
  mkC fun c => x (JetGenerators.dA s μ c)

/-- **The generic colour potential of a point of the ordinary coordinate space.** -/
noncomputable def potOf (x : JetGenerators → ℝ) : ColourPot where
  pot := fun μ => Matrix.of fun i j => mkJet fun k => cmat ((facI k)⁻¹ • cfgC x k μ) i j
  star_pot μ := star_eq_self_of_coeffMat fun k => by
    show star (cmat ((facI k)⁻¹ • cfgC x k μ)) = cmat ((facI k)⁻¹ • cfgC x k μ)
    exact cmat_star _
  trace_pot μ := trace_eq_zero_of_coeffMat fun k => by
    show trace (cmat ((facI k)⁻¹ • cfgC x k μ)) = 0
    exact cmat_trace _

@[simp]
lemma coeffMat_potOf (x : JetGenerators → ℝ) (k : DIdx) (μ : Lor) :
    coeffMat k ((potOf x).pot μ) = cmat ((facI k)⁻¹ • cfgC x k μ) := rfl

@[simp]
lemma coeffC_potOf (x : JetGenerators → ℝ) (k : DIdx) (μ : Lor) :
    (potOf x).coeffC k μ = (facI k)⁻¹ • cfgC x k μ :=
  cmat_injective (coeffMat_potOf x k μ)

/-- Reading off the coordinates of the generic potential returns the point. -/
@[simp]
lemma potPt_potOf (x : JetGenerators → ℝ) : potPt (potOf x) = x := by
  funext g
  cases g with
  | dA s μ c =>
    show facI s * coordC c ((potOf x).coeffC s μ) = _
    rw [coeffC_potOf, map_smul, smul_eq_mul, cfgC, coordC_mkC, ← mul_assoc,
      mul_inv_cancel₀ (facI_ne_zero s), one_mul]

/-- Building the generic potential from the coordinates of a colour potential returns it. -/
@[simp]
lemma potOf_potPt (A : ColourPot) : potOf (potPt A) = A := by
  refine ColourPot.ext' ?_
  funext μ
  refine Matrix.ext fun i j => MvPowerSeries.ext fun k => ?_
  have h : cfgC (potPt A) k μ = facI k • A.coeffC k μ := by
    rw [cfgC, show (fun c => potPt A (JetGenerators.dA k μ c)) =
        (fun c => coordC c (facI k • A.coeffC k μ)) from funext fun c => by
      rw [map_smul, smul_eq_mul]
      rfl]
    exact mkC_coordC _
  have h2 : cmat ((facI k)⁻¹ • cfgC (potPt A) k μ) = coeffMat k (A.pot μ) := by
    rw [h, smul_smul, inv_mul_cancel₀ (facI_ne_zero k), one_smul, ColourPot.cmat_coeffC]
  exact congrFun (congrFun h2 i) j

/-- The local gauge action preserves the physical colour carrier at every Taylor order. -/
noncomputable def actPotC (U : specialUnitaryGroup (Fin 3) JetRing) (A : ColourPot) :
    ColourPot where
  pot := actPot U A.pot
  star_pot μ := by
    rw [actPot, star_add, star_mcH, star_mul, star_mul, star_star, A.star_pot, Matrix.mul_assoc]
  trace_pot μ := by
    rw [actPot, trace_add, trace_mcH, Matrix.trace_mul_cycle, coe_star_mul_self, Matrix.one_mul,
      A.trace_pot, add_zero]

@[simp]
lemma actPotC_pot (U : specialUnitaryGroup (Fin 3) JetRing) (A : ColourPot) :
    (actPotC U A).pot = actPot U A.pot := rfl

lemma actPotC_one (A : ColourPot) : actPotC 1 A = A :=
  ColourPot.ext' (actPot_one A.pot)

lemma actPotC_mul (U V : specialUnitaryGroup (Fin 3) JetRing) (A : ColourPot) :
    actPotC (U * V) A = actPotC U (actPotC V A) :=
  ColourPot.ext' (actPot_mul U V A.pot)

/-!

## G. The coefficient convolution

The generalized Leibniz rule for `∂_s (U A_μ ⋆U)` is carried by power-series multiplication: the
`s`-th coefficient of the conjugate is the convolution of the coefficients of `A_μ` with the
coefficient conjugation operator of section E.  No multinomial bookkeeping is written by hand.

-/

private lemma coeff_mul_mul_split (f g h : JetRing) (s : DIdx) :
    MvPowerSeries.coeff s (f * g * h) =
      ∑ p ∈ Finset.antidiagonal s,
        MvPowerSeries.coeff p.1 g * MvPowerSeries.coeff p.2 (f * h) := by
  rw [show f * g * h = g * (f * h) by ring, MvPowerSeries.coeff_mul]

private lemma mul_mul_apply (P N Q : Matrix (Fin 3) (Fin 3) JetRing) (i j : Fin 3) :
    (P * N * Q) i j = ∑ l, ∑ k, P i k * N k l * Q l j := by
  rw [Matrix.mul_apply]
  refine Finset.sum_congr rfl fun l _ => ?_
  rw [Matrix.mul_apply, Finset.sum_mul]

/-- **The coefficient convolution of a conjugated potential.** -/
lemma coeffMat_conj_split (U : specialUnitaryGroup (Fin 3) JetRing)
    (N : Matrix (Fin 3) (Fin 3) JetRing) (s : DIdx) :
    coeffMat s (U.1 * N * star U.1) =
      ∑ p ∈ Finset.antidiagonal s, conjCoeffM U p.2 (coeffMat p.1 N) := by
  refine Matrix.ext fun i j => ?_
  have hR : (∑ p ∈ Finset.antidiagonal s, conjCoeffM U p.2 (coeffMat p.1 N)) i j =
      ∑ p ∈ Finset.antidiagonal s, ∑ l, ∑ k,
        MvPowerSeries.coeff p.1 (N k l) *
          MvPowerSeries.coeff p.2 (U.1 i k * star U.1 l j) := by
    rw [Matrix.sum_apply]
    refine Finset.sum_congr rfl fun p _ => ?_
    show MvPowerSeries.coeff p.2 ((U.1 * constMat (coeffMat p.1 N) * star U.1) i j) = _
    rw [mul_mul_apply, map_sum]
    refine Finset.sum_congr rfl fun l _ => ?_
    rw [map_sum]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [show U.1 i k * constMat (coeffMat p.1 N) k l * star U.1 l j =
        (MvPowerSeries.C (MvPowerSeries.coeff p.1 (N k l)) : JetRing) *
          (U.1 i k * star U.1 l j) from by
      show U.1 i k * (MvPowerSeries.C (MvPowerSeries.coeff p.1 (N k l)) : JetRing) *
        star U.1 l j = _
      ring, MvPowerSeries.coeff_C_mul]
  rw [hR]
  show MvPowerSeries.coeff s ((U.1 * N * star U.1) i j) = _
  rw [mul_mul_apply, map_sum]
  rw [Finset.sum_comm (s := Finset.antidiagonal s)]
  refine Finset.sum_congr rfl fun l _ => ?_
  rw [map_sum, Finset.sum_comm (s := Finset.antidiagonal s)]
  exact Finset.sum_congr rfl fun k _ => coeff_mul_mul_split _ _ _ s

/-- **The coefficient transcription of the power-series action.** -/
lemma coeffMat_actPot (U : specialUnitaryGroup (Fin 3) JetRing) (A : Potential) (μ : Lor)
    (s : DIdx) :
    coeffMat s (actPot U A μ) =
      (∑ p ∈ Finset.antidiagonal s, conjCoeffM U p.2 (coeffMat p.1 (A μ))) + mcCoeffM U μ s := by
  rw [actPot, coeffMat_add, coeffMat_conj_split]
  rfl

/-- The same statement in the physical colour carrier. -/
lemma coeffC_actPotC (U : specialUnitaryGroup (Fin 3) JetRing) (A : ColourPot) (μ : Lor)
    (s : DIdx) :
    (actPotC U A).coeffC s μ =
      (∑ p ∈ Finset.antidiagonal s, conjC U p.2 (A.coeffC p.1 μ)) + mcCoeffCAt U μ s := by
  apply cmat_injective
  rw [ColourPot.cmat_coeffC, cmat_add, cmat_sum, cmat_mcCoeffCAt, actPotC_pot, coeffMat_actPot]
  refine congrArg₂ _ (Finset.sum_congr rfl fun p _ => ?_) rfl
  rw [cmat_conjC, ColourPot.cmat_coeffC]

/-!

## H. The all-orders jet-gauge substitution

The image of the generator `∂_s A_μ` is the coefficient transcription of
`actPot U A μ = U A_μ ⋆U + mcH U μ` read in the colour basis, with the factorial normalization of
section F.

-/

/-- The colour vector of the generators at derivative index `s` and Lorentz direction `μ`. -/
noncomputable def genVec (s : DIdx) (μ : Lor) : Col → JetAlgebra :=
  fun c => ofGen (JetGenerators.dA s μ c)

@[simp]
lemma evalA_algebraMap (x : JetGenerators → ℝ) (r : ℝ) :
    evalA x (algebraMap ℝ JetAlgebra r) = r := (evalA x).commutes r

/-- **The all-orders gauge substitution on generators.** -/
noncomputable def gaugeSubstGen (U : specialUnitaryGroup (Fin 3) JetRing) :
    JetGenerators → JetAlgebra
  | .dA s μ c =>
      (∑ p ∈ Finset.antidiagonal s, ∑ c',
          algebraMap ℝ JetAlgebra
              (facI s * (facI p.1)⁻¹ * coordC c (conjC U p.2 (colourBasis c'))) *
            genVec p.1 μ c') +
        constR (facI s • mcCoeffCAt U μ s) c

/-- **The all-orders jet-gauge substitution**, as an algebra endomorphism. -/
noncomputable def gaugePull (U : specialUnitaryGroup (Fin 3) JetRing) :
    JetAlgebra →ₐ[ℝ] JetAlgebra :=
  (MvPolynomial.aeval (gaugeSubstGen U)).comp toPoly.toAlgHom

@[simp]
lemma gaugePull_ofGen (U : specialUnitaryGroup (Fin 3) JetRing) (g : JetGenerators) :
    gaugePull U (ofGen g) = gaugeSubstGen U g := by
  show MvPolynomial.aeval (gaugeSubstGen U) (toPoly (ofGen g)) = _
  rw [toPoly_ofGen, aeval_X]

lemma coordC_conjC_mkC (U : specialUnitaryGroup (Fin 3) JetRing) (t : DIdx) (f : Col → ℝ)
    (c : Col) :
    coordC c (conjC U t (mkC f)) = ∑ c', f c' * coordC c (conjC U t (colourBasis c')) := by
  rw [mkC_eq_sum, map_sum, map_sum]
  exact Finset.sum_congr rfl fun c' _ => by rw [map_smul, map_smul, smul_eq_mul]

/-- **The transformed point of the ordinary coordinate space**: build the generic potential, act
  by the honest affine power-series action, and read off the coordinates again. -/
noncomputable def actPtA (U : specialUnitaryGroup (Fin 3) JetRing)
    (x : JetGenerators → ℝ) : JetGenerators → ℝ := potPt (actPotC U (potOf x))

/-- **The substitution really is the coordinate form of the action.**  This is the all-orders
  analogue of `GaugeAction`'s `potCoord_actPot`. -/
lemma evalA_gaugeSubstGen (U : specialUnitaryGroup (Fin 3) JetRing) (x : JetGenerators → ℝ)
    (g : JetGenerators) : evalA x (gaugeSubstGen U g) = actPtA U x g := by
  cases g with
  | dA s μ c =>
    have hR : actPtA U x (JetGenerators.dA s μ c) =
        (∑ p ∈ Finset.antidiagonal s, facI s * ((facI p.1)⁻¹ *
            ∑ c', x (JetGenerators.dA p.1 μ c') *
              coordC c (conjC U p.2 (colourBasis c')))) +
          facI s * coordC c (mcCoeffCAt U μ s) := by
      show facI s * coordC c ((actPotC U (potOf x)).coeffC s μ) = _
      rw [coeffC_actPotC, map_add, map_sum, mul_add, Finset.mul_sum]
      refine congrArg₂ _ (Finset.sum_congr rfl fun p _ => ?_) rfl
      rw [coeffC_potOf, map_smul, map_smul, smul_eq_mul, cfgC, coordC_conjC_mkC]
    rw [hR, gaugeSubstGen, map_add, map_sum]
    refine congrArg₂ _ (Finset.sum_congr rfl fun p _ => ?_) ?_
    · rw [map_sum, Finset.mul_sum, Finset.mul_sum]
      refine Finset.sum_congr rfl fun c' _ => ?_
      rw [map_mul, evalA_algebraMap, genVec, evalA_ofGen]
      ring
    · rw [constR, evalA_algebraMap, map_smul, smul_eq_mul]

/-- **Faithfulness of the substitution.** -/
lemma evalA_gaugePull (U : specialUnitaryGroup (Fin 3) JetRing) (x : JetGenerators → ℝ)
    (P : JetAlgebra) : evalA x (gaugePull U P) = evalA (actPtA U x) P := by
  have h : (evalA x).comp (gaugePull U) = evalA (actPtA U x) :=
    jetAlgHom_ext fun g => by
      rw [AlgHom.comp_apply, gaugePull_ofGen, evalA_gaugeSubstGen, evalA_ofGen]
  exact DFunLike.congr_fun h P

@[simp]
lemma potOf_actPtA (U : specialUnitaryGroup (Fin 3) JetRing) (x : JetGenerators → ℝ) :
    potOf (actPtA U x) = actPotC U (potOf x) := by
  rw [actPtA, potOf_potPt]

lemma actPtA_one (x : JetGenerators → ℝ) :
    actPtA (1 : specialUnitaryGroup (Fin 3) JetRing) x = x := by
  rw [actPtA, actPotC_one, potPt_potOf]

/-- The transformed point is a **left** action, inherited from `actPot_mul`. -/
lemma actPtA_mul (U V : specialUnitaryGroup (Fin 3) JetRing) (x : JetGenerators → ℝ) :
    actPtA (U * V) x = actPtA U (actPtA V x) := by
  show potPt (actPotC (U * V) (potOf x)) = potPt (actPotC U (potOf (actPtA V x)))
  rw [potOf_actPtA, actPotC_mul]

/-- **The identity substitution.** -/
lemma gaugePull_one :
    gaugePull (1 : specialUnitaryGroup (Fin 3) JetRing) = AlgHom.id ℝ JetAlgebra := by
  refine AlgHom.ext fun P => jetAlgebra_funext fun x => ?_
  rw [evalA_gaugePull, actPtA_one, AlgHom.id_apply]

/-- **The composition law of the substitution.**  The raw substitution is pullback along a left
  action on points, so it composes *contravariantly*.  This is the orientation forced by the
  definitions; no covariant composition law holds for `gaugePull`. -/
lemma gaugePull_mul (U V : specialUnitaryGroup (Fin 3) JetRing) :
    gaugePull (U * V) = (gaugePull V).comp (gaugePull U) := by
  refine AlgHom.ext fun P => jetAlgebra_funext fun x => ?_
  rw [AlgHom.comp_apply, evalA_gaugePull, evalA_gaugePull, evalA_gaugePull, actPtA_mul]

/-!

## I. Degree-zero and degree-one agreement with `GaugeAction`

-/

lemma sum_coordC_adC {R : Type*} [CommRing R] [Algebra ℝ R]
    (u : specialUnitaryGroup (Fin 3) ℂ) (q : Col → R) (c : Col) :
    (∑ c', algebraMap ℝ R (coordC c (adC u (colourBasis c'))) * q c') = adR u q c :=
  Finset.sum_congr rfl fun c' _ => by rw [adCoef]

lemma sum_coordC_br_adC {R : Type*} [CommRing R] [Algebra ℝ R] (Y : ColourSpace)
    (u : specialUnitaryGroup (Fin 3) ℂ) (q : Col → R) (c : Col) :
    (∑ c', algebraMap ℝ R (coordC c (br Y (adC u (colourBasis c')))) * q c') =
      brR (constR Y) (adR u q) c := by
  rw [show (∑ c', algebraMap ℝ R (coordC c (br Y (adC u (colourBasis c')))) * q c') =
      ∑ c', ∑ a, ∑ b, (algebraMap ℝ R (coordC a Y) * algebraMap ℝ R (adCoef u b c') *
        algebraMap ℝ R (cstruct a b c)) * q c' from
    Finset.sum_congr rfl fun c' _ => by
      rw [coordC_br, map_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun a _ => ?_
      rw [map_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun b _ => ?_
      rw [map_mul, map_mul, adCoef], Finset.sum_comm, brR]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun b _ => ?_
  rw [constR, adR, Finset.mul_sum, Finset.mul_sum]
  exact Finset.sum_congr rfl fun c' _ => by ring

/-- **Degree-zero agreement with `GaugeAction`.**  On the connection generators the all-orders
  substitution
  is `GaugeAction`'s `gaugeSubst (Coord.conn μ c)`. -/
lemma gaugeSubstGen_zero (U : specialUnitaryGroup (Fin 3) JetRing) (μ : Lor) (c : Col) :
    gaugeSubstGen U (JetGenerators.dA 0 μ c) =
      adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec 0 μ) c + constR (mcC U μ) c := by
  rw [gaugeSubstGen, Finsupp.antidiagonal_zero, Finset.sum_singleton, mcCoeffCAt_zero, facI_zero,
    one_smul]
  refine congrArg₂ _ ?_ rfl
  refine (Finset.sum_congr rfl fun c' _ => ?_).trans (sum_coordC_adC _ (genVec 0 μ) c)
  simp only [inv_one, one_mul, conjC_zero]

/-- A sum over the antidiagonal of a degree-one multi-index has exactly two terms. -/
lemma sum_antidiagonal_single {M : Type*} [AddCommMonoid M] (ν : Lor) (f : DIdx × DIdx → M) :
    ∑ p ∈ Finset.antidiagonal (Finsupp.single ν 1 : DIdx), f p =
      f (0, Finsupp.single ν 1) + f (Finsupp.single ν 1, 0) := by
  rw [Finsupp.antidiagonal_single, show Finset.antidiagonal (1 : ℕ) = {(0, 1), (1, 0)} by decide,
    Finset.sum_map, Finset.sum_insert (by decide), Finset.sum_singleton]
  simp only [Function.Embedding.coe_prodMap, Function.Embedding.coeFn_mk, Prod.map_apply,
    Finsupp.single_zero]

/-- The degree-one coefficient conjugation is minus the colour bracket with the first
  Maurer–Cartan coefficient. -/
lemma conjC_single (U : specialUnitaryGroup (Fin 3) JetRing) (ν : Lor) (X : ColourSpace) :
    conjC U (Finsupp.single ν 1) X =
      -br (mcC U ν) (adC (JetGaugeGroupI.evalSU (Fin 3) U) X) := by
  apply cmat_injective
  have hu : Gluon.jetValue U.1 =
      ((JetGaugeGroupI.evalSU (Fin 3) U : specialUnitaryGroup (Fin 3) ℂ) :
        Matrix (Fin 3) (Fin 3) ℂ) := jetValue_coe_eq U
  show conjCoeffM U (Finsupp.single ν 1) (cmat X) =
    -brMat (cmat (mcC U ν)) (cmat (adC (JetGaugeGroupI.evalSU (Fin 3) U) X))
  rw [conjCoeffM, ← jetDeriv_eq_coeffMat, Gluon.jetDeriv_mul, Gluon.jetDeriv_mul, constMat,
    Gluon.jetDeriv_map_C, jetValue_map_C, Gluon.jetValue_mul, jetValue_map_C,
    Gluon.jetValue_star, jetDeriv_coe, jetDeriv_star_coe, cmat_mcC, cmat_adC, brMat, hu,
    star_eq_conjTranspose]
  simp only [Matrix.smul_mul, Matrix.mul_smul, Matrix.mul_zero, add_zero, Matrix.mul_assoc]
  module

/-- **Degree-one agreement with `GaugeAction`.**  On the first-derivative generators the all-orders
  substitution is `GaugeAction`'s `gaugeSubst (Coord.der ν μ c)`: conjugation by the base-point
  value, a
  bracket with the first Maurer–Cartan coefficient, and a translation by the second. -/
lemma gaugeSubstGen_single (U : specialUnitaryGroup (Fin 3) JetRing) (ν μ : Lor) (c : Col) :
    gaugeSubstGen U (JetGenerators.dA (Finsupp.single ν 1) μ c) =
      adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec (Finsupp.single ν 1) μ) c -
        brR (constR (mcC U ν)) (adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec 0 μ)) c +
        constR (mc2C U ν μ) c := by
  have e1 : (∑ c', algebraMap ℝ JetAlgebra
        (coordC c (conjC U (Finsupp.single ν 1) (colourBasis c'))) * genVec 0 μ c') =
      -brR (constR (mcC U ν)) (adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec 0 μ)) c := by
    calc (∑ c', algebraMap ℝ JetAlgebra
            (coordC c (conjC U (Finsupp.single ν 1) (colourBasis c'))) * genVec 0 μ c')
        = ∑ c', -(algebraMap ℝ JetAlgebra (coordC c (br (mcC U ν)
            (adC (JetGaugeGroupI.evalSU (Fin 3) U) (colourBasis c')))) * genVec 0 μ c') :=
          Finset.sum_congr rfl fun c' _ => by rw [conjC_single, map_neg, map_neg, neg_mul]
      _ = -∑ c', algebraMap ℝ JetAlgebra (coordC c (br (mcC U ν)
            (adC (JetGaugeGroupI.evalSU (Fin 3) U) (colourBasis c')))) * genVec 0 μ c' :=
          Finset.sum_neg_distrib _
      _ = -brR (constR (mcC U ν)) (adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec 0 μ)) c :=
          congrArg Neg.neg (sum_coordC_br_adC _ _ _ _)
  have e2 : (∑ c', algebraMap ℝ JetAlgebra (coordC c (conjC U 0 (colourBasis c'))) *
        genVec (Finsupp.single ν 1) μ c') =
      adR (JetGaugeGroupI.evalSU (Fin 3) U) (genVec (Finsupp.single ν 1) μ) c :=
    (Finset.sum_congr rfl fun c' _ => by rw [conjC_zero]).trans (sum_coordC_adC _ _ _)
  rw [gaugeSubstGen, sum_antidiagonal_single ν (fun p : DIdx × DIdx =>
      ∑ c', algebraMap ℝ JetAlgebra
          (facI (Finsupp.single ν 1) * (facI p.1)⁻¹ *
            coordC c (conjC U p.2 (colourBasis c'))) * genVec p.1 μ c')]
  simp only [facI_single, facI_zero, inv_one, one_mul, one_smul, mcCoeffCAt_single]
  rw [e1, e2]
  ring

end SU3Jet

end StandardModel
