/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Relativity.Fermions.Weyl.Metric
public import Mathlib.LinearAlgebra.CliffordAlgebra.Conjugation
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
public import Mathlib.LinearAlgebra.ExteriorAlgebra.OfAlternating
/-!

# The potential algebra of Weyl fermions

## i. Overview

Fermions anticommute. Thus a potential built out of a Weyl fermion is not a polynomial in the
components of that fermion, but an element of the exterior (Grassmann) algebra generated by them.

The `potentialAlgebra` is the exterior algebra generated by a left-handed Weyl fermion `ψ^α`
together with its conjugate, the right-handed Weyl fermion `ψ̄^{\dot α}`. It carries a `Star`
operation, which conjugates the fermions and reverses the order of the generators, and an action
of `SL(2,ℂ)`, the double cover of the Lorentz group.

A left-handed Weyl fermion of such a theory is a linear map
`LeftHandedWeyl →ₗ[ℂ] potentialAlgebra`. As an example we define the Majorana mass term of such a
fermion, and show that it is Lorentz invariant and fixed by the `Star` operation.

## ii. Key results

- `Fermion.LeftHandedWeyl.conjugate` : the conjugate of a left-handed Weyl fermion.
- `Fermion.potentialAlgebra` : the exterior algebra generated by `ψ^α` and `ψ̄^{\dot α}`.
- `Fermion.potentialAlgebra.instStarRing` : the star operation on the potential algebra.
- `Fermion.potentialAlgebra.rep` : the action of `SL(2,ℂ)` on the potential algebra.
- `Fermion.potentialAlgebra.majoranaMass` : the Majorana mass term of a left-handed Weyl fermion.
- `Fermion.potentialAlgebra.rep_majoranaMass` : the Majorana mass term is Lorentz invariant.
- `Fermion.potentialAlgebra.star_majoranaMass` : the Majorana mass term is real.

## iii. Table of contents

- A. Conjugation of Weyl fermions
  - A.1. The conjugate of a right-handed Weyl fermion
  - A.2. The conjugate of a left-handed Weyl fermion
  - A.3. Conjugation of the Weyl fermion generators
- B. The action of `SL(2,ℂ)` on the Weyl fermion generators
- C. The conjugate of a `ℂ`-algebra
- D. The potential algebra
  - D.1. Basic instances on the potential algebra
  - D.2. The generators of the potential algebra
- E. The star operation on the potential algebra
- F. The action of `SL(2,ℂ)` on the potential algebra
- G. Left-handed Weyl fermions of the theory
- H. The Majorana mass term

## iv. References

- Dreiner, Haber and Martin, *Two-component spinor techniques and Feynman rules for quantum field
  theory and supersymmetry*, https://arxiv.org/abs/0812.1594

-/

@[expose] public section

namespace Fermion
noncomputable section

open Module Matrix
open MatrixGroups
open Complex
open TensorProduct
open CategoryTheory.MonoidalCategory

/-!

## A. Conjugation of Weyl fermions

Complex conjugation of the components of a Weyl fermion exchanges left- and right-handed
Weyl fermions. It is a conjugate-linear map, that is, a semilinear map with respect to
`starRingEnd ℂ`.

-/

/-!

### A.1. The conjugate of a right-handed Weyl fermion

-/

namespace RightHandedWeyl

/-- The conjugate `ψ̄^α` of a right-handed Weyl fermion `ψ^{\dot α}`, defined by complex
  conjugating each component. It is a left-handed Weyl fermion. -/
def conjugate : RightHandedWeyl →ₛₗ[starRingEnd ℂ] LeftHandedWeyl where
  toFun ψ := ⟨fun i => star (ψ.val i)⟩
  map_add' ψ1 ψ2 := by
    apply LeftHandedWeyl.toFin2ℂFun.injective
    funext i
    exact star_add _ _
  map_smul' c ψ := by
    apply LeftHandedWeyl.toFin2ℂFun.injective
    funext i
    exact star_mul' c (ψ.val i)

@[simp]
lemma conjugate_val (ψ : RightHandedWeyl) (i : Fin 2) : (conjugate ψ).val i = star (ψ.val i) := rfl

/-- Conjugation intertwines the representation of `SL(2,ℂ)` on right-handed Weyl fermions with
  the representation on left-handed Weyl fermions. -/
lemma conjugate_rep (M : SL(2,ℂ)) (ψ : RightHandedWeyl) :
    conjugate (rep M ψ) = LeftHandedWeyl.rep M (conjugate ψ) := by
  apply LeftHandedWeyl.toFin2ℂFun.injective
  funext i
  change star ((M.1.map star *ᵥ ψ.val) i) = (M.1 *ᵥ fun j => star (ψ.val j)) i
  simp [mulVec, dotProduct, star_mul']

end RightHandedWeyl

/-!

### A.2. The conjugate of a left-handed Weyl fermion

-/

namespace LeftHandedWeyl

/-- The conjugate `ψ̄^{\dot α}` of a left-handed Weyl fermion `ψ^α`, defined by complex
  conjugating each component. It is a right-handed Weyl fermion. -/
def conjugate : LeftHandedWeyl →ₛₗ[starRingEnd ℂ] RightHandedWeyl where
  toFun ψ := ⟨fun i => star (ψ.val i)⟩
  map_add' ψ1 ψ2 := by
    apply RightHandedWeyl.toFin2ℂFun.injective
    funext i
    exact star_add _ _
  map_smul' c ψ := by
    apply RightHandedWeyl.toFin2ℂFun.injective
    funext i
    exact star_mul' c (ψ.val i)

@[simp]
lemma conjugate_val (ψ : LeftHandedWeyl) (i : Fin 2) : (conjugate ψ).val i = star (ψ.val i) := rfl

@[simp]
lemma conjugate_conjugate (ψ : LeftHandedWeyl) :
    RightHandedWeyl.conjugate (conjugate ψ) = ψ := by
  apply toFin2ℂFun.injective
  funext i
  exact star_star (ψ.val i)

/-- Conjugation intertwines the representation of `SL(2,ℂ)` on left-handed Weyl fermions with
  the representation on right-handed Weyl fermions. -/
lemma conjugate_rep (M : SL(2,ℂ)) (ψ : LeftHandedWeyl) :
    conjugate (rep M ψ) = RightHandedWeyl.rep M (conjugate ψ) := by
  apply RightHandedWeyl.toFin2ℂFun.injective
  funext i
  change star ((M.1 *ᵥ ψ.val) i) = (M.1.map star *ᵥ fun j => star (ψ.val j)) i
  simp [mulVec, dotProduct, star_mul']

end LeftHandedWeyl

@[simp]
lemma RightHandedWeyl.conjugate_conjugate (ψ : RightHandedWeyl) :
    LeftHandedWeyl.conjugate (conjugate ψ) = ψ := by
  apply toFin2ℂFun.injective
  funext i
  exact star_star (ψ.val i)

/-!

### A.3. Conjugation of the Weyl fermion generators

The generators of the potential algebra of a left-handed Weyl fermion `ψ^α` are the components
of `ψ^α` together with the components of its conjugate `ψ̄^{\dot α}`. They therefore live in
`LeftHandedWeyl × RightHandedWeyl`, on which conjugation acts by exchanging the two factors.

-/

/-- Conjugation of the pair `(ψ^α, ψ̄^{\dot α})` of Weyl fermion generators, exchanging the
  left-handed and the right-handed fermion. -/
def conjugateFields :
    LeftHandedWeyl × RightHandedWeyl →ₛₗ[starRingEnd ℂ] LeftHandedWeyl × RightHandedWeyl where
  toFun ψ := (RightHandedWeyl.conjugate ψ.2, LeftHandedWeyl.conjugate ψ.1)
  map_add' ψ φ := by simp
  map_smul' c ψ := by simp

@[simp]
lemma conjugateFields_apply (ψ : LeftHandedWeyl × RightHandedWeyl) :
    conjugateFields ψ = (RightHandedWeyl.conjugate ψ.2, LeftHandedWeyl.conjugate ψ.1) := rfl

@[simp]
lemma conjugateFields_conjugateFields (ψ : LeftHandedWeyl × RightHandedWeyl) :
    conjugateFields (conjugateFields ψ) = ψ := by
  simp

/-!

## B. The action of `SL(2,ℂ)` on the Weyl fermion generators

-/

/-- The representation of `SL(2,ℂ)` on the Weyl fermion generators `(ψ^α, ψ̄^{\dot α})`,
  acting by the fundamental representation on the left-handed fermion and by the conjugate
  representation on the right-handed fermion. -/
def repFields : Representation ℂ SL(2,ℂ) (LeftHandedWeyl × RightHandedWeyl) where
  toFun M := (LeftHandedWeyl.rep M).prodMap (RightHandedWeyl.rep M)
  map_one' := by
    refine LinearMap.ext fun ψ => ?_
    simp
  map_mul' M N := by
    refine LinearMap.ext fun ψ => ?_
    simp [Module.End.mul_apply]

@[simp]
lemma repFields_apply (M : SL(2,ℂ)) (ψ : LeftHandedWeyl × RightHandedWeyl) :
    repFields M ψ = (LeftHandedWeyl.rep M ψ.1, RightHandedWeyl.rep M ψ.2) := rfl

/-- Conjugation of the Weyl fermion generators commutes with the action of `SL(2,ℂ)`. -/
lemma conjugateFields_repFields (M : SL(2,ℂ)) (ψ : LeftHandedWeyl × RightHandedWeyl) :
    conjugateFields (repFields M ψ) = repFields M (conjugateFields ψ) := by
  simp [RightHandedWeyl.conjugate_rep, LeftHandedWeyl.conjugate_rep]

/-!

## C. The conjugate of a `ℂ`-algebra

To define a conjugate-linear algebra map out of an exterior algebra we use its universal property,
which produces `ℂ`-algebra maps. A conjugate-linear algebra map `A → A` is precisely a
`ℂ`-algebra map `A →ₐ[ℂ] ConjAlg A`, where `ConjAlg A` is `A` with the `ℂ`-action twisted by
complex conjugation.

-/

TODO "The construction `ConjAlg` of the conjugate of a `ℂ`-algebra is not specific to fermions.
  It should be generalised to an arbitrary star ring of scalars and moved to a mathematics file."

/-- The `ℂ`-algebra `A` with its `ℂ`-algebra structure twisted by complex conjugation.
  A conjugate-linear algebra map `A → A` is the same thing as a `ℂ`-algebra map
  `A →ₐ[ℂ] ConjAlg A`. -/
def ConjAlg (A : Type) : Type := A

namespace ConjAlg

variable {A : Type}

/-- The identity map from a `ℂ`-algebra to its conjugate. -/
def of (x : A) : ConjAlg A := x

/-- The identity map from the conjugate of a `ℂ`-algebra back to that algebra. -/
def val (x : ConjAlg A) : A := x

@[simp]
lemma val_of (x : A) : val (of x) = x := rfl

variable [Ring A]

instance : Ring (ConjAlg A) := inferInstanceAs (Ring A)

@[simp]
lemma val_add (x y : ConjAlg A) : val (x + y) = val x + val y := rfl

@[simp]
lemma val_mul (x y : ConjAlg A) : val (x * y) = val x * val y := rfl

variable [Algebra ℂ A]

instance : Algebra ℂ (ConjAlg A) :=
  RingHom.toAlgebra' ((algebraMap ℂ A).comp (starRingEnd ℂ) : ℂ →+* ConjAlg A)
    fun c x => Algebra.commutes ((starRingEnd ℂ) c) (val x)

@[simp]
lemma val_algebraMap (c : ℂ) :
    val (algebraMap ℂ (ConjAlg A) c) = algebraMap ℂ A ((starRingEnd ℂ) c) := rfl

lemma smul_of (c : ℂ) (x : A) : c • of x = of ((starRingEnd ℂ) c • x) := by
  rw [Algebra.smul_def, Algebra.smul_def]
  rfl

end ConjAlg

/-!

## D. The potential algebra

-/

/-- The potential algebra of a left-handed Weyl fermion `ψ^α`: the exterior (Grassmann) algebra
  generated by the components of `ψ^α` and of its conjugate `ψ̄^{\dot α}`.
  The potential of a theory of a single Weyl fermion is an element of this algebra. -/
def potentialAlgebra : Type := ExteriorAlgebra ℂ (LeftHandedWeyl × RightHandedWeyl)

namespace potentialAlgebra

/-!

### D.1. Basic instances on the potential algebra

-/

instance : Ring potentialAlgebra :=
  inferInstanceAs (Ring (ExteriorAlgebra ℂ (LeftHandedWeyl × RightHandedWeyl)))

instance : Algebra ℂ potentialAlgebra :=
  inferInstanceAs (Algebra ℂ (ExteriorAlgebra ℂ (LeftHandedWeyl × RightHandedWeyl)))

/-!

### D.2. The generators of the potential algebra

-/

/-- The inclusion of the Weyl fermion generators `(ψ^α, ψ̄^{\dot α})` into the potential
  algebra. -/
def ι : LeftHandedWeyl × RightHandedWeyl →ₗ[ℂ] potentialAlgebra := ExteriorAlgebra.ι ℂ

lemma ι_sq_zero (ψ : LeftHandedWeyl × RightHandedWeyl) : ι ψ * ι ψ = 0 :=
  ExteriorAlgebra.ι_sq_zero ψ

/-- The generators of the potential algebra anticommute, corresponding to the fact that
  fermions anticommute. -/
lemma ι_mul_ι_swap (ψ φ : LeftHandedWeyl × RightHandedWeyl) : ι ψ * ι φ = - (ι φ * ι ψ) := by
  have h := CliffordAlgebra.ι_mul_ι_add_swap
    (Q := (0 : QuadraticForm ℂ (LeftHandedWeyl × RightHandedWeyl))) ψ φ
  simp only [QuadraticMap.polar, QuadraticMap.zero_apply, sub_zero, map_zero] at h
  exact eq_neg_of_add_eq_zero_left h

/-- The generators of the potential algebra coming from the left-handed Weyl fermion `ψ^α`. -/
def ιLeft : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra := ι ∘ₗ LinearMap.inl ℂ _ _

/-- The generators of the potential algebra coming from the right-handed Weyl
  fermion `ψ̄^{\dot α}`. -/
def ιRight : RightHandedWeyl →ₗ[ℂ] potentialAlgebra := ι ∘ₗ LinearMap.inr ℂ _ _

lemma ιLeft_apply (ψ : LeftHandedWeyl) : ιLeft ψ = ι (ψ, 0) := rfl

lemma ιRight_apply (ψ : RightHandedWeyl) : ιRight ψ = ι (0, ψ) := rfl

/-- The potential algebra is generated, as an algebra, by the image of `ι`. -/
@[elab_as_elim]
lemma induction {C : potentialAlgebra → Prop}
    (algebraMap : ∀ c : ℂ, C (algebraMap ℂ potentialAlgebra c))
    (ι : ∀ ψ, C (potentialAlgebra.ι ψ))
    (mul : ∀ a b, C a → C b → C (a * b))
    (add : ∀ a b, C a → C b → C (a + b)) (x : potentialAlgebra) : C x :=
  ExteriorAlgebra.induction algebraMap ι mul add x

/-!

## E. The star operation on the potential algebra

The star operation on the potential algebra conjugates the Weyl fermions, exchanging `ψ^α` and
`ψ̄^{\dot α}`, and reverses the order of the Grassmann generators. The reversal is
`CliffordAlgebra.reverse`, and makes the star operation into an anti-automorphism.

-/

/-- Reversal of the order of the Grassmann generators in the potential algebra. -/
def reverse : potentialAlgebra →ₗ[ℂ] potentialAlgebra := CliffordAlgebra.reverse

@[simp]
lemma reverse_ι (ψ : LeftHandedWeyl × RightHandedWeyl) : reverse (ι ψ) = ι ψ :=
  CliffordAlgebra.reverse_ι ψ

@[simp]
lemma reverse_algebraMap (c : ℂ) :
    reverse (algebraMap ℂ potentialAlgebra c) = algebraMap ℂ potentialAlgebra c :=
  CliffordAlgebra.reverse.commutes c

@[simp]
lemma reverse_mul (x y : potentialAlgebra) : reverse (x * y) = reverse y * reverse x :=
  CliffordAlgebra.reverse.map_mul x y

/-- Conjugation of the Weyl fermions, as a `ℂ`-algebra map from the potential algebra to its
  conjugate algebra. Equivalently, a conjugate-linear algebra map on the potential algebra. -/
def conjHom : potentialAlgebra →ₐ[ℂ] ConjAlg potentialAlgebra :=
  ExteriorAlgebra.lift ℂ ⟨{
      toFun := fun ψ => ConjAlg.of (ι (conjugateFields ψ))
      map_add' := fun ψ φ => by
        rw [map_add, map_add]
        rfl
      map_smul' := fun c ψ => by
        rw [map_smulₛₗ, map_smul, RingHom.id_apply, ConjAlg.smul_of] },
    fun ψ => ι_sq_zero _⟩

@[simp]
lemma conjHom_ι (ψ : LeftHandedWeyl × RightHandedWeyl) :
    conjHom (ι ψ) = ConjAlg.of (ι (conjugateFields ψ)) :=
  ExteriorAlgebra.lift_ι_apply _ _ _ ψ

/-- The conjugation of an element of the potential algebra: conjugate the Weyl fermions and
  reverse the order of the Grassmann generators. -/
def conjugate (x : potentialAlgebra) : potentialAlgebra := reverse (ConjAlg.val (conjHom x))

lemma conjugate_ι (ψ : LeftHandedWeyl × RightHandedWeyl) :
    conjugate (ι ψ) = ι (conjugateFields ψ) := by
  show reverse (ConjAlg.val (conjHom (ι ψ))) = _
  rw [conjHom_ι, ConjAlg.val_of, reverse_ι]

lemma conjugate_algebraMap (c : ℂ) :
    conjugate (algebraMap ℂ potentialAlgebra c) =
      algebraMap ℂ potentialAlgebra ((starRingEnd ℂ) c) := by
  show reverse (ConjAlg.val (conjHom (algebraMap ℂ potentialAlgebra c))) = _
  rw [AlgHom.commutes, ConjAlg.val_algebraMap, reverse_algebraMap]

lemma conjugate_mul (x y : potentialAlgebra) :
    conjugate (x * y) = conjugate y * conjugate x := by
  show reverse (ConjAlg.val (conjHom (x * y))) = _
  rw [map_mul, ConjAlg.val_mul, reverse_mul]
  rfl

lemma conjugate_add (x y : potentialAlgebra) :
    conjugate (x + y) = conjugate x + conjugate y := by
  show reverse (ConjAlg.val (conjHom (x + y))) = _
  rw [map_add, ConjAlg.val_add, map_add]
  rfl

lemma conjugate_conjugate (x : potentialAlgebra) : conjugate (conjugate x) = x := by
  induction x using potentialAlgebra.induction with
  | algebraMap c => rw [conjugate_algebraMap, conjugate_algebraMap, starRingEnd_self_apply]
  | ι ψ => rw [conjugate_ι, conjugate_ι, conjugateFields_conjugateFields]
  | mul a b ha hb => rw [conjugate_mul, conjugate_mul, ha, hb]
  | add a b ha hb => rw [conjugate_add, conjugate_add, ha, hb]

instance instStarRing : StarRing potentialAlgebra where
  star := conjugate
  star_involutive := conjugate_conjugate
  star_mul := conjugate_mul
  star_add := conjugate_add

lemma star_def (x : potentialAlgebra) : star x = conjugate x := rfl

@[simp]
lemma star_ι (ψ : LeftHandedWeyl × RightHandedWeyl) : star (ι ψ) = ι (conjugateFields ψ) :=
  conjugate_ι ψ

@[simp]
lemma star_ιLeft (ψ : LeftHandedWeyl) : star (ιLeft ψ) = ιRight (LeftHandedWeyl.conjugate ψ) := by
  rw [ιLeft_apply, star_ι, ιRight_apply]
  simp

@[simp]
lemma star_ιRight (ψ : RightHandedWeyl) : star (ιRight ψ) = ιLeft (RightHandedWeyl.conjugate ψ) := by
  rw [ιRight_apply, star_ι, ιLeft_apply]
  simp

@[simp]
lemma star_algebraMap (c : ℂ) :
    star (algebraMap ℂ potentialAlgebra c) = algebraMap ℂ potentialAlgebra ((starRingEnd ℂ) c) :=
  conjugate_algebraMap c

/-- The star operation on the potential algebra is conjugate-linear. -/
instance : StarModule ℂ potentialAlgebra where
  star_smul c x := by
    rw [Algebra.smul_def, star_mul, star_algebraMap, ← Algebra.commutes, ← Algebra.smul_def]
    rfl

/-!

## F. The action of `SL(2,ℂ)` on the potential algebra

-/

/-- The representation of `SL(2,ℂ)`, the double cover of the Lorentz group, on the potential
  algebra, induced by its action on the Weyl fermion generators. -/
def rep : Representation ℂ SL(2,ℂ) potentialAlgebra where
  toFun M := (ExteriorAlgebra.map (repFields M)).toLinearMap
  map_one' := by
    refine LinearMap.ext fun x => ?_
    rw [map_one]
    simp [Module.End.one_eq_id]
    rfl
  map_mul' M N := by
    refine LinearMap.ext fun x => ?_
    rw [map_mul]
    exact (AlgHom.congr_fun (ExteriorAlgebra.map_comp_map _ _) x).symm

@[simp]
lemma rep_ι (M : SL(2,ℂ)) (ψ : LeftHandedWeyl × RightHandedWeyl) :
    rep M (ι ψ) = ι (repFields M ψ) :=
  ExteriorAlgebra.map_apply_ι _ _

@[simp]
lemma rep_mul (M : SL(2,ℂ)) (x y : potentialAlgebra) : rep M (x * y) = rep M x * rep M y :=
  map_mul (ExteriorAlgebra.map (repFields M)) x y

@[simp]
lemma rep_algebraMap (M : SL(2,ℂ)) (c : ℂ) :
    rep M (algebraMap ℂ potentialAlgebra c) = algebraMap ℂ potentialAlgebra c :=
  AlgHom.commutes (ExteriorAlgebra.map (repFields M)) c

@[simp]
lemma rep_ιLeft (M : SL(2,ℂ)) (ψ : LeftHandedWeyl) :
    rep M (ιLeft ψ) = ιLeft (LeftHandedWeyl.rep M ψ) := by
  rw [ιLeft_apply, rep_ι, ιLeft_apply]
  simp

/-- The star operation on the potential algebra commutes with the action of `SL(2,ℂ)`. -/
lemma rep_star (M : SL(2,ℂ)) (x : potentialAlgebra) : rep M (star x) = star (rep M x) := by
  induction x using potentialAlgebra.induction with
  | algebraMap c => rw [star_algebraMap, rep_algebraMap, rep_algebraMap, star_algebraMap]
  | ι ψ => rw [star_ι, rep_ι, rep_ι, star_ι, conjugateFields_repFields]
  | mul a b ha hb => rw [star_mul, rep_mul, rep_mul, ha, hb, star_mul]
  | add a b ha hb => rw [star_add, map_add, map_add, ha, hb, star_add]

/-!

## G. Left-handed Weyl fermions of the theory

A left-handed Weyl fermion of a theory whose potentials live in `potentialAlgebra` is a linear
map `ψ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra`, taking each spinor direction to a Grassmann-odd
element of the potential algebra. Such fermions carry the representation
`LeftHandedWeyl.rep.linHom rep` of `SL(2,ℂ)`. The tautological fermion is `ιLeft`, whose
components are the left-handed generators of the potential algebra.

-/

/-- The representation of `SL(2,ℂ)` on the left-handed Weyl fermions of the theory. -/
def repFermionLeft : Representation ℂ SL(2,ℂ) (LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :=
  LeftHandedWeyl.rep.linHom rep

lemma repFermionLeft_apply (M : SL(2,ℂ)) (ψ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    repFermionLeft M ψ = (rep M) ∘ₗ ψ ∘ₗ LeftHandedWeyl.rep M⁻¹ := rfl

/-- The tautological left-handed Weyl fermion, whose components are the left-handed generators
  of the potential algebra, is invariant under `SL(2,ℂ)`. -/
lemma repFermionLeft_ιLeft (M : SL(2,ℂ)) : repFermionLeft M ιLeft = ιLeft := by
  refine LinearMap.ext fun ψ => ?_
  rw [repFermionLeft_apply]
  simp only [LinearMap.comp_apply, rep_ιLeft, ← Module.End.mul_apply, ← map_mul,
    mul_inv_cancel, map_one, Module.End.one_apply]

/-!

## H. The Majorana mass term

The Majorana mass term of a left-handed Weyl fermion `ψ` is `m ε^{αβ} ψ_α ψ_β` plus its
conjugate. It is obtained by contracting the metric `ε` with two copies of `ψ` and multiplying
the resulting elements of the potential algebra. Since the components of `ψ` anticommute, the
bilinear does not vanish, and it is Lorentz invariant because the metric is.

-/

/-- The bilinear `ε^{αβ} ψ_α φ_β` of two left-handed Weyl fermions, obtained by contracting the
  metric `leftMetricVal` with `ψ` and `φ`, and multiplying the results in the potential
  algebra. -/
def leftBilinear (ψ φ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) : potentialAlgebra :=
  LinearMap.mul' ℂ potentialAlgebra (TensorProduct.map ψ φ leftMetricVal)

lemma leftBilinear_eq (ψ φ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    leftBilinear ψ φ = - (ψ (LeftHandedWeyl.basis 0) * φ (LeftHandedWeyl.basis 1))
      + ψ (LeftHandedWeyl.basis 1) * φ (LeftHandedWeyl.basis 0) := by
  rw [leftBilinear, leftMetricVal_expand_tmul]
  simp

/-- Acting with `SL(2,ℂ)` on the potential algebra can be moved through the bilinear. -/
lemma rep_leftBilinear (M : SL(2,ℂ)) (ψ φ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    rep M (leftBilinear ψ φ) = leftBilinear ((rep M) ∘ₗ ψ) ((rep M) ∘ₗ φ) := by
  simp [leftBilinear_eq, map_add, map_neg]

/-- Acting with `SL(2,ℂ)` on the spinor index of both fermions leaves the bilinear unchanged,
  since the metric `ε` is invariant. -/
lemma leftBilinear_comp_rep (M : SL(2,ℂ)) (ψ φ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    leftBilinear (ψ ∘ₗ LeftHandedWeyl.rep M) (φ ∘ₗ LeftHandedWeyl.rep M) = leftBilinear ψ φ := by
  rw [leftBilinear, leftBilinear, TensorProduct.map_comp, LinearMap.comp_apply, leftMetricVal_rep]

/-- The bilinear of two left-handed Weyl fermions transforms as a scalar of the potential
  algebra under `SL(2,ℂ)`. -/
lemma leftBilinear_repFermionLeft (M : SL(2,ℂ)) (ψ φ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    leftBilinear (repFermionLeft M ψ) (repFermionLeft M φ) = rep M (leftBilinear ψ φ) := by
  rw [repFermionLeft_apply, repFermionLeft_apply, ← rep_leftBilinear, leftBilinear_comp_rep]

/-- In terms of the basis, the bilinear of the tautological fermion with itself is
  `- 2 ψ^1 ψ^2`. It is non-zero precisely because the components of `ψ` anticommute. -/
lemma leftBilinear_ιLeft_eq_smul : leftBilinear ιLeft ιLeft =
    (-2 : ℂ) • (ιLeft (LeftHandedWeyl.basis 0) * ιLeft (LeftHandedWeyl.basis 1)) := by
  have h : ιLeft (LeftHandedWeyl.basis 1) * ιLeft (LeftHandedWeyl.basis 0) =
      - (ιLeft (LeftHandedWeyl.basis 0) * ιLeft (LeftHandedWeyl.basis 1)) :=
    ι_mul_ι_swap _ _
  rw [leftBilinear_eq, h]
  module

/-- The bilinear of the tautological fermion with itself is non-zero. For a commuting field the
  same expression would vanish by the antisymmetry of `ε`. -/
lemma leftBilinear_ιLeft_ne_zero : leftBilinear ιLeft ιLeft ≠ 0 := by
  /- The alternating form `(v, w) ↦ det ![v.1, w.1]` on the generators lifts to a linear
  functional on the potential algebra which is non-zero on the bilinear. -/
  let form : (LeftHandedWeyl × RightHandedWeyl) [⋀^Fin 2]→ₗ[ℂ] ℂ :=
    Matrix.detRowAlternating.compLinearMap
      (LeftHandedWeyl.toFin2ℂEquiv.toLinearMap ∘ₗ LinearMap.fst ℂ LeftHandedWeyl RightHandedWeyl)
  let f : ∀ i, (LeftHandedWeyl × RightHandedWeyl) [⋀^Fin i]→ₗ[ℂ] ℂ :=
    Function.update (fun _ => 0) 2 form
  have hprod : ιLeft (LeftHandedWeyl.basis 0) * ιLeft (LeftHandedWeyl.basis 1) =
      ExteriorAlgebra.ιMulti ℂ 2
        ![(LeftHandedWeyl.basis 0, 0), (LeftHandedWeyl.basis 1, 0)] := by
    rw [ExteriorAlgebra.ιMulti_apply]
    simp [ιLeft_apply, ι]
    rfl
  let F : potentialAlgebra →ₗ[ℂ] ℂ := ExteriorAlgebra.liftAlternating f
  have hmulti : F (ExteriorAlgebra.ιMulti ℂ 2
      ![(LeftHandedWeyl.basis 0, 0), (LeftHandedWeyl.basis 1, 0)]) = 1 := by
    show ExteriorAlgebra.liftAlternating f _ = 1
    rw [ExteriorAlgebra.liftAlternating_apply_ιMulti]
    simp only [f, Function.update_self, form, AlternatingMap.compLinearMap_apply]
    show Matrix.det _ = 1
    simp [Matrix.det_fin_two, LeftHandedWeyl.toFin2ℂFun, LeftHandedWeyl.basis_apply]
  have hF : F (leftBilinear ιLeft ιLeft) = -2 := by
    rw [leftBilinear_ιLeft_eq_smul, map_smul, hprod, hmulti, smul_eq_mul, mul_one]
  intro h
  rw [h, map_zero] at hF
  norm_num at hF

/-- The Majorana mass term, of complex mass `m`, of a left-handed Weyl fermion `ψ`. It is the sum
  of the bilinear `m ε^{αβ} ψ_α ψ_β` and its conjugate. -/
def majoranaMass (m : ℂ) (ψ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) : potentialAlgebra :=
  m • leftBilinear ψ ψ + star (m • leftBilinear ψ ψ)

/-- The Majorana mass term is real, that is, it is fixed by the star operation. -/
lemma star_majoranaMass (m : ℂ) (ψ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    star (majoranaMass m ψ) = majoranaMass m ψ := by
  rw [majoranaMass, star_add, star_star, add_comm]

/-- The Majorana mass term is Lorentz invariant: transforming the fermion by `M` is the same as
  transforming the resulting element of the potential algebra by `M`. -/
lemma rep_majoranaMass (M : SL(2,ℂ)) (m : ℂ) (ψ : LeftHandedWeyl →ₗ[ℂ] potentialAlgebra) :
    majoranaMass m (repFermionLeft M ψ) = rep M (majoranaMass m ψ) := by
  rw [majoranaMass, majoranaMass, leftBilinear_repFermionLeft, map_add, rep_star, map_smul]

/-- The Majorana mass term of the tautological left-handed Weyl fermion is invariant under the
  action of `SL(2,ℂ)` on the potential algebra. -/
lemma rep_majoranaMass_ιLeft (M : SL(2,ℂ)) (m : ℂ) :
    rep M (majoranaMass m ιLeft) = majoranaMass m ιLeft := by
  rw [← rep_majoranaMass, repFermionLeft_ιLeft]

end potentialAlgebra
end
end Fermion
