/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Matter.JetComponentSpace.CovariantDeriv
/-!
# The infinitesimal action underlying a matter representation

## i. Overview

The covariant derivative `∇_ρ F = D_ρ F + A_ρ · F` of a matter family is built from an
`ℝ`-bilinear action `act` of the gauge algebra on the value space. For the covariant
derivative to transform covariantly, `act` must be the *infinitesimal action* underlying
the representation `rep` of the jet gauge group in which the family transforms — the
physicists' statement that the matrices `i dρ(T^a)` generate `ρ`. This file packages
that compatibility as the structure `IsInfinitesimalActionOf`, and proves the theorem it
exists for: the covariant derivative preserves the gauge tensors,
`TransformsIn.covDerivAction`.

## ii. Key results

- `IsGaugeField.IsInfinitesimalActionOf` : `act` is the infinitesimal action underlying
  `rep`.
- `IsGaugeField.TransformsIn.covDerivAction` : the covariant derivative preserves
  `TransformsIn`.

## iii. Table of contents

- A. The infinitesimal action underlying a representation
- B. The covariant derivative preserves `TransformsIn`

-/

@[expose] public section

namespace StandardModel
open Matrix MatrixGroups TensorProduct MvPowerSeries
variable {B : Type} [Ring B] [Algebra ℂ B]
variable {V : Type} [AddCommGroup V] [Module ℂ V]

namespace IsGaugeField

variable {repLorentz : Representation ℂ SL(2,ℂ) B}
variable {repGauge : Representation ℂ JetGaugeGroupI B}
variable {A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}

/-!

## A. The infinitesimal action underlying a representation

-/

/-- `act` is the *infinitesimal action* of the gauge algebra underlying the
  representation `rep` of the jet gauge group, when the base-point Taylor
  coefficients of `rep` satisfy the two laws forced by `rep` being generated by
  `act`:

  * `repCoeff_cons` — the Leibniz rule in the Maurer–Cartan form: differentiating
    the representation once produces minus the action of the Maurer–Cartan form,
    with the remaining derivatives distributed over the antidiagonal (for the
    adjoint representation this is `adjointDualCoeff_cons`);
  * `repCoeff_act` — the transports of `rep` intertwine `act` with the adjoint
    transports, as an antidiagonal convolution (for the adjoint representation this
    is `adjointTransport_bracket`); at `x = 0` it is the classical equivariance
    `rep(U)|₀ ∘ act c = act (Ad(U) c)|₀ ∘ rep(U)|₀`.

  These are exactly the identities consumed by the proof that the covariant
  derivative `covDerivAction` preserves `TransformsIn`. -/
structure IsInfinitesimalActionOf (act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℝ] V)
    (rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)) : Prop where
  repCoeff_cons : ∀ (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3)
      (x : Multiset (Fin 1 ⊕ Fin 3)),
    repCoeff rep U (μ ::ₘ x) =
      -((x.antidiagonal.map fun p =>
        act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
          (maurerCartanForm U μ))) ∘ₗ repCoeff rep U p.2).sum)
  repCoeff_act : ∀ (U : JetGaugeGroupI) (x : Multiset (Fin 1 ⊕ Fin 3))
      (c : GaugeAlgebra),
    repCoeff rep U x ∘ₗ act c =
      ((x.antidiagonal.map fun p =>
        act (adjointCoeff U p.1 c) ∘ₗ repCoeff rep U p.2).sum)

/-- The dual form of the Leibniz law: the once-more-derived dual coefficient is
  minus the antidiagonal convolution of dual coefficients against `act` of the
  derived Maurer–Cartan form — the analogue of `adjointDualCoeff_cons`. -/
lemma IsInfinitesimalActionOf.repDualCoeff_cons
    {act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℝ] V}
    {rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)}
    (h : IsInfinitesimalActionOf act rep) (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3)
    (x : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ V) :
    repDualCoeff rep U (μ ::ₘ x) φ =
      -((x.antidiagonal.map fun p =>
        repDualCoeff rep U p.2 (φ ∘ₗ act (JetGaugeAlgebra.eval
          (JetGaugeAlgebra.iteratedDeriv p.1 (maurerCartanForm U μ))))).sum) := by
  refine LinearMap.ext fun v => ?_
  have h1 := LinearMap.congr_fun (h.repCoeff_cons U μ x) v
  simp only [LinearMap.neg_apply, Multiset.sum_linearMap_apply, Multiset.map_map,
    Function.comp_apply, LinearMap.coe_comp] at h1
  simp only [repDualCoeff, LinearMap.dualMap_apply, LinearMap.neg_apply,
    Multiset.sum_linearMap_apply, Multiset.map_map, Function.comp_apply,
    LinearMap.coe_comp]
  rw [h1, map_neg, map_multiset_sum, Multiset.map_map]
  exact congrArg Neg.neg (congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => rfl))

/-!

## B. The covariant derivative preserves `TransformsIn`

-/

section MatterCovariance

variable {rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)}
variable {act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℝ] V}
variable [FiniteDimensional ℝ V]

/-- The action of families against the dual representation coefficients: the
  antidiagonal convolution mixing the adjoint transport on the field slot with the
  representation transport on the matter slot — the family-level form of
  `IsInfinitesimalActionOf.repCoeff_act`, and the analogue of
  `bracketFam_adjointDualCoeff`. -/
lemma IsInfinitesimalActionOf.actionFam_repDualCoeff
    (h : IsInfinitesimalActionOf act rep) (U : JetGaugeGroupI)
    (x : Multiset (Fin 1 ⊕ Fin 3)) (f : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (g : Module.Dual ℝ V →ₗ[ℝ] B) (φ : Module.Dual ℝ V) :
    actionFam act f g (repDualCoeff rep U x φ) =
      (x.antidiagonal.map fun p =>
        actionFam act (f ∘ₗ adjointDualCoeff U p.1)
          (g ∘ₗ repDualCoeff rep U p.2) φ).sum := by
  have hT : ∀ (c : GaugeAlgebra) (v : V), repCoeff rep U x (act c v) =
      (x.antidiagonal.map fun p =>
        act (adjointCoeff U p.1 c) (repCoeff rep U p.2 v)).sum := by
    intro c v
    have h1 := LinearMap.congr_fun (h.repCoeff_act U x c) v
    simpa [Multiset.sum_linearMap_apply, Multiset.map_map, LinearMap.coe_comp,
      Function.comp_apply] using h1
  rw [show repDualCoeff rep U x = (repCoeff rep U x).dualMap from rfl,
    show actionFam act f g ((repCoeff rep U x).dualMap φ) =
      dualPairEquivW ((TensorProduct.map LinearMap.id (repCoeff rep U x))
        (tensorAction act (dualPairEquiv.symm f) (dualPairEquivW.symm g))) φ from
      (dualPairEquivW_map_right (repCoeff rep U x) _ φ).symm,
    ← tensorAction_map_right_antidiagonal act (adjointCoeff U) (repCoeff rep U) x hT,
    map_multiset_sum, Multiset.map_map, Multiset.sum_linearMap_apply, Multiset.map_map]
  refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
  simp only [Function.comp_apply]
  rw [← symm_comp_right, ← symm_comp_right_W]
  rfl


omit [FiniteDimensional ℝ V] in
/-- If `F` transforms in `rep`, so do its `κ ::ₘ s`-derived symbols, with the extra
  derivative traced through `IsInfinitesimalActionOf.repDualCoeff_cons`: the Leibniz
  splittings where `κ` stays a derivative, minus the convolution where `κ` hits the
  representation — `act` of the derived Maurer–Cartan form. -/
lemma TransformsIn.repGauge_cons
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ V →ₗ[ℝ] B}
    (hF : TransformsIn (repGauge := repGauge) rep F)
    (hact : IsInfinitesimalActionOf act rep)
    (U : JetGaugeGroupI) (κ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℝ V) :
    repGauge U (F (κ ::ₘ s) φ) =
      (s.antidiagonal.map fun p =>
        F (κ ::ₘ p.2) (repDualCoeff rep U⁻¹ p.1 φ)).sum
      - (s.antidiagonal.map fun p =>
          (p.1.antidiagonal.map fun q =>
            F p.2 (repDualCoeff rep U⁻¹ q.2
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
                (maurerCartanForm U⁻¹ κ)))))).sum).sum := by
  rw [hF U φ (κ ::ₘ s)]
  simp only [Multiset.antidiagonal_cons, Multiset.map_add, Multiset.sum_add,
    Multiset.map_map, Function.comp_apply, Prod.map_fst, Prod.map_snd, id_eq]
  have hsec : (Multiset.map (fun p =>
        F p.2 (repDualCoeff rep U⁻¹ (κ ::ₘ p.1) φ)) s.antidiagonal).sum =
      -(s.antidiagonal.map fun p =>
          (p.1.antidiagonal.map fun q =>
            F p.2 (repDualCoeff rep U⁻¹ q.2
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
                (maurerCartanForm U⁻¹ κ)))))).sum).sum := by
    rw [← Multiset.sum_map_neg'']
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [hact.repDualCoeff_cons U⁻¹ κ p.1 φ, map_neg, map_multiset_sum, Multiset.map_map]
    exact congrArg Neg.neg (congrArg Multiset.sum (Multiset.map_congr rfl fun q hq => rfl))
  rw [hsec, sub_eq_add_neg]

set_option maxHeartbeats 2000000 in
/-- The all-orders gauge transformation of the derived action `A_ρ · F` for `F`
  transforming in `rep`: since `F` transforms homogeneously, only one cross-term
  convolution through `act` survives — the analogue of
  `TransformsInAdjoint.repGauge_bracketFamConv` with a matter field in the second
  slot. -/
lemma TransformsIn.repGauge_actionFamConv
    (hA : IsGaugeField repLorentz repGauge A)
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ V →ₗ[ℝ] B}
    (hF : TransformsIn (repGauge := repGauge) rep F)
    (hact : IsInfinitesimalActionOf act rep)
    (U : JetGaugeGroupI) (s : Multiset (Fin 1 ⊕ Fin 3)) (ρ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ V) :
    repGauge U (actionFamConv A act ρ F s φ) =
      (s.antidiagonal.map fun p =>
        actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum
      + (s.antidiagonal.map fun p =>
          (p.2.antidiagonal.map fun r =>
            F r.2 (repDualCoeff rep U⁻¹ r.1
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
                (maurerCartanForm U⁻¹ ρ)))))).sum).sum := by
  have hAlaw : ∀ (u : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℝ GaugeAlgebra),
      repGauge U (A u ρ ψ) =
        ((u.antidiagonal.map fun q => A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1).sum) ψ
        + algebraMap ℂ B (ψ (JetGaugeAlgebra.eval
            (JetGaugeAlgebra.iteratedDeriv u (maurerCartanForm U⁻¹ ρ)))) := by
    intro u ψ
    rw [hA.gauge_apply_deriv U u ρ ψ, Multiset.sum_linearMap_apply, Multiset.map_map]
    congr 1
  have hFlaw : ∀ (u : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℝ V),
      repGauge U (F u ψ) =
        ((u.antidiagonal.map fun r => F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum) ψ := by
    intro u ψ
    rw [hF U ψ u, Multiset.sum_linearMap_apply, Multiset.map_map]
    congr 1
  have hMa : (s.antidiagonal.map fun p =>
      actionFam act ((p.1.antidiagonal.map fun q =>
          A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1).sum)
        ((p.2.antidiagonal.map fun r =>
          F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum) φ).sum =
      (s.antidiagonal.map fun p =>
        (p.1.antidiagonal.map fun q =>
          (p.2.antidiagonal.map fun r =>
            actionFam act (A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1)
              (F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1) φ).sum).sum).sum := by
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [actionFam_sum_left, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun q hq => ?_)
    simp only [Function.comp_apply]
    rw [actionFam_sum_right, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun r hr => ?_)
    simp only [Function.comp_apply]
  have hMc : (s.antidiagonal.map fun p =>
      actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum =
      (s.antidiagonal.map fun p =>
        (p.1.antidiagonal.map fun q =>
          (p.2.antidiagonal.map fun r =>
            actionFam act (A r.1 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1)
              (F r.2 ∘ₗ repDualCoeff rep U⁻¹ q.2) φ).sum).sum).sum := by
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [actionFamConv, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_congr rfl (fun r hr => by
        rw [Function.comp_apply,
          hact.actionFam_repDualCoeff U⁻¹ p.1 (A r.1 ρ) (F r.2) φ]),
      Multiset.sum_map_sum_map]
  have hM := hMa.trans ((Multiset.sum_antidiagonal_exchange s fun a b c d =>
      actionFam act (A b ρ ∘ₗ adjointDualCoeff U⁻¹ a)
        (F d ∘ₗ repDualCoeff rep U⁻¹ c) φ).trans hMc.symm)
  have hCg : ∀ p : Multiset (Fin 1 ⊕ Fin 3) × Multiset (Fin 1 ⊕ Fin 3),
      ((p.2.antidiagonal.map fun r => F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum)
        (φ ∘ₗ act (JetGaugeAlgebra.eval
          (JetGaugeAlgebra.iteratedDeriv p.1 (maurerCartanForm U⁻¹ ρ)))) =
      (p.2.antidiagonal.map fun r =>
        F r.2 (repDualCoeff rep U⁻¹ r.1
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
            (maurerCartanForm U⁻¹ ρ)))))).sum := by
    intro p
    rw [Multiset.sum_linearMap_apply, Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun r hr => ?_)
    simp only [Function.comp_apply, LinearMap.coe_comp]
  rw [actionFamConv, Multiset.sum_linearMap_apply, Multiset.map_map, map_multiset_sum,
    Multiset.map_map,
    Multiset.map_congr rfl (fun p hp => by
      rw [Function.comp_apply, Function.comp_apply,
        repGauge_actionFam hA U (hAlaw p.1) (hFlaw p.2) φ, hCg p]),
    Multiset.sum_map_add, hM]

set_option maxHeartbeats 2000000 in
/-- **The covariant derivative preserves `TransformsIn`**: if `F` transforms in the
  representation `rep` and `act` is the infinitesimal action underlying `rep`, then
  `∇_ρ F = [∂_ρ F] + A_ρ · F` transforms in `rep`. The single inhomogeneous
  convolution of `[∂_{ρ ::ₘ s} F]` cancels the single `act` cross-term convolution of
  `A_ρ · F` through the coassociativity of the antidiagonal — the matter-field
  analogue of `TransformsInAdjoint.covDerivAdjoint`. -/
theorem TransformsIn.covDerivAction
    (hA : IsGaugeField repLorentz repGauge A)
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ V →ₗ[ℝ] B}
    (hF : TransformsIn (repGauge := repGauge) rep F)
    (hact : IsInfinitesimalActionOf act rep) (ρ : Fin 1 ⊕ Fin 3) :
    TransformsIn (repGauge := repGauge) rep (IsGaugeField.covDerivAction A act F ρ) := by
  intro U φ s
  have hL : repGauge U (IsGaugeField.covDerivAction A act F ρ s φ) =
      repGauge U (F (ρ ::ₘ s) φ) + repGauge U (actionFamConv A act ρ F s φ) := by
    rw [covDerivAction_apply, map_add]
  have hR : (s.antidiagonal.map fun p =>
      IsGaugeField.covDerivAction A act F ρ p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum =
      (s.antidiagonal.map fun p =>
        F (ρ ::ₘ p.2) (repDualCoeff rep U⁻¹ p.1 φ)).sum
      + (s.antidiagonal.map fun p =>
        actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum := by
    rw [← Multiset.sum_map_add]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [covDerivAction_apply]
  have hcancel : (s.antidiagonal.map fun p =>
      (p.1.antidiagonal.map fun q =>
        F p.2 (repDualCoeff rep U⁻¹ q.2
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
            (maurerCartanForm U⁻¹ ρ)))))).sum).sum =
    (s.antidiagonal.map fun p =>
      (p.2.antidiagonal.map fun r =>
        F r.2 (repDualCoeff rep U⁻¹ r.1
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
            (maurerCartanForm U⁻¹ ρ)))))).sum).sum :=
    Multiset.sum_antidiagonal_assoc s (fun a b c =>
      F c (repDualCoeff rep U⁻¹ b
        (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv a
          (maurerCartanForm U⁻¹ ρ))))))
  rw [hL, hF.repGauge_cons hact U ρ s φ, hF.repGauge_actionFamConv hA hact U s ρ φ,
    hR, hcancel]
  abel

end MatterCovariance

end IsGaugeField

end StandardModel