/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsHiggsSector.MassWeight.Basic
public import Physlib.Particles.StandardModel.IsHiggsSector.DerivSubmodule.GaugeWeightDecomposition
/-!
# The gauge weight decomposition of the Higgs mass-weight submodules

Each mass-weight submodule of the Higgs sector up to weight eight has an explicit
description in terms of the derivative submodules `derivSubmodule n`, and each derivative
submodule carries a gauge weight decomposition.  Transporting the latter along the former
decomposes every mass-weight submodule up to weight eight.

The weights carried by a derivative submodule are the four weights of the Higgs doublet
and its conjugate, `(0, 0, ∓1, -3)` and `(0, 0, ±1, 3)`.  Every one of them has
hypercharge `± 3`, so a product of `k` derivative submodules can only reach gauge weight
zero when `k` is even and the Higgs and conjugate-Higgs factors are equally many.  This
is what makes the weight-zero pieces small: at mass weight four and six they are spanned
by the isospin-diagonal pairings `∇H^i ∇H̄^i`, and at mass weight eight the quartic
monomials `∇H^i ∇H̄^i ∇H^j ∇H̄^j` join them.

Section A gives the decompositions themselves, section B reads off the pieces of a single
derivative submodule, section C computes the weight-zero pieces of the products of
derivative submodules that occur, and section D assembles these into the weight-zero piece
of each mass-weight submodule up to weight eight.  Section E turns those into a sieve on
the gauge invariants.

The gauge weight alone cannot finish the job: it cannot separate the isospin singlet
`∇H · ∇H̄` from the neutral component of the isospin triplet, which carries the same
weight.  Sections F to H refine the weight-zero pieces by the Weyl element of `SU(2)`,
which does separate the two, and section I removes the one combination that survives both
gradings — the square of the neutral triplet component — by averaging over the cyclic
group generated by a quarter turn about the diagonal isospin axis.  Section J assembles
the resulting descriptions of the gauge invariants up to mass weight eight.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace IsHiggsSector

set_option linter.unusedVariables false

variable {B : Type} [Ring B] [Algebra ℂ B]
  {rep : Representation ℂ GaugeGroupI B}
  {hrep_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B), rep g (b₁ * b₂) = rep g b₁ * rep g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {H : (n : ℕ) → (Fin n → (Fin 1 ⊕ Fin 3)) → Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : (n : ℕ) → (Fin n → (Fin 1 ⊕ Fin 3)) →
    Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsHiggsSector B rep hrep_mul repLorentz hrepLorentz_mul H barH
      massWeightPoly)

/-!

## A. The decompositions

Every term of the Higgs algebra has even mass weight, so the odd mass-weight submodules
vanish and are decomposed by the empty decomposition.  The even ones are built from the
derivative submodules by the descriptions of `MassWeight.Basic`: weight two is a single
derivative submodule, and the higher weights add the products which distribute the mass
weight over several towers.

-/

/-- The odd mass-weight submodules are trivial, so they carry the empty decomposition. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightOdd (n : ℕ) (hn : Odd n) :
    GaugeWeightDecomposition rep (h.massWeightSubmodule n) :=
  GaugeWeightDecomposition.copy (GaugeWeightDecomposition.bot h.rep_mul) _
    (h.massWeightSubmodule_odd_eq_bot n hn)

/-- Weight one is trivial. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightOne :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 1) :=
  h.massWeightSubmoduleGaugeWeightOdd 1 (by decide)

/-- Weight two is the underived Higgs tower. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightTwo :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 2) :=
  GaugeWeightDecomposition.copy (h.derivSubmoduleGaugeWeight 0) _
    h.massWeightSubmodule_two_eq_deriv

/-- Weight three is trivial. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightThree :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 3) :=
  h.massWeightSubmoduleGaugeWeightOdd 3 (by decide)

/-- Weight four is the once-derived tower together with the products of two underived
  ones. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightFour :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 4) :=
  GaugeWeightDecomposition.copy
    (GaugeWeightDecomposition.sup (d := h.derivSubmoduleGaugeWeight 1)
      (d' := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 0)
        (d' := h.derivSubmoduleGaugeWeight 0))) _
    h.massWeightSubmodule_four_eq_deriv

/-- Weight five is trivial. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightFive :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 5) :=
  h.massWeightSubmoduleGaugeWeightOdd 5 (by decide)

/-- Weight six is the twice-derived tower, the once-derived tower against an underived
  one, and the products of three underived ones. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightSix :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 6) :=
  GaugeWeightDecomposition.copy
    (GaugeWeightDecomposition.sup
      (d := GaugeWeightDecomposition.sup (d := h.derivSubmoduleGaugeWeight 2)
        (d' := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 1)
          (d' := h.derivSubmoduleGaugeWeight 0)))
      (d' := GaugeWeightDecomposition.mul
        (d := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 0)
          (d' := h.derivSubmoduleGaugeWeight 0))
        (d' := h.derivSubmoduleGaugeWeight 0))) _
    h.massWeightSubmodule_six_eq_deriv

/-- Weight seven is trivial. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightSeven :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 7) :=
  h.massWeightSubmoduleGaugeWeightOdd 7 (by decide)

/-- Weight eight: the thrice-derived tower, the two ways of splitting the derivatives over
  two towers, the once-derived tower against two underived ones, and the products of four
  underived ones. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeightEight :
    GaugeWeightDecomposition rep (h.massWeightSubmodule 8) :=
  GaugeWeightDecomposition.copy
    (GaugeWeightDecomposition.sup
      (d := GaugeWeightDecomposition.sup
        (d := GaugeWeightDecomposition.sup
          (d := GaugeWeightDecomposition.sup (d := h.derivSubmoduleGaugeWeight 3)
            (d' := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 2)
              (d' := h.derivSubmoduleGaugeWeight 0)))
          (d' := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 1)
            (d' := h.derivSubmoduleGaugeWeight 1)))
        (d' := GaugeWeightDecomposition.mul
          (d := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 1)
            (d' := h.derivSubmoduleGaugeWeight 0))
          (d' := h.derivSubmoduleGaugeWeight 0)))
      (d' := GaugeWeightDecomposition.mul
        (d := GaugeWeightDecomposition.mul
          (d := GaugeWeightDecomposition.mul (d := h.derivSubmoduleGaugeWeight 0)
            (d' := h.derivSubmoduleGaugeWeight 0))
          (d' := h.derivSubmoduleGaugeWeight 0))
        (d' := h.derivSubmoduleGaugeWeight 0))) _
    h.massWeightSubmodule_eight_eq_deriv

/-!

## B. The pieces of a derivative submodule

A derivative submodule is the join of a Higgs and a conjugate-Higgs submodule, and each of
those is concentrated in two weights.  The four weights are distinct, so each piece of the
join is the span of one of the four families of symbols, and every other weight — the zero
weight in particular — has vanishing piece.

-/

/-- The weight-`w` piece of a derivative submodule, as the join of the Higgs and
  conjugate-Higgs pieces. -/
lemma derivSubmoduleGaugeWeight_piece_eq (n : ℕ) (w : GaugeWeight) :
    (h.derivSubmoduleGaugeWeight n).piece w
      = (if w = ((0, 0, -1, -3) : GaugeWeight) then
          ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.higgs d 0
        else if w = ((0, 0, 1, -3) : GaugeWeight) then
          ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.higgs d 1
        else ⊥)
        ⊔ (if w = ((0, 0, 1, 3) : GaugeWeight) then
            ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.barHiggs d 0
          else if w = ((0, 0, -1, 3) : GaugeWeight) then
            ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.barHiggs d 1
          else ⊥) := rfl

/-- The piece at the weight of the upper Higgs component. -/
lemma derivSubmoduleGaugeWeight_piece_higgs_zero (n : ℕ) :
    (h.derivSubmoduleGaugeWeight n).piece (0, 0, -1, -3)
      = ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.higgs d 0 := by
  rw [h.derivSubmoduleGaugeWeight_piece_eq, if_pos rfl, if_neg (by decide),
    if_neg (by decide), sup_bot_eq]

/-- The piece at the weight of the lower Higgs component. -/
lemma derivSubmoduleGaugeWeight_piece_higgs_one (n : ℕ) :
    (h.derivSubmoduleGaugeWeight n).piece (0, 0, 1, -3)
      = ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.higgs d 1 := by
  rw [h.derivSubmoduleGaugeWeight_piece_eq, if_neg (by decide), if_pos rfl,
    if_neg (by decide), if_neg (by decide), sup_bot_eq]

/-- The piece at the weight of the upper conjugate-Higgs component. -/
lemma derivSubmoduleGaugeWeight_piece_barHiggs_zero (n : ℕ) :
    (h.derivSubmoduleGaugeWeight n).piece (0, 0, 1, 3)
      = ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.barHiggs d 0 := by
  rw [h.derivSubmoduleGaugeWeight_piece_eq, if_neg (by decide), if_neg (by decide),
    if_pos rfl, bot_sup_eq]

/-- The piece at the weight of the lower conjugate-Higgs component. -/
lemma derivSubmoduleGaugeWeight_piece_barHiggs_one (n : ℕ) :
    (h.derivSubmoduleGaugeWeight n).piece (0, 0, -1, 3)
      = ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), ℂ ∙ h.barHiggs d 1 := by
  rw [h.derivSubmoduleGaugeWeight_piece_eq, if_neg (by decide), if_neg (by decide),
    if_neg (by decide), if_pos rfl, bot_sup_eq]

/-- A derivative submodule has no weight-zero content: every Higgs symbol carries
  hypercharge. -/
lemma derivSubmoduleGaugeWeight_piece_zero (n : ℕ) :
    (h.derivSubmoduleGaugeWeight n).piece 0 = ⊥ :=
  (h.derivSubmoduleGaugeWeight n).piece_eq_zero_of_not_mem_supp 0
    (by rw [h.derivSubmoduleGaugeWeight_supp]; decide)

/-!

## C. The weight-zero pieces of the products

Two derivative submodules pair to weight zero exactly by matching a Higgs symbol against a
conjugate-Higgs symbol of the same isospin component, in either order, so the weight-zero
piece of such a product is a join of four spans of pairings `∇H^i ∇H̄^i`.  Three of them
cannot reach weight zero at all, because hypercharge is `± 3` on every generator, so an odd
number of factors leaves an odd multiple of three.  Four of them reach weight zero on the
three quartic monomials.

-/

/-- The span of the isospin-diagonal pairings of a Higgs symbol carrying `n` derivatives
  with a conjugate-Higgs symbol carrying `m` derivatives, at isospin component `i`. -/
noncomputable def higgsBarHiggsSpan (h : IsHiggsSector B rep hrep_mul repLorentz
      hrepLorentz_mul H barH massWeightPoly) (n m : ℕ) (i : Fin 2) : Submodule ℂ B :=
  ⨆ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
    ℂ ∙ (h.higgs d i * h.barHiggs d' i)

/-- The span of the underived quartic monomial pairing the isospin components `i` and
  `j`. -/
noncomputable def quarticSpan (h : IsHiggsSector B rep hrep_mul repLorentz
      hrepLorentz_mul H barH massWeightPoly) (i j : Fin 2) : Submodule ℂ B :=
  ℂ ∙ (h.higgs ![] i * h.barHiggs ![] i * h.higgs ![] j * h.barHiggs ![] j)

/-- The weight-zero piece of a product of two derivative submodules: the isospin-diagonal
  pairings, taken in both orders of the two towers. -/
lemma derivSubmodule_mul_piece_zero (n m : ℕ) :
    GaugeWeightDecomposition.piece rep (h.derivSubmodule n * h.derivSubmodule m) 0
      = h.higgsBarHiggsSpan n m 0 ⊔ h.higgsBarHiggsSpan n m 1
        ⊔ h.higgsBarHiggsSpan m n 0 ⊔ h.higgsBarHiggsSpan m n 1 := by
  rw [GaugeWeightDecomposition.mul_piece_eq_sub 0, h.derivSubmoduleGaugeWeight_supp n]
  simp only [Finset.iSup_insert, Finset.iSup_singleton,
    show (0 : GaugeWeight) - (0, 0, -1, -3) = (0, 0, 1, 3) from by decide,
    show (0 : GaugeWeight) - (0, 0, 1, -3) = (0, 0, -1, 3) from by decide,
    show (0 : GaugeWeight) - (0, 0, 1, 3) = (0, 0, -1, -3) from by decide,
    show (0 : GaugeWeight) - (0, 0, -1, 3) = (0, 0, 1, -3) from by decide,
    h.derivSubmoduleGaugeWeight_piece_higgs_zero,
    h.derivSubmoduleGaugeWeight_piece_higgs_one,
    h.derivSubmoduleGaugeWeight_piece_barHiggs_zero,
    h.derivSubmoduleGaugeWeight_piece_barHiggs_one]
  have hcomm : ∀ {n1 n2 : ℕ} (d1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (d2 : Fin n2 → (Fin 1 ⊕ Fin 3))
      (a b : Fin 2), h.barHiggs d1 a * h.higgs d2 b = h.higgs d2 b * h.barHiggs d1 a :=
    fun d1 d2 a b => ((h.H_comm_barH _ _ _ _ _ _).symm).eq
  simp only [Submodule.iSup_mul, Submodule.mul_iSup, Submodule.span_mul_span,
    Set.singleton_mul_singleton, hcomm]
  simp only [higgsBarHiggsSpan, sup_assoc]
  refine congrArg₂ (· ⊔ ·) iSup_comm (congrArg₂ (· ⊔ ·) iSup_comm rfl)

/-- A product of three derivative submodules has no weight-zero content: the hypercharge of
  three Higgs generators is an odd multiple of three. -/
lemma derivSubmodule_mul_mul_piece_zero (n m k : ℕ) :
    GaugeWeightDecomposition.piece rep
      (h.derivSubmodule n * h.derivSubmodule m * h.derivSubmodule k) 0 = ⊥ := by
  refine GaugeWeightDecomposition.piece_eq_zero_of_not_mem_supp _ 0 ?_
  rw [GaugeWeightDecomposition.mul_supp, GaugeWeightDecomposition.mul_supp,
    h.derivSubmoduleGaugeWeight_supp n, h.derivSubmoduleGaugeWeight_supp m,
    h.derivSubmoduleGaugeWeight_supp k]
  decide

set_option maxHeartbeats 1000000 in
/-- The weight-zero piece of the product of four underived derivative submodules: the three
  quartic monomials, the ones pairing two Higgs symbols against two conjugate ones with
  matching isospin. -/
lemma derivSubmodule_zero_pow_four_piece_zero :
    GaugeWeightDecomposition.piece rep
      (h.derivSubmodule 0 * h.derivSubmodule 0 * h.derivSubmodule 0
        * h.derivSubmodule 0) 0
      = h.quarticSpan 0 0 ⊔ h.quarticSpan 0 1 ⊔ h.quarticSpan 1 1 := by
  have hbh : ∀ (a b : Fin 2),
      h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) a * h.higgs ![] b
        = h.higgs ![] b * h.barHiggs ![] a := fun a b => (h.H_comm_barH _ _ _ _ _ _).symm.eq
  have hbh' : ∀ (a b : Fin 2) (y : B),
      h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) a * (h.higgs ![] b * y)
        = h.higgs ![] b * (h.barHiggs ![] a * y) := fun a b y => by
    rw [← mul_assoc, hbh, mul_assoc]
  have hhh : h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 1 * h.higgs ![] 0
      = h.higgs ![] 0 * h.higgs ![] 1 := (h.H_comm_H _ _ _ _ _ _).eq
  have hhh' : ∀ y : B, h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 1 * (h.higgs ![] 0 * y)
      = h.higgs ![] 0 * (h.higgs ![] 1 * y) := fun y => by rw [← mul_assoc, hhh, mul_assoc]
  have hbb : h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 1 * h.barHiggs ![] 0
      = h.barHiggs ![] 0 * h.barHiggs ![] 1 := (h.barH_comm_barH _ _ _ _ _ _).eq
  simp +decide only [GaugeWeightDecomposition.mul_piece_eq_sub',
    h.derivSubmoduleGaugeWeight_supp 0, Finset.iSup_insert, Finset.iSup_singleton,
    h.derivSubmoduleGaugeWeight_piece_eq, if_true, if_false, bot_sup_eq, sup_bot_eq,
    Submodule.bot_mul]
  simp only [Matrix.empty_eq, ciSup_unique, quarticSpan, Submodule.sup_mul,
    Submodule.span_mul_span, Set.singleton_mul_singleton, mul_assoc, hbh, hbh', hhh,
    hhh', hbb]
  generalize (ℂ ∙ (h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 0 *
    (h.higgs ![] 0 * (h.barHiggs ![] 0 * h.barHiggs ![] 0)))) = A
  generalize (ℂ ∙ (h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 0 *
    (h.higgs ![] 1 * (h.barHiggs ![] 0 * h.barHiggs ![] 1)))) = C
  generalize (ℂ ∙ (h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) 1 *
    (h.higgs ![] 1 * (h.barHiggs ![] 1 * h.barHiggs ![] 1)))) = D
  simp only [sup_comm, sup_left_comm, sup_idem, sup_left_idem]

/-!

## D. The weight-zero pieces of the mass-weight submodules

Assembling section C along the descriptions of section A gives the weight-zero piece of
each mass-weight submodule up to weight eight.  The odd weights and weight two are trivial,
weight four is the underived pairing, weight six adds the pairings with one derivative on
either factor, and weight eight adds the pairings with two derivatives, those with one
derivative on each factor, and the three quartic monomials.

-/

/-- The weight-zero piece at an odd mass weight: the submodule itself is trivial. -/
lemma massWeightSubmoduleGaugeWeightOdd_piece_zero (n : ℕ) (hn : Odd n) :
    (h.massWeightSubmoduleGaugeWeightOdd n hn).piece 0 = ⊥ := rfl

/-- The weight-zero piece at mass weight two: a single Higgs symbol carries
  hypercharge. -/
lemma massWeightSubmoduleGaugeWeightTwo_piece_zero :
    (h.massWeightSubmoduleGaugeWeightTwo).piece 0 = ⊥ :=
  h.derivSubmoduleGaugeWeight_piece_zero 0

/-- The weight-zero piece at mass weight four: the underived isospin-diagonal pairings. -/
lemma massWeightSubmoduleGaugeWeightFour_piece_zero :
    (h.massWeightSubmoduleGaugeWeightFour).piece 0
      = h.higgsBarHiggsSpan 0 0 0 ⊔ h.higgsBarHiggsSpan 0 0 1 := by
  show (h.derivSubmoduleGaugeWeight 1).piece 0
      ⊔ GaugeWeightDecomposition.piece rep (h.derivSubmodule 0 * h.derivSubmodule 0) 0 = _
  rw [h.derivSubmoduleGaugeWeight_piece_zero 1, h.derivSubmodule_mul_piece_zero 0 0,
    bot_sup_eq]
  simp only [sup_comm, sup_left_comm, sup_idem, sup_left_idem]

/-- The weight-zero piece at mass weight six: the isospin-diagonal pairings carrying one
  derivative, on either of the two factors. -/
lemma massWeightSubmoduleGaugeWeightSix_piece_zero :
    (h.massWeightSubmoduleGaugeWeightSix).piece 0
      = h.higgsBarHiggsSpan 1 0 0 ⊔ h.higgsBarHiggsSpan 1 0 1
        ⊔ h.higgsBarHiggsSpan 0 1 0 ⊔ h.higgsBarHiggsSpan 0 1 1 := by
  show ((h.derivSubmoduleGaugeWeight 2).piece 0
      ⊔ GaugeWeightDecomposition.piece rep (h.derivSubmodule 1 * h.derivSubmodule 0) 0)
      ⊔ GaugeWeightDecomposition.piece rep
        (h.derivSubmodule 0 * h.derivSubmodule 0 * h.derivSubmodule 0) 0 = _
  rw [h.derivSubmoduleGaugeWeight_piece_zero 2, h.derivSubmodule_mul_piece_zero 1 0,
    h.derivSubmodule_mul_mul_piece_zero 0 0 0, bot_sup_eq, sup_bot_eq]

/-- The weight-zero piece at mass weight eight: the isospin-diagonal pairings carrying two
  derivatives on one factor or one on each, together with the three quartic monomials. -/
lemma massWeightSubmoduleGaugeWeightEight_piece_zero :
    (h.massWeightSubmoduleGaugeWeightEight).piece 0
      = h.higgsBarHiggsSpan 2 0 0 ⊔ h.higgsBarHiggsSpan 2 0 1
        ⊔ h.higgsBarHiggsSpan 0 2 0 ⊔ h.higgsBarHiggsSpan 0 2 1
        ⊔ (h.higgsBarHiggsSpan 1 1 0 ⊔ h.higgsBarHiggsSpan 1 1 1)
        ⊔ (h.quarticSpan 0 0 ⊔ h.quarticSpan 0 1 ⊔ h.quarticSpan 1 1) := by
  show ((((h.derivSubmoduleGaugeWeight 3).piece 0
        ⊔ GaugeWeightDecomposition.piece rep
          (h.derivSubmodule 2 * h.derivSubmodule 0) 0)
      ⊔ GaugeWeightDecomposition.piece rep (h.derivSubmodule 1 * h.derivSubmodule 1) 0)
      ⊔ GaugeWeightDecomposition.piece rep
        (h.derivSubmodule 1 * h.derivSubmodule 0 * h.derivSubmodule 0) 0)
      ⊔ GaugeWeightDecomposition.piece rep
        (h.derivSubmodule 0 * h.derivSubmodule 0 * h.derivSubmodule 0
          * h.derivSubmodule 0) 0 = _
  rw [h.derivSubmoduleGaugeWeight_piece_zero 3, h.derivSubmodule_mul_piece_zero 2 0,
    h.derivSubmodule_mul_piece_zero 1 1, h.derivSubmodule_mul_mul_piece_zero 1 0 0,
    h.derivSubmodule_zero_pow_four_piece_zero, bot_sup_eq, sup_bot_eq]
  simp only [sup_assoc, sup_comm, sup_left_comm, sup_idem, sup_left_idem]

/-!

## E. The gauge sieve

A gauge-invariant element is fixed by the gauge torus, so it sits in the weight-zero piece
of any decomposition of a submodule containing it.  Section D therefore bounds the
invariants of each mass-weight submodule up to weight eight.  The bound is a sieve, not a
characterisation: the gauge torus cannot separate the isospin singlet from the neutral
component of the isospin triplet, and that separation needs the Weyl element of `SU(2)`.

-/

/-- A gauge-invariant term of odd mass weight vanishes. -/
lemma eq_zero_of_invariant_massWeightSubmodule_odd (n : ℕ) (hn : Odd n) {x : B}
    (hx : x ∈ h.massWeightSubmodule n) : x = 0 :=
  Submodule.mem_bot ℂ |>.mp (h.massWeightSubmodule_odd_eq_bot n hn ▸ hx)

/-- A gauge-invariant term of mass weight two vanishes: a single Higgs symbol carries
  hypercharge, so nothing at that weight is neutral. -/
lemma eq_zero_of_invariant_massWeightSubmodule_two {x : B}
    (hx : x ∈ h.massWeightSubmodule 2) (hg : ∀ g : GaugeGroupI, rep g x = x) : x = 0 := by
  have hmem := GaugeWeightDecomposition.mem_zero_of_invariant
    h.massWeightSubmoduleGaugeWeightTwo hx hg
  rwa [h.massWeightSubmoduleGaugeWeightTwo_piece_zero, Submodule.mem_bot] at hmem

/-- A gauge-invariant term of mass weight four is a combination of the two underived
  isospin-diagonal pairings. -/
lemma mem_of_invariant_massWeightSubmodule_four {x : B}
    (hx : x ∈ h.massWeightSubmodule 4) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.higgsBarHiggsSpan 0 0 0 ⊔ h.higgsBarHiggsSpan 0 0 1 := by
  rw [← h.massWeightSubmoduleGaugeWeightFour_piece_zero]
  exact GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg

/-- A gauge-invariant term of mass weight six is a combination of the isospin-diagonal
  pairings carrying one derivative, on either factor. -/
lemma mem_of_invariant_massWeightSubmodule_six {x : B}
    (hx : x ∈ h.massWeightSubmodule 6) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.higgsBarHiggsSpan 1 0 0 ⊔ h.higgsBarHiggsSpan 1 0 1
      ⊔ h.higgsBarHiggsSpan 0 1 0 ⊔ h.higgsBarHiggsSpan 0 1 1 := by
  rw [← h.massWeightSubmoduleGaugeWeightSix_piece_zero]
  exact GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg

/-- A gauge-invariant term of mass weight eight is a combination of the isospin-diagonal
  pairings carrying two derivatives and of the three quartic monomials. -/
lemma mem_of_invariant_massWeightSubmodule_eight {x : B}
    (hx : x ∈ h.massWeightSubmodule 8) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.higgsBarHiggsSpan 2 0 0 ⊔ h.higgsBarHiggsSpan 2 0 1
      ⊔ h.higgsBarHiggsSpan 0 2 0 ⊔ h.higgsBarHiggsSpan 0 2 1
      ⊔ (h.higgsBarHiggsSpan 1 1 0 ⊔ h.higgsBarHiggsSpan 1 1 1)
      ⊔ (h.quarticSpan 0 0 ⊔ h.quarticSpan 0 1 ⊔ h.quarticSpan 1 1) := by
  rw [← h.massWeightSubmoduleGaugeWeightEight_piece_zero]
  exact GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg

/-!

## F. The Weyl refinement of the pairing spans

-/

/-- The span of the isospin contractions of a Higgs tower carrying `n` derivatives against
  a conjugate tower carrying `m`. -/
noncomputable def dotSpan (h : IsHiggsSector B rep hrep_mul repLorentz
      hrepLorentz_mul H barH massWeightPoly) (n m : ℕ) : Submodule ℂ B :=
  ⨆ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)), ℂ ∙ h.dotGaugeHiggs d d'

/-- The span of the neutral triplet combinations of a Higgs tower carrying `n` derivatives
  against a conjugate tower carrying `m`. -/
noncomputable def tripletSpan (h : IsHiggsSector B rep hrep_mul repLorentz
      hrepLorentz_mul H barH massWeightPoly) (n m : ℕ) : Submodule ℂ B :=
  ⨆ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
    ℂ ∙ (h.higgs d 0 * h.barHiggs d' 0 - h.higgs d 1 * h.barHiggs d' 1)

/-- The Weyl grading of the isospin-diagonal pairing span: the symmetric combination is the
  isospin contraction, of grade zero, and the antisymmetric one is the neutral triplet
  component, of grade two. -/
noncomputable def higgsBarHiggsSpanSU2Perm (n m : ℕ) :
    SU2PermDecomposition rep (h.higgsBarHiggsSpan n m 0 ⊔ h.higgsBarHiggsSpan n m 1) where
  piece k := if k = 0 then h.dotSpan n m else if k = 2 then h.tripletSpan n m else ⊥
  piece_le := by
    have hzero : h.dotSpan n m
        ≤ Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign 0) := by
      rw [dotSpan]
      refine iSup_le fun d => iSup_le fun d' =>
        (Submodule.span_singleton_le_iff_mem _ _).mpr ?_
      exact Module.End.mem_eigenspace_iff.mpr
        (by rw [su2PermSign_zero, one_smul, h.rep_dotGaugeHiggs])
    have htwo : h.tripletSpan n m
        ≤ Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign 2) := by
      rw [tripletSpan]
      refine iSup_le fun d => iSup_le fun d' =>
        (Submodule.span_singleton_le_iff_mem _ _).mpr ?_
      exact Module.End.mem_eigenspace_iff.mpr
        (by rw [su2PermSign_two, neg_one_smul, h.rep_gaugeSU2Perm_higgsBarHiggs_sub])
    intro k x hx
    rcases eq_or_ne k 0 with rfl | hk0
    · rw [if_pos rfl] at hx
      exact Module.End.mem_eigenspace_iff.mp (hzero hx)
    · rcases eq_or_ne k 2 with rfl | hk2
      · rw [if_neg hk0, if_pos rfl] at hx
        exact Module.End.mem_eigenspace_iff.mp (htwo hx)
      · rw [if_neg hk0, if_neg hk2, Submodule.mem_bot] at hx
        subst hx
        simp
  iSup_piece := by
    have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
    refine le_antisymm (iSup_le fun k => ?_) ?_
    · rcases hcases k with rfl | rfl | rfl | rfl
      · rw [if_pos rfl, dotSpan]
        refine iSup_le fun d => iSup_le fun d' =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr ?_
        rw [dotGaugeHiggs]
        exact add_mem
          (Submodule.mem_sup_left (Submodule.mem_iSup_of_mem d
            (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))))
          (Submodule.mem_sup_right (Submodule.mem_iSup_of_mem d
            (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
      · rw [if_neg (by decide), if_pos rfl, tripletSpan]
        refine iSup_le fun d => iSup_le fun d' =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr ?_
        exact sub_mem
          (Submodule.mem_sup_left (Submodule.mem_iSup_of_mem d
            (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))))
          (Submodule.mem_sup_right (Submodule.mem_iSup_of_mem d
            (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))))
      · rw [if_neg (by decide), if_neg (by decide)]
        exact bot_le
    · refine le_trans ?_ (sup_le (le_iSup _ (0 : ZMod 4)) (le_iSup _ (2 : ZMod 4)))
      rw [if_pos rfl, if_neg (by decide : ¬(2 : ZMod 4) = 0), if_pos rfl, higgsBarHiggsSpan,
        higgsBarHiggsSpan]
      have hd : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
          h.dotGaugeHiggs d d' ∈ h.dotSpan n m := fun d d' =>
        Submodule.mem_iSup_of_mem d
          (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))
      have ht : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
          h.higgs d 0 * h.barHiggs d' 0 - h.higgs d 1 * h.barHiggs d' 1
            ∈ h.tripletSpan n m := fun d d' =>
        Submodule.mem_iSup_of_mem d
          (Submodule.mem_iSup_of_mem d' (Submodule.mem_span_singleton_self _))
      have hmem0 : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
          h.higgs d 0 * h.barHiggs d' 0 ∈ h.dotSpan n m ⊔ h.tripletSpan n m := by
        intro d d'
        rw [show h.higgs d 0 * h.barHiggs d' 0 = (2⁻¹ : ℂ) • (h.dotGaugeHiggs d d'
          + (h.higgs d 0 * h.barHiggs d' 0 - h.higgs d 1 * h.barHiggs d' 1))
          from by rw [dotGaugeHiggs]; module]
        exact Submodule.smul_mem _ _ (add_mem (Submodule.mem_sup_left (hd d d'))
          (Submodule.mem_sup_right (ht d d')))
      have hmem1 : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (d' : Fin m → (Fin 1 ⊕ Fin 3)),
          h.higgs d 1 * h.barHiggs d' 1 ∈ h.dotSpan n m ⊔ h.tripletSpan n m := by
        intro d d'
        rw [show h.higgs d 1 * h.barHiggs d' 1 = (2⁻¹ : ℂ) • (h.dotGaugeHiggs d d'
          - (h.higgs d 0 * h.barHiggs d' 0 - h.higgs d 1 * h.barHiggs d' 1))
          from by rw [dotGaugeHiggs]; module]
        exact Submodule.smul_mem _ _ (sub_mem (Submodule.mem_sup_left (hd d d'))
          (Submodule.mem_sup_right (ht d d')))
      exact sup_le (iSup_le fun d => iSup_le fun d' =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem0 d d'))
        (iSup_le fun d => iSup_le fun d' =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem1 d d'))

/-!

## G. The Weyl grading at mass weights four and six

-/

/-- The Weyl grading of the weight-zero piece at mass weight four. -/
noncomputable def massWeightSubmoduleGaugeWeightFourSU2Perm :
    SU2PermDecomposition rep ((h.massWeightSubmoduleGaugeWeightFour).piece 0) :=
  SU2PermDecomposition.copy (h.higgsBarHiggsSpanSU2Perm 0 0) _
    h.massWeightSubmoduleGaugeWeightFour_piece_zero

/-- The Weyl grading of the weight-zero piece at mass weight six. -/
noncomputable def massWeightSubmoduleGaugeWeightSixSU2Perm :
    SU2PermDecomposition rep ((h.massWeightSubmoduleGaugeWeightSix).piece 0) :=
  SU2PermDecomposition.copy
    ((h.higgsBarHiggsSpanSU2Perm 1 0).sup (h.higgsBarHiggsSpanSU2Perm 0 1)) _
    (by rw [h.massWeightSubmoduleGaugeWeightSix_piece_zero, sup_assoc])

/-- A gauge-invariant term of mass weight four is a multiple of the underived isospin
  contraction. -/
lemma mem_dotSpan_of_invariant_massWeightSubmodule_four {x : B}
    (hx : x ∈ h.massWeightSubmodule 4) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.dotSpan 0 0 := by
  have hmem := SU2PermDecomposition.mem_zero_of_invariant
    h.massWeightSubmoduleGaugeWeightFourSU2Perm
    (GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg) hg
  rwa [show (h.massWeightSubmoduleGaugeWeightFourSU2Perm).piece 0 = h.dotSpan 0 0 from rfl]
    at hmem

/-- A gauge-invariant term of mass weight six is a combination of the isospin contractions
  carrying one derivative, on either factor. -/
lemma mem_dotSpan_of_invariant_massWeightSubmodule_six {x : B}
    (hx : x ∈ h.massWeightSubmodule 6) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.dotSpan 1 0 ⊔ h.dotSpan 0 1 := by
  have hmem := SU2PermDecomposition.mem_zero_of_invariant
    h.massWeightSubmoduleGaugeWeightSixSU2Perm
    (GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg) hg
  rwa [show (h.massWeightSubmoduleGaugeWeightSixSU2Perm).piece 0
    = h.dotSpan 1 0 ⊔ h.dotSpan 0 1 from rfl] at hmem

/-!

## H. The Weyl grading at mass weight eight

The quartic monomials need their own grading.  The Weyl element exchanges the two diagonal
quartics `(H⁰H̄⁰)²` and `(H¹H̄¹)²` and fixes the mixed one `H⁰H̄⁰H¹H̄¹`, so it is the
symmetric combination of the diagonal pair and the mixed monomial that have grade zero,
the antisymmetric combination having grade two.

-/

/-- The span of a single eigenvector of the Weyl element, as a grading concentrated in the
  single grade that eigenvector carries. -/
noncomputable def su2PermSpanSingleton (x : B) (k : ZMod 4)
    (hx : rep gaugeSU2Perm x = su2PermSign k • x) :
    SU2PermDecomposition rep (ℂ ∙ x) where
  piece k' := if k' = k then ℂ ∙ x else ⊥
  piece_le := by
    intro k' y hy
    split_ifs at hy with hk
    · subst hk
      obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hy
      rw [map_smul, hx, smul_comm]
    · rw [Submodule.mem_bot] at hy
      subst hy
      simp
  iSup_piece := by
    refine le_antisymm (iSup_le fun k' => ?_) (le_iSup_of_le k (by rw [if_pos rfl]))
    split_ifs
    · exact le_rfl
    · exact bot_le

/-- Replacing two of three lines by their symmetric and antisymmetric combinations spans
  the same submodule, since two is invertible. -/
lemma sup_span_symm_antisymm (a b m : B) :
    (ℂ ∙ (a + b) ⊔ ℂ ∙ m) ⊔ ℂ ∙ (a - b) = (ℂ ∙ a ⊔ ℂ ∙ m) ⊔ ℂ ∙ b := by
  refine le_antisymm (sup_le (sup_le ?_ ?_) ?_) (sup_le (sup_le ?_ ?_) ?_) <;>
    rw [Submodule.span_singleton_le_iff_mem]
  · exact add_mem
      (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _)))
      (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
  · exact Submodule.mem_sup_left (Submodule.mem_sup_right
      (Submodule.mem_span_singleton_self _))
  · exact sub_mem
      (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _)))
      (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
  · have hs : (2⁻¹ : ℂ) • ((a + b) + (a - b)) ∈ (ℂ ∙ (a + b) ⊔ ℂ ∙ m) ⊔ ℂ ∙ (a - b) :=
      Submodule.smul_mem _ _ (add_mem
        (Submodule.mem_sup_left (Submodule.mem_sup_left
          (Submodule.mem_span_singleton_self _)))
        (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)))
    rwa [show (2⁻¹ : ℂ) • ((a + b) + (a - b)) = a from by module] at hs
  · exact Submodule.mem_sup_left (Submodule.mem_sup_right
      (Submodule.mem_span_singleton_self _))
  · have hs : (2⁻¹ : ℂ) • ((a + b) - (a - b)) ∈ (ℂ ∙ (a + b) ⊔ ℂ ∙ m) ⊔ ℂ ∙ (a - b) :=
      Submodule.smul_mem _ _ (sub_mem
        (Submodule.mem_sup_left (Submodule.mem_sup_left
          (Submodule.mem_span_singleton_self _)))
        (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)))
    rwa [show (2⁻¹ : ℂ) • ((a + b) - (a - b)) = b from by module] at hs

/-- The Weyl grading of the span of the three quartic monomials. -/
noncomputable def quarticSpanSU2Perm :
    SU2PermDecomposition rep
      (h.quarticSpan 0 0 ⊔ h.quarticSpan 0 1 ⊔ h.quarticSpan 1 1) :=
  SU2PermDecomposition.copy
    (((su2PermSpanSingleton (rep := rep)
        (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1) 0
        (by rw [su2PermSign_zero, one_smul, h.rep_gaugeSU2Perm_quartic_add])).sup
      (su2PermSpanSingleton (rep := rep)
        (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1) 0
        (by rw [su2PermSign_zero, one_smul, h.rep_gaugeSU2Perm_quartic_mixed]))).sup
      (su2PermSpanSingleton (rep := rep)
        (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          - h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1) 2
        (by rw [su2PermSign_two, neg_one_smul, h.rep_gaugeSU2Perm_quartic_sub])))
    _ (by simp only [quarticSpan]; exact (sup_span_symm_antisymm _ _ _).symm)


/-- The grade-zero piece of the quartic grading: the symmetric diagonal combination and
  the mixed monomial. -/
lemma quarticSpanSU2Perm_piece_zero :
    (h.quarticSpanSU2Perm).piece 0
      = ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
        ⊔ ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1) := by
  simp +decide [quarticSpanSU2Perm, su2PermSpanSingleton, SU2PermDecomposition.copy,
    SU2PermDecomposition.sup]

/-- The grade-zero piece of the Weyl grading of a pairing span. -/
lemma higgsBarHiggsSpanSU2Perm_piece_zero (n m : ℕ) :
    (h.higgsBarHiggsSpanSU2Perm n m).piece 0 = h.dotSpan n m := rfl

/-- The Weyl grading of the weight-zero piece at mass weight eight. -/
noncomputable def massWeightSubmoduleGaugeWeightEightSU2Perm :
    SU2PermDecomposition rep ((h.massWeightSubmoduleGaugeWeightEight).piece 0) :=
  SU2PermDecomposition.copy
    ((((h.higgsBarHiggsSpanSU2Perm 2 0).sup (h.higgsBarHiggsSpanSU2Perm 0 2)).sup
      (h.higgsBarHiggsSpanSU2Perm 1 1)).sup h.quarticSpanSU2Perm) _
    (by rw [h.massWeightSubmoduleGaugeWeightEight_piece_zero]; simp only [sup_assoc])

/-- The grade-zero piece of the Weyl grading at mass weight eight. -/
lemma massWeightSubmoduleGaugeWeightEightSU2Perm_piece_zero :
    (h.massWeightSubmoduleGaugeWeightEightSU2Perm).piece 0
      = h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1
        ⊔ (ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
            + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
          ⊔ ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1
            * h.barHiggs ![] 1)) := by
  show (((h.higgsBarHiggsSpanSU2Perm 2 0).piece 0 ⊔ (h.higgsBarHiggsSpanSU2Perm 0 2).piece 0)
      ⊔ (h.higgsBarHiggsSpanSU2Perm 1 1).piece 0) ⊔ (h.quarticSpanSU2Perm).piece 0 = _
  rw [h.quarticSpanSU2Perm_piece_zero]
  simp only [h.higgsBarHiggsSpanSU2Perm_piece_zero]

/-- A gauge-invariant term of mass weight eight lies in the span of the isospin
  contractions carrying two derivatives, the symmetric diagonal quartic and the mixed
  quartic.  This is what the two gradings alone can see. -/
lemma mem_of_invariant_massWeightSubmodule_eight_perm {x : B}
    (hx : x ∈ h.massWeightSubmodule 8) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1
      ⊔ (ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
        ⊔ ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1
          * h.barHiggs ![] 1)) := by
  have hmem := SU2PermDecomposition.mem_zero_of_invariant
    h.massWeightSubmoduleGaugeWeightEightSU2Perm
    (GaugeWeightDecomposition.mem_zero_of_invariant _ hx hg) hg
  rwa [h.massWeightSubmoduleGaugeWeightEightSU2Perm_piece_zero] at hmem

/-!

## I. Completing the gauge argument at mass weight eight

The two gradings together leave a two-dimensional quartic sector: the square of the
isospin contraction and the square of the neutral triplet component.  Neither grading can
tell the two apart, because a grading sees only an abelian subgroup, and the square of a
neutral triplet component is fixed by the whole gauge torus and by the Weyl element alike.

The continuous symmetry does tell them apart.  The `SU(2)` element implementing a quarter
turn about the diagonal axis cycles the three triplet components `n₃ ↦ n₁ ↦ i n₂`, and the
Fierz identity says that the sum of the three squares is the square of the isospin
contraction.  Averaging over the cyclic group generated by that element therefore sends
the triplet square into the span of the contraction square, and an invariant element is
its own average.

-/

/-- The symmetric diagonal quartic and the mixed quartic span the same plane as the square
  of the isospin contraction and the square of the neutral triplet component. -/
lemma sup_quartic_eq_dotSq_sup_tripletSq :
    ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
        + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
      ⊔ ℂ ∙ (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1)
      = ℂ ∙ (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![])
        ⊔ ℂ ∙ ((h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
          * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)) := by
  have hHH : ∀ i j, h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.higgs ![] j
      = h.higgs ![] j * h.higgs ![] i := fun i j => (h.H_comm_H _ _ _ _ _ _).eq
  have hbH : ∀ i j, h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.higgs ![] j
      = h.higgs ![] j * h.barHiggs ![] i := fun i j => (h.H_comm_barH _ _ _ _ _ _).symm.eq
  have hbb : ∀ i j, h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.barHiggs ![] j
      = h.barHiggs ![] j * h.barHiggs ![] i := fun i j => (h.barH_comm_barH _ _ _ _ _ _).eq
  have hHH' : ∀ i j (y : B), h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * (h.higgs ![] j * y)
      = h.higgs ![] j * (h.higgs ![] i * y) := fun i j y => by rw [← mul_assoc, hHH, mul_assoc]
  have hbH' : ∀ i j (y : B),
      h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * (h.higgs ![] j * y)
      = h.higgs ![] j * (h.barHiggs ![] i * y) := fun i j y => by
    rw [← mul_assoc, hbH, mul_assoc]
  have hmm : h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]
      = (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
        + (2 : ℂ) • (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1
          * h.barHiggs ![] 1) := by
    rw [dotGaugeHiggs]
    simp only [add_mul, mul_add, mul_assoc, hHH', hbH', hbb]
    match_scalars <;> norm_num
  have htt : (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      = (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
          + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
        - (2 : ℂ) • (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1
          * h.barHiggs ![] 1) := by
    simp only [sub_mul, mul_sub, mul_assoc, hHH', hbH', hbb]
    match_scalars <;> norm_num
  refine le_antisymm (sup_le ?_ ?_) (sup_le ?_ ?_) <;>
    rw [Submodule.span_le, Set.singleton_subset_iff]
  · rw [show h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
        + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1
        = (2⁻¹ : ℂ) • (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]
          + (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
            * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1))
        from by rw [hmm, htt]; module]
    exact Submodule.smul_mem _ _ (add_mem
      (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
      (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)))
  · rw [show h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1
        = ((4 : ℂ)⁻¹) • (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]
          - (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
            * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1))
        from by rw [hmm, htt]; module]
    exact Submodule.smul_mem _ _ (sub_mem
      (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
      (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)))
  · rw [hmm]
    exact add_mem (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
      (Submodule.smul_mem _ _ (Submodule.mem_sup_right
        (Submodule.mem_span_singleton_self _)))
  · rw [htt]
    exact sub_mem (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
      (Submodule.smul_mem _ _ (Submodule.mem_sup_right
        (Submodule.mem_span_singleton_self _)))

set_option maxHeartbeats 1000000 in
/-- The full gauge argument at mass weight eight: a gauge-invariant term is a combination
  of the isospin contractions carrying two derivatives and of the square of the underived
  contraction.  The square of the neutral triplet component, which neither grading can
  discard, is removed by averaging over the cyclic group generated by the quarter turn
  about the diagonal isospin axis. -/
lemma mem_dotSpan_of_invariant_massWeightSubmodule_eight {x : B}
    (hx : x ∈ h.massWeightSubmodule 8) (hg : ∀ g : GaugeGroupI, rep g x = x) :
    x ∈ h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1
      ⊔ ℂ ∙ (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]) := by
  have hspan := h.mem_of_invariant_massWeightSubmodule_eight_perm hx hg
  rw [h.sup_quartic_eq_dotSq_sup_tripletSq] at hspan
  -- commutation lemmas for sorting quartic monomials
  have hHH : ∀ i j, h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.higgs ![] j
      = h.higgs ![] j * h.higgs ![] i := fun i j => (h.H_comm_H _ _ _ _ _ _).eq
  have hbH : ∀ i j, h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.higgs ![] j
      = h.higgs ![] j * h.barHiggs ![] i := fun i j => (h.H_comm_barH _ _ _ _ _ _).symm.eq
  have hbb : ∀ i j, h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * h.barHiggs ![] j
      = h.barHiggs ![] j * h.barHiggs ![] i := fun i j => (h.barH_comm_barH _ _ _ _ _ _).eq
  have hHH' : ∀ i j (y : B), h.higgs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * (h.higgs ![] j * y)
      = h.higgs ![] j * (h.higgs ![] i * y) := fun i j y => by rw [← mul_assoc, hHH, mul_assoc]
  have hbH' : ∀ i j (y : B),
      h.barHiggs (![] : Fin 0 → (Fin 1 ⊕ Fin 3)) i * (h.higgs ![] j * y)
      = h.higgs ![] j * (h.barHiggs ![] i * y) := fun i j y => by
    rw [← mul_assoc, hbH, mul_assoc]
  -- the cyclic `SU(2)` element implementing the quarter turn about the diagonal axis
  have hSU : !![(1 - Complex.I) / 2, (-1 - Complex.I) / 2;
      (1 - Complex.I) / 2, (1 + Complex.I) / 2] ∈ specialUnitaryGroup (Fin 2) ℂ := by
    rw [Matrix.mem_specialUnitaryGroup_iff]
    refine ⟨?_, ?_⟩
    · rw [Matrix.mem_unitaryGroup_iff]
      ext a b
      fin_cases a <;> fin_cases b <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two, star_eq_conjTranspose,
          Matrix.conjTranspose_apply, map_div₀, map_ofNat,
          Complex.ext_iff] <;> norm_num
    · rw [Matrix.det_fin_two_of]
      simp [Complex.ext_iff]
      norm_num
  set g : GaugeGroupI := ⟨1, ⟨_, hSU⟩, 1⟩ with hgdef
  have hgmat : ((g⁻¹).toSU2 : Matrix (Fin 2) (Fin 2) ℂ)
      = !![(1 + Complex.I)/2, (1 + Complex.I)/2; (-1 + Complex.I)/2, (1 - Complex.I)/2] := by
    rw [map_inv, ← Matrix.star_eq_inv, Matrix.specialUnitaryGroup.coe_star]
    ext a b
    fin_cases a <;> fin_cases b <;>
      simp [hgdef, GaugeGroupI.toSU2, Complex.conj_I, Complex.ext_iff]
  have hU1 : ((g⁻¹).toU1 : ℂ) = 1 := by simp [hgdef, GaugeGroupI.toU1]
  have hH0 : rep g (h.higgs ![] 0)
      = ((1 + Complex.I)/2) • h.higgs ![] 0 + ((1 + Complex.I)/2) • h.higgs ![] 1 := by
    rw [h.rep_higgsComponent, Fin.sum_univ_two, hU1, hgmat]
    simp
  have hH1 : rep g (h.higgs ![] 1)
      = ((-1 + Complex.I)/2) • h.higgs ![] 0 + ((1 - Complex.I)/2) • h.higgs ![] 1 := by
    rw [h.rep_higgsComponent, Fin.sum_univ_two, hU1, hgmat]
    simp
  have hB0 : rep g (h.barHiggs ![] 0)
      = ((1 - Complex.I)/2) • h.barHiggs ![] 0 + ((1 - Complex.I)/2) • h.barHiggs ![] 1 := by
    rw [h.rep_barHiggsComponent, Fin.sum_univ_two, hU1, hgmat]
    simp [map_div₀, Complex.conj_I, map_ofNat]
    module
  have hB1 : rep g (h.barHiggs ![] 1)
      = ((-1 - Complex.I)/2) • h.barHiggs ![] 0 + ((1 + Complex.I)/2) • h.barHiggs ![] 1 := by
    rw [h.rep_barHiggsComponent, Fin.sum_univ_two, hU1, hgmat]
    simp [map_div₀, Complex.conj_I, map_ofNat]
    module
  -- the triplet term cycles: `n₃ ↦ n₁ ↦ i n₂`, and the Fierz identity closes the orbit
  have hn3 : rep g (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      = h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0 := by
    rw [map_sub, h.rep_mul, h.rep_mul, hH0, hB0, hH1, hB1]
    simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm]
    match_scalars <;> simp [Complex.ext_iff] <;> norm_num
  have hn1 : rep g (h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0)
      = Complex.I • (h.higgs ![] 0 * h.barHiggs ![] 1 - h.higgs ![] 1 * h.barHiggs ![] 0) := by
    rw [map_add, h.rep_mul, h.rep_mul, hH0, hB0, hH1, hB1]
    simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm, smul_sub]
    match_scalars <;> simp [Complex.ext_iff] <;> norm_num
  have fierz : (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
        * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      + (h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0)
        * (h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0)
      + (Complex.I • (h.higgs ![] 0 * h.barHiggs ![] 1 - h.higgs ![] 1 * h.barHiggs ![] 0))
        * (Complex.I • (h.higgs ![] 0 * h.barHiggs ![] 1 - h.higgs ![] 1 * h.barHiggs ![] 0))
      = h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![] := by
    rw [dotGaugeHiggs]
    simp only [sub_mul, mul_sub, add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
      mul_assoc, hHH', hbH', hbb]
    match_scalars <;> simp [Complex.ext_iff]
  have hT3 : ∀ y : B, rep (g * g) y = rep g (rep g y) := by
    intro y
    rw [map_mul]
    rfl
  have e1 : rep g ((h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1))
      = (h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0)
        * (h.higgs ![] 0 * h.barHiggs ![] 1 + h.higgs ![] 1 * h.barHiggs ![] 0) := by
    rw [h.rep_mul, hn3]
  have e2 : rep (g * g)
      ((h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
      * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1))
      = (Complex.I • (h.higgs ![] 0 * h.barHiggs ![] 1 - h.higgs ![] 1 * h.barHiggs ![] 0))
        * (Complex.I • (h.higgs ![] 0 * h.barHiggs ![] 1
          - h.higgs ![] 1 * h.barHiggs ![] 0)) := by
    rw [hT3, e1, h.rep_mul, hn1]
  have hmm2 : ∀ k : GaugeGroupI, rep k (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![])
      = h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![] := fun k => by
    rw [h.rep_mul, h.rep_dotGaugeHiggs_invariant]
  -- averaging over `{1, g, g²}` projects onto the genuinely invariant span
  set T : B →ₗ[ℂ] B := LinearMap.id + rep g + rep (g * g) with hTdef
  have hTapp : ∀ y : B, T y = y + rep g y + rep (g * g) y := fun y => rfl
  have hmaple : Submodule.map T ((h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1)
      ⊔ (ℂ ∙ (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![])
        ⊔ ℂ ∙ ((h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1)
          * (h.higgs ![] 0 * h.barHiggs ![] 0 - h.higgs ![] 1 * h.barHiggs ![] 1))))
      ≤ h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1
        ⊔ ℂ ∙ (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]) := by
    simp only [dotSpan, Submodule.map_sup, Submodule.map_iSup, Submodule.map_span,
      Set.image_singleton]
    refine sup_le (sup_le (sup_le (iSup_le fun d => iSup_le fun d' => ?_)
      (iSup_le fun d => iSup_le fun d' => ?_)) (iSup_le fun d => iSup_le fun d' => ?_))
      (sup_le ?_ ?_) <;>
      rw [Submodule.span_le, Set.singleton_subset_iff]
    · rw [hTapp, h.rep_dotGaugeHiggs_invariant, h.rep_dotGaugeHiggs_invariant]
      exact add_mem (add_mem
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_left
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _))))))
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_left
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _)))))))
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_left
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _))))))
    · rw [hTapp, h.rep_dotGaugeHiggs_invariant, h.rep_dotGaugeHiggs_invariant]
      exact add_mem (add_mem
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _))))))
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _)))))))
        (Submodule.mem_sup_left (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _))))))
    · rw [hTapp, h.rep_dotGaugeHiggs_invariant, h.rep_dotGaugeHiggs_invariant]
      exact add_mem (add_mem
        (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _)))))
        (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _))))))
        (Submodule.mem_sup_left (Submodule.mem_sup_right
          (Submodule.mem_iSup_of_mem d (Submodule.mem_iSup_of_mem d'
            (Submodule.mem_span_singleton_self _)))))
    · rw [hTapp, hmm2, hmm2]
      exact add_mem (add_mem
        (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
        (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)))
        (Submodule.mem_sup_right (Submodule.mem_span_singleton_self _))
    · rw [hTapp, e1, e2, fierz]
      exact Submodule.mem_sup_right (Submodule.mem_span_singleton_self _)
  have hfin := hmaple ⟨x, hspan, rfl⟩
  rw [hTapp, hg, hg] at hfin
  have hfin' := Submodule.smul_mem _ ((3 : ℂ)⁻¹) hfin
  rwa [show ((3 : ℂ)⁻¹) • (x + x + x) = x from by module] at hfin'

/-!

## J. The gauge-invariant submodules up to mass weight eight

Both inclusions are now available: sections E to I bound the invariants from above, and
the isospin contractions are themselves invariant and of the right mass weight, which
bounds them from below.  The two meet, so the gauge-invariant part of each mass-weight
submodule up to weight eight is exactly described.

-/

/-- An isospin contraction has the mass weight of its two towers together. -/
lemma dotGaugeHiggs_mem_massWeightSubmodule {n1 n2 : ℕ} (d1 : Fin n1 → (Fin 1 ⊕ Fin 3))
    (d2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    h.dotGaugeHiggs d1 d2 ∈ h.massWeightSubmodule (2 * (1 + n1) + 2 * (1 + n2)) := by
  have hH : ∀ i, h.higgs d1 i ∈ h.massWeightSubmodule (2 * (1 + n1)) := fun i =>
    h.massWeightSubmodule_higgsSubmodule_le n1
      (Submodule.mem_iSup_of_mem d1 (LinearMap.mem_range_self _ _))
  have hbH : ∀ i, h.barHiggs d2 i ∈ h.massWeightSubmodule (2 * (1 + n2)) := fun i =>
    h.massWeightSubmodule_barHiggsSubmodule_le n2
      (Submodule.mem_iSup_of_mem d2 (LinearMap.mem_range_self _ _))
  rw [dotGaugeHiggs]
  exact add_mem (h.massWeightSubmodule_mul_le _ _ (Submodule.mul_mem_mul (hH 0) (hbH 0)))
    (h.massWeightSubmodule_mul_le _ _ (Submodule.mul_mem_mul (hH 1) (hbH 1)))

/-- The gauge invariants of mass weight four: the underived isospin contraction. -/
lemma gaugeInvariantOfMassDim_four_eq_dotSpan :
    h.gaugeInvariantOfMassDim 4 = h.dotSpan 0 0 := by
  refine le_antisymm (fun x hx =>
    h.mem_dotSpan_of_invariant_massWeightSubmodule_four hx.1 hx.2) ?_
  rw [dotSpan]
  refine iSup_le fun d => iSup_le fun d' =>
    (Submodule.span_singleton_le_iff_mem _ _).mpr ⟨?_, fun k =>
      h.rep_dotGaugeHiggs_invariant k d d'⟩
  exact h.dotGaugeHiggs_mem_massWeightSubmodule d d'

/-- The gauge invariants of mass weight six: the isospin contractions with one derivative
  on either factor. -/
lemma gaugeInvariantOfMassDim_six_eq_dotSpan :
    h.gaugeInvariantOfMassDim 6 = h.dotSpan 1 0 ⊔ h.dotSpan 0 1 := by
  refine le_antisymm (fun x hx =>
    h.mem_dotSpan_of_invariant_massWeightSubmodule_six hx.1 hx.2) (sup_le ?_ ?_) <;>
    rw [dotSpan] <;>
    refine iSup_le fun d => iSup_le fun d' =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr ⟨?_, fun k =>
        h.rep_dotGaugeHiggs_invariant k d d'⟩
  · exact h.dotGaugeHiggs_mem_massWeightSubmodule d d'
  · exact h.dotGaugeHiggs_mem_massWeightSubmodule d d'

/-- The gauge invariants of mass weight eight: the isospin contractions with two
  derivatives distributed over the two factors, together with the square of the underived
  contraction. -/
lemma gaugeInvariantOfMassDim_eight_eq_dotSpan :
    h.gaugeInvariantOfMassDim 8 = h.dotSpan 2 0 ⊔ h.dotSpan 0 2 ⊔ h.dotSpan 1 1
      ⊔ ℂ ∙ (h.dotGaugeHiggs ![] ![] * h.dotGaugeHiggs ![] ![]) := by
  refine le_antisymm (fun x hx =>
    h.mem_dotSpan_of_invariant_massWeightSubmodule_eight hx.1 hx.2)
    (sup_le (sup_le (sup_le ?_ ?_) ?_) ?_)
  · rw [dotSpan]
    exact iSup_le fun d => iSup_le fun d' =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        ⟨h.dotGaugeHiggs_mem_massWeightSubmodule d d',
          fun k => h.rep_dotGaugeHiggs_invariant k d d'⟩
  · rw [dotSpan]
    exact iSup_le fun d => iSup_le fun d' =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        ⟨h.dotGaugeHiggs_mem_massWeightSubmodule d d',
          fun k => h.rep_dotGaugeHiggs_invariant k d d'⟩
  · rw [dotSpan]
    exact iSup_le fun d => iSup_le fun d' =>
      (Submodule.span_singleton_le_iff_mem _ _).mpr
        ⟨h.dotGaugeHiggs_mem_massWeightSubmodule d d',
          fun k => h.rep_dotGaugeHiggs_invariant k d d'⟩
  · refine (Submodule.span_singleton_le_iff_mem _ _).mpr ⟨?_, fun k => ?_⟩
    · exact h.massWeightSubmodule_mul_le 4 4 (Submodule.mul_mem_mul
        (h.dotGaugeHiggs_mem_massWeightSubmodule ![] ![])
        (h.dotGaugeHiggs_mem_massWeightSubmodule ![] ![]))
    · rw [h.rep_mul, h.rep_dotGaugeHiggs_invariant]

end IsHiggsSector

end StandardModel
