/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalFieldAlgebra.FieldAlgebra.Basic
public import Physlib.Mathematics.SymmetricAlgebra
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
/-!
# The bosonic and fermionic algebras

## i. Overview

The two field algebras of the matter field `M`, distinguished by the statistics of the
field:

* the **bosonic algebra** `BosonicAlgebra M`, the symmetric algebra on the jet component
  space — the component functions commute;
* the **fermionic algebra** `FermionicAlgebra M`, the exterior algebra on the jet component
  space — the component functions anticommute.

Both are instances of `IsFieldAlgebra`, so the gauge and Lorentz actions, the total
derivative and the mass-weight scaling of
`Physlib.ClassicalFieldTheory.GaugeTheory.LocalFieldAlgebra.FieldAlgebra` apply to both.
This file contains only what is specific to each: the definition, the
`IsFieldAlgebra` instance, the commutation relations of the generators, and the inclusion
of a species `comap` (contravariant in the target space, hence not part of the
single-space interface).

## ii. Key results

- `BosonicAlgebra`, `FermionicAlgebra` : the two algebras.
- `BosonicAlgebra.instIsFieldAlgebra`, `FermionicAlgebra.instIsFieldAlgebra`.
- `BosonicAlgebra.ι_mul_ι_comm`, `FermionicAlgebra.ι_sq_zero`,
  `FermionicAlgebra.ι_mul_ι_swap` : the statistics.
- `BosonicAlgebra.comap`, `FermionicAlgebra.comap` : the inclusion of a species.

-/

@[expose] public section

section Bosonic

open TensorProduct

variable {G : Type} [Group G] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤]
  {G₀ : Type} [Group G₀] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G 𝔤 G₀ 𝔤J} {M : MatterField jets}

/-!

## A. The bosonic algebra

-/

/-- The bosonic algebra of the matter field `M`: the symmetric algebra on the space
  of component functions `∂_s φ_α` and `∂_s φ̄_α`. The symmetric product is the product of
  bosonic fields, its commutativity the Bose statistics. -/
abbrev BosonicAlgebra (M : MatterField jets) : Type :=
  SymmetricAlgebra ℂ (JetComponentSpace M)

namespace BosonicAlgebra

/-!

### A.1. The generators of the bosonic algebra

-/

/-- **The bosonic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s φ_α` and `∂_s φ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (SymmetricAlgebra.ι ℂ (JetComponentSpace M))) = ⊤ :=
  SymmetricAlgebra.adjoin_range_ι

/-- Two component functions commute: Bose statistics. -/
lemma ι_mul_ι_comm (x y : JetComponentSpace M) :
    (SymmetricAlgebra.ι ℂ _ x * SymmetricAlgebra.ι ℂ _ y : BosonicAlgebra M)
      = SymmetricAlgebra.ι ℂ _ y * SymmetricAlgebra.ι ℂ _ x :=
  mul_comm _ _

/-- The bosonic algebra is a field algebra: the symmetric algebra has the universal
  property. -/
noncomputable instance instIsFieldAlgebra : IsFieldAlgebra (JetComponentSpace M) (BosonicAlgebra M) where
  ι := SymmetricAlgebra.ι ℂ _
  map := SymmetricAlgebra.map
  map_ι f x := SymmetricAlgebra.map_apply_ι f x
  map_id := SymmetricAlgebra.map_id
  map_comp_map f g := SymmetricAlgebra.map_comp_map g f
  induction h1 h2 h3 h4 a := by
    induction a using SymmetricAlgebra.induction with
    | algebraMap r => exact h1 r
    | ι x => exact h2 x
    | mul a b ha hb => exact h3 a b ha hb
    | add a b ha hb => exact h4 a b ha hb
  adjoin_ι_eq_top := SymmetricAlgebra.adjoin_range_ι

lemma ι_eq : FieldAlgebra.ι (BosonicAlgebra M) = SymmetricAlgebra.ι ℂ (JetComponentSpace M) := rfl

/-!

### A.2. Inclusion of a species

A field valued in `V` that is one *species* among several — i.e. `V` is a summand of a
larger target space `W` — has its bosonic algebra sitting inside the bosonic algebra of
`W`. The inclusion is induced by the *projection* `W →ₗ[ℂ] V`, because component functions
are covectors on the target and therefore transpose. `comap` is that induced map, and it is
functorial and compatible with everything the algebra carries.

-/

variable {N : MatterField jets}

/-- **The bosonic algebra is contravariant in the target space.** A linear map
  `f : V →ₗ[ℂ] W` induces an algebra homomorphism `BosonicAlgebra N →ₐ[ℂ] BosonicAlgebra M`
  by pulling back component functions. Applied to a *projection* out of a multi-species
  target space, this is the inclusion of one species' algebra into the whole. -/
noncomputable def comap (f : M.V →ₗ[ℂ] N.V) : BosonicAlgebra N →ₐ[ℂ] BosonicAlgebra M :=
  SymmetricAlgebra.map (JetComponentSpace.comap f)

@[simp]
lemma comap_ι (f : M.V →ₗ[ℂ] N.V) (x : JetComponentSpace N) :
    comap f (FieldAlgebra.ι (BosonicAlgebra N) x)
      = FieldAlgebra.ι (BosonicAlgebra M) (JetComponentSpace.comap f x) :=
  SymmetricAlgebra.map_apply_ι _ x

@[simp]
lemma comap_id : comap (LinearMap.id : M.V →ₗ[ℂ] M.V) = AlgHom.id ℂ (BosonicAlgebra M) := by
  rw [comap, JetComponentSpace.comap_id, SymmetricAlgebra.map_id]

/-- Functoriality: the order reverses, as it must for a contravariant construction. -/
lemma comap_comp {P : MatterField jets} (f : M.V →ₗ[ℂ] N.V) (g : N.V →ₗ[ℂ] P.V) :
    comap (g.comp f) = (comap f).comp (comap g) := by
  rw [comap, comap, comap, JetComponentSpace.comap_comp, ← SymmetricAlgebra.map_comp_map]

/-- The inclusion sends a component function of the species to the corresponding component
  function of the whole. -/
@[simp]
lemma comap_ofField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ N.V) :
    comap f (FieldAlgebra.ofField (BosonicAlgebra N) φ)
      = FieldAlgebra.ofField (BosonicAlgebra M) (φ ∘ₗ f) := by
  rw [FieldAlgebra.ofField_apply, comap_ι, FieldAlgebra.ofField_apply]
  congr 1

/-- The inclusion sends a conjugate component function of the species to the corresponding
  conjugate component function of the whole. -/
@[simp]
lemma comap_ofConjField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ (ConjModule N.V)) :
    comap f (FieldAlgebra.ofConjField (BosonicAlgebra N) φ)
      = FieldAlgebra.ofConjField (BosonicAlgebra M) (φ ∘ₗ ConjModule.map f) := by
  rw [FieldAlgebra.ofConjField_apply, comap_ι, FieldAlgebra.ofConjField_apply]
  congr 1

end BosonicAlgebra

end Bosonic

section Fermionic

open TensorProduct

variable {G : Type} [Group G] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤]
  {G₀ : Type} [Group G₀] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G 𝔤 G₀ 𝔤J} {M : MatterField jets}

/-!

## A. The fermionic algebra

-/

/-- The fermionic algebra of the matter field `M`: the exterior algebra on the space
  of component functions `∂_s ψ_α` and `∂_s ψ̄_α`. The exterior product is the product of
  fermionic fields, its anticommutativity the Fermi statistics. -/
abbrev FermionicAlgebra (M : MatterField jets) : Type :=
  ExteriorAlgebra ℂ (JetComponentSpace M)

namespace FermionicAlgebra

/-!

### A.1. The generators of the fermionic algebra

-/

/-- **The fermionic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s ψ_α` and `∂_s ψ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (ExteriorAlgebra.ι ℂ (M := JetComponentSpace M))) = ⊤ :=
  CliffordAlgebra.adjoin_range_ι

/-- A component function squares to zero: no fermionic field appears twice. -/
lemma ι_sq_zero (x : JetComponentSpace M) :
    ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ x = (0 : FermionicAlgebra M) :=
  ExteriorAlgebra.ι_sq_zero x

/-- Two component functions anticommute. -/
lemma ι_mul_ι_swap (x y : JetComponentSpace M) :
    (ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ y : FermionicAlgebra M)
      = - (ExteriorAlgebra.ι ℂ y * ExteriorAlgebra.ι ℂ x) :=
  eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap (R := ℂ) x y)

/-- The fermionic algebra is a field algebra: the exterior algebra has the universal
  property. -/
noncomputable instance instIsFieldAlgebra : IsFieldAlgebra (JetComponentSpace M) (FermionicAlgebra M) where
  ι := ExteriorAlgebra.ι ℂ
  map := ExteriorAlgebra.map
  map_ι f x := ExteriorAlgebra.map_apply_ι f x
  map_id := ExteriorAlgebra.map_id
  map_comp_map f g := ExteriorAlgebra.map_comp_map f g
  induction h1 h2 h3 h4 a := by
    induction a using ExteriorAlgebra.induction with
    | algebraMap r => exact h1 r
    | ι x => exact h2 x
    | mul a b ha hb => exact h3 a b ha hb
    | add a b ha hb => exact h4 a b ha hb
  adjoin_ι_eq_top := CliffordAlgebra.adjoin_range_ι

lemma ι_eq : FieldAlgebra.ι (FermionicAlgebra M) = ExteriorAlgebra.ι ℂ := rfl

/-!

### A.2. Inclusion of a species

A field valued in `V` that is one *species* among several — i.e. `V` is a summand of a
larger target space `U` — has its fermionic algebra sitting inside the fermionic algebra of
`U`. The inclusion is induced by the *projection* `U →ₗ[ℂ] V`, because component functions
are covectors on the target and therefore transpose. `comap` is that induced map, and it is
functorial and compatible with everything the algebra carries.

-/

variable {N : MatterField jets}

/-- **The fermionic algebra is contravariant in the target space.** A linear map
  `f : V →ₗ[ℂ] W` induces an algebra homomorphism `FermionicAlgebra N →ₐ[ℂ] FermionicAlgebra M`
  by pulling back component functions. Applied to a *projection* out of a multi-species target
  space, this is the inclusion of one species' algebra into the whole. -/
noncomputable def comap (f : M.V →ₗ[ℂ] N.V) : FermionicAlgebra N →ₐ[ℂ] FermionicAlgebra M :=
  ExteriorAlgebra.map (JetComponentSpace.comap f)

@[simp]
lemma comap_ι (f : M.V →ₗ[ℂ] N.V) (x : JetComponentSpace N) :
    comap f (FieldAlgebra.ι (FermionicAlgebra N) x)
      = FieldAlgebra.ι (FermionicAlgebra M) (JetComponentSpace.comap f x) :=
  ExteriorAlgebra.map_apply_ι _ x

@[simp]
lemma comap_id : comap (LinearMap.id : M.V →ₗ[ℂ] M.V) = AlgHom.id ℂ (FermionicAlgebra M) := by
  rw [comap, JetComponentSpace.comap_id, ExteriorAlgebra.map_id]

/-- Functoriality: the order reverses, as it must for a contravariant construction. -/
lemma comap_comp {P : MatterField jets} (f : M.V →ₗ[ℂ] N.V) (g : N.V →ₗ[ℂ] P.V) :
    comap (g.comp f) = (comap f).comp (comap g) := by
  rw [comap, comap, comap, JetComponentSpace.comap_comp, ← ExteriorAlgebra.map_comp_map]

/-- The inclusion sends a component function of the species to the corresponding component
  function of the whole. -/
@[simp]
lemma comap_ofField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ N.V) :
    comap f (FieldAlgebra.ofField (FermionicAlgebra N) φ)
      = FieldAlgebra.ofField (FermionicAlgebra M) (φ ∘ₗ f) := by
  rw [FieldAlgebra.ofField_apply, comap_ι, FieldAlgebra.ofField_apply]
  congr 1

/-- The inclusion sends a conjugate component function of the species to the corresponding
  conjugate component function of the whole. -/
@[simp]
lemma comap_ofConjField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ (ConjModule N.V)) :
    comap f (FieldAlgebra.ofConjField (FermionicAlgebra N) φ)
      = FieldAlgebra.ofConjField (FermionicAlgebra M) (φ ∘ₗ ConjModule.map f) := by
  rw [FieldAlgebra.ofConjField_apply, comap_ι, FieldAlgebra.ofConjField_apply]
  congr 1

end FermionicAlgebra

end Fermionic
