/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith, Jinzheng Li, Nathaneal Sajan
-/
module

public import Physlib.Particles.LagrangianTheory.Basic

/-!

# The EFT Lagrangian with free derivatives

## i. Overview

For a Lagrangian theory, this file defines the algebra of complex-scalar, real-boson, and
fermionic expressions with arbitrarily many derivatives. It defines the Lorentz and gauge actions
as algebra automorphisms and gives their corresponding linear representations.

-/

@[expose] public section

namespace LagrangianTheory

open TensorProduct Matrix MatrixGroups

noncomputable section

variable {R H A : Type*} [CommSemiring R] [Group H] [Semiring A] [Algebra R A]

/-- Promote algebra endomorphisms agreeing with a linear representation to a group action by
algebra automorphisms. -/
def algAutOfRepresentation (ρ : Representation R H A) (φ : H → A →ₐ[R] A)
    (h : ∀ g x, ρ g x = φ g x) : H →* A ≃ₐ[R] A where
  toFun g :=
    { φ g with
      invFun := φ g⁻¹
      left_inv := fun x => by
        change φ g⁻¹ (φ g x) = x
        rw [← h g x, ← h g⁻¹ (ρ g x)]
        change (ρ g⁻¹ * ρ g) x = x
        rw [← ρ.map_mul]
        simp
      right_inv := fun x => by
        change φ g (φ g⁻¹ x) = x
        rw [← h g⁻¹ x, ← h g (ρ g⁻¹ x)]
        change (ρ g * ρ g⁻¹) x = x
        rw [← ρ.map_mul]
        simp }
  map_one' := by
    apply AlgEquiv.ext
    intro x
    change φ 1 x = x
    rw [← h 1 x]
    simp
  map_mul' g₁ g₂ := by
    apply AlgEquiv.ext
    intro x
    change φ (g₁ * g₂) x = φ g₁ (φ g₂ x)
    rw [← h (g₁ * g₂) x, ← h g₂ x, ← h g₁ (ρ g₂ x)]
    change ρ (g₁ * g₂) x = (ρ g₁ * ρ g₂) x
    rw [ρ.map_mul]

/-- Combine algebra-automorphism actions on two factors into an action on their tensor-product
algebra. -/
def tensorProductAlgAut {B : Type*} [Semiring B] [Algebra R B]
    (σA : H →* A ≃ₐ[R] A) (σB : H →* B ≃ₐ[R] B) :
    H →* ((A ⊗[R] B) ≃ₐ[R] (A ⊗[R] B)) where
  toFun g := Algebra.TensorProduct.congr (σA g) (σB g)
  map_one' := by
    apply AlgEquiv.ext
    intro x
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a b => simp
    | add x y hx hy => simpa only [map_add] using congrArg₂ (· + ·) hx hy
  map_mul' g₁ g₂ := by
    apply AlgEquiv.ext
    intro x
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a b => simp
    | add x y hx hy => simpa only [map_add] using congrArg₂ (· + ·) hx hy

variable {G : Type} [Group G]
variable {L : LagrangianTheory G}

/-- The algebra of Lagrangian expressions freely generated by fields and their derivatives. -/
abbrev EFTLagrangianFreeDeriv (L : LagrangianTheory G) : Type :=
  L.ComplexScalarEFTFreeDeriv ⊗[ℂ]
    L.RealBosonEFTFreeDerivComplex ⊗[ℂ] L.FermionicEFTFreeDeriv

namespace EFTLagrangianFreeDeriv

set_option maxSynthPendingDepth 4 in
noncomputable instance : Ring L.EFTLagrangianFreeDeriv := inferInstanceAs <|
  Ring (L.ComplexScalarEFTFreeDeriv ⊗[ℂ]
    L.RealBosonEFTFreeDerivComplex ⊗[ℂ] L.FermionicEFTFreeDeriv)

set_option maxSynthPendingDepth 4 in
noncomputable instance : Algebra ℂ L.EFTLagrangianFreeDeriv := inferInstanceAs <|
  Algebra ℂ (L.ComplexScalarEFTFreeDeriv ⊗[ℂ]
    L.RealBosonEFTFreeDerivComplex ⊗[ℂ] L.FermionicEFTFreeDeriv)

/-!

## A. Lorentz-group action

### A.1. Actions on the factors

-/

/-- The Lorentz action on the complex-scalar factor as an algebra homomorphism. -/
noncomputable def complexScalarLorentzAlgHom (Λ : SL(2,ℂ)) :
    L.ComplexScalarEFTFreeDeriv →ₐ[ℂ] L.ComplexScalarEFTFreeDeriv :=
  SymmetricAlgebra.lift
    (SymmetricAlgebra.ι ℂ _ ∘ₗ ComplexScalarComponentSpaceWithDeriv.repLorentzGroup Λ)

/-- The Lorentz action on the complex-scalar factor by algebra automorphisms. -/
noncomputable def complexScalarLorentzAlgAut :
    SL(2,ℂ) →* (L.ComplexScalarEFTFreeDeriv ≃ₐ[ℂ] L.ComplexScalarEFTFreeDeriv) :=
  algAutOfRepresentation ComplexScalarEFTFreeDeriv.repLorentzGroup
    complexScalarLorentzAlgHom fun _ _ => rfl

/-- The Lorentz action on the fermionic factor as an algebra homomorphism. -/
noncomputable def fermionicLorentzAlgHom (Λ : SL(2,ℂ)) :
    L.FermionicEFTFreeDeriv →ₐ[ℂ] L.FermionicEFTFreeDeriv :=
  ExteriorAlgebra.map (FermionicComponentSpaceWithDeriv.repLorentzGroup Λ)

/-- The Lorentz action on the fermionic factor by algebra automorphisms. -/
noncomputable def fermionicLorentzAlgAut :
    SL(2,ℂ) →* (L.FermionicEFTFreeDeriv ≃ₐ[ℂ] L.FermionicEFTFreeDeriv) :=
  algAutOfRepresentation FermionicEFTFreeDeriv.repLorentzGroup
    fermionicLorentzAlgHom fun _ _ => rfl

/-- The Lorentz action on the real-boson factor as a real algebra homomorphism. -/
noncomputable def realBosonLorentzAlgHom (Λ : SL(2,ℂ)) :
    L.RealBosonEFTFreeDeriv →ₐ[ℝ] L.RealBosonEFTFreeDeriv :=
  SymmetricAlgebra.lift
    (SymmetricAlgebra.ι ℝ _ ∘ₗ RealBosonComponentSpaceWithDeriv.repLorentzGroup Λ)

/-- The scalar extension of the real-boson Lorentz action as a complex algebra homomorphism. -/
noncomputable def realBosonComplexLorentzAlgHom (Λ : SL(2,ℂ)) :
    L.RealBosonEFTFreeDerivComplex →ₐ[ℂ] L.RealBosonEFTFreeDerivComplex :=
  (AlgHom.liftEquiv ℝ ℂ L.RealBosonEFTFreeDeriv L.RealBosonEFTFreeDerivComplex)
    ((Algebra.TensorProduct.includeRight :
      L.RealBosonEFTFreeDeriv →ₐ[ℝ] L.RealBosonEFTFreeDerivComplex).comp
      (realBosonLorentzAlgHom Λ))

/-- The complex real-boson Lorentz representation agrees with its algebra homomorphism. -/
lemma realBosonComplex_repLorentzGroup_apply (Λ : SL(2,ℂ))
    (x : L.RealBosonEFTFreeDerivComplex) :
    RealBosonEFTFreeDerivComplex.repLorentzGroup Λ x =
      realBosonComplexLorentzAlgHom Λ x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul c x =>
      change c ⊗ₜ[ℝ] realBosonLorentzAlgHom Λ x =
        c • (1 ⊗ₜ[ℝ] realBosonLorentzAlgHom Λ x)
      exact TensorProduct.tmul_eq_smul_one_tmul c _
  | add x y hx hy => simpa only [map_add] using congrArg₂ (· + ·) hx hy

/-- The Lorentz action on the complexified real-boson factor by algebra automorphisms. -/
noncomputable def realBosonComplexLorentzAlgAut :
    SL(2,ℂ) →*
      (L.RealBosonEFTFreeDerivComplex ≃ₐ[ℂ] L.RealBosonEFTFreeDerivComplex) :=
  algAutOfRepresentation RealBosonEFTFreeDerivComplex.repLorentzGroup
    realBosonComplexLorentzAlgHom realBosonComplex_repLorentzGroup_apply

/-!

### A.2. The full action and its representation

-/

/-- The Lorentz action on the two bosonic factors by algebra automorphisms. -/
noncomputable def bosonicLorentzAlgAut :
    SL(2,ℂ) →*
      ((L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex) ≃ₐ[ℂ]
        (L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex)) :=
  tensorProductAlgAut complexScalarLorentzAlgAut realBosonComplexLorentzAlgAut

/-- The Lorentz action on the bosonic factors as an algebra homomorphism. -/
noncomputable def bosonicLorentzAlgHom (Λ : SL(2,ℂ)) :
    L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex →ₐ[ℂ]
      L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex :=
  (bosonicLorentzAlgAut Λ).toAlgHom

/-- The Lorentz action on the free-derivative Lagrangian by algebra automorphisms. -/
noncomputable def lorentzAlgAut :
    SL(2,ℂ) →* (L.EFTLagrangianFreeDeriv ≃ₐ[ℂ] L.EFTLagrangianFreeDeriv) :=
  tensorProductAlgAut bosonicLorentzAlgAut fermionicLorentzAlgAut

/-- The action of a Lorentz-group element as an algebra homomorphism. -/
noncomputable def lorentzAlgHom (Λ : SL(2,ℂ)) :
    L.EFTLagrangianFreeDeriv →ₐ[ℂ] L.EFTLagrangianFreeDeriv :=
  (lorentzAlgAut Λ).toAlgHom

/-- The representation of the Lorentz group underlying its algebra-automorphism action. -/
noncomputable def repLorentzGroup :
    Representation ℂ SL(2,ℂ) L.EFTLagrangianFreeDeriv :=
  (AlgEquiv.toLinearMapHom ℂ L.EFTLagrangianFreeDeriv).comp lorentzAlgAut

/-- The Lorentz representation agrees with its algebra homomorphism. -/
lemma repLorentzGroup_apply (Λ : SL(2,ℂ)) (x : L.EFTLagrangianFreeDeriv) :
    repLorentzGroup Λ x = lorentzAlgHom Λ x := rfl

/-- The Lorentz representation preserves multiplication. -/
lemma repLorentzGroup_mul (Λ : SL(2,ℂ)) (V W : L.EFTLagrangianFreeDeriv) :
    repLorentzGroup Λ (V * W) = repLorentzGroup Λ V * repLorentzGroup Λ W := by
  simpa only [repLorentzGroup_apply] using map_mul (lorentzAlgHom Λ) V W

/-- The Lorentz representation preserves the unit. -/
@[simp]
lemma repLorentzGroup_one (Λ : SL(2,ℂ)) :
    repLorentzGroup (L := L) Λ 1 = 1 := by
  simpa only [repLorentzGroup_apply] using map_one (lorentzAlgHom (L := L) Λ)

/-!

## B. Gauge-group action

### B.1. Actions on the factors

-/

/-- The gauge action on the complex-scalar factor as an algebra homomorphism. -/
noncomputable def complexScalarGaugeAlgHom (g : G) :
    L.ComplexScalarEFTFreeDeriv →ₐ[ℂ] L.ComplexScalarEFTFreeDeriv :=
  SymmetricAlgebra.lift
    (SymmetricAlgebra.ι ℂ _ ∘ₗ ComplexScalarComponentSpaceWithDeriv.repGaugeGroup g)

/-- The gauge action on the complex-scalar factor by algebra automorphisms. -/
noncomputable def complexScalarGaugeAlgAut :
    G →* (L.ComplexScalarEFTFreeDeriv ≃ₐ[ℂ] L.ComplexScalarEFTFreeDeriv) :=
  algAutOfRepresentation ComplexScalarEFTFreeDeriv.repGaugeGroup
    complexScalarGaugeAlgHom fun _ _ => rfl

/-- The gauge action on the fermionic factor as an algebra homomorphism. -/
noncomputable def fermionicGaugeAlgHom (g : G) :
    L.FermionicEFTFreeDeriv →ₐ[ℂ] L.FermionicEFTFreeDeriv :=
  ExteriorAlgebra.map (FermionicComponentSpaceWithDeriv.repGaugeGroup g)

/-- The gauge action on the fermionic factor by algebra automorphisms. -/
noncomputable def fermionicGaugeAlgAut :
    G →* (L.FermionicEFTFreeDeriv ≃ₐ[ℂ] L.FermionicEFTFreeDeriv) :=
  algAutOfRepresentation FermionicEFTFreeDeriv.repGaugeGroup
    fermionicGaugeAlgHom fun _ _ => rfl

/-- The gauge action on the real-boson factor as a real algebra homomorphism. -/
noncomputable def realBosonGaugeAlgHom (g : G) :
    L.RealBosonEFTFreeDeriv →ₐ[ℝ] L.RealBosonEFTFreeDeriv :=
  SymmetricAlgebra.lift
    (SymmetricAlgebra.ι ℝ _ ∘ₗ RealBosonComponentSpaceWithDeriv.repGaugeGroup g)

/-- The scalar extension of the real-boson gauge action as a complex algebra homomorphism. -/
noncomputable def realBosonComplexGaugeAlgHom (g : G) :
    L.RealBosonEFTFreeDerivComplex →ₐ[ℂ] L.RealBosonEFTFreeDerivComplex :=
  (AlgHom.liftEquiv ℝ ℂ L.RealBosonEFTFreeDeriv L.RealBosonEFTFreeDerivComplex)
    ((Algebra.TensorProduct.includeRight :
      L.RealBosonEFTFreeDeriv →ₐ[ℝ] L.RealBosonEFTFreeDerivComplex).comp
      (realBosonGaugeAlgHom g))

/-- The complex real-boson gauge representation agrees with its algebra homomorphism. -/
lemma realBosonComplex_repGaugeGroup_apply (g : G)
    (x : L.RealBosonEFTFreeDerivComplex) :
    RealBosonEFTFreeDerivComplex.repGaugeGroup g x =
      realBosonComplexGaugeAlgHom g x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul c x =>
      change c ⊗ₜ[ℝ] realBosonGaugeAlgHom g x =
        c • (1 ⊗ₜ[ℝ] realBosonGaugeAlgHom g x)
      exact TensorProduct.tmul_eq_smul_one_tmul c _
  | add x y hx hy => simpa only [map_add] using congrArg₂ (· + ·) hx hy

/-- The gauge action on the complex real-boson factor by algebra automorphisms. -/
noncomputable def realBosonComplexGaugeAlgAut :
    G →* (L.RealBosonEFTFreeDerivComplex ≃ₐ[ℂ] L.RealBosonEFTFreeDerivComplex) :=
  algAutOfRepresentation RealBosonEFTFreeDerivComplex.repGaugeGroup
    realBosonComplexGaugeAlgHom realBosonComplex_repGaugeGroup_apply

/-!

### B.2. The full action and its representation

-/

/-- The gauge action on the two bosonic factors by algebra automorphisms. -/
noncomputable def bosonicGaugeAlgAut :
    G →* ((L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex) ≃ₐ[ℂ]
      (L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex)) :=
  tensorProductAlgAut complexScalarGaugeAlgAut realBosonComplexGaugeAlgAut

/-- The gauge action on the bosonic factors as an algebra homomorphism. -/
noncomputable def bosonicGaugeAlgHom (g : G) :
    L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex →ₐ[ℂ]
      L.ComplexScalarEFTFreeDeriv ⊗[ℂ] L.RealBosonEFTFreeDerivComplex :=
  (bosonicGaugeAlgAut g).toAlgHom

/-- The gauge action on the free-derivative Lagrangian by algebra automorphisms. -/
noncomputable def gaugeAlgAut :
    G →* (L.EFTLagrangianFreeDeriv ≃ₐ[ℂ] L.EFTLagrangianFreeDeriv) :=
  tensorProductAlgAut bosonicGaugeAlgAut fermionicGaugeAlgAut

/-- The action of a gauge-group element as an algebra homomorphism. -/
noncomputable def gaugeAlgHom (g : G) :
    L.EFTLagrangianFreeDeriv →ₐ[ℂ] L.EFTLagrangianFreeDeriv :=
  (gaugeAlgAut g).toAlgHom

/-- The representation of the gauge group underlying its algebra-automorphism action. -/
noncomputable def repGaugeGroup : Representation ℂ G L.EFTLagrangianFreeDeriv :=
  (AlgEquiv.toLinearMapHom ℂ L.EFTLagrangianFreeDeriv).comp gaugeAlgAut

/-- The gauge representation agrees with its algebra homomorphism. -/
lemma repGaugeGroup_apply (g : G) (x : L.EFTLagrangianFreeDeriv) :
    repGaugeGroup g x = gaugeAlgHom g x := rfl

/-- The gauge representation preserves multiplication. -/
lemma repGaugeGroup_mul (g : G) (V W : L.EFTLagrangianFreeDeriv) :
    repGaugeGroup g (V * W) = repGaugeGroup g V * repGaugeGroup g W := by
  simpa only [repGaugeGroup_apply] using map_mul (gaugeAlgHom g) V W

/-- The gauge representation preserves the unit. -/
@[simp]
lemma repGaugeGroup_one (g : G) : repGaugeGroup (L := L) g 1 = 1 := by
  simpa only [repGaugeGroup_apply] using map_one (gaugeAlgHom (L := L) g)

/-!

## C. The `IsInvariant` condition

This section is reserved for the predicate expressing simultaneous Lorentz and gauge invariance.

-/

end EFTLagrangianFreeDeriv

end


end LagrangianTheory
