/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Mathlib.LinearAlgebra.Eigenspace.Basic
/-!
# `SU(3)` permutation decompositions

## i. Overview

An `SU(3)` permutation decomposition of a submodule `V` is a `ZMod 3`-indexed family of
subspaces whose supremum is `V`, the grade-`k` piece scaled by `ω ^ k` under the `SU(3)`
element

  `su3Perm = !![0, 0, 1; 1, 0, 0; 0, 1, 0]`,

the cyclic colour rotation. On a colour triplet it sends `(a, b, c)` to `(c, a, b)`,
cycling the three colours and so cycling the three colour weights that the first two
coordinates of a `GaugeWeight` record.

`su3Perm` is the lift to `SU(3)` of a three-cycle in the Weyl group `S₃`. A three-cycle is
an even permutation, so its permutation matrix already has determinant `1`: unlike the
`SU(2)` transposition, which has to be twisted by a sign to land in `SU(2)`, the cyclic
matrix needs no phase correction at all.

`su3Perm` cubes to `1`, so it has order three in `SU(3)` and `rep gaugeSU3Perm` satisfies
`T ^ 3 = 1`. Its spectrum is therefore contained in the cube roots of unity, and the index
group is `ZMod 3` with eigenvalue `ω ^ k` for `ω = exp (2 π i / 3)` — multiplicative in
`k`, which is what makes the grading add under multiplication, exactly as gauge weights do
in `GaugeWeightDecomposition`. Because `ZMod 3` is finite there is no support field: the
finiteness that `GaugeWeightDecomposition.supp` has to record is automatic here.

The three grades separate the colour directions. A colour triplet splits into the three
lines spanned by `e_r + ω ^ (-k) • e_g + ω ^ (-2 * k) • e_b`, one in each grade, and a
colour contraction, being cyclically symmetric, lands in grade `0`. The grading group has
to be `ZMod 3` rather than the `ZMod 4` of the `SU(2)` file precisely because the element
used here has order three: on `ZMod 4` the character `k ↦ ω ^ k` would not be well defined.

## ii. A warning: grade zero is weaker than invariance

Like the colour weight, this is a *sieve* rather than a characterization.
`mem_zero_of_invariant` says an invariant element has grade zero, and there is no converse.
What it buys is a genuine sharpening of the colour weight in `GaugeWeightDecomposition`,
whose weight-zero piece cannot separate the colour singlet from the neutral components of a
higher multiplet — the Cartan-neutral part of the adjoint is three dimensional, not one.
Because `su3Perm` cycles the three colours it acts on the colour-weight-zero subspace, and
its grade-`1` and grade-`2` parts are thrown away by this sieve.

The sieve cannot be pushed further by grading alone. A grading sees only the cyclic group
generated by the element it uses, and the invariants of a `ZMod 3` subgroup of `SU(3)` are
far larger than the `SU(3)` invariants. Even combining this grading with the full colour
weight only reaches the normalizer of the maximal torus; cutting the remainder down needs
the continuous symmetry, not another grading.

## iii. Key results

- `su3Perm` : the `SU(3)` cyclic Weyl element `!![0, 0, 1; 1, 0, 0; 0, 1, 0]`, and
  `gaugeSU3Perm` its image in the gauge group.
- `su3Omega` : the primitive cube root of unity `exp (2 π i / 3)`.
- `su3PermSign` : the character `k ↦ ω ^ k` on `ZMod 3`, injective and multiplicative.
- `SU3PermDecomposition` : a `ZMod 3`-graded family of pure-sign subspaces with supremum `V`.
- `SU3PermDecomposition.sup` : two decompositions combine gradewise into one of `V ⊔ V'`.
- `SU3PermDecomposition.mul` : grades add under multiplication, decomposing `V * V'`.
- `SU3PermDecomposition.mem_zero_of_invariant` : a gauge-invariant element has grade zero.

## iv. Table of contents

- A. The `SU(3)` cyclic Weyl element
- B. The cube-root character of `ZMod 3`
- C. `SU(3)` permutation decompositions
- D. Joins
- E. Products
- F. Invariants

-/

@[expose] public section

namespace StandardModel

open Matrix

/-!

## A. The `SU(3)` cyclic Weyl element

-/

/-- The `SU(3)` cyclic permutation element `!![0, 0, 1; 1, 0, 0; 0, 1, 0]`. On a colour
  triplet it sends `(a, b, c)` to `(c, a, b)`, cycling the three colours; it cubes to `1`,
  so it has order three in `SU(3)`. A three-cycle is even, so the plain permutation matrix
  already has determinant `1`. -/
noncomputable def su3Perm : specialUnitaryGroup (Fin 3) ℂ :=
  ⟨!![0, 0, 1; 1, 0, 0; 0, 1, 0], by
    rw [Matrix.mem_specialUnitaryGroup_iff]
    refine ⟨?_, ?_⟩
    · rw [Matrix.mem_unitaryGroup_iff]
      ext a b
      fin_cases a <;> fin_cases b <;>
        simp [Matrix.mul_apply, Fin.sum_univ_three, star_eq_conjTranspose,
          Matrix.conjTranspose_apply]
    · simp [Matrix.det_fin_three]⟩

/-- The underlying matrix of the cyclic element. -/
lemma su3Perm_coe :
    (su3Perm : specialUnitaryGroup (Fin 3) ℂ).1 = !![0, 0, 1; 1, 0, 0; 0, 1, 0] := rfl

/-- The inverse cyclic element is the transpose `!![0, 1, 0; 0, 0, 1; 1, 0, 0]`, the
  three-cycle running the other way. -/
lemma su3Perm_inv_coe :
    (su3Perm⁻¹ : specialUnitaryGroup (Fin 3) ℂ).1 = !![0, 1, 0; 0, 0, 1; 1, 0, 0] := by
  rw [← Matrix.star_eq_inv, Matrix.specialUnitaryGroup.coe_star, su3Perm_coe]
  ext a b
  fin_cases a <;> fin_cases b <;> simp

/-- The cyclic element cubes to the identity, so it has order three in `SU(3)`. This is why
  the grading group below is `ZMod 3`. -/
lemma su3Perm_pow_three : su3Perm ^ 3 = 1 := by
  ext a b
  rw [SubmonoidClass.coe_pow, su3Perm_coe]
  fin_cases a <;> fin_cases b <;>
    simp [pow_succ, Matrix.mul_apply, Fin.sum_univ_three]

/-- The cyclic element as a gauge transformation: trivial on isospin and hypercharge. -/
noncomputable def gaugeSU3Perm : GaugeGroupI := ⟨su3Perm, 1, 1⟩

/-!

## B. The cube-root character of `ZMod 3`

-/

/-- The primitive cube root of unity `ω = exp (2 π i / 3)`. -/
noncomputable def su3Omega : ℂ := Complex.exp (2 * (Real.pi : ℂ) * Complex.I / 3)

/-- `ω` is a primitive cube root of unity. -/
lemma su3Omega_isPrimitiveRoot : IsPrimitiveRoot su3Omega 3 := by
  have h := Complex.isPrimitiveRoot_exp 3 (by norm_num)
  simpa [su3Omega] using h

/-- `ω` cubes to one. -/
@[simp] lemma su3Omega_pow_three : su3Omega ^ 3 = 1 :=
  su3Omega_isPrimitiveRoot.pow_eq_one

/-- `ω` is nonzero, being a value of the complex exponential. -/
lemma su3Omega_ne_zero : su3Omega ≠ 0 := Complex.exp_ne_zero _

/-- Powers of `ω` only see the exponent modulo three. -/
lemma su3Omega_pow_mod (m : ℕ) : su3Omega ^ (m % 3) = su3Omega ^ m := by
  conv_rhs => rw [← Nat.div_add_mod m 3]
  rw [pow_add, pow_mul, su3Omega_pow_three, one_pow, one_mul]

/-- The cube root of unity `ω ^ k` attached to a grade `k : ZMod 3`: the eigenvalue of the
  cyclic element on the `k` piece of a decomposition. -/
noncomputable def su3PermSign (k : ZMod 3) : ℂ := su3Omega ^ k.val

/-- The grade-zero sign is `1`. -/
@[simp] lemma su3PermSign_zero : su3PermSign 0 = 1 := by
  rw [su3PermSign, show (0 : ZMod 3).val = 0 from by decide, pow_zero]

/-- The grade-one sign is `ω`. -/
@[simp] lemma su3PermSign_one : su3PermSign 1 = su3Omega := by
  rw [su3PermSign, show (1 : ZMod 3).val = 1 from by decide, pow_one]

/-- The grade-two sign is `ω ^ 2`. -/
@[simp] lemma su3PermSign_two : su3PermSign 2 = su3Omega ^ 2 := by
  rw [su3PermSign, show (2 : ZMod 3).val = 2 from by decide]

/-- The sign is a character: grades add under multiplication because the cube roots of
  unity multiply. -/
lemma su3PermSign_add (k l : ZMod 3) :
    su3PermSign (k + l) = su3PermSign k * su3PermSign l := by
  rw [su3PermSign, su3PermSign, su3PermSign, ZMod.val_add, su3Omega_pow_mod, pow_add]

/-- Every sign is nonzero, being a root of unity. -/
lemma su3PermSign_ne_zero (k : ZMod 3) : su3PermSign k ≠ 0 :=
  pow_ne_zero _ su3Omega_ne_zero

/-- The three cube roots of unity are distinct, so the pieces of a decomposition sit in
  eigenspaces at distinct eigenvalues and are automatically independent. -/
lemma su3PermSign_injective : Function.Injective su3PermSign := by
  intro k l hkl
  simp only [su3PermSign] at hkl
  exact ZMod.val_injective 3
    (su3Omega_isPrimitiveRoot.pow_inj (ZMod.val_lt k) (ZMod.val_lt l) hkl)

/-!

## C. `SU(3)` permutation decompositions

-/

variable {B : Type*} [Ring B] [Algebra ℂ B]

/-- An `SU(3)` permutation decomposition of a submodule `V`: a `ZMod 3`-graded family of
  subspaces of pure sign under the cyclic element `gaugeSU3Perm`, whose supremum is `V`.

  Unlike `GaugeWeightDecomposition` there is no support field — `ZMod 3` is finite, so the
  finiteness condition is automatic. The three grades carry the three cube roots of
  unity. -/
structure SU3PermDecomposition (rep : Representation ℂ GaugeGroupI B)
    (V : Submodule ℂ B) where
  /-- The grade `k` piece of the decomposition. -/
  piece : ZMod 3 → Submodule ℂ B
  /-- Each piece is of pure sign under the cyclic element. -/
  piece_le : ∀ k, ∀ x, x ∈ piece k → rep gaugeSU3Perm x = su3PermSign k • x
  /-- The pieces exhaust `V`. -/
  iSup_piece : (⨆ k, piece k) = V

namespace SU3PermDecomposition

variable {rep : Representation ℂ GaugeGroupI B} {V V' : Submodule ℂ B}

/-- The grade-`k` piece lies in the `su3PermSign k` eigenspace of the cyclic element. This
  is `piece_le` phrased as an inequality of submodules. -/
lemma piece_le_eigenspace (d : SU3PermDecomposition rep V) (k : ZMod 3) :
    d.piece k ≤ Module.End.eigenspace (rep gaugeSU3Perm) (su3PermSign k) :=
  fun _ hy => Module.End.mem_eigenspace_iff.mpr (d.piece_le k _ hy)

/-- Transport a decomposition along an equality of submodules. -/
def copy (d : SU3PermDecomposition rep V) (W : Submodule ℂ B) (hW : W = V) :
    SU3PermDecomposition rep W where
  piece := d.piece
  piece_le := d.piece_le
  iSup_piece := by rw [d.iSup_piece, hW]

/-- Copying leaves the pieces unchanged. -/
@[simp]
lemma copy_piece (d : SU3PermDecomposition rep V) (W : Submodule ℂ B) (hW : W = V) :
    (d.copy W hW).piece = d.piece := rfl

/-- The zero submodule carries the trivial decomposition, with every grade empty. This is
  the unit for `sup`, and the decomposition of every submodule that turns out to vanish. -/
def bot : SU3PermDecomposition rep (⊥ : Submodule ℂ B) where
  piece _ := ⊥
  piece_le k x hx := by
    rw [Submodule.mem_bot] at hx
    subst hx
    simp
  iSup_piece := by simp

/-- Every piece of the trivial decomposition is the zero submodule. -/
@[simp]
lemma bot_piece (k : ZMod 3) : (bot (rep := rep)).piece k = ⊥ := rfl

/-!

## D. Joins

-/

/-- The join of two decompositions: the pieces and suprema combine gradewise, decomposing
  `V ⊔ V'`. -/
noncomputable def sup (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V') :
    SU3PermDecomposition rep (V ⊔ V') where
  piece k := d.piece k ⊔ d'.piece k
  piece_le k x hx :=
    Module.End.mem_eigenspace_iff.mp
      (sup_le (d.piece_le_eigenspace k) (d'.piece_le_eigenspace k) hx)
  iSup_piece := by
    rw [iSup_sup_eq, d.iSup_piece, d'.iSup_piece]

/-- The pieces of a join are the joins of the pieces. -/
@[simp]
lemma sup_piece (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V')
    (k : ZMod 3) : (d.sup d').piece k = d.piece k ⊔ d'.piece k := rfl

/-!

## E. Products

-/

/-- The product of two decompositions: grades add under multiplication, so the grade-`k`
  piece of `V * V'` is spanned by the products of pieces whose grades sum to `k`.

  Multiplicativity of the representation is a hypothesis rather than a field: a
  `Representation` records only a linear action. -/
noncomputable def mul (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V') :
    SU3PermDecomposition rep (V * V') where
  piece k := ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂
  piece_le k x hx := by
    have key : (⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂)
        ≤ Module.End.eigenspace (rep gaugeSU3Perm) (su3PermSign k) := by
      refine iSup_le fun k₁ => iSup_le fun k₂ => iSup_le fun hk => ?_
      refine Submodule.mul_le.mpr fun m hm n hn => ?_
      refine Module.End.mem_eigenspace_iff.mpr ?_
      rw [hmul, d.piece_le k₁ m hm, d'.piece_le k₂ n hn, smul_mul_smul_comm,
        ← su3PermSign_add, hk]
    exact Module.End.mem_eigenspace_iff.mp (key hx)
  iSup_piece := by
    refine le_antisymm (iSup_le fun k => iSup_le fun k₁ => iSup_le fun k₂ =>
      iSup_le fun _ => ?_) ?_
    · exact mul_le_mul' ((le_iSup d.piece k₁).trans d.iSup_piece.le)
        ((le_iSup d'.piece k₂).trans d'.iSup_piece.le)
    · have hV : (⨆ k₁, d.piece k₁) * (⨆ k₂, d'.piece k₂) = V * V' := by
        rw [d.iSup_piece, d'.iSup_piece]
      rw [← hV, Submodule.iSup_mul]
      refine iSup_le fun k₁ => ?_
      rw [Submodule.mul_iSup]
      refine iSup_le fun k₂ => ?_
      exact le_iSup_of_le (k₁ + k₂)
        (le_iSup_of_le k₁ (le_iSup_of_le k₂ (le_iSup_of_le rfl le_rfl)))

/-- The grade-`k` piece of a product, as a double join over pairs of grades summing to
  `k`. -/
lemma mul_piece (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V') (k : ZMod 3) :
    (d.mul hmul d').piece k = ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂ := rfl

/-- The grade-`k` piece of a product, with the second grade solved for: the double join
  collapses to a single one. -/
lemma mul_piece_eq_sub
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V') (k : ZMod 3) :
    (d.mul hmul d').piece k = ⨆ k₁, d.piece k₁ * d'.piece (k - k₁) := by
  rw [mul_piece]
  refine le_antisymm (iSup_le fun k₁ => iSup_le fun k₂ => iSup_le fun hk => ?_) ?_
  · exact le_iSup_of_le k₁ (by rw [eq_sub_of_add_eq' hk])
  · exact iSup_le fun k₁ =>
      le_iSup_of_le k₁ (le_iSup_of_le (k - k₁) (le_iSup_of_le (add_sub_cancel k₁ k) le_rfl))

/-- The grade-`k` piece of a product, written out. `ZMod 3` has three elements, so the
  join is a three-term one. -/
lemma mul_piece_eq (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (d' : SU3PermDecomposition rep V') (k : ZMod 3) :
    (d.mul hmul d').piece k
      = d.piece 0 * d'.piece k ⊔ d.piece 1 * d'.piece (k - 1)
        ⊔ d.piece 2 * d'.piece (k - 2) := by
  have hcases : ∀ j : ZMod 3, j = 0 ∨ j = 1 ∨ j = 2 := by decide
  rw [mul_piece_eq_sub]
  refine le_antisymm (iSup_le fun k₁ => ?_) (sup_le (sup_le ?_ ?_) ?_)
  · rcases hcases k₁ with rfl | rfl | rfl
    · rw [sub_zero]
      exact le_sup_of_le_left le_sup_left
    · exact le_sup_of_le_left le_sup_right
    · exact le_sup_right
  · exact le_iSup_of_le 0 (by rw [sub_zero])
  · exact le_iSup_of_le 1 le_rfl
  · exact le_iSup_of_le 2 le_rfl

/-- The unit submodule has grade zero: the identity of `B` is fixed by every gauge
  transformation, provided the representation preserves the unit. -/
noncomputable def one (hone : ∀ g : GaugeGroupI, rep g 1 = 1) :
    SU3PermDecomposition rep (1 : Submodule ℂ B) where
  piece k := if k = 0 then 1 else ⊥
  piece_le := by
    intro k x hx
    rcases eq_or_ne k 0 with rfl | hk
    · rw [if_pos rfl, Submodule.one_eq_span, Submodule.mem_span_singleton] at hx
      obtain ⟨c, rfl⟩ := hx
      rw [map_smul, hone, su3PermSign_zero, one_smul]
    · rw [if_neg hk, Submodule.mem_bot] at hx
      subst hx
      simp
  iSup_piece := by
    refine le_antisymm (iSup_le fun k => ?_) (le_iSup_of_le 0 (le_of_eq (if_pos rfl).symm))
    by_cases hk : k = 0
    · rw [if_pos hk]
    · rw [if_neg hk]
      exact bot_le

/-- The unit decomposition is concentrated in grade zero. -/
@[simp]
lemma one_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1) (k : ZMod 3) :
    (one (B := B) (rep := rep) hone).piece k = if k = 0 then 1 else ⊥ := rfl

/-- Powers of a decomposed submodule: grades add, so `V ^ n` inherits a decomposition, built
  by iterating `mul` from `one`. -/
noncomputable def pow (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) :
    (n : ℕ) → SU3PermDecomposition rep (V ^ n)
  | 0 => (one hone).copy _ (pow_zero V)
  | (n + 1) => ((pow hone hmul d n).mul hmul d).copy _ (pow_succ V n)

/-- The zeroth power decomposition is the unit one. -/
@[simp]
lemma pow_zero_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (k : ZMod 3) :
    (d.pow hone hmul 0).piece k = if k = 0 then 1 else ⊥ := rfl

/-- The pieces of a successor power, unfolded one step of `mul`. -/
@[simp]
lemma pow_succ_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU3PermDecomposition rep V) (n : ℕ) (k : ZMod 3) :
    (d.pow hone hmul (n + 1)).piece k
      = ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, (d.pow hone hmul n).piece k₁ * d.piece k₂ := rfl

/-!

## F. Invariants

-/

/-- A gauge-invariant element has grade zero. Only invariance under the single cyclic
  element `gaugeSU3Perm` is used: the other pieces lie in eigenspaces at `ω` and `ω ^ 2`,
  both distinct from `1`.

  There is no converse; see the warning in the module docstring. -/
lemma mem_zero_of_invariant (d : SU3PermDecomposition rep V) {x : B} (hx : x ∈ V)
    (hV : ∀ g : GaugeGroupI, rep g x = x) : x ∈ d.piece 0 := by
  have hdisj : Disjoint
      (Module.End.eigenspace (rep gaugeSU3Perm) (su3PermSign 0))
      (⨆ k, ⨆ _ : k ≠ (0 : ZMod 3), d.piece k) :=
    (((Module.End.eigenspaces_iSupIndep (rep gaugeSU3Perm : Module.End ℂ B)).comp
      su3PermSign_injective) 0).mono_right (iSup₂_mono fun k _ => d.piece_le_eigenspace k)
  have key : (⨆ k, d.piece k)
      ⊓ Module.End.eigenspace (rep gaugeSU3Perm) (su3PermSign 0) ≤ d.piece 0 := by
    rw [iSup_split_single d.piece 0, sup_inf_assoc_of_le _ (d.piece_le_eigenspace 0)]
    exact sup_le le_rfl (hdisj.symm.le_bot.trans bot_le)
  refine key ⟨?_, Module.End.mem_eigenspace_iff.mpr ?_⟩
  · rw [d.iSup_piece]
    exact hx
  · rw [su3PermSign_zero, one_smul]
    exact hV _

end SU3PermDecomposition
end StandardModel
