/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.HiggsBoson.Basic
public import Physlib.Particles.StandardModel.JetAlgebra.CovJetAlgebra.Higgs
public import Physlib.Relativity.IsLorentzDeriv
public import Physlib.Relativity.LightConeDeriv
public import Physlib.Relativity.SL2C.AxisRotations
public import Physlib.Particles.StandardModel.GaugeGroup.JetGaugeGroup.Basic
public import Physlib.Relativity.LorentzGroup.Boosts.WeightGrading
public import Physlib.Particles.StandardModel.GaugeGroup.GaugeWeightDecomposition
public import Physlib.Particles.StandardModel.GaugeGroup.SU2PermDecomposition
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.JetDeriv
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.LorentzAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.GaugeAction
public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.MassDim
public import Mathlib.LinearAlgebra.TensorProduct.Pi
public import Mathlib.Analysis.Normed.Lp.Matrix
public import Mathlib.RingTheory.TensorProduct.Maps
public import Mathlib.RepresentationTheory.Invariants
/-!
# The algebra valued Higgs boson

An algebra `B` carries a Higgs sector when the covariant towers `∇_l H` and `∇_l H̄`, and
every polynomial expression in them, sit inside it compatibly with the global gauge action,
the Lorentz action and the mass-weight grading. `CovHiggsJetAlgebra` is the universal object
with those towers, so the statement is a single one: an algebra map
`CovHiggsJetAlgebra →ₐ[ℂ] B`, equivariant for the global gauge group and the Lorentz group
and compatible with `massWeightPoly`. That is the structure `HiggsAlgebraCovRealization`, together with
the two demands that the group actions be multiplicative on the whole of `B`.

The two towers are then derived: `h.covH` and `h.covBarH` are the covariant jet algebra of
the Higgs field's own towers pushed along the map, and every law they satisfy — the gauge
equivariance `H_equivariant` and `barH_equivariant`, the commutation `H_comm_H`,
`H_comm_barH` and `barH_comm_barH`, the mass weights `H_massWeight` and `barH_massWeight`,
and the Lorentz laws `repLorentz_H` and `repLorentz_barH` — is that algebra's own law
pushed along it. They carry the names they carried when they were axioms, so they are used
exactly as before.

We let `higgsSubmodule` be the submodule of `B` generated by the images of `covH`,
and `barHiggsSubmodule` be the submodule of `B` generated by the images of `covBarH`.

The algebra `B` carries a grading due to hypercharge, through its representation
of the global gauge group. This grading can be used to eliminate
a large collection of the possible terms in the lagrangian.

We want to consider invariants within
- `higgsSubModule * barHiggsSubModule`

We also want to consider derivatives.

The invariance involving the Higgs fields, up to
mass-dimension 4 are given by:
`H^† D_μ D_μ H`,`H D_μ D_μ H^†`, `D_μ H D_μ H^†`, `H H^†` and `(H^† H)^2`.

So let
`x := a0 TT + a1 XX + a2 YY + a3 ZZ`.

Write `M := TT - XX - YY - ZZ` for the target, and abbreviate the three coefficients
appearing in the conditions by
`u := a0 + a1`, `v := a0 + a2`, `w := a0 + a3`.
Expanding `M` gives the identity
`x = a0 M + u XX + v YY + w ZZ`.

Rotational average gives
`x = a0 M + (u + v + w)/3  (XX + YY + ZZ)`.

while the three boost conditions read `u (TT + XX) = 0`, `v (TT + YY) = 0` and
`w (TT + ZZ) = 0`, that is `u XX = - u TT`, `v YY = - v TT` and `w ZZ = - w TT`.
Substituting these in,
`x = a0 M - (u + v + w) TT`.

So we must have that `(u+v+w) TT = (u+v+w) M / 4`, and hence
`x = ( a0 - (u + v + w) / 4 ) M`.
-/

@[expose] public section

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 1000000
set_option synthInstance.maxSize 2048
set_option maxRecDepth 8000

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz Lorentz.SL2C

/-- The algebra `B`, with a gauge action, a Lorentz action and a mass-weight grading,
  carries a Higgs sector when it receives an algebra map from the covariant jet algebra of
  the Higgs field which is equivariant for both actions and compatible with the grading.
  The covariant towers `∇_l H` and `∇_l H̄` then sit inside `B` as the images of that
  algebra's own, and every law they satisfy there is its law pushed along the map.

  It is the Higgs-sector counterpart of `CovAlgebraRealization`, and stands to
  `CovHiggsJetAlgebra` as that does to `CovJetAlgebra`.

  The last two fields are not consequences of the first three: an equivariant map forces
  the two actions to be multiplicative only on its image, whereas the sector needs them
  multiplicative on the whole of `B`. -/
structure HiggsAlgebraCovRealization (B : Type) [Ring B] [Algebra ℂ B]
    (rep : Representation ℂ GaugeGroupI B)
    (repLorentz : Representation ℂ SL(2,ℂ) B)
    (massWeightPoly : B →ₐ[ℂ] Polynomial B) where
  /-- The algebra map out of the covariant jet algebra of the Higgs field: it is what
    places the Higgs towers, and every polynomial expression in them, inside `B`. -/
  toAlgHom : CovHiggsJetAlgebra →ₐ[ℂ] B
  /-- The map is equivariant for the global gauge group. -/
  map_rep : ∀ (g : GaugeGroupI) (x : CovHiggsJetAlgebra),
    toAlgHom (CovHiggsJetAlgebra.repGaugeGroupI g x) = rep g (toAlgHom x)
  /-- The map is equivariant for the Lorentz group. -/
  map_repLorentz : ∀ (Λ : SL(2,ℂ)) (x : CovHiggsJetAlgebra),
    toAlgHom (CovHiggsJetAlgebra.repLorentzGroup Λ x) = repLorentz Λ (toAlgHom x)
  /-- The map carries the mass-weight grading of the covariant jet algebra of the Higgs
    field to that of `B`. -/
  map_massWeight : ∀ x : CovHiggsJetAlgebra, massWeightPoly (toAlgHom x)
    = Polynomial.mapAlgHom toAlgHom (CovHiggsJetAlgebra.massWeightPoly x)
  /-- Gauge transformations act on `B` by algebra maps. -/
  rep_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B), rep g (b₁ * b₂) = rep g b₁ * rep g b₂
  /-- Lorentz transformations act on `B` by algebra maps. -/
  repLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂

set_option linter.unusedVariables false
namespace HiggsAlgebraCovRealization

variable {B : Type} [Ring B] [Algebra ℂ B]
  {rep : Representation ℂ GaugeGroupI B}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly)

/-!

## A. The Higgs towers and their laws

The two towers the sector is written in are not data of the structure. They are the towers
of the covariant jet algebra of the Higgs field, carried into `B` along the defining
algebra map, and every law they satisfy is that algebra's law pushed along it.

-/

/-- The covariant derivatives `∇_l H` of the Higgs field inside `B`. -/
noncomputable def covH (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ HiggsVec →ₗ[ℂ] B :=
  h.toAlgHom.toLinearMap ∘ₗ CovHiggsJetAlgebra.higgsField l

/-- The covariant derivatives `∇_l H̄` of the conjugate Higgs field inside `B`. -/
noncomputable def covBarH (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B :=
  h.toAlgHom.toLinearMap ∘ₗ CovHiggsJetAlgebra.conjHiggsField l

/-- A gauge law of the covariant jet algebra of the Higgs field transports along the
  defining map. -/
lemma map_rep_eq {g : GaugeGroupI} {x y : CovHiggsJetAlgebra}
    (hxy : CovHiggsJetAlgebra.repGaugeGroupI g x = y) :
    rep g (h.toAlgHom x) = h.toAlgHom y := by
  rw [← h.map_rep, hxy]

/-- A mass-weight eigenvalue equation transports along the defining map. -/
lemma map_massWeight_monomial {n : ℕ} {x : CovHiggsJetAlgebra}
    (hx : CovHiggsJetAlgebra.massWeightPoly x = Polynomial.monomial n x) :
    massWeightPoly (h.toAlgHom x) = Polynomial.monomial n (h.toAlgHom x) := by
  rw [h.map_massWeight, hx, Polynomial.mapAlgHom_monomial]

/-- The Higgs symbol carries the dual of the gauge representation on `HiggsVec`: the
  `SU(2)` index transforms contragrediently, and the hypercharge character by `u⁻³`. -/
lemma H_equivariant (g : GaugeGroupI) (φ : Module.Dual ℂ HiggsVec) (n : ℕ)
    (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep g (h.covH n l φ) = h.covH n l (HiggsVec.repGaugeGroupI.dual g φ) :=
  h.map_rep_eq (CovHiggsJetAlgebra.repGaugeGroupI_higgsField g l φ)

/-- The conjugate Higgs symbol carries the conjugate-dual of the gauge representation:
  the physicists' `H^† ↦ H^† g^†`. -/
lemma barH_equivariant (g : GaugeGroupI) (φ : Module.Dual ℂ (ConjModule HiggsVec)) (n : ℕ)
    (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep g (h.covBarH n l φ) = h.covBarH n l (HiggsVec.repGaugeGroupI.conj.dual g φ) :=
  h.map_rep_eq (CovHiggsJetAlgebra.repGaugeGroupI_conjHiggsField g l φ)

/-- The Higgs is bosonic: two Higgs symbols commute. -/
lemma H_comm_H (φ ψ : Module.Dual ℂ HiggsVec) (n1 n2 : ℕ)
    (l1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (l2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    Commute (h.covH n1 l1 φ) (h.covH n2 l2 ψ) :=
  (CovHiggsJetAlgebra.commute_higgsField_higgsField l1 l2 φ ψ).map h.toAlgHom

/-- A Higgs symbol commutes with a conjugate Higgs symbol. -/
lemma H_comm_barH (φ : Module.Dual ℂ HiggsVec) (ψ : Module.Dual ℂ (ConjModule HiggsVec))
    (n1 n2 : ℕ) (l1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (l2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    Commute (h.covH n1 l1 φ) (h.covBarH n2 l2 ψ) :=
  (CovHiggsJetAlgebra.commute_higgsField_conjHiggsField l1 l2 φ ψ).map h.toAlgHom

/-- Two conjugate Higgs symbols commute. -/
lemma barH_comm_barH (φ ψ : Module.Dual ℂ (ConjModule HiggsVec)) (n1 n2 : ℕ)
    (l1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (l2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    Commute (h.covBarH n1 l1 φ) (h.covBarH n2 l2 ψ) :=
  (CovHiggsJetAlgebra.commute_conjHiggsField_conjHiggsField l1 l2 φ ψ).map h.toAlgHom

/-- The mass weight of the Higgs tower is `2 * (1 + n)`. -/
lemma H_massWeight (φ : Module.Dual ℂ HiggsVec) (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    massWeightPoly (h.covH n l φ) = Polynomial.monomial (2 * (1 + n)) (h.covH n l φ) :=
  h.map_massWeight_monomial (CovHiggsJetAlgebra.massWeightPoly_higgsField l φ)

/-- The mass weight of the conjugate Higgs tower is `2 * (1 + n)`. -/
lemma barH_massWeight (φ : Module.Dual ℂ (ConjModule HiggsVec)) (n : ℕ)
    (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    massWeightPoly (h.covBarH n l φ)
      = Polynomial.monomial (2 * (1 + n)) (h.covBarH n l φ) :=
  h.map_massWeight_monomial (CovHiggsJetAlgebra.massWeightPoly_conjHiggsField l φ)

/-- A Lorentz law of the covariant jet algebra of the Higgs field transports along the
  defining map. -/
lemma map_lorentz {V : Type} [AddCommGroup V] [Module ℂ V]
    {repV : Representation ℂ SL(2,ℂ) V}
    {G : {n : ℕ} → (Fin n → (Fin 1 ⊕ Fin 3)) → Module.Dual ℂ V →ₗ[ℂ] CovHiggsJetAlgebra}
    (hG : IsLorentzCovDerivTransforms CovHiggsJetAlgebra.repLorentzGroup repV G) :
    IsLorentzCovDerivTransforms repLorentz repV
      (fun {_n} l => h.toAlgHom.toLinearMap ∘ₗ G l) := by
  intro Λ n l φ
  show repLorentz Λ (h.toAlgHom (G l φ)) = _
  rw [← h.map_repLorentz, hG Λ n l φ, map_sum]
  exact Finset.sum_congr rfl fun p _ => map_smul h.toAlgHom _ _

/-- The Higgs tower transforms under the Lorentz group as the covariant derivatives of a
  Lorentz scalar: each derivative slot mixes by the Lorentz matrix, and the value index is
  inert. -/
lemma repLorentz_H : IsLorentzCovDerivTransforms repLorentz
    (Representation.trivial ℂ SL(2,ℂ) HiggsVec) (fun {n} => h.covH n) :=
  h.map_lorentz CovHiggsJetAlgebra.isLorentzCovDerivTransforms_higgsField

/-- The conjugate Higgs tower transforms as the covariant derivatives of a Lorentz scalar,
  through the conjugate of the trivial representation. -/
lemma repLorentz_barH : IsLorentzCovDerivTransforms repLorentz
    (Representation.trivial ℂ SL(2,ℂ) HiggsVec).conj (fun {n} => h.covBarH n) :=
  h.map_lorentz CovHiggsJetAlgebra.isLorentzCovDerivTransforms_conjHiggsField

include h in
/-- The pointwise form of the structure field `repLorentz_H`: the Lorentz action
  rotates the derivative indices of a Higgs symbol, and the value index is inert. -/
lemma repLorentz_H_apply (g : SL(2,ℂ)) (φ : Module.Dual ℂ HiggsVec) (n : ℕ)
    (l : Fin n → Fin 1 ⊕ Fin 3) :
    repLorentz g (h.covH n l φ) = ∑ (a : Fin n → Fin 1 ⊕ Fin 3),
      (∏ (i : Fin n), (((SL2C.toLorentzGroup g).1 (a i) (l i) : ℝ) : ℂ)) • h.covH n a φ := by
  simpa only [Representation.trivial_dual_apply] using h.repLorentz_H g n l φ

include h in
/-- The pointwise form of the structure field `repLorentz_barH`. -/
lemma repLorentz_barH_apply (g : SL(2,ℂ)) (φ : Module.Dual ℂ (ConjModule HiggsVec))
    (n : ℕ) (l : Fin n → Fin 1 ⊕ Fin 3) :
    repLorentz g (h.covBarH n l φ) = ∑ (a : Fin n → Fin 1 ⊕ Fin 3),
      (∏ (i : Fin n), (((SL2C.toLorentzGroup g).1 (a i) (l i) : ℝ) : ℂ)) • h.covBarH n a φ := by
  simpa only [Representation.conj_trivial_dual_apply] using h.repLorentz_barH g n l φ

/-!

## B. The basic generators and the submodules generated by them.

-/

/-- The component `∇_d H^i` in the algebra. -/
noncomputable def higgs  (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly)
    {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) (i : Fin 2) :B :=
  h.covH n d (HiggsVec.orthonormBasis.toBasis.dualBasis i)

/-- The component `∇_d barH^i` in the algebra. -/
noncomputable def barHiggs (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly)
    {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) (i : Fin 2) : B :=
  h.covBarH n d (HiggsVec.orthonormBasis.toBasis.conj.dualBasis i)

/-!

### A.1. The representation of the gauge group on the components

-/

lemma rep_higgsComponent (g : GaugeGroupI) {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) (i : Fin 2) :
    rep g (h.higgs d i) =
      ∑ j, (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j) • h.higgs d j := by
  have key : HiggsVec.repGaugeGroupI.dual g (HiggsVec.orthonormBasis.toBasis.dualBasis i)
      = ∑ j, (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j) •
          HiggsVec.orthonormBasis.toBasis.dualBasis j := by
    refine HiggsVec.orthonormBasis.toBasis.ext fun k => ?_
    rw [LinearMap.sum_apply]
    simp only [LinearMap.smul_apply, smul_eq_mul, Module.Basis.dualBasis_apply_self,
      mul_ite, mul_one, mul_zero, Finset.sum_ite_eq]
    simp [Representation.dual, HiggsVec.repGaugeGroupI_apply, HiggsVec.orthonormBasis,
      Submonoid.smul_def, -inv_pow]
  rw [higgs, h.H_equivariant, key, map_sum]
  exact Finset.sum_congr rfl fun j _ => by rw [map_smul]; rfl

lemma rep_barHiggsComponent (g : GaugeGroupI)  {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) (i : Fin 2) :
    rep g (h.barHiggs d i) =
      ∑ j, (starRingEnd ℂ (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j)) •  h.barHiggs d j := by
  have key : HiggsVec.repGaugeGroupI.conj.dual g
        (HiggsVec.orthonormBasis.toBasis.conj.dualBasis i)
      = ∑ j, (starRingEnd ℂ (((g⁻¹).toU1 : ℂ) ^ 3 * (g⁻¹).toSU2.1 i j)) •
          HiggsVec.orthonormBasis.toBasis.conj.dualBasis j := by
    refine HiggsVec.orthonormBasis.toBasis.conj.ext fun k => ?_
    rw [LinearMap.sum_apply]
    simp only [LinearMap.smul_apply, smul_eq_mul, Module.Basis.dualBasis_apply_self,
      mul_ite, mul_one, mul_zero, Finset.sum_ite_eq]
    simp [Representation.dual, Representation.conj_apply, HiggsVec.repGaugeGroupI_apply,
      HiggsVec.orthonormBasis, Submonoid.smul_def, -inv_pow]
  rw [barHiggs, h.barH_equivariant, key, map_sum]
  exact Finset.sum_congr rfl fun j _ => by rw [map_smul]; rfl

/-!

### A.2. The submodules generated by the Higges and conjugate Higgs components

-/

/-- The submodule of `B` generated by the Higgs symbols carrying `n` derivatives: the join,
  over the Lorentz indices `d`, of the ranges of the symbol maps `H n d`. Its elements are
  the terms linear in `∇_d H` — of mass dimension `1 + n`. -/
noncomputable def higgsSubmodule (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly) (n : ℕ) :
    Submodule ℂ B := ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), LinearMap.range (h.covH n d)

/-- The submodule of `B` generated by the conjugate Higgs symbols carrying `n` derivatives:
  the join, over the Lorentz indices `d`, of the ranges of the symbol maps `barH n d`. -/
noncomputable def barHiggsSubmodule (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly)
    (n : ℕ) : Submodule ℂ B := ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), LinearMap.range (h.covBarH n d)

/-!

### A.n. Commutativity of higgs and barHiggsSubmodules

-/

@[simp]
lemma barHiggsSubmodule_comm_higgsSubmodule (n1 n2 : ℕ) :
    (h.barHiggsSubmodule n1) * (h.higgsSubmodule n2)
    =  (h.higgsSubmodule n2)  * (h.barHiggsSubmodule n1) := by
  have gen : ∀ (d1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule HiggsVec)),
      h.higgsSubmodule n2 ≤ LinearMap.ker (LinearMap.mulLeft ℂ (h.covBarH n1 d1 φ)
        - LinearMap.mulRight ℂ (h.covBarH n1 d1 φ)) := by
    intro d1 φ
    rw [higgsSubmodule]
    refine iSup_le fun d2 => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.H_comm_barH ψ φ n2 n1 d2 d1).symm.eq
  have key : ∀ x ∈ h.barHiggsSubmodule n1, ∀ y ∈ h.higgsSubmodule n2, x * y = y * x := by
    intro x hx y hy
    have step : h.barHiggsSubmodule n1
        ≤ LinearMap.ker (LinearMap.mulRight ℂ y - LinearMap.mulLeft ℂ y) := by
      rw [barHiggsSubmodule]
      refine iSup_le fun d1 => ?_
      rintro _ ⟨φ, rfl⟩
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
        LinearMap.mulLeft_apply, sub_eq_zero]
      have := gen d1 φ hy
      simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] using this
    have := step hx
    simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
      LinearMap.mulLeft_apply, sub_eq_zero] using this
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun y hy x hx => ?_)
  · rw [key x hx y hy]
    exact Submodule.mul_mem_mul hy hx
  · rw [← key x hx y hy]
    exact Submodule.mul_mem_mul hx hy

lemma higgsSubmodule_comm_higgsSubmodule (n1 n2 : ℕ) (h1 : n1 < n2) :
    (h.higgsSubmodule n1) * (h.higgsSubmodule n2)
    =  (h.higgsSubmodule n2)  * (h.higgsSubmodule n1) := by
  have gen : ∀ (d1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ HiggsVec),
      h.higgsSubmodule n2 ≤ LinearMap.ker (LinearMap.mulLeft ℂ (h.covH n1 d1 φ)
        - LinearMap.mulRight ℂ (h.covH n1 d1 φ)) := by
    intro d1 φ
    rw [higgsSubmodule]
    refine iSup_le fun d2 => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.H_comm_H φ ψ n1 n2 d1 d2).eq
  have key : ∀ x ∈ h.higgsSubmodule n1, ∀ y ∈ h.higgsSubmodule n2, x * y = y * x := by
    intro x hx y hy
    have step : h.higgsSubmodule n1
        ≤ LinearMap.ker (LinearMap.mulRight ℂ y - LinearMap.mulLeft ℂ y) := by
      rw [higgsSubmodule]
      refine iSup_le fun d1 => ?_
      rintro _ ⟨φ, rfl⟩
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
        LinearMap.mulLeft_apply, sub_eq_zero]
      have := gen d1 φ hy
      simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] using this
    have := step hx
    simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
      LinearMap.mulLeft_apply, sub_eq_zero] using this
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun y hy x hx => ?_)
  · rw [key x hx y hy]
    exact Submodule.mul_mem_mul hy hx
  · rw [← key x hx y hy]
    exact Submodule.mul_mem_mul hx hy

lemma barHiggsSubmodule_comm_barHiggsSubmodule (n1 n2 : ℕ) (h1 : n1 < n2) :
    (h.barHiggsSubmodule n1) * (h.barHiggsSubmodule n2)
    =  (h.barHiggsSubmodule n2)  * (h.barHiggsSubmodule n1) := by
  have gen : ∀ (d1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule HiggsVec)),
      h.barHiggsSubmodule n2 ≤ LinearMap.ker (LinearMap.mulLeft ℂ (h.covBarH n1 d1 φ)
        - LinearMap.mulRight ℂ (h.covBarH n1 d1 φ)) := by
    intro d1 φ
    rw [barHiggsSubmodule]
    refine iSup_le fun d2 => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.barH_comm_barH φ ψ n1 n2 d1 d2).eq
  have key : ∀ x ∈ h.barHiggsSubmodule n1, ∀ y ∈ h.barHiggsSubmodule n2, x * y = y * x := by
    intro x hx y hy
    have step : h.barHiggsSubmodule n1
        ≤ LinearMap.ker (LinearMap.mulRight ℂ y - LinearMap.mulLeft ℂ y) := by
      rw [barHiggsSubmodule]
      refine iSup_le fun d1 => ?_
      rintro _ ⟨φ, rfl⟩
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
        LinearMap.mulLeft_apply, sub_eq_zero]
      have := gen d1 φ hy
      simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] using this
    have := step hx
    simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
      LinearMap.mulLeft_apply, sub_eq_zero] using this
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun y hy x hx => ?_)
  · rw [key x hx y hy]
    exact Submodule.mul_mem_mul hy hx
  · rw [← key x hx y hy]
    exact Submodule.mul_mem_mul hx hy

/-!

### A.3. The closure of the Higgs and conjugate Higgs submodules under the gauge group

-/

lemma higgsSubmodule_map_rep_le (n : ℕ) (g : GaugeGroupI) :
    (h.higgsSubmodule n).map (rep g) ≤ h.higgsSubmodule n := by
  rw [higgsSubmodule, Submodule.map_iSup]
  refine iSup_le fun d => ?_
  rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
  exact Submodule.mem_iSup_of_mem d
    ⟨HiggsVec.repGaugeGroupI.dual g φ, (h.H_equivariant g φ n d).symm⟩

lemma barHiggsSubmodule_map_rep_le (n : ℕ) (g : GaugeGroupI) :
    (h.barHiggsSubmodule n).map (rep g) ≤ h.barHiggsSubmodule n := by
  rw [barHiggsSubmodule, Submodule.map_iSup]
  refine iSup_le fun d => ?_
  rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
  exact Submodule.mem_iSup_of_mem d
    ⟨HiggsVec.repGaugeGroupI.conj.dual g φ, (h.barH_equivariant g φ n d).symm⟩

/-!

### A.4. The gauge decomposition

-/

/-!

#### A.4.1. The action of the gauge torus on the Higgs components

-/

lemma rep_gaugeTorusGen_higgs_zero (i : Fin 4) {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep (gaugeTorusGen i) (h.higgs d 0)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, -3) i) • h.higgs d 0 := by
  have hstar : ((starRingEnd ℂ) (expI : ℂ)) ^ 3 = (((expI : ℂ)) ^ 3)⁻¹ := by
    rw [← inv_pow]
    congr 1
    exact expI_inv_eq_star.symm
  rw [h.rep_higgsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, expI_inv_eq_star, Matrix.one_apply, Unitary.coe_inv, hstar]

lemma rep_gaugeTorusGen_higg_one (i : Fin 4) {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep (gaugeTorusGen i) (h.higgs d 1)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, -3) i) • h.higgs d 1 := by
  have hstar : ((starRingEnd ℂ) (expI : ℂ)) ^ 3 = (((expI : ℂ)) ^ 3)⁻¹ := by
    rw [← inv_pow]
    congr 1
    exact expI_inv_eq_star.symm
  rw [h.rep_higgsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, expI_inv_eq_star, Matrix.one_apply, Unitary.coe_inv, hstar]

lemma rep_gaugeTorusGen_barHiggsComponent_zero (i : Fin 4) {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep (gaugeTorusGen i) (h.barHiggs d 0)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, 3) i) • h.barHiggs d 0 := by
  have hc : (starRingEnd ℂ) (expI : ℂ) = ((expI : ℂ))⁻¹ := expI_inv_eq_star.symm
  rw [h.rep_barHiggsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, Matrix.one_apply, Unitary.coe_inv, hc]

lemma rep_gaugeTorusGen_barHiggsComponent_one (i : Fin 4) {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep (gaugeTorusGen i) (h.barHiggs d 1)
      = ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, 3) i) • h.barHiggs d 1 := by
  have hc : (starRingEnd ℂ) (expI : ℂ) = ((expI : ℂ))⁻¹ := expI_inv_eq_star.symm
  rw [h.rep_barHiggsComponent]
  fin_cases i <;>
    simp [gaugeTorusGen, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2ExpI_inv_coe,
      Fin.sum_univ_two, Matrix.one_apply, Unitary.coe_inv, hc]

/-!

#### A.4.1b. The action of the Weyl element on the Higgs components

-/

lemma rep_gaugeSU2Perm_higgsComponent_zero {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.higgs d 0) = h.higgs d 1 := by
  rw [h.rep_higgsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe, Fin.sum_univ_two]

lemma rep_gaugeSU2Perm_higgsComponent_one {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.higgs d 1) = -h.higgs d 0 := by
  rw [h.rep_higgsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe, Fin.sum_univ_two]

lemma rep_gaugeSU2Perm_barHiggsComponent_zero {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.barHiggs d 0) = h.barHiggs d 1 := by
  rw [h.rep_barHiggsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe, Fin.sum_univ_two]

lemma rep_gaugeSU2Perm_barHiggsComponent_one {n : ℕ} (d : Fin n → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.barHiggs d 1) = -h.barHiggs d 0 := by
  rw [h.rep_barHiggsComponent]
  simp [gaugeSU2Perm, GaugeGroupI.toU1, GaugeGroupI.toSU2, su2Perm_inv_coe, Fin.sum_univ_two]

/-- The mass-term pairing `∇H⁰ ∇H̄⁰ + ∇H¹ ∇H̄¹` is invariant under the Weyl element,
  for any derivative indices on the two factors. -/
lemma rep_gaugeSU2Perm_higgsBarHiggs_add {n1 n2 : ℕ} (d1 : Fin n1 → (Fin 1 ⊕ Fin 3))
    (d2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.higgs d1 0 * h.barHiggs d2 0 + h.higgs d1 1 * h.barHiggs d2 1)
      = h.higgs d1 0 * h.barHiggs d2 0 + h.higgs d1 1 * h.barHiggs d2 1 := by
  rw [map_add, h.rep_mul, h.rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
    h.rep_gaugeSU2Perm_barHiggsComponent_zero, h.rep_gaugeSU2Perm_higgsComponent_one,
    h.rep_gaugeSU2Perm_barHiggsComponent_one, neg_mul_neg, add_comm]

/-- The triplet-term pairing `∇H⁰ ∇H̄⁰ - ∇H¹ ∇H̄¹` changes sign under the Weyl element,
  for any derivative indices on the two factors. -/
lemma rep_gaugeSU2Perm_higgsBarHiggs_sub {n1 n2 : ℕ} (d1 : Fin n1 → (Fin 1 ⊕ Fin 3))
    (d2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    rep gaugeSU2Perm (h.higgs d1 0 * h.barHiggs d2 0 - h.higgs d1 1 * h.barHiggs d2 1)
      = -(h.higgs d1 0 * h.barHiggs d2 0 - h.higgs d1 1 * h.barHiggs d2 1) := by
  rw [map_sub, h.rep_mul, h.rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
    h.rep_gaugeSU2Perm_barHiggsComponent_zero, h.rep_gaugeSU2Perm_higgsComponent_one,
    h.rep_gaugeSU2Perm_barHiggsComponent_one, neg_mul_neg, neg_sub]

/-- The diagonal quartic combination `(H⁰H̄⁰)² + (H¹H̄¹)²` is invariant under the Weyl
  element. -/
lemma rep_gaugeSU2Perm_quartic_add :
    rep gaugeSU2Perm (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
      + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
    = h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
      + h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1 := by
  simp only [map_add, h.rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
    h.rep_gaugeSU2Perm_higgsComponent_one, h.rep_gaugeSU2Perm_barHiggsComponent_zero,
    h.rep_gaugeSU2Perm_barHiggsComponent_one, mul_neg, neg_mul, neg_neg]
  rw [add_comm]

/-- The diagonal quartic combination `(H⁰H̄⁰)² - (H¹H̄¹)²` changes sign under the Weyl
  element. -/
lemma rep_gaugeSU2Perm_quartic_sub :
    rep gaugeSU2Perm (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
      - h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1)
    = -(h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 0 * h.barHiggs ![] 0
      - h.higgs ![] 1 * h.barHiggs ![] 1 * h.higgs ![] 1 * h.barHiggs ![] 1) := by
  simp only [map_sub, h.rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
    h.rep_gaugeSU2Perm_higgsComponent_one, h.rep_gaugeSU2Perm_barHiggsComponent_zero,
    h.rep_gaugeSU2Perm_barHiggsComponent_one, mul_neg, neg_mul, neg_neg]
  rw [neg_sub]

/-- The mixed quartic `H⁰H̄⁰H¹H̄¹` is invariant under the Weyl element. -/
lemma rep_gaugeSU2Perm_quartic_mixed :
    rep gaugeSU2Perm (h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1)
    = h.higgs ![] 0 * h.barHiggs ![] 0 * h.higgs ![] 1 * h.barHiggs ![] 1 := by
  have hbh2 : ∀ (a b : Fin 2), h.barHiggs ![] a * h.higgs ![] b
      = h.higgs ![] b * h.barHiggs ![] a :=
    fun a b => ((h.H_comm_barH _ _ _ _ _ _).symm).eq
  have hhh' : ∀ (c : B), h.higgs ![] 1 * (h.higgs ![] 0 * c)
      = h.higgs ![] 0 * (h.higgs ![] 1 * c) :=
    fun c => (h.H_comm_H _ _ _ _ _ _).left_comm c
  have hbb2 : h.barHiggs ![] 1 * h.barHiggs ![] 0 = h.barHiggs ![] 0 * h.barHiggs ![] 1 :=
    (h.barH_comm_barH _ _ _ _ _ _).eq
  simp only [h.rep_mul, h.rep_gaugeSU2Perm_higgsComponent_zero,
    h.rep_gaugeSU2Perm_higgsComponent_one, h.rep_gaugeSU2Perm_barHiggsComponent_zero,
    h.rep_gaugeSU2Perm_barHiggsComponent_one, mul_neg, neg_mul, neg_neg,
    mul_assoc, hbh2, hhh', hbb2]

/-!

#### A.4.2. The gauge decomposition on the Higgs submodule

-/

@[simps!]
noncomputable instance higgsSubmoduleGaugeWeight (n : ℕ) :
    GaugeWeightDecomposition rep (h.higgsSubmodule n) where
  rep_mul := h.rep_mul
  piece := fun w =>
    if w = (0, 0, -1, -3) then ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.higgs d 0}
    else if w = (0, 0, 1, -3) then ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.higgs d 1}
    else ⊥
  supp := {(0, 0, -1, -3), (0, 0, 1, -3)}
  piece_le := by
    have hz : ∀ i : Fin 4, (⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.higgs d 0})
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, -3) i) := fun i =>
      iSup_le fun d => (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_higgs_zero i d))
    have ho : ∀ i : Fin 4, (⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.higgs d 1})
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, -3) i) := fun i =>
      iSup_le fun d => (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_higg_one i d))
    intro w x hx i
    rcases eq_or_ne w (0, 0, -1, -3) with rfl | hw0
    · rw [if_pos rfl] at hx
      exact Module.End.mem_eigenspace_iff.mp (hz i hx)
    · rcases eq_or_ne w (0, 0, 1, -3) with rfl | hw1
      · rw [if_neg hw0, if_pos rfl] at hx
        exact Module.End.mem_eigenspace_iff.mp (ho i hx)
      · rw [if_neg hw0, if_neg hw1, Submodule.mem_bot] at hx
        subst hx
        simp
  piece_eq_bot := by
    intro w hw
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hw
    rw [if_neg hw.1, if_neg hw.2]
  iSup_piece := by
    have hrange : ∀ d : Fin n → (Fin 1 ⊕ Fin 3),
        LinearMap.range (h.covH n d) = Submodule.span ℂ (Set.range (h.higgs d)) := fun d => by
      rw [LinearMap.range_eq_map, ← (HiggsVec.orthonormBasis.toBasis.dualBasis).span_eq,
        Submodule.map_span, ← Set.range_comp]
      rfl
    have hmem : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (j : Fin 2),
        h.higgs d j ∈ h.higgsSubmodule n := fun d j =>
      Submodule.mem_iSup_of_mem d ⟨HiggsVec.orthonormBasis.toBasis.dualBasis j, rfl⟩
    refine le_antisymm (iSup_le fun w => ?_) ?_
    · rcases eq_or_ne w (0, 0, -1, -3) with rfl | hw0
      · rw [if_pos rfl]
        exact iSup_le fun d =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem d 0)
      · rcases eq_or_ne w (0, 0, 1, -3) with rfl | hw1
        · rw [if_neg hw0, if_pos rfl]
          exact iSup_le fun d =>
            (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem d 1)
        · rw [if_neg hw0, if_neg hw1]
          exact bot_le
    · rw [higgsSubmodule]
      refine iSup_le fun d => ?_
      rw [hrange d, Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      fin_cases j
      · refine Submodule.mem_iSup_of_mem (0, 0, -1, -3) ?_
        rw [if_pos rfl]
        exact Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _)
      · refine Submodule.mem_iSup_of_mem (0, 0, 1, -3) ?_
        rw [if_neg (by decide), if_pos rfl]
        exact Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _)

/-!

#### A.4.2. The gauge decomposition on the conjugate Higgs submodule

-/

@[simps!]
noncomputable instance barHiggsSubmoduleGaugeWeight (n : ℕ) :
    GaugeWeightDecomposition rep (h.barHiggsSubmodule n) where
  rep_mul := h.rep_mul
  piece := fun w =>
    if w = (0, 0, 1, 3) then ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.barHiggs d 0}
    else if w = (0, 0, -1, 3) then
      ⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.barHiggs d 1}
    else ⊥
  supp := {(0, 0, 1, 3), (0, 0, -1, 3)}
  piece_le := by
    have hz : ∀ i : Fin 4, (⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.barHiggs d 0})
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, 1, 3) i) := fun i =>
      iSup_le fun d => (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_barHiggsComponent_zero i d))
    have ho : ∀ i : Fin 4, (⨆ d : Fin n → (Fin 1 ⊕ Fin 3), Submodule.span ℂ {h.barHiggs d 1})
        ≤ Module.End.eigenspace (rep (gaugeTorusGen i))
          ((expI : ℂ) ^ GaugeWeight.coord (0, 0, -1, 3) i) := fun i =>
      iSup_le fun d => (Submodule.span_singleton_le_iff_mem _ _).mpr
        (Module.End.mem_eigenspace_iff.mpr (h.rep_gaugeTorusGen_barHiggsComponent_one i d))
    intro w x hx i
    rcases eq_or_ne w (0, 0, 1, 3) with rfl | hw0
    · rw [if_pos rfl] at hx
      exact Module.End.mem_eigenspace_iff.mp (hz i hx)
    · rcases eq_or_ne w (0, 0, -1, 3) with rfl | hw1
      · rw [if_neg hw0, if_pos rfl] at hx
        exact Module.End.mem_eigenspace_iff.mp (ho i hx)
      · rw [if_neg hw0, if_neg hw1, Submodule.mem_bot] at hx
        subst hx
        simp
  piece_eq_bot := by
    intro w hw
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hw
    rw [if_neg hw.1, if_neg hw.2]
  iSup_piece := by
    have hrange : ∀ d : Fin n → (Fin 1 ⊕ Fin 3),
        LinearMap.range (h.covBarH n d) = Submodule.span ℂ (Set.range (h.barHiggs d)) := fun d => by
      rw [LinearMap.range_eq_map, ← (HiggsVec.orthonormBasis.toBasis.conj.dualBasis).span_eq,
        Submodule.map_span, ← Set.range_comp]
      rfl
    have hmem : ∀ (d : Fin n → (Fin 1 ⊕ Fin 3)) (j : Fin 2),
        h.barHiggs d j ∈ h.barHiggsSubmodule n := fun d j =>
      Submodule.mem_iSup_of_mem d ⟨HiggsVec.orthonormBasis.toBasis.conj.dualBasis j, rfl⟩
    refine le_antisymm (iSup_le fun w => ?_) ?_
    · rcases eq_or_ne w (0, 0, 1, 3) with rfl | hw0
      · rw [if_pos rfl]
        exact iSup_le fun d =>
          (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem d 0)
      · rcases eq_or_ne w (0, 0, -1, 3) with rfl | hw1
        · rw [if_neg hw0, if_pos rfl]
          exact iSup_le fun d =>
            (Submodule.span_singleton_le_iff_mem _ _).mpr (hmem d 1)
        · rw [if_neg hw0, if_neg hw1]
          exact bot_le
    · rw [barHiggsSubmodule]
      refine iSup_le fun d => ?_
      rw [hrange d, Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      fin_cases j
      · refine Submodule.mem_iSup_of_mem (0, 0, 1, 3) ?_
        rw [if_pos rfl]
        exact Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _)
      · refine Submodule.mem_iSup_of_mem (0, 0, -1, 3) ?_
        rw [if_neg (by decide), if_pos rfl]
        exact Submodule.mem_iSup_of_mem d (Submodule.mem_span_singleton_self _)

/-!

### A.5. The inner product of higges

-/

open Lorentz.BoostWeight

noncomputable def dot (x y : Fin 2 → B) : B := x 0 * y 0 + x 1 * y 1

noncomputable def dotGaugeHiggs (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly)
    (d1 : Fin n1 → (Fin 1 ⊕ Fin 3)) (d2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    B := h.higgs d1 0 * h.barHiggs d2 0 + h.higgs d1 1 * h.barHiggs d2 1

lemma rep_dotGaugeHiggs_invariant (g : GaugeGroupI) (d1 : Fin n1 → (Fin 1 ⊕ Fin 3))
    (d2 : Fin n2 → (Fin 1 ⊕ Fin 3)) :
    rep g (h.dotGaugeHiggs d1 d2) = h.dotGaugeHiggs d1 d2 := by
  have hu : ((g⁻¹).toU1 : ℂ) * (starRingEnd ℂ) ((g⁻¹).toU1 : ℂ) = 1 :=
    Unitary.mul_star_self_of_mem (g⁻¹).toU1.2
  have hM : star ((g⁻¹).toSU2.1) * (g⁻¹).toSU2.1 = 1 :=
    Matrix.mem_unitaryGroup_iff'.mp (g⁻¹).toSU2.2.1
  have hM00 := congrFun (congrFun hM 0) 0
  have hM01 := congrFun (congrFun hM 0) 1
  have hM10 := congrFun (congrFun hM 1) 0
  have hM11 := congrFun (congrFun hM 1) 1
  simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, star_eq_conjTranspose,
    Matrix.conjTranspose_apply, reduceIte, Complex.star_def,
    show ¬((0 : Fin 2) = 1) from by decide,
    show ¬((1 : Fin 2) = 0) from by decide] at hM00 hM01 hM10 hM11
  have hM01' := congrArg (starRingEnd ℂ) hM01
  have hM10' := congrArg (starRingEnd ℂ) hM10
  simp only [map_add, map_mul, Complex.conj_conj, map_zero] at hM01' hM10'
  have hu3 : ((g⁻¹).toU1 : ℂ) ^ 3 * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3) = 1 := by
    rw [map_pow, ← mul_pow, hu, one_pow]
  have key : ∀ a b : ℂ, (((g⁻¹).toU1 : ℂ) ^ 3 * a) * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3 * b)
      = a * (starRingEnd ℂ) b := by
    intro a b
    rw [map_mul]
    calc (((g⁻¹).toU1 : ℂ) ^ 3 * a) * ((starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3)
          * (starRingEnd ℂ) b)
        = (((g⁻¹).toU1 : ℂ) ^ 3 * (starRingEnd ℂ) (((g⁻¹).toU1 : ℂ) ^ 3))
          * (a * (starRingEnd ℂ) b) := by ring
      _ = a * (starRingEnd ℂ) b := by rw [hu3, one_mul]
  rw [dotGaugeHiggs, map_add, h.rep_mul, h.rep_mul, h.rep_higgsComponent,
    h.rep_barHiggsComponent, h.rep_higgsComponent, h.rep_barHiggsComponent]
  simp only [Fin.sum_univ_two, add_mul, mul_add, smul_mul_smul_comm, key]
  match_scalars
  · linear_combination hM00
  · linear_combination hM10'
  · linear_combination hM01'
  · linear_combination hM11

/-!
### E

An aside on derivatives and
boost weights (to be moved).

-/

lemma succ_deriv_span {n : ℕ} (f : (Fin n.succ → (Fin 1 ⊕ Fin 3)) → B) :
    ⨆ d, ℂ ∙ f d = ⨆ μ : Fin 1 ⊕ Fin 3, ⨆ d, ℂ ∙ f (Fin.cons μ d) := by
  refine le_antisymm (iSup_le fun d => ?_) (iSup_le fun μ => iSup_le fun d => ?_)
  · exact le_iSup_of_le (d 0) (le_iSup_of_le (Fin.tail d) (by rw [Fin.cons_self_tail]))
  · exact le_iSup (fun d => ℂ ∙ f d) (Fin.cons μ d)

structure IsDerivativeCollection {W} [AddCommGroup W] [Module ℂ W]
    (repW : Representation ℂ SL(2,ℂ) W) (α : ℕ)
    (f : (num : Fin α → ℕ) → (Fin (∑ i, num i) → (Fin 1 ⊕ Fin 3)) → W →ₗ[ℂ] B) where
  /-- The symbol map intertwines the Lorentz action on `W` with the one on `B`, up to the
    rotation of its derivative indices: each index is a Lorentz vector index. The partition
    `num` of the indices among the `α` factors is a spectator — the rotation does not see
    how the indices are grouped — so the law is one sum over one product. -/
  repLorentz_equiv : ∀ (g : SL(2,ℂ)) (num : Fin α → ℕ)
      (d : Fin (∑ i, num i) → (Fin 1 ⊕ Fin 3)) (w : W),
      repLorentz g (f num d w) = ∑ (a : Fin (∑ i, num i) → Fin 1 ⊕ Fin 3),
        (∏ (j : Fin (∑ i, num i)), (((SL2C.toLorentzGroup g).1 (a j) (d j) : ℝ) : ℂ)) •
          (f num a (repW g w))

namespace IsDerivativeCollection

variable {W} [AddCommGroup W] [Module ℂ W] {repW : Representation ℂ SL(2,ℂ) W}

/-- **The boost-weight decomposition of the symbols carrying `n` derivatives.** The
  multi-index is read in the light-cone basis: a slot of type `c j` contributes
  `lightConeWeight (c j)` — `+2` for `D₀ - Dᵢ`, `-2` for `D₀ + Dᵢ`, `0` for the two
  transverse directions — on top of the weight the argument already carries in `W`. -/
noncomputable def boostDecomp {n : ℕ} (F : (Fin n → Fin 1 ⊕ Fin 3) → W →ₗ[ℂ] B)
    (hF : RotatesIndices repW repLorentz F)
    (i : Fin 3) (hw : WeightDecomposition (K := ℂ) repW i ⊤) :
    WeightDecomposition repLorentz i (⨆ d : Fin n → Fin 1 ⊕ Fin 3, (F d).range) where
  piece k := ⨆ c : Fin n → Fin 4,
    (hw.piece (k - ∑ j, lightConeWeight (c j))).map (lightConeDeriv F i c)
  supp := (Finset.univ ×ˢ hw.supp).image
    fun p : (Fin n → Fin 4) × ℤ => (∑ j, lightConeWeight (p.1 j)) + p.2
  piece_le k := by
    refine iSup_le fun c => ?_
    rintro _ ⟨w, hwmem, rfl⟩
    have hmem := lightConeDeriv_mem F hF i c (hw.piece_le _ hwmem)
    rwa [show (∑ j, lightConeWeight (c j)) + (k - ∑ j, lightConeWeight (c j)) = k from by ring]
      at hmem
  piece_eq_bot k hk := by
    refine le_antisymm (iSup_le fun c => ?_) bot_le
    have hb : k - (∑ j, lightConeWeight (c j)) ∉ hw.supp := fun hb =>
      hk (Finset.mem_image.2 ⟨(c, k - ∑ j, lightConeWeight (c j)),
        Finset.mem_product.2 ⟨Finset.mem_univ c, hb⟩, by dsimp only; ring⟩)
    rw [hw.piece_eq_bot _ hb, Submodule.map_bot]
  iSup_piece := by
    have hc : ∀ c : Fin n → Fin 4,
        (⨆ k : ℤ, hw.piece (k - ∑ j, lightConeWeight (c j))) = ⊤ := by
      intro c
      refine le_antisymm le_top ?_
      calc (⊤ : Submodule ℂ W) = ⨆ b, hw.piece b := hw.iSup_piece.symm
        _ ≤ ⨆ k : ℤ, hw.piece (k - ∑ j, lightConeWeight (c j)) :=
            iSup_le fun b => le_iSup_of_le (b + ∑ j, lightConeWeight (c j))
              (by rw [add_sub_cancel_right])
    rw [iSup_comm]
    calc (⨆ c : Fin n → Fin 4, ⨆ k : ℤ,
          (hw.piece (k - ∑ j, lightConeWeight (c j))).map (lightConeDeriv F i c))
        = ⨆ c : Fin n → Fin 4, LinearMap.range (lightConeDeriv F i c) := by
          refine iSup_congr fun c => ?_
          rw [← Submodule.map_iSup, hc c, Submodule.map_top]
      _ = ⨆ d : Fin n → Fin 1 ⊕ Fin 3, LinearMap.range (F d) := by
          refine le_antisymm (iSup_le fun c => ?_) (iSup_le fun d => ?_)
          · rintro _ ⟨w, rfl⟩
            rw [lightConeDeriv, LinearMap.sum_apply]
            refine Submodule.sum_mem _ fun d _ => ?_
            rw [LinearMap.smul_apply]
            exact Submodule.smul_mem _ _ (Submodule.mem_iSup_of_mem d ⟨w, rfl⟩)
          · rintro _ ⟨w, rfl⟩
            rw [eq_sum_lightConeDeriv F i d, LinearMap.sum_apply]
            refine Submodule.sum_mem _ fun c _ => ?_
            rw [LinearMap.smul_apply]
            exact Submodule.smul_mem _ _ (Submodule.mem_iSup_of_mem c ⟨w, rfl⟩)

/-- Each shape of a derivative collection rotates its indices. -/
lemma rotatesIndices {α : ℕ}
    {f : (num : Fin α → ℕ) → (Fin (∑ i, num i) → (Fin 1 ⊕ Fin 3)) → W →ₗ[ℂ] B}
    (hD : IsDerivativeCollection (repLorentz := repLorentz) repW α f) (num : Fin α → ℕ) :
    RotatesIndices repW repLorentz (f num) :=
  fun g d w => hD.repLorentz_equiv g num d w

end IsDerivativeCollection

/-!

### E.1. The two-factor collection from the Higgs inner product

The gauge-invariant inner product `dotGaugeHiggs` of a Higgs and a conjugate Higgs, each
carrying its own derivatives, is a two-factor derivative collection over `W = ℂ`: the
Lorentz group rotates the derivative indices of the two factors independently, and the
trivial action on `ℂ` records that the inner product itself is a Lorentz scalar.

-/

/-- The Lorentz action rotates the derivative indices of a Higgs symbol. -/
lemma repLorentz_higgs {n : ℕ} (g : SL(2,ℂ)) (d : Fin n → Fin 1 ⊕ Fin 3) (k : Fin 2) :
    repLorentz g (h.higgs d k) = ∑ a : Fin n → Fin 1 ⊕ Fin 3,
      (∏ j, (((SL2C.toLorentzGroup g).1 (a j) (d j) : ℝ) : ℂ)) • h.higgs a k := by
  simp only [higgs]
  rw [h.repLorentz_H_apply]

/-- The Lorentz action rotates the derivative indices of a conjugate Higgs symbol. -/
lemma repLorentz_barHiggs {n : ℕ} (g : SL(2,ℂ)) (d : Fin n → Fin 1 ⊕ Fin 3) (k : Fin 2) :
    repLorentz g (h.barHiggs d k) = ∑ a : Fin n → Fin 1 ⊕ Fin 3,
      (∏ j, (((SL2C.toLorentzGroup g).1 (a j) (d j) : ℝ) : ℂ)) • h.barHiggs a k := by
  simp only [barHiggs]
  rw [h.repLorentz_barH_apply]

/-- **The Lorentz action on the Higgs inner product.** The two factors' derivative indices
  rotate independently; the inner product itself is a Lorentz scalar. -/
lemma repLorentz_dotGaugeHiggs {m n : ℕ} (g : SL(2,ℂ))
    (d₁ : Fin m → Fin 1 ⊕ Fin 3) (d₂ : Fin n → Fin 1 ⊕ Fin 3) :
    repLorentz g (h.dotGaugeHiggs d₁ d₂) =
      ∑ a₁ : Fin m → Fin 1 ⊕ Fin 3, ∑ a₂ : Fin n → Fin 1 ⊕ Fin 3,
        ((∏ j, (((SL2C.toLorentzGroup g).1 (a₁ j) (d₁ j) : ℝ) : ℂ)) *
          (∏ j, (((SL2C.toLorentzGroup g).1 (a₂ j) (d₂ j) : ℝ) : ℂ))) •
          h.dotGaugeHiggs a₁ a₂ := by
  simp only [dotGaugeHiggs, map_add, h.repLorentz_mul, repLorentz_higgs, repLorentz_barHiggs,
    Finset.sum_mul_sum, smul_mul_smul_comm, smul_add, Finset.sum_add_distrib]

/-- The weight decomposition of `ℂ` under the trivial Lorentz action: every scalar has
  boost weight zero. -/
noncomputable def trivialWeightDecomposition (i : Fin 3) :
    WeightDecomposition (1 : Representation ℂ SL(2,ℂ) ℂ) i ⊤ where
  piece k := if k = 0 then ⊤ else ⊥
  supp := {0}
  piece_le k := by
    by_cases hk : k = 0
    · subst hk
      rw [if_pos rfl]
      intro x _ t ht
      simp
    · rw [if_neg hk]
      exact bot_le
  piece_eq_bot k hk := if_neg (by simpa using hk)
  iSup_piece := le_antisymm le_top (le_iSup_of_le 0 (by rw [if_pos rfl]))

@[simp]
lemma trivialWeightDecomposition_piece (i : Fin 3) (k : ℤ) :
    (trivialWeightDecomposition i).piece k = if k = 0 then ⊤ else ⊥ := rfl

/-!

## C. The Higgs algebra

-/

/-- The algebra generated by the Higgs, it's conjugate and
  all their derivatives. -/
def higgsAlgebra (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly) :
    Subalgebra ℂ B := (Algebra.adjoin ℂ (⋃ (k : ℕ) (d : Fin k → (Fin 1 ⊕ Fin 3)),
      Set.range (h.covH k d) ∪ Set.range (h.covBarH k d)))

/-!

## D. Mass weight submodules

-/

set_option linter.unusedVariables false in
/-- All terms built from the Higgs symbols and their derivatives which have mass weight
  exactly `n`: the intersection of the algebra generated by every `∇_d H` and `∇_d H̄` with
  the part on which `massWeightPoly` is the monomial `X ^ n`. -/
noncomputable def massWeightSubmodule
    (h : HiggsAlgebraCovRealization B rep repLorentz massWeightPoly) (n : ℕ) :
    Submodule ℂ B :=
  h.higgsAlgebra.toSubmodule
    ⊓ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial n : B →ₗ[B] Polynomial B).restrictScalars ℂ)

/-- Any two elements of the algebra generated by the Higgs symbols commute. -/
lemma commute_of_mem_higgsAlgebra {x y : B} (hx : x ∈ h.higgsAlgebra) (hy : y ∈ h.higgsAlgebra) :
    Commute x y := by
  have hgen : ∀ a ∈ (⋃ (k : ℕ) (d : Fin k → (Fin 1 ⊕ Fin 3)),
      Set.range (h.covH k d) ∪ Set.range (h.covBarH k d)),
      ∀ b ∈ (⋃ (k : ℕ) (d : Fin k → (Fin 1 ⊕ Fin 3)),
      Set.range (h.covH k d) ∪ Set.range (h.covBarH k d)), Commute a b := by
    intro a ha b hb
    simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at ha hb
    obtain ⟨k1, d1, ⟨φ1, rfl⟩ | ⟨φ1, rfl⟩⟩ := ha <;>
      obtain ⟨k2, d2, ⟨φ2, rfl⟩ | ⟨φ2, rfl⟩⟩ := hb
    · exact h.H_comm_H _ _ _ _ _ _
    · exact h.H_comm_barH _ _ _ _ _ _
    · exact (h.H_comm_barH _ _ _ _ _ _).symm
    · exact h.barH_comm_barH _ _ _ _ _ _
  rw [higgsAlgebra] at hx hy
  refine Algebra.commute_of_mem_adjoin_of_forall_mem_commute hy fun b hb => ?_
  exact (Algebra.commute_of_mem_adjoin_of_forall_mem_commute hx fun a ha => hgen b hb a ha).symm

lemma massWeightPoly_of_mem_massWeightSubmodule {n : ℕ} {x : B} (hx : x ∈ h.massWeightSubmodule n) :
    massWeightPoly x = Polynomial.monomial n x := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  rcases hx with ⟨hx, hx'⟩
  rw [LinearMap.mem_ker] at hx'
  simp at hx'
  grind

lemma mem_higgsAlgebra_of_mem_massWeightSubmodule {n : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule n) : x ∈ h.higgsAlgebra := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  exact hx.1

lemma massWeightSubmodule_mul_comm (n m : ℕ) :
    h.massWeightSubmodule n * h.massWeightSubmodule m
    = h.massWeightSubmodule m * h.massWeightSubmodule n := by
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun y hy x hx => ?_)
  · rw [(h.commute_of_mem_higgsAlgebra (h.mem_higgsAlgebra_of_mem_massWeightSubmodule hx)
      (h.mem_higgsAlgebra_of_mem_massWeightSubmodule hy)).eq]
    exact Submodule.mul_mem_mul hy hx
  · rw [← (h.commute_of_mem_higgsAlgebra (h.mem_higgsAlgebra_of_mem_massWeightSubmodule hx)
      (h.mem_higgsAlgebra_of_mem_massWeightSubmodule hy)).eq]
    exact Submodule.mul_mem_mul hx hy

/-!

### B.1. Basic grading properties of massWeightPoly

-/

lemma one_le_massWeightSubmodule_zero : (1 : Submodule ℂ B) ≤ h.massWeightSubmodule 0 := by
  rw [Submodule.one_eq_span, Submodule.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
    massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Subalgebra.one_mem _, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero, map_one]
  simp

lemma massWeightSubmodule_mul_le (m n : ℕ) :
    h.massWeightSubmodule m * h.massWeightSubmodule n ≤ h.massWeightSubmodule (m + n) := by
  rw [Submodule.mul_le]
  intro x hx y hy
  have hx' := hx
  have hy' := hy
  rw [massWeightSubmodule, Submodule.mem_inf] at hx hy
  rw [massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Subalgebra.mul_mem _ hx.1 hy.1, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero]
  rw [map_mul, h.massWeightPoly_of_mem_massWeightSubmodule hx',
    h.massWeightPoly_of_mem_massWeightSubmodule hy', Polynomial.monomial_mul_monomial]

/-!

### B.1. The closure of the mass weight submodules under the gauge group

-/

lemma massWeightSubmodule_map_rep_le (n : ℕ) (g : GaugeGroupI) :
    (h.massWeightSubmodule n).map (rep g) ≤ h.massWeightSubmodule n := by
  have hone : rep g 1 = 1 := by
    have h1 := h.rep_mul g 1 (rep g⁻¹ 1)
    rw [one_mul, rep.self_inv_apply, mul_one] at h1
    exact h1.symm
  let F : B →ₐ[ℂ] B := AlgHom.ofLinearMap (rep g) hone (h.rep_mul g)
  have hFapp : ∀ x : B, F x = rep g x := fun _ => rfl
  have hFring : ∀ x : B, F.toRingHom x = rep g x := fun _ => rfl
  -- the generating symbols are permuted among themselves
  have hmaps : ∀ x ∈ (⋃ (k : ℕ) (d : Fin k → (Fin 1 ⊕ Fin 3)),
      Set.range (h.covH k d) ∪ Set.range (h.covBarH k d)), F x ∈ h.higgsAlgebra := by
    intro x hx
    simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hx
    obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hx
    · refine Algebra.subset_adjoin ?_
      simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range]
      exact ⟨k, d, Or.inl ⟨HiggsVec.repGaugeGroupI.dual g φ,
        by rw [hFapp, h.H_equivariant]⟩⟩
    · refine Algebra.subset_adjoin ?_
      simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range]
      exact ⟨k, d, Or.inr ⟨HiggsVec.repGaugeGroupI.conj.dual g φ,
        by rw [hFapp, h.barH_equivariant]⟩⟩
  have hadj : h.higgsAlgebra.map F ≤ h.higgsAlgebra := by
    rw [higgsAlgebra, AlgHom.map_adjoin]
    exact Algebra.adjoin_le (by rintro _ ⟨x, hx, rfl⟩; exact hmaps x hx)
  -- the grading is gauge invariant on the generated algebra
  have key : ∀ b ∈ h.higgsAlgebra,
      massWeightPoly (F b) = (massWeightPoly b).map F.toRingHom := by
    intro b hb
    rw [higgsAlgebra] at hb
    induction hb using Algebra.adjoin_induction with
    | mem x hx =>
      simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hx
      obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hx
      · rw [hFapp, h.H_equivariant, h.H_massWeight, h.H_massWeight,
          Polynomial.map_monomial, hFring, h.H_equivariant]
      · rw [hFapp, h.barH_equivariant, h.barH_massWeight, h.barH_massWeight,
          Polynomial.map_monomial, hFring, h.barH_equivariant]
    | algebraMap r => simp
    | add x y hx hy ihx ihy => rw [map_add, map_add, map_add, Polynomial.map_add, ihx, ihy]
    | mul x y hx hy ihx ihy => rw [map_mul, map_mul, map_mul, Polynomial.map_mul, ihx, ihy]
  rintro _ ⟨b, hb, rfl⟩
  rw [SetLike.mem_coe] at hb
  have hb' := hb
  rw [massWeightSubmodule, Submodule.mem_inf] at hb
  rw [massWeightSubmodule, Submodule.mem_inf]
  refine ⟨hadj ⟨b, hb.1, rfl⟩, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero]
  rw [← hFapp, key b hb.1, h.massWeightPoly_of_mem_massWeightSubmodule hb',
    Polynomial.map_monomial, hFring, hFapp]

/-!

### B.2. The odd mass weight submodules

Every term in the Higgs algebra has even mass weight, so the odd mass weight submodules are
trivial.
-/

lemma massWeightSubmodule_odd_eq_bot (n : ℕ) (hn : Odd n) :
    h.massWeightSubmodule n = ⊥ := by
  refine le_antisymm (fun b hb => ?_) bot_le
  have hb' := hb
  rw [massWeightSubmodule, Submodule.mem_inf] at hb
  -- every generator has even mass weight, and weights add under multiplication
  have key : ∀ x ∈ h.higgsAlgebra, ∀ i, Odd i → (massWeightPoly x).coeff i = 0 := by
    intro x hx
    rw [higgsAlgebra] at hx
    induction hx using Algebra.adjoin_induction with
    | mem y hy =>
      simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hy
      obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hy
      · intro i hi
        rw [h.H_massWeight, Polynomial.coeff_monomial, if_neg]
        rintro rfl
        obtain ⟨r, hr⟩ := hi
        omega
      · intro i hi
        rw [h.barH_massWeight, Polynomial.coeff_monomial, if_neg]
        rintro rfl
        obtain ⟨r, hr⟩ := hi
        omega
    | algebraMap r =>
      intro i hi
      have hi0 : i ≠ 0 := by rintro rfl; simp at hi
      rw [AlgHom.commutes]
      simp [Polynomial.algebraMap_apply, Polynomial.coeff_C, hi0]
    | add x y hx hy ihx ihy =>
      intro i hi
      rw [map_add, Polynomial.coeff_add, ihx i hi, ihy i hi, add_zero]
    | mul x y hx hy ihx ihy =>
      intro i hi
      rw [map_mul, Polynomial.coeff_mul]
      refine Finset.sum_eq_zero fun p hp => ?_
      have hsum := Finset.mem_antidiagonal.mp hp
      rcases Nat.even_or_odd p.1 with ⟨a, ha⟩ | ho
      · obtain ⟨c, hc⟩ := hi
        rw [ihy p.2 ⟨c - a, by omega⟩, mul_zero]
      · rw [ihx p.1 ho, zero_mul]
  have hcoeff := key b hb.1 n hn
  rw [h.massWeightPoly_of_mem_massWeightSubmodule hb', Polynomial.coeff_monomial,
    if_pos rfl] at hcoeff
  exact hcoeff

/-!

### B.3. The inclusion of the Higgs and conjugate Higgs submodules in the mass weight submodule

-/

lemma massWeightSubmodule_higgsSubmodule_le (n : ℕ) :
    h.higgsSubmodule n ≤ h.massWeightSubmodule (2 * (1 + n)) := by
  rw [higgsSubmodule]
  refine iSup_le fun d => ?_
  rintro _ ⟨φ, rfl⟩
  rw [massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Algebra.subset_adjoin ?_, ?_⟩
  · simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range]
    exact ⟨n, d, Or.inl ⟨φ, rfl⟩⟩
  · rw [LinearMap.mem_ker]
    simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
      sub_eq_zero]
    rw [h.H_massWeight]

lemma massWeightSubmodule_barHiggsSubmodule_le (n : ℕ) :
    h.barHiggsSubmodule n ≤ h.massWeightSubmodule (2 * (1 + n)) := by
  rw [barHiggsSubmodule]
  refine iSup_le fun d => ?_
  rintro _ ⟨φ, rfl⟩
  rw [massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Algebra.subset_adjoin ?_, ?_⟩
  · simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range]
    exact ⟨n, d, Or.inr ⟨φ, rfl⟩⟩
  · rw [LinearMap.mem_ker]
    simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
      sub_eq_zero]
    rw [h.barH_massWeight]

/-!

### B.4. Decomposition of the mass weight submodule

-/

lemma massWeightSubmodule_eq (i : ℕ) (hi : 0 < i) :
    h.massWeightSubmodule i
      = (⨆ k ∈ Finset.univ.filter (fun k : Fin i => 2 * (1 + (k : ℕ)) = i),
          h.higgsSubmodule (k : ℕ) ⊔ h.barHiggsSubmodule (k : ℕ))
        ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i),
            h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) := by
  refine le_antisymm (fun b hb => ?_) (sup_le ?_ ?_)
  · -- the weight-zero component of an element of the algebra is a scalar
    have hzero : ∀ x ∈ h.higgsAlgebra, (massWeightPoly x).coeff 0 ∈ (1 : Submodule ℂ B) := by
      intro x hx
      rw [higgsAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hy
        obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hy
        · rw [h.H_massWeight, Polynomial.coeff_monomial, if_neg (by omega)]
          exact zero_mem _
        · rw [h.barH_massWeight, Polynomial.coeff_monomial, if_neg (by omega)]
          exact zero_mem _
      | algebraMap r =>
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C]
        exact Submodule.mem_one.mpr ⟨r, rfl⟩
      | add x y hx hy ihx ihy =>
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ ihx ihy
      | mul x y hx hy ihx ihy =>
        rw [map_mul, Polynomial.mul_coeff_zero]
        have hmem := Submodule.mul_mem_mul ihx ihy
        rwa [Submodule.one_mul] at hmem
    -- the components of an element of the algebra are homogeneous
    have hcomp : ∀ x ∈ h.higgsAlgebra, ∀ m, (massWeightPoly x).coeff m
        ∈ h.massWeightSubmodule m := by
      intro x hx
      rw [higgsAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hy
        obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hy
        · intro m
          rw [h.H_massWeight, Polynomial.coeff_monomial]
          split_ifs with hw
          · subst hw
            exact h.massWeightSubmodule_higgsSubmodule_le k
              (Submodule.mem_iSup_of_mem d ⟨φ, rfl⟩)
          · exact zero_mem _
        · intro m
          rw [h.barH_massWeight, Polynomial.coeff_monomial]
          split_ifs with hw
          · subst hw
            exact h.massWeightSubmodule_barHiggsSubmodule_le k
              (Submodule.mem_iSup_of_mem d ⟨φ, rfl⟩)
          · exact zero_mem _
      | algebraMap r =>
        intro m
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C]
        split_ifs with hm
        · subst hm
          exact h.one_le_massWeightSubmodule_zero (Submodule.mem_one.mpr ⟨r, rfl⟩)
        · exact zero_mem _
      | add x y hx hy ihx ihy =>
        intro m
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ (ihx m) (ihy m)
      | mul x y hx hy ihx ihy =>
        intro m
        rw [map_mul, Polynomial.coeff_mul]
        refine Submodule.sum_mem _ fun p hp => ?_
        have hsum := Finset.mem_antidiagonal.mp hp
        subst hsum
        exact h.massWeightSubmodule_mul_le _ _ (Submodule.mul_mem_mul (ihx p.1) (ihy p.2))
    -- the weight-`m` component lands in the right-hand side, for every positive `m`
    have main : ∀ x ∈ h.higgsAlgebra, ∀ m, 0 < m → (massWeightPoly x).coeff m
        ∈ (⨆ k ∈ Finset.univ.filter (fun k : Fin m => 2 * (1 + (k : ℕ)) = m),
            h.higgsSubmodule (k : ℕ) ⊔ h.barHiggsSubmodule (k : ℕ))
          ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin m × Fin m => (p.1 : ℕ) + (p.2 : ℕ) = m),
              h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) := by
      intro x hx
      rw [higgsAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hy
        obtain ⟨k, d, (⟨φ, rfl⟩ | ⟨φ, rfl⟩)⟩ := hy
        · intro m _
          rw [h.H_massWeight, Polynomial.coeff_monomial]
          split_ifs with hw
          · exact Submodule.mem_sup_left (Submodule.mem_iSup_of_mem ⟨k, by omega⟩
              (Submodule.mem_iSup_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hw⟩)
                (Submodule.mem_sup_left (Submodule.mem_iSup_of_mem d ⟨φ, rfl⟩))))
          · exact zero_mem _
        · intro m _
          rw [h.barH_massWeight, Polynomial.coeff_monomial]
          split_ifs with hw
          · exact Submodule.mem_sup_left (Submodule.mem_iSup_of_mem ⟨k, by omega⟩
              (Submodule.mem_iSup_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hw⟩)
                (Submodule.mem_sup_right (Submodule.mem_iSup_of_mem d ⟨φ, rfl⟩))))
          · exact zero_mem _
      | algebraMap r =>
        intro m hm
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C, if_neg (by omega : ¬ m = 0)]
        exact zero_mem _
      | add x y hx hy ihx ihy =>
        intro m hm
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ (ihx m hm) (ihy m hm)
      | mul x y hx hy ihx ihy =>
        intro m hm
        rw [map_mul, Polynomial.coeff_mul]
        refine Submodule.sum_mem _ fun p hp => ?_
        obtain ⟨j, l⟩ := p
        have hsum := Finset.mem_antidiagonal.mp hp
        simp only at hsum ⊢
        rcases Nat.eq_zero_or_pos j with rfl | hj
        · have hlm : l = m := by omega
          rw [hlm]
          have hmem := Submodule.mul_mem_mul (hzero x hx) (ihy m hm)
          rwa [Submodule.one_mul] at hmem
        · rcases Nat.eq_zero_or_pos l with rfl | hl
          · have hjm : j = m := by omega
            rw [hjm]
            have hmem := Submodule.mul_mem_mul (ihx m hm) (hzero y hy)
            rwa [Submodule.mul_one] at hmem
          · refine Submodule.mem_sup_right (Submodule.mem_iSup_of_mem
              ((⟨⟨j, by omega⟩, ⟨l, by omega⟩⟩ : Fin m × Fin m))
              (Submodule.mem_iSup_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hsum⟩) ?_))
            exact Submodule.mul_mem_mul (hcomp x hx j) (hcomp y hy l)
    have hb' := hb
    rw [massWeightSubmodule, Submodule.mem_inf] at hb
    have hmain := main b hb.1 i hi
    rwa [h.massWeightPoly_of_mem_massWeightSubmodule hb', Polynomial.coeff_monomial,
      if_pos rfl] at hmain
  · refine iSup_le fun k => iSup_le fun hk => ?_
    have hk' := (Finset.mem_filter.mp hk).2
    exact (sup_le (h.massWeightSubmodule_higgsSubmodule_le (k : ℕ))
      (h.massWeightSubmodule_barHiggsSubmodule_le (k : ℕ))).trans (le_of_eq (by rw [hk']))
  · refine iSup_le fun p => iSup_le fun hp => ?_
    have hp' := (Finset.mem_filter.mp hp).2
    exact (h.massWeightSubmodule_mul_le (p.1 : ℕ) (p.2 : ℕ)).trans (le_of_eq (by rw [hp']))

/-- **The gauge weight decomposition of the mass weight submodules.** By recursion on the
  weight through `massWeightSubmodule_eq`: a term of weight `i` is either a symbol of that
  weight — decomposed by `higgsSubmoduleGaugeWeight` and `barHiggsSubmoduleGaugeWeight` — or a
  product of two terms of lower positive weight, decomposed by `mul` from the decompositions
  supplied by the recursion. -/
@[implicit_reducible]
noncomputable def massWeightSubmoduleGaugeWeight :
    (i : ℕ) → 0 < i → GaugeWeightDecomposition rep (h.massWeightSubmodule i) := by
  intro i
  induction i using Nat.strongRecOn with
  | _ i ih =>
    intro hi
    refine (GaugeWeightDecomposition.sup (d := ?_) (d' := ?_)).copy _
      (h.massWeightSubmodule_eq i hi)
    · exact GaugeWeightDecomposition.iSup h.rep_mul fun k : Fin i =>
        GaugeWeightDecomposition.iSupProp h.rep_mul fun _ =>
          GaugeWeightDecomposition.sup (d := h.higgsSubmoduleGaugeWeight (k : ℕ))
            (d' := h.barHiggsSubmoduleGaugeWeight (k : ℕ))
    · exact GaugeWeightDecomposition.iSup h.rep_mul fun p : Fin i × Fin i =>
        GaugeWeightDecomposition.iSupProp h.rep_mul fun hp =>
          have hsum : (p.1 : ℕ) + (p.2 : ℕ) = i := (Finset.mem_filter.mp hp).2
          have hj : (p.1 : ℕ) < i := p.1.isLt
          have hl : (p.2 : ℕ) < i := p.2.isLt
          GaugeWeightDecomposition.mul (d := ih (p.1 : ℕ) hj (by omega))
            (d' := ih (p.2 : ℕ) hl (by omega))

/-- The `NeZero` form of `massWeightSubmoduleGaugeWeight`. -/
noncomputable instance massWeightSubmoduleGaugeWeightOfNeZero (i : ℕ) [NeZero i] :
    GaugeWeightDecomposition rep (h.massWeightSubmodule i) :=
  h.massWeightSubmoduleGaugeWeight i (Nat.pos_of_ne_zero (NeZero.ne i))

/-!

### B.6. Expansion of the low dimensional cases

-/

open GaugeWeightDecomposition

lemma massWeightSubmodule_two_eq :
    h.massWeightSubmodule 2 = h.higgsSubmodule 0 ⊔ h.barHiggsSubmodule 0 := by
  rw [h.massWeightSubmodule_eq 2 (by decide)]
  rw [show (Finset.univ.filter (fun k : Fin 2 => 2 * (1 + (k : ℕ)) = 2)) = {0} from by decide,
    show (Finset.univ.filter (fun p : Fin 2 × Fin 2 => (p.1 : ℕ) + (p.2 : ℕ) = 2)) = {(1, 1)}
      from by decide]
  simp only [Fin.isValue, Finset.mem_singleton, iSup_iSup_eq_left, Fin.coe_ofNat_eq_mod,
    Nat.zero_mod, Nat.mod_succ, h.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.mul_bot,
    bot_le, sup_of_le_left]

lemma massWeightSubmodule_four_eq :
    h.massWeightSubmodule 4 = h.higgsSubmodule 1 ⊔ h.barHiggsSubmodule 1 ⊔
    h.higgsSubmodule 0 * h.higgsSubmodule 0 ⊔ h.higgsSubmodule 0 *
    h.barHiggsSubmodule 0 ⊔ h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0:= by
  rw [h.massWeightSubmodule_eq 4 (by decide)]
  rw [show (Finset.univ.filter (fun k : Fin 4 => 2 * (1 + (k : ℕ)) = 4)) = {1} from by decide,
    show (Finset.univ.filter (fun p : Fin 4 × Fin 4 => (p.1 : ℕ) + (p.2 : ℕ) = 4)) =
    {(1, 3), (3, 1), (2, 2)} from by decide]
  simp  [Fin.isValue, Finset.mem_singleton, iSup_iSup_eq_left, Fin.coe_ofNat_eq_mod,
    Nat.one_mod,- Finset.mem_insert, Finset.iSup_insert,
    h.massWeightSubmodule_odd_eq_bot 1 (by decide),
    massWeightSubmodule_two_eq, ]
  simp [Submodule.sup_mul, Submodule.mul_sup, Submodule.mul_sup,
    barHiggsSubmodule_comm_higgsSubmodule, ← sup_assoc]

lemma massWeightSubmodule_six_eq : h.massWeightSubmodule 6 =
    -- The derivative terms
    h.higgsSubmodule 2 ⊔ h.barHiggsSubmodule 2 ⊔
    h.higgsSubmodule 1 * h.higgsSubmodule 0 ⊔
    h.higgsSubmodule 1 * h.barHiggsSubmodule 0 ⊔
    h.barHiggsSubmodule 1 * h.higgsSubmodule 0 ⊔
    h.barHiggsSubmodule 1 * h.barHiggsSubmodule 0 ⊔
    -- The potential terms
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.higgsSubmodule 0  ⊔
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0  := by
  rw [h.massWeightSubmodule_eq 6 (by decide)]
  rw [show (Finset.univ.filter (fun k : Fin 6 => 2 * (1 + (k : ℕ)) = 6)) = {2} from by decide,
    show (Finset.univ.filter (fun p : Fin 6 × Fin 6 => (p.1 : ℕ) + (p.2 : ℕ) = 6)) =
    {(1, 5), (5, 1), (2, 4), (4, 2), (3, 3)} from by decide]
  simp (disch := decide) [Fin.isValue, Finset.mem_singleton, iSup_iSup_eq_left, Fin.coe_ofNat_eq_mod,
    Nat.one_mod,- Finset.mem_insert, Finset.iSup_insert,
    h.massWeightSubmodule_odd_eq_bot, h.massWeightSubmodule_mul_comm,
    bot_sup_eq, sup_bot_eq, sup_idem]
  rw [massWeightSubmodule_two_eq, massWeightSubmodule_four_eq]
  have hlc : ∀ (n1 n2 : ℕ) (C : Submodule ℂ B),
      h.barHiggsSubmodule n1 * (h.higgsSubmodule n2 * C)
      = h.higgsSubmodule n2 * (h.barHiggsSubmodule n1 * C) :=
    fun n1 n2 C => Commute.left_comm (h.barHiggsSubmodule_comm_higgsSubmodule n1 n2) C
  simp only [Submodule.sup_mul, Submodule.mul_sup, barHiggsSubmodule_comm_higgsSubmodule,
    mul_assoc, hlc, h.higgsSubmodule_comm_higgsSubmodule 0 1 (by decide),
    h.barHiggsSubmodule_comm_barHiggsSubmodule 0 1 (by decide), ← sup_assoc, sup_right_idem]

lemma massWeightSubmodule_eight_eq :
    h.massWeightSubmodule 8 =
      -- The derivative terms
    h.higgsSubmodule 3 ⊔ h.barHiggsSubmodule 3 ⊔
    h.higgsSubmodule 2 * h.higgsSubmodule 0 ⊔
    h.higgsSubmodule 2 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.barHiggsSubmodule 2 ⊔
    h.barHiggsSubmodule 2 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 1 * h.higgsSubmodule 1 ⊔
    h.higgsSubmodule 1 * h.barHiggsSubmodule 1 ⊔
    h.barHiggsSubmodule 1 * h.barHiggsSubmodule 1 ⊔
    h.higgsSubmodule 1 * h.higgsSubmodule 0 * h.higgsSubmodule 0 ⊔
    h.higgsSubmodule 1 * h.higgsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 1 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.barHiggsSubmodule 1 ⊔
    h.higgsSubmodule 0 * h.barHiggsSubmodule 1 * h.barHiggsSubmodule 0 ⊔
    h.barHiggsSubmodule 1 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    -- The potential terms
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.higgsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.higgsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.higgsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 ⊔
    h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0 *
      h.barHiggsSubmodule 0 := by
  rw [h.massWeightSubmodule_eq 8 (by decide)]
  rw [show (Finset.univ.filter (fun k : Fin 8 => 2 * (1 + (k : ℕ)) = 8)) = {3} from by decide,
    show (Finset.univ.filter (fun p : Fin 8 × Fin 8 => (p.1 : ℕ) + (p.2 : ℕ) = 8)) =
    {(1, 7), (7, 1), (2, 6), (6, 2), (3, 5), (5, 3), (4, 4)} from by decide]
  simp (disch := decide) [Fin.isValue, Finset.mem_singleton, iSup_iSup_eq_left, Fin.coe_ofNat_eq_mod,
    Nat.one_mod,- Finset.mem_insert, Finset.iSup_insert,
    h.massWeightSubmodule_odd_eq_bot, h.massWeightSubmodule_mul_comm,
    bot_sup_eq, sup_left_idem]
  rw [massWeightSubmodule_two_eq, massWeightSubmodule_four_eq, massWeightSubmodule_six_eq]
  have hlc : ∀ (n1 n2 : ℕ) (C : Submodule ℂ B),
      h.barHiggsSubmodule n1 * (h.higgsSubmodule n2 * C)
      = h.higgsSubmodule n2 * (h.barHiggsSubmodule n1 * C) :=
    fun n1 n2 C => Commute.left_comm (h.barHiggsSubmodule_comm_higgsSubmodule n1 n2) C
  have hlcH : ∀ (C : Submodule ℂ B),
      h.higgsSubmodule 0 * (h.higgsSubmodule 1 * C)
      = h.higgsSubmodule 1 * (h.higgsSubmodule 0 * C) :=
    fun C => Commute.left_comm (h.higgsSubmodule_comm_higgsSubmodule 0 1 (by decide)) C
  have hlcB : ∀ (C : Submodule ℂ B),
      h.barHiggsSubmodule 0 * (h.barHiggsSubmodule 1 * C)
      = h.barHiggsSubmodule 1 * (h.barHiggsSubmodule 0 * C) :=
    fun C => Commute.left_comm (h.barHiggsSubmodule_comm_barHiggsSubmodule 0 1 (by decide)) C
  simp only [Submodule.sup_mul, Submodule.mul_sup, barHiggsSubmodule_comm_higgsSubmodule,
    mul_assoc, hlc, hlcH, hlcB,
    h.higgsSubmodule_comm_higgsSubmodule 0 1 (by decide),
    h.higgsSubmodule_comm_higgsSubmodule 0 2 (by decide),
    h.barHiggsSubmodule_comm_barHiggsSubmodule 0 1 (by decide),
    h.barHiggsSubmodule_comm_barHiggsSubmodule 0 2 (by decide)]
  generalize h.higgsSubmodule 3 = v1
  generalize h.barHiggsSubmodule 3 = v2
  generalize h.higgsSubmodule 2 * h.higgsSubmodule 0 = v3
  generalize h.higgsSubmodule 2 * h.barHiggsSubmodule 0 = v4
  generalize h.higgsSubmodule 0 * h.barHiggsSubmodule 2 = v5
  generalize h.barHiggsSubmodule 2 * h.barHiggsSubmodule 0 = v6
  generalize h.higgsSubmodule 1 * h.higgsSubmodule 1 = v7
  generalize h.higgsSubmodule 1 * h.barHiggsSubmodule 1 = v8
  generalize h.barHiggsSubmodule 1 * h.barHiggsSubmodule 1 = v9
  generalize h.higgsSubmodule 1 * (h.higgsSubmodule 0 * h.higgsSubmodule 0) = v10
  generalize h.higgsSubmodule 1 * (h.higgsSubmodule 0 * h.barHiggsSubmodule 0) = v11
  generalize h.higgsSubmodule 1 * (h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0) = v12
  generalize h.higgsSubmodule 0 * (h.higgsSubmodule 0 * h.barHiggsSubmodule 1) = v13
  generalize h.higgsSubmodule 0 * (h.barHiggsSubmodule 1 * h.barHiggsSubmodule 0) = v14
  generalize h.barHiggsSubmodule 1 * (h.barHiggsSubmodule 0 * h.barHiggsSubmodule 0) = v15
  generalize h.higgsSubmodule 0 * (h.higgsSubmodule 0 * (h.higgsSubmodule 0 *
    h.higgsSubmodule 0)) = v16
  generalize h.higgsSubmodule 0 * (h.higgsSubmodule 0 * (h.higgsSubmodule 0 *
    h.barHiggsSubmodule 0)) = v17
  generalize h.higgsSubmodule 0 * (h.higgsSubmodule 0 * (h.barHiggsSubmodule 0 *
    h.barHiggsSubmodule 0)) = v18
  generalize h.higgsSubmodule 0 * (h.barHiggsSubmodule 0 * (h.barHiggsSubmodule 0 *
    h.barHiggsSubmodule 0)) = v19
  generalize h.barHiggsSubmodule 0 * (h.barHiggsSubmodule 0 * (h.barHiggsSubmodule 0 *
    h.barHiggsSubmodule 0)) = v20
  simp only [sup_comm, sup_left_comm, sup_idem, sup_left_idem]

/-!

## E. Gauge invariance

-/

/-- The gauge invariants of a given mass weight. -/
noncomputable def gaugeInvariantOfMassDim (M : ℕ) : Submodule ℂ B :=
  h.massWeightSubmodule M ⊓ Representation.invariants rep

end HiggsAlgebraCovRealization

end StandardModel
