/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.Invariants.Subgroups.RotationsPi
/-!
# The boosts along the coordinate axes

The one-parameter boosts `boostZel t`, `boostXel t`, `boostYel t` along the
three coordinate axes, the subgroups `boostSubgroupZ/X/Y` they generate, and
their Lorentz matrices; together with the two fixed `z`-boosts `boostZ2`,
`boostZ3` used to kill the weight-six sector.

These boosts are the subgroup that `Averages/BoostAverage` averages over; its
`boostAvg_calculator` tactic computes their action on the weight-eight monomials from the
`boostMat*` matrices below together with the transformation laws of `LorentzAction`. Being non-compact they admit no invariant average, which is why that
file has to weight them by hand.
-/

@[expose] public section

set_option maxHeartbeats 1000000

namespace LeptonGaugeSector
open TensorProduct StandardModel

namespace JetAlgebra

open scoped minkowskiMatrix PauliMatrix
open Matrix MatrixGroups

/-!

### Parametric boosts along the three axes

The one-parameter families of boosts `diag(t, t⁻¹)` (along `z`) and their
conjugates along `x` and `y`, with symbolic Lorentz matrices in `t`.

-/

/-- The lift `diag(t, t⁻¹)` of the boost along the `z`-axis with rapidity
  `2 log t`. -/
noncomputable def boostZel (t : ℝ) (ht : t ≠ 0) : SL(2,ℂ) :=
  ⟨!![(t : ℂ), 0; 0, (t : ℂ)⁻¹], by
    have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
    rw [Matrix.det_fin_two_of]
    simp [mul_inv_cancel₀ htc]⟩

/-- The lift of the boost along the `x`-axis with rapidity `2 log t`. -/
noncomputable def boostXel (t : ℝ) (ht : t ≠ 0) : SL(2,ℂ) :=
  ⟨!![((t : ℂ) + (t : ℂ)⁻¹)/2, ((t : ℂ) - (t : ℂ)⁻¹)/2;
      ((t : ℂ) - (t : ℂ)⁻¹)/2, ((t : ℂ) + (t : ℂ)⁻¹)/2], by
    have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
    rw [Matrix.det_fin_two_of]
    field_simp
    ring⟩

/-- The lift of the boost along the `y`-axis with rapidity `2 log t`. -/
noncomputable def boostYel (t : ℝ) (ht : t ≠ 0) : SL(2,ℂ) :=
  ⟨!![((t : ℂ) + (t : ℂ)⁻¹)/2, -Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2;
      Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2, ((t : ℂ) + (t : ℂ)⁻¹)/2], by
    have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
    have h2 : -Complex.I * ((t : ℂ) - (t : ℂ)⁻¹) / 2 *
        (Complex.I * ((t : ℂ) - (t : ℂ)⁻¹) / 2) =
        ((t : ℂ) - (t : ℂ)⁻¹) / 2 * (((t : ℂ) - (t : ℂ)⁻¹) / 2) := by
      have hI : -Complex.I * Complex.I = 1 := by
        rw [neg_mul, Complex.I_mul_I, neg_neg]
      calc -Complex.I * ((t : ℂ) - (t : ℂ)⁻¹) / 2 *
            (Complex.I * ((t : ℂ) - (t : ℂ)⁻¹) / 2)
          = (-Complex.I * Complex.I) *
              (((t : ℂ) - (t : ℂ)⁻¹) / 2 * (((t : ℂ) - (t : ℂ)⁻¹) / 2)) := by
            ring
        _ = ((t : ℂ) - (t : ℂ)⁻¹) / 2 * (((t : ℂ) - (t : ℂ)⁻¹) / 2) := by
            rw [hI, one_mul]
    rw [Matrix.det_fin_two_of, h2]
    field_simp
    ring⟩

/-!

### The boosts as one-parameter subgroups

`t ↦ diag(t, t⁻¹)` is a homomorphism from the multiplicative group of nonzero
reals, so the `z`-boosts form a genuine subgroup of `SL(2,ℂ)`; the `x`- and
`y`-boosts are its conjugates. The averages of `Averages/BoostAverage` are taken
over finitely many elements of these subgroups.

-/

/-- The boosts along the `z`-axis as a homomorphism from the nonzero reals. -/
noncomputable def boostHomZ : ℝˣ →* SL(2,ℂ) where
  toFun u := boostZel (u : ℝ) u.ne_zero
  map_one' := by
    refine Subtype.ext ?_
    rw [boostZel, Matrix.SpecialLinearGroup.coe_one]
    ext i j
    fin_cases i <;> fin_cases j <;> simp [Matrix.one_apply]
  map_mul' u v := by
    refine Subtype.ext ?_
    rw [boostZel, boostZel, boostZel]
    have hu : ((u : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr u.ne_zero
    have hv : ((v : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr v.ne_zero
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Units.val_mul, mul_inv] <;> ring

/-- The one-parameter subgroup of `SL(2,ℂ)` of boosts along the `z`-axis. -/
noncomputable def boostSubgroupZ : Subgroup SL(2,ℂ) := boostHomZ.range

lemma boostZel_mem_boostSubgroupZ (t : ℝ) (ht : t ≠ 0) :
    boostZel t ht ∈ boostSubgroupZ :=
  ⟨Units.mk0 t ht, rfl⟩

/-- The subgroup of `SL(2,ℂ)` generated by the boosts along the `x`-axis. -/
noncomputable def boostSubgroupX : Subgroup SL(2,ℂ) :=
  Subgroup.closure (Set.range fun u : ℝˣ => boostXel (u : ℝ) u.ne_zero)

lemma boostXel_mem_boostSubgroupX (t : ℝ) (ht : t ≠ 0) :
    boostXel t ht ∈ boostSubgroupX :=
  Subgroup.subset_closure ⟨Units.mk0 t ht, rfl⟩

/-- The subgroup of `SL(2,ℂ)` generated by the boosts along the `y`-axis. -/
noncomputable def boostSubgroupY : Subgroup SL(2,ℂ) :=
  Subgroup.closure (Set.range fun u : ℝˣ => boostYel (u : ℝ) u.ne_zero)

lemma boostYel_mem_boostSubgroupY (t : ℝ) (ht : t ≠ 0) :
    boostYel t ht ∈ boostSubgroupY :=
  Subgroup.subset_closure ⟨Units.mk0 t ht, rfl⟩

/-- The Lorentz matrix of `boostZel t`: `ch = (t² + t⁻²)/2` on the time-time
  and `zz` entries, `-sh = -(t² - t⁻²)/2` on the mixed entries. -/
noncomputable def boostMatZ (t : ℝ) : (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → ℝ
  | Sum.inl _, Sum.inl _ => (t^2 + (t⁻¹)^2)/2
  | Sum.inl _, Sum.inr 2 => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 2, Sum.inl _ => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 0, Sum.inr 0 => 1
  | Sum.inr 1, Sum.inr 1 => 1
  | Sum.inr 2, Sum.inr 2 => (t^2 + (t⁻¹)^2)/2
  | _, _ => 0

/-- The Lorentz matrix of `boostXel t`. -/
noncomputable def boostMatX (t : ℝ) : (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → ℝ
  | Sum.inl _, Sum.inl _ => (t^2 + (t⁻¹)^2)/2
  | Sum.inl _, Sum.inr 0 => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 0, Sum.inl _ => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 0, Sum.inr 0 => (t^2 + (t⁻¹)^2)/2
  | Sum.inr 1, Sum.inr 1 => 1
  | Sum.inr 2, Sum.inr 2 => 1
  | _, _ => 0

/-- The Lorentz matrix of `boostYel t`. -/
noncomputable def boostMatY (t : ℝ) : (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → ℝ
  | Sum.inl _, Sum.inl _ => (t^2 + (t⁻¹)^2)/2
  | Sum.inl _, Sum.inr 1 => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 1, Sum.inl _ => -((t^2 - (t⁻¹)^2)/2)
  | Sum.inr 0, Sum.inr 0 => 1
  | Sum.inr 1, Sum.inr 1 => (t^2 + (t⁻¹)^2)/2
  | Sum.inr 2, Sum.inr 2 => 1
  | _, _ => 0

set_option maxHeartbeats 4000000 in
set_option linter.unusedSimpArgs false in
/-- The Lorentz matrix of the parametric `z`-boost. -/
lemma toLorentzGroup_boostZel (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostZel t ht)).1 a b = boostMatZ t a b := by
  have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · try simp [boostZel, boostMatZ, PauliMatrix.pauliSelfAdjoint',
        PauliMatrix.pauliMatrix, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.conjTranspose, Matrix.diag, Complex.conj_ofNat,
        Complex.conj_ofReal, Complex.conj_I, Complex.I_sq]
      try simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]
      try push_cast
      try field_simp
      try ring_nf
      try norm_num [Complex.I_sq, Complex.conj_ofNat]
      try ring

set_option maxHeartbeats 4000000 in
set_option linter.unusedSimpArgs false in
/-- The Lorentz matrix of the parametric `x`-boost. -/
lemma toLorentzGroup_boostXel (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostXel t ht)).1 a b = boostMatX t a b := by
  have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · try simp [boostXel, boostMatX, PauliMatrix.pauliSelfAdjoint',
        PauliMatrix.pauliMatrix, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.conjTranspose, Matrix.diag, Complex.conj_ofNat,
        Complex.conj_ofReal, Complex.conj_I, Complex.I_sq]
      try simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]
      try push_cast
      try field_simp
      try ring_nf
      try norm_num [Complex.I_sq, Complex.conj_ofNat]
      try ring

set_option maxHeartbeats 4000000 in
set_option linter.unusedSimpArgs false in
/-- The Lorentz matrix of the parametric `y`-boost. -/
lemma toLorentzGroup_boostYel (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostYel t ht)).1 a b = boostMatY t a b := by
  have htc : (t : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr ht
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · try simp [boostYel, boostMatY, PauliMatrix.pauliSelfAdjoint',
        PauliMatrix.pauliMatrix, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.conjTranspose, Matrix.diag, Complex.conj_ofNat,
        Complex.conj_ofReal, Complex.conj_I, Complex.I_sq]
      try simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]
      try push_cast
      try field_simp
      try ring_nf
      try norm_num [Complex.I_sq, Complex.conj_ofNat]
      try ring

/-- The inverse of the parametric `z`-boost is the boost at the inverse
  parameter. -/
lemma boostZel_inv (t : ℝ) (ht : t ≠ 0) :
    (boostZel t ht)⁻¹ = boostZel t⁻¹ (inv_ne_zero ht) := by
  ext i j
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  fin_cases i <;> fin_cases j <;>
    simp [boostZel, Complex.ofReal_inv, inv_inv]

/-- The inverse of the parametric `x`-boost is the boost at the inverse
  parameter. -/
lemma boostXel_inv (t : ℝ) (ht : t ≠ 0) :
    (boostXel t ht)⁻¹ = boostXel t⁻¹ (inv_ne_zero ht) := by
  ext i j
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  fin_cases i <;> fin_cases j <;>
    · simp [boostXel, Complex.ofReal_inv, inv_inv]
      try ring

/-- The inverse of the parametric `y`-boost is the boost at the inverse
  parameter. -/
lemma boostYel_inv (t : ℝ) (ht : t ≠ 0) :
    (boostYel t ht)⁻¹ = boostYel t⁻¹ (inv_ne_zero ht) := by
  ext i j
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  fin_cases i <;> fin_cases j <;>
    · simp [boostYel, Complex.ofReal_inv, inv_inv]
      try ring

/-- The matrix of the `z`-boost. -/
lemma boostZel_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostZel t ht : SL(2,ℂ)) : Matrix (Fin 2) (Fin 2) ℂ) =
      !![((t : ℝ) : ℂ), 0; 0, (((t : ℝ) : ℂ))⁻¹] := rfl

/-- The matrix of the `x`-boost. -/
lemma boostXel_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostXel t ht : SL(2,ℂ)) : Matrix (Fin 2) (Fin 2) ℂ) =
      !![((t : ℂ) + (t : ℂ)⁻¹)/2, ((t : ℂ) - (t : ℂ)⁻¹)/2;
         ((t : ℂ) - (t : ℂ)⁻¹)/2, ((t : ℂ) + (t : ℂ)⁻¹)/2] := rfl

/-- The matrix of the `y`-boost. -/
lemma boostYel_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostYel t ht : SL(2,ℂ)) : Matrix (Fin 2) (Fin 2) ℂ) =
      !![((t : ℂ) + (t : ℂ)⁻¹)/2, -Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2;
         Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2, ((t : ℂ) + (t : ℂ)⁻¹)/2] := rfl

/-- The inverse of the parametric `z`-boost, entrywise, with real entries. -/
lemma boostZel_inv_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostZel t ht)⁻¹ : SL(2,ℂ)).1 =
      !![(((t⁻¹ : ℝ)) : ℂ), 0; 0, ((t : ℝ) : ℂ)] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [boostZel]

/-- The inverse of the parametric `x`-boost, entrywise. -/
lemma boostXel_inv_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostXel t ht)⁻¹ : SL(2,ℂ)).1 =
      !![((t : ℂ) + (t : ℂ)⁻¹)/2, -(((t : ℂ) - (t : ℂ)⁻¹)/2);
         -(((t : ℂ) - (t : ℂ)⁻¹)/2), ((t : ℂ) + (t : ℂ)⁻¹)/2] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [boostXel]

/-- The inverse of the parametric `y`-boost, entrywise. -/
lemma boostYel_inv_coe (t : ℝ) (ht : t ≠ 0) :
    ((boostYel t ht)⁻¹ : SL(2,ℂ)).1 =
      !![((t : ℂ) + (t : ℂ)⁻¹)/2, Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2;
         -(Complex.I * ((t : ℂ) - (t : ℂ)⁻¹)/2), ((t : ℂ) + (t : ℂ)⁻¹)/2] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> · simp [boostYel]; try ring

/-- The Lorentz matrix of the inverse `z`-boost: the boost matrix at the
  inverse parameter. -/
lemma toLorentzGroup_boostZel_inv (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostZel t ht)⁻¹).1 a b = boostMatZ t⁻¹ a b := by
  rw [boostZel_inv, toLorentzGroup_boostZel]

/-- The Lorentz matrix of the inverse `x`-boost. -/
lemma toLorentzGroup_boostXel_inv (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostXel t ht)⁻¹).1 a b = boostMatX t⁻¹ a b := by
  rw [boostXel_inv, toLorentzGroup_boostXel]

/-- The Lorentz matrix of the inverse `y`-boost. -/
lemma toLorentzGroup_boostYel_inv (t : ℝ) (ht : t ≠ 0) (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup (boostYel t ht)⁻¹).1 a b = boostMatY t⁻¹ a b := by
  rw [boostYel_inv, toLorentzGroup_boostYel]


/-!

### The two fixed `z`-boosts

Two diagonal boosts `diag(t, t⁻¹)` with `t = 2, 3`. Together with the Klein
four-group of rotations by `π` they suffice to kill the neutral weight-six
sector: the rotation average projects onto the twelve surviving field-strength
components and the diagonal fermion pairs, and a rational combination of the
two boosts (with weights summing to one) annihilates all of them. That
combination is `rotationPiBoostAvg` of `Averages/RotationPiBoostAverage`.

-/

/-- The lift `diag(2, 1/2)` of the boost along the `z`-axis with rapidity
  `log 4`. -/
noncomputable def boostZ2 : SL(2,ℂ) :=
  ⟨!![2, 0; 0, 2⁻¹], by norm_num [Matrix.det_fin_two_of]⟩

/-- The lift `diag(3, 1/3)` of the boost along the `z`-axis with rapidity
  `log 9`. -/
noncomputable def boostZ3 : SL(2,ℂ) :=
  ⟨!![3, 0; 0, 3⁻¹], by norm_num [Matrix.det_fin_two_of]⟩

/-- The Lorentz matrix of `boostZ2`. -/
noncomputable def boostMatA : (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → ℝ
  | Sum.inl _, Sum.inl _ => 17/8
  | Sum.inl _, Sum.inr 2 => -(15/8)
  | Sum.inr 2, Sum.inl _ => -(15/8)
  | Sum.inr 0, Sum.inr 0 => 1
  | Sum.inr 1, Sum.inr 1 => 1
  | Sum.inr 2, Sum.inr 2 => 17/8
  | _, _ => 0

/-- The Lorentz matrix of `boostZ3`. -/
noncomputable def boostMatB : (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → ℝ
  | Sum.inl _, Sum.inl _ => 41/9
  | Sum.inl _, Sum.inr 2 => -(40/9)
  | Sum.inr 2, Sum.inl _ => -(40/9)
  | Sum.inr 0, Sum.inr 0 => 1
  | Sum.inr 1, Sum.inr 1 => 1
  | Sum.inr 2, Sum.inr 2 => 41/9
  | _, _ => 0

set_option maxHeartbeats 2000000 in
/-- The Lorentz matrix of the first boost. -/
lemma toLorentzGroup_boostZ2 (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup boostZ2).1 a b = boostMatA a b := by
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · try simp [boostZ2, boostMatA, PauliMatrix.pauliSelfAdjoint',
        PauliMatrix.pauliMatrix, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.conjTranspose, Matrix.diag]
      try simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]
      try norm_num [Complex.ext_iff]

set_option maxHeartbeats 2000000 in
/-- The Lorentz matrix of the second boost. -/
lemma toLorentzGroup_boostZ3 (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup boostZ3).1 a b = boostMatB a b := by
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · try simp [boostZ3, boostMatB, PauliMatrix.pauliSelfAdjoint',
        PauliMatrix.pauliMatrix, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.conjTranspose, Matrix.diag]
      try simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]
      try norm_num [Complex.ext_iff]

/-- The inverse of the first boost, entrywise, with real entries. -/
lemma boostZ2_inv_coe :
    (boostZ2⁻¹ : SL(2,ℂ)).1 = !![((2⁻¹ : ℝ) : ℂ), 0; 0, ((2 : ℝ) : ℂ)] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [boostZ2]

/-- The inverse of the second boost, entrywise, with real entries. -/
lemma boostZ3_inv_coe :
    (boostZ3⁻¹ : SL(2,ℂ)).1 = !![((3⁻¹ : ℝ) : ℂ), 0; 0, ((3 : ℝ) : ℂ)] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [boostZ3]

end JetAlgebra

end LeptonGaugeSector
