/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.LeptonGaugeSector.JetAlgebra.Invariants.Grading.NeutralSectors
/-!
# The rotations by `π` about the coordinate axes

The three rotations by `π` about the coordinate axes, lifted to `SL(2,ℂ)` as
`i σ_k`, and the subgroup `rotationPiSubgroup` they generate. Their Lorentz
matrices are the diagonal sign matrices fixing the time axis and the rotation
axis and reversing the two others, recorded here entry by entry.

This is the finite subgroup of the classification; `Averages/RotationAverage`
is the average taken over it. Being finite it admits an honest invariant
average, unlike the boosts of `AxisBoosts`.
-/

@[expose] public section

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false

namespace LeptonGaugeSector
open TensorProduct StandardModel

namespace JetAlgebra

open scoped minkowskiMatrix PauliMatrix
open Matrix MatrixGroups

/-!

### The rotations by `π`

The three rotations by `π` about the coordinate axes lift to `SL(2,ℂ)` as
`i σ_k`; their Lorentz matrices are the diagonal sign matrices fixing the time
axis and the rotation axis and reversing the two others. Averaging over this
Klein four-group kills every tensor component with an odd index pattern; since
every antisymmetric index pair is odd under exactly two of the three parities,
the weight-four sector admits no invariant.

-/

/-- The lift `diag(i, -i)` of the rotation by `π` about the `z`-axis. -/
noncomputable def rotationPiZ : SL(2,ℂ) :=
  ⟨!![Complex.I, 0; 0, -Complex.I], by
    simp [Matrix.det_fin_two_of]⟩

/-- The lift `i σ1` of the rotation by `π` about the `x`-axis. -/
noncomputable def rotationPiX : SL(2,ℂ) :=
  ⟨!![0, Complex.I; Complex.I, 0], by
    simp [Matrix.det_fin_two_of]⟩

/-- The lift `i σ2` of the rotation by `π` about the `y`-axis. -/
noncomputable def rotationPiY : SL(2,ℂ) :=
  ⟨!![0, 1; -1, 0], by simp [Matrix.det_fin_two_of]⟩

/-- The subgroup of `SL(2,ℂ)` generated by the lifted rotations by `π` about the
  three coordinate axes. In `SL(2,ℂ)` this is the quaternion group `Q₈`: each
  lift squares to `-1` rather than to `1`, so it is the double cover of the Klein
  four-group `{1, R_x, R_y, R_z}` of rotations by `π` inside the rotation group.
  `rotationPiAvg` averages the representation over the four elements
  `1, R_z, R_y, R_x`, which is the average over that Klein four-group. -/
noncomputable def rotationPiSubgroup : Subgroup SL(2,ℂ) :=
  Subgroup.closure {rotationPiZ, rotationPiX, rotationPiY}

lemma rotationPiZ_mem_rotationPiSubgroup : rotationPiZ ∈ rotationPiSubgroup :=
  Subgroup.subset_closure (by simp)

lemma rotationPiX_mem_rotationPiSubgroup : rotationPiX ∈ rotationPiSubgroup :=
  Subgroup.subset_closure (by simp)

lemma rotationPiY_mem_rotationPiSubgroup : rotationPiY ∈ rotationPiSubgroup :=
  Subgroup.subset_closure (by simp)

/-- The sign pattern of the rotation by `π` about the `z`-axis. -/
def rotationPiSignZ : Fin 1 ⊕ Fin 3 → ℝ
  | Sum.inl _ => 1
  | Sum.inr 0 => -1
  | Sum.inr 1 => -1
  | Sum.inr 2 => 1

/-- The sign pattern of the rotation by `π` about the `x`-axis. -/
def rotationPiSignX : Fin 1 ⊕ Fin 3 → ℝ
  | Sum.inl _ => 1
  | Sum.inr 0 => 1
  | Sum.inr 1 => -1
  | Sum.inr 2 => -1

/-- The sign pattern of the rotation by `π` about the `y`-axis. -/
def rotationPiSignY : Fin 1 ⊕ Fin 3 → ℝ
  | Sum.inl _ => 1
  | Sum.inr 0 => -1
  | Sum.inr 1 => 1
  | Sum.inr 2 => -1

/-- The Lorentz matrix of the `z`-parity is the diagonal sign matrix. -/
lemma toLorentzGroup_rotationPiZ (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 a b =
      if a = b then rotationPiSignZ a else 0 := by
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · simp [rotationPiZ, rotationPiSignZ, PauliMatrix.pauliSelfAdjoint', PauliMatrix.pauliMatrix,
        Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two, Matrix.conjTranspose,
        Matrix.diag]
      simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]

/-- The Lorentz matrix of the `x`-parity is the diagonal sign matrix. -/
lemma toLorentzGroup_rotationPiX (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 a b =
      if a = b then rotationPiSignX a else 0 := by
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · simp [rotationPiX, rotationPiSignX, PauliMatrix.pauliSelfAdjoint', PauliMatrix.pauliMatrix,
        Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two, Matrix.conjTranspose,
        Matrix.diag]
      simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]

/-- The Lorentz matrix of the `y`-parity is the diagonal sign matrix. -/
lemma toLorentzGroup_rotationPiY (a b : Fin 1 ⊕ Fin 3) :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 a b =
      if a = b then rotationPiSignY a else 0 := by
  refine Complex.ofReal_injective ?_
  rw [Lorentz.SL2C.toLorentzGroup_eq_trace]
  rcases a with a | a <;> rcases b with b | b <;> fin_cases a <;> fin_cases b <;>
    · simp [rotationPiY, rotationPiSignY, PauliMatrix.pauliSelfAdjoint', PauliMatrix.pauliMatrix,
        Matrix.trace, Matrix.mul_apply, Fin.sum_univ_two, Matrix.conjTranspose,
        Matrix.diag]
      simp [Matrix.vecMul, Matrix.vecHead, Matrix.vecTail]

/-- The inverse of the `z`-parity, entrywise. -/
lemma rotationPiZ_inv_coe :
    (rotationPiZ⁻¹ : SL(2,ℂ)).1 = !![-Complex.I, 0; 0, Complex.I] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rotationPiZ]

/-- The inverse of the `y`-parity, entrywise. -/
lemma rotationPiY_inv_coe :
    (rotationPiY⁻¹ : SL(2,ℂ)).1 = !![0, -1; 1, 0] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rotationPiY]

/-- The inverse of the `x`-parity, entrywise. -/
lemma rotationPiX_inv_coe :
    (rotationPiX⁻¹ : SL(2,ℂ)).1 = !![0, -Complex.I; -Complex.I, 0] := by
  rw [Matrix.SpecialLinearGroup.SL2_inv_expl]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rotationPiX]


/-!

### The Lorentz matrices of the rotations, entry by entry

-/

/-- Entries of the Lorentz matrix of `rotationPiZ`. -/
lemma rotationPiMatZ_00 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inl 0) (Sum.inl 0) = 1 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_01 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inl 0) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_02 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inl 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_03 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inl 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_10 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 0) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_11 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 0) (Sum.inr 0) = -1 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_12 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_13 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_20 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 1) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_21 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 1) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_22 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 1) (Sum.inr 1) = -1 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_23 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 1) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_30 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 2) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_31 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 2) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_32 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 2) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

lemma rotationPiMatZ_33 :
    (Lorentz.SL2C.toLorentzGroup rotationPiZ).1 (Sum.inr 2) (Sum.inr 2) = 1 := by
  rw [toLorentzGroup_rotationPiZ]
  norm_num [rotationPiSignZ]
  all_goals decide

/-- Entries of the Lorentz matrix of `rotationPiX`. -/
lemma rotationPiMatX_00 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inl 0) (Sum.inl 0) = 1 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_01 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inl 0) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_02 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inl 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_03 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inl 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_10 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 0) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_11 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 0) (Sum.inr 0) = 1 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_12 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_13 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_20 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 1) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_21 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 1) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_22 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 1) (Sum.inr 1) = -1 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_23 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 1) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_30 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 2) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_31 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 2) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_32 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 2) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

lemma rotationPiMatX_33 :
    (Lorentz.SL2C.toLorentzGroup rotationPiX).1 (Sum.inr 2) (Sum.inr 2) = -1 := by
  rw [toLorentzGroup_rotationPiX]
  norm_num [rotationPiSignX]
  all_goals decide

/-- Entries of the Lorentz matrix of `rotationPiY`. -/
lemma rotationPiMatY_00 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inl 0) (Sum.inl 0) = 1 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_01 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inl 0) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_02 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inl 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_03 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inl 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_10 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 0) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_11 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 0) (Sum.inr 0) = -1 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_12 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 0) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_13 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 0) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_20 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 1) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_21 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 1) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_22 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 1) (Sum.inr 1) = 1 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_23 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 1) (Sum.inr 2) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_30 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 2) (Sum.inl 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_31 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 2) (Sum.inr 0) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_32 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 2) (Sum.inr 1) = 0 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

lemma rotationPiMatY_33 :
    (Lorentz.SL2C.toLorentzGroup rotationPiY).1 (Sum.inr 2) (Sum.inr 2) = -1 := by
  rw [toLorentzGroup_rotationPiY]
  norm_num [rotationPiSignY]
  all_goals decide

end JetAlgebra

end LeptonGaugeSector
